In [1]:
import math
from scipy.stats import t
def calc_williams_t(rjk,rjh,rkh,N):
    diff=rjk-rjh
    numerator=(N-1)*(1+rkh)
    r_pool=(1/2*(rjk+rjh))**2
    R=(1-rjk**2-rjh**2-rkh**2)+(2*rjk*rjh*rkh)
    denominator=(2*((N-1)/(N-3))*R)+(r_pool*(1-rkh)**3)
    sq=math.sqrt(numerator/denominator)
    t2=diff*sq
    p=2*(1 - t.cdf(abs(t2), N-3))
    return t2,p

from scipy.stats import binom, chi2

def mcnemar(b: int, c: int, continuity_correction: bool = False) -> float:
    check_valid = lambda n: isinstance(n, int) or (isinstance(n, float) and n.is_integer())
    if not all(map(check_valid, [b, c])):
        raise ValueError("b and c must be integers!")
    n_min, n_max = sorted([b, c])
    corr = int(continuity_correction)
    if (n_min + n_max) < 25:
        pvalue = 2 * binom.cdf(n_min, n_min+n_max, 0.5) - binom.pmf(n_min, n_min+n_max, 0.5)
    else:
        chi2_statistic = (abs(n_min - n_max) - corr) ** 2 / (n_min + n_max)
        pvalue = chi2.sf(chi2_statistic, 1)
    return pvalue

In [2]:
import pandas as pd
import numpy as np 
def safe_corr(x, y):
    """Compute Pearson correlation on non-NaN pairs of two arrays/Series."""
    x = np.asarray(x)
    y = np.asarray(y)
    mask = ~np.isnan(x) & ~np.isnan(y)
    if mask.sum() < 2:
        return np.nan, 0
    return round(np.corrcoef(x[mask], y[mask])[0, 1],4), mask.sum()

In [3]:
import pandas as pd
import numpy as np 
def safe_corr_raw(x, y):
    """Compute Pearson correlation on non-NaN pairs of two arrays/Series."""
    x = np.asarray(x)
    y = np.asarray(y)
    mask = ~np.isnan(x) & ~np.isnan(y)
    if mask.sum() < 2:
        return np.nan, 0
    return np.corrcoef(x[mask], y[mask])[0, 1], mask.sum()

## CLEAR

In [4]:
import pandas as pd
clearv2=pd.read_csv('.../clearv2.csv')
clearv2

,Unnamed: 0,ID,Last Changed,Author,Title,Anthology,URL,Source,Pub Year,Category,...,noscale_aya_8b_entropy,noscale_gemma_2b_vanilla,noscale_gemma_2b_avg,noscale_gemma_2b_entropy,noscale_gemma_27b_vanilla,noscale_gemma_27b_avg,noscale_gemma_27b_entropy,noscale_gemma_9b_vanilla,noscale_gemma_9b_avg,noscale_gemma_9b_entropy
0,0,403,NaN,CHARLES KINGSLEY,THE WATER-BABIES\nA Fairy Tale for a Land-Baby,NaN,http://www.gutenberg.org/files/25564/25564-h/2...,gutenberg,1863.0,Lit,...,0.031834,5,4.976873,0.102799,5,5.289848,0.068867,6,5.957567,0.030652
1,1,429,NaN,Edith Bancroft,Jane Allen: Right Guard,NaN,http://www.gutenberg.org/files/19015/19015-h/1...,gutenberg,1918.0,Lit,...,0.064853,4,4.578913,0.086931,4,4.058805,0.035683,6,5.528469,0.067524
2,2,431,NaN,Edith Van Dyne,The Flying Girl\n,NaN,http://www.gutenberg.org/files/53386/53386-h/5...,gutenberg,1911.0,Lit,...,0.053931,4,4.721560,0.095685,4,4.196626,0.048985,6,5.775146,0.047276
3,3,432,NaN,Edith van Dyne,Mary Louise,NaN,http://www.gutenberg.org/cache/epub/5660/pg566...,gutenberg,2002.0,Lit,...,0.011944,5,5.123579,0.092917,4,3.934734,0.035510,6,5.553071,0.063331
4,4,438,NaN,Edward Sylvester Ellis,LOST IN A BLIZZARD,The Jungle Fugitives and Others,http://www.gutenberg.org/files/16805/16805-h/1...,gutenberg,1903.0,Lit,...,0.023126,5,5.081093,0.093700,4,4.098474,0.040634,6,5.520923,0.064855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1885,1885,8020,NaN,original text by Stephen Whitt\nadapted by Jes...,At Home in the Cold,Beyond Penguins and Polar Bears\n,http://static.ehe.osu.edu/sites/beyond/penguin...,static.ehe.osu.edu,2009.0,Info,...,0.038689,5,4.815241,0.095167,2,2.013367,0.006608,3,2.535322,0.058227
1886,1886,8024,NaN,wikijunior,Introduction to The Elements,Wikijunior\n,https://en.wikibooks.org/wiki/Wikijunior:The_E...,wikibooks,2013.0,Info,...,0.032940,5,4.908336,0.104820,3,2.920735,0.031165,4,3.844360,0.040791
1887,1887,8027,NaN,wikijunior,Bugs/Monarch butterfly,"""Wikijunior\n",https://en.wikibooks.org/wiki/Wikijunior:Bugs/...,wikibooks,2019.0,Info,...,0.057042,5,4.838552,0.097822,3,2.715972,0.052195,4,3.594110,0.059694
1888,1888,8028,NaN,wikijunior,Bugs/Walking Stick,"""Wikijunior\n",https://en.wikibooks.org/wiki/Wikijunior:Bugs/...,wikibooks,2020.0,Info,...,0.059842,6,5.841824,0.049032,4,4.423093,0.062812,5,5.280104,0.066350
1889,1889,8029,NaN,wikijunior,Bugs/Black Widow,Wikijunior\n,https://en.wikibooks.org/wiki/Wikijunior:Bugs/...,wikibooks,2020.0,Info,...,0.019972,5,4.800860,0.092058,3,3.060150,0.028728,3,3.144534,0.050385

In [5]:
clearv2.columns[-50:]

Index(['conf_noscale_aya_32b_entropy', 'conf_noscale_aya_32b_verbal_conf',
       'conf_noscale_llama_70b_vanilla', 'conf_noscale_llama_70b_avg',
       'conf_noscale_llama_70b_entropy', 'conf_noscale_llama_70b_verbal_conf',
       'conf_llama_70b_vanilla', 'conf_llama_70b_avg',
       'conf_llama_70b_entropy', 'conf_llama_70b_verbal_conf',
       'conf_llama_8b_vanilla', 'conf_llama_8b_avg', 'conf_llama_8b_entropy',
       'conf_llama_8b_verbal_conf', 'conf_noscore_llama_8b_vanilla',
       'conf_noscore_llama_8b_avg', 'conf_noscore_llama_8b_entropy',
       'conf_noscore_llama_8b_verbal_conf', 'conf_noscore_llama_3b_vanilla',
       'conf_noscore_llama_3b_avg', 'conf_noscore_llama_3b_entropy',
       'conf_noscore_llama_3b_verbal_conf', 'conf_llama_3b_vanilla',
       'conf_llama_3b_avg', 'conf_llama_3b_entropy',
       'conf_llama_3b_verbal_conf', 'noscale_llama_3b_vanilla',
       'noscale_llama_3b_avg', 'noscale_llama_3b_entropy',
       'noscale_llama_8b_vanilla', 'noscale_llama_8b_avg',
       'noscale_llama_8b_entropy', 'noscale_llama_70b_vanilla',
       'noscale_llama_70b_avg', 'noscale_llama_70b_entropy',
       'noscale_aya_32b_vanilla', 'noscale_aya_32b_avg',
       'noscale_aya_32b_entropy', 'noscale_aya_8b_vanilla',
       'noscale_aya_8b_avg', 'noscale_aya_8b_entropy',
       'noscale_gemma_2b_vanilla', 'noscale_gemma_2b_avg',
       'noscale_gemma_2b_entropy', 'noscale_gemma_27b_vanilla',
       'noscale_gemma_27b_avg', 'noscale_gemma_27b_entropy',
       'noscale_gemma_9b_vanilla', 'noscale_gemma_9b_avg',
       'noscale_gemma_9b_entropy'],
      dtype='object')

In [6]:
import numpy as np
clearv2 = clearv2.replace("na", np.nan)

In [7]:
ref_col = clearv2.columns[23]

for i in range(41, len(clearv2.columns)):  
    col = clearv2.columns[i]
    corr = clearv2[ref_col].astype(float).corr(clearv2[col].astype(float))
    if ('entropy' not in col) and ('verbal_conf' not in col):
        print(f"{i+1}: {col} -> correlation with {ref_col}: {corr:.4f}")

42: LLAMA_70B_vanilla -> correlation with BT Easiness: -0.7364
43: LLAMA_70B_avg -> correlation with BT Easiness: -0.7493
45: LLAMA_8B_vanilla -> correlation with BT Easiness: -0.6324
46: LLAMA_8B_avg -> correlation with BT Easiness: -0.6645
48: AYA_32B_vanilla -> correlation with BT Easiness: -0.7130
49: AYA_32B_avg -> correlation with BT Easiness: -0.7324
51: LLAMA_3B_vanilla -> correlation with BT Easiness: -0.5376
52: LLAMA_3B_avg -> correlation with BT Easiness: -0.6074
54: phi_vanilla -> correlation with BT Easiness: -0.7344
55: phi_avg -> correlation with BT Easiness: -0.7571
57: mixtral_vanilla -> correlation with BT Easiness: -0.6242
58: mixtral_avg -> correlation with BT Easiness: -0.6356
60: AYA_8b_vanilla -> correlation with BT Easiness: -0.4953
61: AYA_8b_avg -> correlation with BT Easiness: -0.5512
63: gemma_2B_vanilla -> correlation with BT Easiness: -0.6104
64: gemma_2B_avg -> correlation with BT Easiness: -0.6542
66: gemma_9B_vanilla -> correlation with BT Easiness: -0.6841
67: gemma_9B_avg -> correlation with BT Easiness: -0.6977
69: gemma_27B_vanilla -> correlation with BT Easiness: -0.7290
70: gemma_27B_avg -> correlation with BT Easiness: -0.7416
72: noscale_phi_vanilla -> correlation with BT Easiness: -0.7313
73: noscale_phi_avg -> correlation with BT Easiness: -0.7517
75: noscale_mixtral_vanilla -> correlation with BT Easiness: -0.6513
76: noscale_mixtral_avg -> correlation with BT Easiness: -0.6701
78: conf_noscale_phi_vanilla -> correlation with BT Easiness: -0.7481
79: conf_noscale_phi_avg -> correlation with BT Easiness: -0.7718
82: conf_phi_vanilla -> correlation with BT Easiness: -0.7351
83: conf_phi_avg -> correlation with BT Easiness: -0.7632
86: conf_noscale_gemma_9b_vanilla -> correlation with BT Easiness: -0.7189
87: conf_noscale_gemma_9b_avg -> correlation with BT Easiness: -0.7422
90: conf_gemma_9b_vanilla -> correlation with BT Easiness: -0.6970
91: conf_gemma_9b_avg -> correlation with BT Easiness: -0.7099
94: conf_noscale_gemma_27b_vanilla -> correlation with BT Easiness: -0.7472
95: conf_noscale_gemma_27b_avg -> correlation with BT Easiness: -0.7714
98: conf_gemma_27b_vanilla -> correlation with BT Easiness: -0.7149
99: conf_gemma_27b_avg -> correlation with BT Easiness: -0.7327
102: conf_gemma_2b_vanilla -> correlation with BT Easiness: -0.5233
103: conf_gemma_2b_avg -> correlation with BT Easiness: -0.6061
106: conf_noscale_gemma_2b_vanilla -> correlation with BT Easiness: -0.3285
107: conf_noscale_gemma_2b_avg -> correlation with BT Easiness: -0.3672
110: conf_noscale_mixtral_vanilla -> correlation with BT Easiness: -0.6913
111: conf_noscale_mixtral_avg -> correlation with BT Easiness: -0.7074
114: conf_mixtral_vanilla -> correlation with BT Easiness: -0.6820
115: conf_mixtral_avg -> correlation with BT Easiness: -0.6958
118: conf_aya_32B_vanilla -> correlation with BT Easiness: -0.7002
119: conf_aya_32B_avg -> correlation with BT Easiness: -0.7219
122: conf_noscale_aya_32b_vanilla -> correlation with BT Easiness: -0.7012
123: conf_noscale_aya_32b_avg -> correlation with BT Easiness: -0.7349
126: conf_noscale_llama_70b_vanilla -> correlation with BT Easiness: -0.7250
127: conf_noscale_llama_70b_avg -> correlation with BT Easiness: -0.7445
130: conf_llama_70b_vanilla -> correlation with BT Easiness: -0.7386
131: conf_llama_70b_avg -> correlation with BT Easiness: -0.7536
134: conf_llama_8b_vanilla -> correlation with BT Easiness: -0.6509
135: conf_llama_8b_avg -> correlation with BT Easiness: -0.6843
138: conf_noscore_llama_8b_vanilla -> correlation with BT Easiness: -0.6630
139: conf_noscore_llama_8b_avg -> correlation with BT Easiness: -0.7131
142: conf_noscore_llama_3b_vanilla -> correlation with BT Easiness: -0.5533
143: conf_noscore_llama_3b_avg -> correlation with BT Easiness: -0.6052
146: conf_llama_3b_vanilla -> correlation with BT Easiness: -0.6070
147: conf_llama_3b_avg -> correlation with BT Easiness: -0.6272
150: noscale_llama_3b_vanilla -> correlation with BT Easiness: -0.4902
151: noscale_llama_3b_avg -> correlation with BT Easiness: -0.5527
153: noscale_llama_8b_vanilla -> correlation with BT Easiness: -0.6772
154: noscale_llama_8b_avg -> correlation with BT Easiness: -0.7263
156: noscale_llama_70b_vanilla -> correlation with BT Easiness: -0.7338
157: noscale_llama_70b_avg -> correlation with BT Easiness: -0.7618
159: noscale_aya_32b_vanilla -> correlation with BT Easiness: -0.6778
160: noscale_aya_32b_avg -> correlation with BT Easiness: -0.7052
162: noscale_aya_8b_vanilla -> correlation with BT Easiness: -0.5356
163: noscale_aya_8b_avg -> correlation with BT Easiness: -0.5636
165: noscale_gemma_2b_vanilla -> correlation with BT Easiness: -0.5155
166: noscale_gemma_2b_avg -> correlation with BT Easiness: -0.5609
168: noscale_gemma_27b_vanilla -> correlation with BT Easiness: -0.7569
169: noscale_gemma_27b_avg -> correlation with BT Easiness: -0.7767
171: noscale_gemma_9b_vanilla -> correlation with BT Easiness: -0.7310
172: noscale_gemma_9b_avg -> correlation with BT Easiness: -0.7496
174: RSRS_mBERT -> correlation with BT Easiness: -0.4836

In [8]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
clearv2 = clearv2.apply(pd.to_numeric, errors="coerce")
rf_string='Flesch-Kincaid-Grade-Level'
std_cols = [c for c in clearv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
clearv2[std_cols] = StandardScaler().fit_transform(clearv2[std_cols])
model='conf_noscale_llama_70b'
vconf_col=f'{model}_verbal_conf'
avg_col = f"{model}_avg"


verbal_avg_rf=((1 - clearv2[vconf_col]/10) * clearv2[rf_string]) + (clearv2[vconf_col]/10 * clearv2[avg_col])


rjk,n1=safe_corr_raw(verbal_avg_rf, clearv2.iloc[:,23])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(clearv2.iloc[:,125], clearv2.iloc[:,23])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,clearv2.iloc[:,125])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs LLM : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, clearv2.iloc[:,23])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(clearv2[rf_string], clearv2.iloc[:,23])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,clearv2[rf_string])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RF : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, clearv2.iloc[:,23])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(clearv2['RSRS_mBERT'], clearv2.iloc[:,23])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,clearv2['RSRS_mBERT'])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RSRS : t2:{res1[0]}, p:{res1[1]}')

-0.735074190859022 -0.724961487853396 0.9616438656353052
1890
t_test: Vconf RF vs LLM : t2:-2.3499953487241867, p:0.01887615896817496
-0.735074190859022 -0.5168100999782614 0.7955004072366376
1890
t_test: Vconf RF vs RF : t2:-22.05997093905406, p:0.0
-0.735074190859022 -0.4835967356070031 0.7511883900501058
1890
t_test: Vconf RF vs RSRS : t2:-22.946972125630992, p:0.0

In [9]:
import numpy as np
rjk,n1=safe_corr_raw(clearv2.iloc[:,126], clearv2.iloc[:,23])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(clearv2.iloc[:,125], clearv2.iloc[:,23])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(clearv2.iloc[:,126],clearv2.iloc[:,125])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Expected vs Vanilla : t2:{res1[0]}, p:{res1[1]}')
## More negative is better for CLEAR because readability scores are for reading_ease, rather than reading difficulty

-0.7444650312422447 -0.724961487853396 0.9752867407212038
1890
t_test: Expected vs Vanilla : t2:-5.707353106622201, p:1.3297416945334817e-08

In [10]:
for i in range(25, 30): 
    col = clearv2.columns[i]
    corr = clearv2[ref_col].astype(float).corr(clearv2[col].astype(float))
    if 'entropy' not in col:
        print(f"{i+1}: {col} -> correlation with {ref_col}: {corr:.4f}")

26: Flesch-Reading-Ease -> correlation with BT Easiness: 0.5396
27: Flesch-Kincaid-Grade-Level -> correlation with BT Easiness: -0.5168
28: Automated Readability Index -> correlation with BT Easiness: -0.4840
29: SMOG Readability -> correlation with BT Easiness: -0.5515
30: New Dale-Chall Readability Formula -> correlation with BT Easiness: -0.5559

In [11]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
clearv2 = clearv2.apply(pd.to_numeric, errors="coerce")
rf_string='Flesch-Kincaid-Grade-Level'
ref_col = clearv2.columns[23]
#clearv2['RSRS_mBERT']= StandardScaler().fit_transform(clearv2['RSRS_mBERT'])
# Step 1: Normalize entropy columns
entropy_cols = [c for c in clearv2.columns if c.endswith("_entropy")]
entropy_cols_minmax = [c + "_minmax" for c in entropy_cols]
clearv2[entropy_cols_minmax] = MinMaxScaler().fit_transform(clearv2[entropy_cols])

vconf_cols = [c for c in clearv2.columns if c.endswith("verbal_conf")]
vconf_cols_minmax = [c + "_minmax" for c in vconf_cols]
clearv2[vconf_cols_minmax] = MinMaxScaler().fit_transform(clearv2[vconf_cols])
clearv2[vconf_cols] = clearv2[vconf_cols]/10

std_cols = [c for c in clearv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
clearv2[std_cols] = StandardScaler().fit_transform(clearv2[std_cols])
suffixes = ["_avg", "_vanilla", "_entropy"]
models = set(
    c.rsplit("_", 1)[0]  # remove the last part after the final underscore
    for c in entropy_cols  # for any column list containing these suffixes
)
sorted_models = sorted(models, key=lambda x: x[::-1].lower())
for model in sorted_models:
    print(model)
    vanilla_col = f"{model}_vanilla"
    avg_col = f"{model}_avg"
    print(f'unweighted:\n AVG:{safe_corr(clearv2[avg_col], clearv2[ref_col])},Vanilla:{safe_corr(clearv2[vanilla_col], clearv2[ref_col])},RSRS:{safe_corr(clearv2["RSRS_mBERT"], clearv2[ref_col])},Readability Formula: {safe_corr(clearv2[rf_string], clearv2[ref_col])}')
    naive_avg_mBERT=clearv2[avg_col]+clearv2["RSRS_mBERT"]
    naive_vanilla_mBERT=clearv2[vanilla_col]+clearv2["RSRS_mBERT"]
    
    naive_avg_rf=clearv2[avg_col]+clearv2[rf_string]
    naive_vanilla_rf=clearv2[vanilla_col]+clearv2[rf_string]
    print(f'naive weightings: \n AVG mBERT:{safe_corr(naive_avg_mBERT, clearv2[ref_col])},Vanilla mBERT:{safe_corr(naive_vanilla_mBERT, clearv2[ref_col])}, AVG Readability Formula: {safe_corr(naive_avg_rf, clearv2[ref_col])}, Vanilla Readability Formula: {safe_corr(naive_vanilla_rf, clearv2[ref_col])}')
    entropy_col = f"{model}_entropy"
    entropy_col_minmax = f"{model}_entropy_minmax"
    if model.startswith('conf_'):
        vconf_col=f'{model}_verbal_conf'
        vconf_col_minmax = f"{model}_verbal_conf_minmax"
    
    entropy_avg_mBERT=(clearv2[entropy_col] * clearv2["RSRS_mBERT"]) + ((1 - clearv2[entropy_col]) * clearv2[avg_col])
    entropy_vanilla_mBERT=(clearv2[entropy_col] * clearv2["RSRS_mBERT"]) + ((1 - clearv2[entropy_col]) * clearv2[vanilla_col])
    entropy_minmax_avg_mBERT=(clearv2[entropy_col_minmax] * clearv2["RSRS_mBERT"]) + ((1 - clearv2[entropy_col_minmax]) * clearv2[avg_col])
    entropy_minmax_vanilla_mBERT=(clearv2[entropy_col_minmax] * clearv2["RSRS_mBERT"]) + ((1 - clearv2[entropy_col_minmax]) * clearv2[vanilla_col])
    
    entropy_avg_rf=(clearv2[entropy_col] * clearv2[rf_string]) + ((1 - clearv2[entropy_col]) * clearv2[avg_col])
    entropy_vanilla_rf=(clearv2[entropy_col] * clearv2[rf_string]) + ((1 - clearv2[entropy_col]) * clearv2[vanilla_col])
    entropy_minmax_avg_rf=(clearv2[entropy_col_minmax] * clearv2[rf_string]) + ((1 - clearv2[entropy_col_minmax]) * clearv2[avg_col])
    entropy_minmax_vanilla_rf=(clearv2[entropy_col_minmax] * clearv2[rf_string]) + ((1 - clearv2[entropy_col_minmax]) * clearv2[vanilla_col])
    print(f'entropy weightings:\n AVG mBERT:{safe_corr(entropy_avg_mBERT, clearv2[ref_col])},Vanilla mBERT:{safe_corr(entropy_vanilla_mBERT, clearv2[ref_col])},Avg mBERT minmax:{safe_corr(entropy_minmax_avg_mBERT, clearv2[ref_col])},Vanilla mBERT minmax:{safe_corr(entropy_minmax_vanilla_mBERT, clearv2[ref_col])},Avg Readability Formula: {safe_corr(entropy_avg_rf, clearv2[ref_col])},Vanilla Readability Formula: {safe_corr(entropy_vanilla_rf, clearv2[ref_col])},Average Readability Formula minmax:{safe_corr(entropy_minmax_avg_rf, clearv2[ref_col])}, Vanilla Readability Formula minmax:{safe_corr(entropy_minmax_vanilla_rf, clearv2[ref_col])}')
    if model.startswith('conf_'):
        verbal_avg_mBERT=((1 - clearv2[vconf_col]) * clearv2["RSRS_mBERT"]) + (clearv2[vconf_col] * clearv2[avg_col])
        verbal_vanilla_mBERT=((1 - clearv2[vconf_col]) * clearv2["RSRS_mBERT"]) + (clearv2[vconf_col] * clearv2[vanilla_col])
        verbal_minmax_avg_mBERT=((1 - clearv2[vconf_col_minmax]) * clearv2["RSRS_mBERT"]) + (clearv2[vconf_col_minmax] * clearv2[avg_col])
        verbal_minmax_vanilla_mBERT=((1 - clearv2[vconf_col_minmax]) * clearv2["RSRS_mBERT"]) + (clearv2[vconf_col_minmax] * clearv2[vanilla_col])
        
        verbal_avg_rf=((1 - clearv2[vconf_col]) * clearv2[rf_string]) + (clearv2[vconf_col] * clearv2[avg_col])
        verbal_vanilla_rf=((1 - clearv2[vconf_col]) * clearv2[rf_string]) + (clearv2[vconf_col] * clearv2[vanilla_col])
        verbal_minmax_avg_rf=((1 - clearv2[vconf_col_minmax]) * clearv2[rf_string]) + (clearv2[vconf_col_minmax] * clearv2[avg_col])
        verbal_minmax_vanilla_rf=((1 - clearv2[vconf_col_minmax]) * clearv2[rf_string]) + (clearv2[vconf_col_minmax] * clearv2[vanilla_col])
        print(f'verbal conf weightings:\n AVG mBERT:{safe_corr(verbal_avg_mBERT, clearv2[ref_col])},Vanilla mBERT:{safe_corr(verbal_vanilla_mBERT, clearv2[ref_col])},Avg mBERT minmax:{safe_corr(verbal_minmax_avg_mBERT, clearv2[ref_col])},Vanilla mBERT minmax:{safe_corr(verbal_minmax_vanilla_mBERT, clearv2[ref_col])},Avg Readability Formula: {safe_corr(verbal_avg_rf, clearv2[ref_col])},Vanilla Readability Formula:{safe_corr(verbal_vanilla_rf, clearv2[ref_col])},Average Readability Formula minmax:{safe_corr(verbal_minmax_avg_rf, clearv2[ref_col])},Vanilla Readability Formula minmax: {safe_corr(verbal_minmax_vanilla_rf, clearv2[ref_col])}','\n \n \n')
    else:
        print('\n \n \n')

LLAMA_70B
unweighted:
 AVG:(-0.7493, 1890),Vanilla:(-0.7364, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6771, 1890),Vanilla mBERT:(-0.6732, 1890), AVG Readability Formula: (-0.6867, 1890), Vanilla Readability Formula: (-0.6828, 1890)
entropy weightings:
 AVG mBERT:(-0.7483, 1890),Vanilla mBERT:(-0.7369, 1890),Avg mBERT minmax:(-0.6774, 1890),Vanilla mBERT minmax:(-0.6747, 1890),Avg Readability Formula: (-0.7484, 1890),Vanilla Readability Formula: (-0.7369, 1890),Average Readability Formula minmax:(-0.6812, 1890), Vanilla Readability Formula minmax:(-0.6785, 1890)




noscale_llama_70b
unweighted:
 AVG:(-0.7618, 1890),Vanilla:(-0.7338, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6798, 1890),Vanilla mBERT:(-0.6679, 1890), AVG Readability Formula: (-0.6929, 1890), Vanilla Readability Formula: (-0.6813, 1890)
entropy weightings:
 AVG mBERT:(-0.7594, 1890),Vanilla mBERT:(-0.7344, 1890),Avg mBERT minmax:(-0.6588, 1890),Vanilla mBERT minmax:(-0.6539, 1890),Avg Readability Formula: (-0.7602, 1890),Vanilla Readability Formula: (-0.7353, 1890),Average Readability Formula minmax:(-0.6786, 1890), Vanilla Readability Formula minmax:(-0.6741, 1890)




conf_noscale_llama_70b
unweighted:
 AVG:(-0.7445, 1890),Vanilla:(-0.725, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6727, 1890),Vanilla mBERT:(-0.6659, 1890), AVG Readability Formula: (-0.6865, 1890), Vanilla Readability Formula: (-0.6801, 1890)
entropy weightings:
 AVG mBERT:(-0.743, 1890),Vanilla mBERT:(-0.7262, 1890),Avg mBERT minmax:(-0.652, 1890),Vanilla mBERT minmax:(-0.6487, 1890),Avg Readability Formula: (-0.744, 1890),Vanilla Readability Formula: (-0.7272, 1890),Average Readability Formula minmax:(-0.6714, 1890), Vanilla Readability Formula minmax:(-0.6687, 1890)
verbal conf weightings:
 AVG mBERT:(-0.7307, 1890),Vanilla mBERT:(-0.717, 1890),Avg mBERT minmax:(-0.6383, 1890),Vanilla mBERT minmax:(-0.6336, 1890),Avg Readability Formula: (-0.7351, 1890),Vanilla Readability Formula:(-0.7217, 1890),Average Readability Formula minmax:(-0.6541, 1890),Vanilla Readability Formula minmax: (-0.6499, 1890)



conf_llama_70b
unweighted:
 AVG:(-0.7536, 1890),Vanilla:(-0.7386, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6804, 1890),Vanilla mBERT:(-0.6736, 1890), AVG Readability Formula: (-0.6885, 1890), Vanilla Readability Formula: (-0.6818, 1890)
entropy weightings:
 AVG mBERT:(-0.7527, 1890),Vanilla mBERT:(-0.7387, 1890),Avg mBERT minmax:(-0.6849, 1890),Vanilla mBERT minmax:(-0.6789, 1890),Avg Readability Formula: (-0.7526, 1890),Vanilla Readability Formula: (-0.7386, 1890),Average Readability Formula minmax:(-0.69, 1890), Vanilla Readability Formula minmax:(-0.6839, 1890)
verbal conf weightings:
 AVG mBERT:(-0.7414, 1890),Vanilla mBERT:(-0.7296, 1890),Avg mBERT minmax:(-0.6534, 1890),Vanilla mBERT minmax:(-0.6479, 1890),Avg Readability Formula: (-0.7419, 1890),Vanilla Readability Formula:(-0.7303, 1890),Average Readability Formula minmax:(-0.6645, 1890),Vanilla Readability Formula minmax: (-0.6591, 1890)



AYA_32B
unweighted:
 AVG:(-0.7324, 1890),Vanilla:(-0.713, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6827, 1890),Vanilla mBERT:(-0.6743, 1890), AVG Readability Formula: (-0.683, 1890), Vanilla Readability Formula: (-0.6755, 1890)
entropy weightings:
 AVG mBERT:(-0.7336, 1890),Vanilla mBERT:(-0.7157, 1890),Avg mBERT minmax:(-0.6954, 1890),Vanilla mBERT minmax:(-0.6891, 1890),Avg Readability Formula: (-0.7328, 1890),Vanilla Readability Formula: (-0.715, 1890),Average Readability Formula minmax:(-0.6988, 1890), Vanilla Readability Formula minmax:(-0.6928, 1890)




noscale_aya_32b
unweighted:
 AVG:(-0.7052, 1890),Vanilla:(-0.6778, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6774, 1890),Vanilla mBERT:(-0.6685, 1890), AVG Readability Formula: (-0.7008, 1890), Vanilla Readability Formula: (-0.6912, 1890)
entropy weightings:
 AVG mBERT:(-0.7079, 1890),Vanilla mBERT:(-0.6832, 1890),Avg mBERT minmax:(-0.6736, 1890),Vanilla mBERT minmax:(-0.6671, 1890),Avg Readability Formula: (-0.7093, 1890),Vanilla Readability Formula: (-0.6845, 1890),Average Readability Formula minmax:(-0.6901, 1890), Vanilla Readability Formula minmax:(-0.6834, 1890)




conf_noscale_aya_32b
unweighted:
 AVG:(-0.7349, 1890),Vanilla:(-0.7012, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6865, 1890),Vanilla mBERT:(-0.673, 1890), AVG Readability Formula: (-0.7042, 1890), Vanilla Readability Formula: (-0.691, 1890)
entropy weightings:
 AVG mBERT:(-0.7367, 1890),Vanilla mBERT:(-0.7056, 1890),Avg mBERT minmax:(-0.6899, 1890),Vanilla mBERT minmax:(-0.6809, 1890),Avg Readability Formula: (-0.738, 1890),Vanilla Readability Formula: (-0.707, 1890),Average Readability Formula minmax:(-0.7081, 1890), Vanilla Readability Formula minmax:(-0.6995, 1890)
verbal conf weightings:
 AVG mBERT:(-0.7301, 1890),Vanilla mBERT:(-0.7083, 1890),Avg mBERT minmax:(-0.5967, 1890),Vanilla mBERT minmax:(-0.5935, 1890),Avg Readability Formula: (-0.7402, 1890),Vanilla Readability Formula:(-0.7186, 1890),Average Readability Formula minmax:(-0.6264, 1890),Vanilla Readability Formula minmax: (-0.6231, 1890)



conf_aya_32B
unweighted:
 AVG:(-0.7219, 1890),Vanilla:(-0.7002, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6765, 1890),Vanilla mBERT:(-0.6679, 1890), AVG Readability Formula: (-0.681, 1890), Vanilla Readability Formula: (-0.6727, 1890)
entropy weightings:
 AVG mBERT:(-0.7232, 1890),Vanilla mBERT:(-0.7033, 1890),Avg mBERT minmax:(-0.7072, 1890),Vanilla mBERT minmax:(-0.6995, 1890),Avg Readability Formula: (-0.7231, 1890),Vanilla Readability Formula: (-0.7032, 1890),Average Readability Formula minmax:(-0.7096, 1890), Vanilla Readability Formula minmax:(-0.7018, 1890)
verbal conf weightings:
 AVG mBERT:(-0.7238, 1886),Vanilla mBERT:(-0.7078, 1886),Avg mBERT minmax:(-0.7119, 1886),Vanilla mBERT minmax:(-0.6952, 1886),Avg Readability Formula: (-0.7221, 1886),Vanilla Readability Formula:(-0.7063, 1886),Average Readability Formula minmax:(-0.7103, 1886),Vanilla Readability Formula minmax: (-0.6932, 1886)



gemma_2B
unweighted:
 AVG:(-0.6542, 1890),Vanilla:(-0.6104, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6639, 1890),Vanilla mBERT:(-0.6432, 1890), AVG Readability Formula: (-0.6651, 1890), Vanilla Readability Formula: (-0.6463, 1890)
entropy weightings:
 AVG mBERT:(-0.6695, 1890),Vanilla mBERT:(-0.6299, 1890),Avg mBERT minmax:(-0.6656, 1890),Vanilla mBERT minmax:(-0.6469, 1890),Avg Readability Formula: (-0.6681, 1890),Vanilla Readability Formula: (-0.6291, 1890),Average Readability Formula minmax:(-0.6668, 1890), Vanilla Readability Formula minmax:(-0.6494, 1890)




noscale_gemma_2b
unweighted:
 AVG:(-0.5609, 1890),Vanilla:(-0.5155, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6303, 1890),Vanilla mBERT:(-0.6121, 1890), AVG Readability Formula: (-0.6247, 1890), Vanilla Readability Formula: (-0.6064, 1890)
entropy weightings:
 AVG mBERT:(-0.5824, 1890),Vanilla mBERT:(-0.5412, 1890),Avg mBERT minmax:(-0.6087, 1890),Vanilla mBERT minmax:(-0.594, 1890),Avg Readability Formula: (-0.5802, 1890),Vanilla Readability Formula: (-0.5392, 1890),Average Readability Formula minmax:(-0.6087, 1890), Vanilla Readability Formula minmax:(-0.5933, 1890)




conf_noscale_gemma_2b
unweighted:
 AVG:(-0.3672, 1590),Vanilla:(-0.3285, 1590),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.545, 1590),Vanilla mBERT:(-0.5228, 1590), AVG Readability Formula: (-0.542, 1590), Vanilla Readability Formula: (-0.5239, 1590)
entropy weightings:
 AVG mBERT:(-0.3954, 1590),Vanilla mBERT:(-0.3593, 1590),Avg mBERT minmax:(-0.5139, 1590),Vanilla mBERT minmax:(-0.5071, 1590),Avg Readability Formula: (-0.3953, 1590),Vanilla Readability Formula: (-0.3595, 1590),Average Readability Formula minmax:(-0.5184, 1590), Vanilla Readability Formula minmax:(-0.5137, 1590)
verbal conf weightings:
 AVG mBERT:(-0.485, 1590),Vanilla mBERT:(-0.4535, 1590),Avg mBERT minmax:(-0.5426, 1590),Vanilla mBERT minmax:(-0.5273, 1590),Avg Readability Formula: (-0.481, 1590),Vanilla Readability Formula:(-0.4524, 1590),Average Readability Formula minmax:(-0.5461, 1590),Vanilla Readability Formula minmax: (-0.5344, 1590)



conf_gemma_2b
unweighted:
 AVG:(-0.6061, 1890),Vanilla:(-0.5233, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6384, 1890),Vanilla mBERT:(-0.599, 1890), AVG Readability Formula: (-0.6375, 1890), Vanilla Readability Formula: (-0.6028, 1890)
entropy weightings:
 AVG mBERT:(-0.6239, 1890),Vanilla mBERT:(-0.5479, 1890),Avg mBERT minmax:(-0.6349, 1890),Vanilla mBERT minmax:(-0.5894, 1890),Avg Readability Formula: (-0.6221, 1890),Vanilla Readability Formula: (-0.5477, 1890),Average Readability Formula minmax:(-0.635, 1890), Vanilla Readability Formula minmax:(-0.5938, 1890)
verbal conf weightings:
 AVG mBERT:(-0.646, 1890),Vanilla mBERT:(-0.584, 1890),Avg mBERT minmax:(-0.6064, 1890),Vanilla mBERT minmax:(-0.5794, 1890),Avg Readability Formula: (-0.6417, 1890),Vanilla Readability Formula:(-0.5836, 1890),Average Readability Formula minmax:(-0.6174, 1890),Vanilla Readability Formula minmax: (-0.5937, 1890)



LLAMA_3B
unweighted:
 AVG:(-0.6074, 1890),Vanilla:(-0.5376, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.628, 1890),Vanilla mBERT:(-0.5989, 1890), AVG Readability Formula: (-0.6368, 1890), Vanilla Readability Formula: (-0.6105, 1890)

entropy weightings:
 AVG mBERT:(-0.6187, 1890),Vanilla mBERT:(-0.5549, 1890),Avg mBERT minmax:(-0.6144, 1890),Vanilla mBERT minmax:(-0.5888, 1890),Avg Readability Formula: (-0.619, 1890),Vanilla Readability Formula: (-0.556, 1890),Average Readability Formula minmax:(-0.6307, 1890), Vanilla Readability Formula minmax:(-0.6077, 1890)




noscale_llama_3b
unweighted:
 AVG:(-0.5527, 1890),Vanilla:(-0.4902, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6095, 1890),Vanilla mBERT:(-0.5796, 1890), AVG Readability Formula: (-0.6313, 1890), Vanilla Readability Formula: (-0.6011, 1890)
entropy weightings:
 AVG mBERT:(-0.5718, 1890),Vanilla mBERT:(-0.5134, 1890),Avg mBERT minmax:(-0.6108, 1890),Vanilla mBERT minmax:(-0.5837, 1890),Avg Readability Formula: (-0.5747, 1890),Vanilla Readability Formula: (-0.5161, 1890),Average Readability Formula minmax:(-0.6376, 1890), Vanilla Readability Formula minmax:(-0.6103, 1890)




conf_noscore_llama_3b
unweighted:
 AVG:(-0.6052, 1890),Vanilla:(-0.5533, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6231, 1890),Vanilla mBERT:(-0.602, 1890), AVG Readability Formula: (-0.6409, 1890), Vanilla Readability Formula: (-0.6194, 1890)
entropy weightings:
 AVG mBERT:(-0.6175, 1890),Vanilla mBERT:(-0.57, 1890),Avg mBERT minmax:(-0.6236, 1890),Vanilla mBERT minmax:(-0.6029, 1890),Avg Readability Formula: (-0.62, 1890),Vanilla Readability Formula: (-0.5724, 1890),Average Readability Formula minmax:(-0.6466, 1890), Vanilla Readability Formula minmax:(-0.6259, 1890)
verbal conf weightings:
 AVG mBERT:(-0.6308, 1889),Vanilla mBERT:(-0.5917, 1889),Avg mBERT minmax:(-0.6246, 1889),Vanilla mBERT minmax:(-0.6004, 1889),Avg Readability Formula: (-0.6376, 1889),Vanilla Readability Formula:(-0.5983, 1889),Average Readability Formula minmax:(-0.6378, 1889),Vanilla Readability Formula minmax: (-0.613, 1889)



conf_llama_3b
unweighted:
 AVG:(-0.6272, 1890),Vanilla:(-0.607, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6418, 1890),Vanilla mBERT:(-0.6351, 1890), AVG Readability Formula: (-0.6489, 1890), Vanilla Readability Formula: (-0.6427, 1890)
entropy weightings:
 AVG mBERT:(-0.6399, 1890),Vanilla mBERT:(-0.6223, 1890),Avg mBERT minmax:(-0.6374, 1890),Vanilla mBERT minmax:(-0.6313, 1890),Avg Readability Formula: (-0.6399, 1890),Vanilla Readability Formula: (-0.6223, 1890),Average Readability Formula minmax:(-0.6492, 1890), Vanilla Readability Formula minmax:(-0.6437, 1890)
verbal conf weightings:
 AVG mBERT:(-0.6528, 1890),Vanilla mBERT:(-0.6379, 1890),Avg mBERT minmax:(-0.6536, 1890),Vanilla mBERT minmax:(-0.6418, 1890),Avg Readability Formula: (-0.6531, 1890),Vanilla Readability Formula:(-0.6386, 1890),Average Readability Formula minmax:(-0.6552, 1890),Vanilla Readability Formula minmax: (-0.6437, 1890)



gemma_27B
unweighted:
 AVG:(-0.7416, 1890),Vanilla:(-0.729, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6856, 1890),Vanilla mBERT:(-0.6819, 1890), AVG Readability Formula: (-0.6826, 1890), Vanilla Readability Formula: (-0.6787, 1890)
entropy weightings:
 AVG mBERT:(-0.7426, 1890),Vanilla mBERT:(-0.7312, 1890),Avg mBERT minmax:(-0.668, 1890),Vanilla mBERT minmax:(-0.6652, 1890),Avg Readability Formula: (-0.7407, 1890),Vanilla Readability Formula: (-0.7293, 1890),Average Readability Formula minmax:(-0.669, 1890), Vanilla Readability Formula minmax:(-0.6659, 1890)




noscale_gemma_27b
unweighted:
 AVG:(-0.7767, 1890),Vanilla:(-0.7569, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.7026, 1890),Vanilla mBERT:(-0.6956, 1890), AVG Readability Formula: (-0.7062, 1890), Vanilla Readability Formula: (-0.6991, 1890)
entropy weightings:
 AVG mBERT:(-0.7767, 1890),Vanilla mBERT:(-0.7587, 1890),Avg mBERT minmax:(-0.6915, 1890),Vanilla mBERT minmax:(-0.6866, 1890),Avg Readability Formula: (-0.7758, 1890),Vanilla Readability Formula: (-0.7577, 1890),Average Readability Formula minmax:(-0.6961, 1890), Vanilla Readability Formula minmax:(-0.691, 1890)




conf_noscale_gemma_27b
unweighted:
 AVG:(-0.7714, 1890),Vanilla:(-0.7472, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6995, 1890),Vanilla mBERT:(-0.6897, 1890), AVG Readability Formula: (-0.7041, 1890), Vanilla Readability Formula: (-0.6951, 1890)
entropy weightings:
 AVG mBERT:(-0.7717, 1890),Vanilla mBERT:(-0.7494, 1890),Avg mBERT minmax:(-0.6904, 1890),Vanilla mBERT minmax:(-0.6831, 1890),Avg Readability Formula: (-0.7708, 1890),Vanilla Readability Formula: (-0.7487, 1890),Average Readability Formula minmax:(-0.6947, 1890), Vanilla Readability Formula minmax:(-0.688, 1890)
verbal conf weightings:
 AVG mBERT:(-0.7449, 1890),Vanilla mBERT:(-0.7298, 1890),Avg mBERT minmax:(-0.716, 1890),Vanilla mBERT minmax:(-0.7029, 1890),Avg Readability Formula: (-0.7437, 1890),Vanilla Readability Formula:(-0.7293, 1890),Average Readability Formula minmax:(-0.7156, 1890),Vanilla Readability Formula minmax: (-0.7033, 1890)



conf_gemma_27b
unweighted:
 AVG:(-0.7327, 1890),Vanilla:(-0.7149, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6821, 1890),Vanilla mBERT:(-0.6743, 1890), AVG Readability Formula: (-0.6784, 1890), Vanilla Readability Formula: (-0.6706, 1890)
entropy weightings:
 AVG mBERT:(-0.7342, 1890),Vanilla mBERT:(-0.7175, 1890),Avg mBERT minmax:(-0.6709, 1890),Vanilla mBERT minmax:(-0.6652, 1890),Avg Readability Formula: (-0.7323, 1890),Vanilla Readability Formula: (-0.7156, 1890),Average Readability Formula minmax:(-0.6707, 1890), Vanilla Readability Formula minmax:(-0.665, 1890)
verbal conf weightings:
 AVG mBERT:(-0.7214, 1890),Vanilla mBERT:(-0.7096, 1890),Avg mBERT minmax:(-0.6687, 1890),Vanilla mBERT minmax:(-0.6618, 1890),Avg Readability Formula: (-0.7138, 1890),Vanilla Readability Formula:(-0.7022, 1890),Average Readability Formula minmax:(-0.6677, 1890),Vanilla Readability Formula minmax: (-0.6608, 1890)



LLAMA_8B
unweighted:
 AVG:(-0.6645, 1890),Vanilla:(-0.6324, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6366, 1890),Vanilla mBERT:(-0.6254, 1890), AVG Readability Formula: (-0.6459, 1890), Vanilla Readability Formula: (-0.6356, 1890)
entropy weightings:
 AVG mBERT:(-0.6685, 1890),Vanilla mBERT:(-0.6392, 1890),Avg mBERT minmax:(-0.6619, 1890),Vanilla mBERT minmax:(-0.6489, 1890),Avg Readability Formula: (-0.6688, 1890),Vanilla Readability Formula: (-0.6398, 1890),Average Readability Formula minmax:(-0.6682, 1890), Vanilla Readability Formula minmax:(-0.6559, 1890)




noscale_llama_8b
unweighted:
 AVG:(-0.7263, 1890),Vanilla:(-0.6772, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6738, 1890),Vanilla mBERT:(-0.6539, 1890), AVG Readability Formula: (-0.6871, 1890), Vanilla Readability Formula: (-0.6682, 1890)
entropy weightings:
 AVG mBERT:(-0.7284, 1890),Vanilla mBERT:(-0.6844, 1890),Avg mBERT minmax:(-0.6653, 1890),Vanilla mBERT minmax:(-0.6514, 1890),Avg Readability Formula: (-0.7294, 1890),Vanilla Readability Formula: (-0.6855, 1890),Average Readability Formula minmax:(-0.6814, 1890), Vanilla Readability Formula minmax:(-0.6686, 1890)




conf_noscore_llama_8b
unweighted:
 AVG:(-0.7131, 1890),Vanilla:(-0.663, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.665, 1890),Vanilla mBERT:(-0.6453, 1890), AVG Readability Formula: (-0.6804, 1890), Vanilla Readability Formula: (-0.6609, 1890)
entropy weightings:
 AVG mBERT:(-0.7157, 1890),Vanilla mBERT:(-0.6707, 1890),Avg mBERT minmax:(-0.6762, 1890),Vanilla mBERT minmax:(-0.6605, 1890),Avg Readability Formula: (-0.7168, 1890),Vanilla Readability Formula: (-0.6717, 1890),Average Readability Formula minmax:(-0.6912, 1890), Vanilla Readability Formula minmax:(-0.6761, 1890)
verbal conf weightings:
 AVG mBERT:(-0.7107, 1890),Vanilla mBERT:(-0.6733, 1890),Avg mBERT minmax:(-0.6869, 1890),Vanilla mBERT minmax:(-0.6597, 1890),Avg Readability Formula: (-0.7158, 1890),Vanilla Readability Formula:(-0.6787, 1890),Average Readability Formula minmax:(-0.6949, 1890),Vanilla Readability Formula minmax: (-0.6679, 1890)



conf_llama_8b
unweighted:
 AVG:(-0.6843, 1889),Vanilla:(-0.6509, 1889),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.646, 1889),Vanilla mBERT:(-0.6356, 1889), AVG Readability Formula: (-0.6566, 1889), Vanilla Readability Formula: (-0.6468, 1889)
entropy weightings:
 AVG mBERT:(-0.6871, 1889),Vanilla mBERT:(-0.6575, 1889),Avg mBERT minmax:(-0.6727, 1889),Vanilla mBERT minmax:(-0.6631, 1889),Avg Readability Formula: (-0.6877, 1889),Vanilla Readability Formula: (-0.6582, 1889),Average Readability Formula minmax:(-0.6821, 1889), Vanilla Readability Formula minmax:(-0.673, 1889)
verbal conf weightings:
 AVG mBERT:(-0.6822, 1796),Vanilla mBERT:(-0.6589, 1796),Avg mBERT minmax:(-0.5319, 1796),Vanilla mBERT minmax:(-0.5278, 1796),Avg Readability Formula: (-0.6842, 1796),Vanilla Readability Formula:(-0.6613, 1796),Average Readability Formula minmax:(-0.5571, 1796),Vanilla Readability Formula minmax: (-0.5535, 1796)



AYA_8b
unweighted:
 AVG:(-0.5512, 1890),Vanilla:(-0.4953, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.5905, 1890),Vanilla mBERT:(-0.5683, 1890), AVG Readability Formula: (-0.6071, 1890), Vanilla Readability Formula: (-0.5851, 1890)
entropy weightings:
 AVG mBERT:(-0.5575, 1890),Vanilla mBERT:(-0.506, 1890),Avg mBERT minmax:(-0.5794, 1890),Vanilla mBERT minmax:(-0.5641, 1890),Avg Readability Formula: (-0.5583, 1890),Vanilla Readability Formula: (-0.5067, 1890),Average Readability Formula minmax:(-0.5883, 1890), Vanilla Readability Formula minmax:(-0.5732, 1890)




noscale_aya_8b
unweighted:
 AVG:(-0.5636, 1890),Vanilla:(-0.5356, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6048, 1890),Vanilla mBERT:(-0.596, 1890), AVG Readability Formula: (-0.6253, 1890), Vanilla Readability Formula: (-0.6168, 1890)
entropy weightings:
 AVG mBERT:(-0.574, 1890),Vanilla mBERT:(-0.5492, 1890),Avg mBERT minmax:(-0.6048, 1890),Vanilla mBERT minmax:(-0.5993, 1890),Avg Readability Formula: (-0.5759, 1890),Vanilla Readability Formula: (-0.5512, 1890),Average Readability Formula minmax:(-0.621, 1890), Vanilla Readability Formula minmax:(-0.6161, 1890)




gemma_9B
unweighted:
 AVG:(-0.6977, 1890),Vanilla:(-0.6841, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)

naive weightings:
 AVG mBERT:(-0.6603, 1890),Vanilla mBERT:(-0.655, 1890), AVG Readability Formula: (-0.6605, 1890), Vanilla Readability Formula: (-0.6558, 1890)
entropy weightings:
 AVG mBERT:(-0.6999, 1890),Vanilla mBERT:(-0.6873, 1890),Avg mBERT minmax:(-0.6428, 1890),Vanilla mBERT minmax:(-0.6395, 1890),Avg Readability Formula: (-0.6989, 1890),Vanilla Readability Formula: (-0.6865, 1890),Average Readability Formula minmax:(-0.649, 1890), Vanilla Readability Formula minmax:(-0.646, 1890)




noscale_gemma_9b
unweighted:
 AVG:(-0.7496, 1890),Vanilla:(-0.731, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.686, 1890),Vanilla mBERT:(-0.6802, 1890), AVG Readability Formula: (-0.6934, 1890), Vanilla Readability Formula: (-0.688, 1890)
entropy weightings:
 AVG mBERT:(-0.7505, 1890),Vanilla mBERT:(-0.7337, 1890),Avg mBERT minmax:(-0.6847, 1890),Vanilla mBERT minmax:(-0.6789, 1890),Avg Readability Formula: (-0.7504, 1890),Vanilla Readability Formula: (-0.7336, 1890),Average Readability Formula minmax:(-0.6948, 1890), Vanilla Readability Formula minmax:(-0.6895, 1890)




conf_noscale_gemma_9b
unweighted:
 AVG:(-0.7422, 1890),Vanilla:(-0.7189, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.684, 1890),Vanilla mBERT:(-0.6771, 1890), AVG Readability Formula: (-0.6921, 1890), Vanilla Readability Formula: (-0.6863, 1890)
entropy weightings:
 AVG mBERT:(-0.7437, 1890),Vanilla mBERT:(-0.7229, 1890),Avg mBERT minmax:(-0.6772, 1890),Vanilla mBERT minmax:(-0.6704, 1890),Avg Readability Formula: (-0.7436, 1890),Vanilla Readability Formula: (-0.723, 1890),Average Readability Formula minmax:(-0.6874, 1890), Vanilla Readability Formula minmax:(-0.6816, 1890)
verbal conf weightings:
 AVG mBERT:(-0.7359, 1890),Vanilla mBERT:(-0.7206, 1890),Avg mBERT minmax:(-0.7181, 1890),Vanilla mBERT minmax:(-0.7076, 1890),Avg Readability Formula: (-0.7368, 1890),Vanilla Readability Formula:(-0.7222, 1890),Average Readability Formula minmax:(-0.7218, 1890),Vanilla Readability Formula minmax: (-0.7121, 1890)



conf_gemma_9b
unweighted:
 AVG:(-0.7099, 1890),Vanilla:(-0.697, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6673, 1890),Vanilla mBERT:(-0.6632, 1890), AVG Readability Formula: (-0.6667, 1890), Vanilla Readability Formula: (-0.6626, 1890)
entropy weightings:
 AVG mBERT:(-0.7122, 1890),Vanilla mBERT:(-0.7003, 1890),Avg mBERT minmax:(-0.6488, 1890),Vanilla mBERT minmax:(-0.6457, 1890),Avg Readability Formula: (-0.711, 1890),Vanilla Readability Formula: (-0.6991, 1890),Average Readability Formula minmax:(-0.6548, 1890), Vanilla Readability Formula minmax:(-0.6516, 1890)
verbal conf weightings:
 AVG mBERT:(-0.7089, 1890),Vanilla mBERT:(-0.7, 1890),Avg mBERT minmax:(-0.6438, 1890),Vanilla mBERT minmax:(-0.6409, 1890),Avg Readability Formula: (-0.7043, 1890),Vanilla Readability Formula:(-0.6955, 1890),Average Readability Formula minmax:(-0.6465, 1890),Vanilla Readability Formula minmax: (-0.6436, 1890)



phi
unweighted:
 AVG:(-0.7571, 1890),Vanilla:(-0.7344, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.7004, 1890),Vanilla mBERT:(-0.6912, 1890), AVG Readability Formula: (-0.6972, 1890), Vanilla Readability Formula: (-0.6884, 1890)
entropy weightings:
 AVG mBERT:(-0.7601, 1890),Vanilla mBERT:(-0.7408, 1890),Avg mBERT minmax:(-0.6211, 1890),Vanilla mBERT minmax:(-0.6161, 1890),Avg Readability Formula: (-0.7557, 1890),Vanilla Readability Formula: (-0.7366, 1890),Average Readability Formula minmax:(-0.6283, 1890), Vanilla Readability Formula minmax:(-0.6234, 1890)




noscale_phi
unweighted:
 AVG:(-0.7517, 1890),Vanilla:(-0.7313, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.7016, 1890),Vanilla mBERT:(-0.6947, 1890), AVG Readability Formula: (-0.7048, 1890), Vanilla Readability Formula: (-0.6983, 1890)
entropy weightings:
 AVG mBERT:(-0.7558, 1890),Vanilla mBERT:(-0.7384, 1890),Avg mBERT minmax:(-0.7028, 1890),Vanilla mBERT minmax:(-0.6967, 1890),Avg Readability Formula: (-0.7546, 1890),Vanilla Readability Formula: (-0.7372, 1890),Average Readability Formula minmax:(-0.7071, 1890), Vanilla Readability Formula minmax:(-0.7012, 1890)




conf_noscale_phi
unweighted:
 AVG:(-0.7718, 1890),Vanilla:(-0.7481, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.708, 1890),Vanilla mBERT:(-0.699, 1890), AVG Readability Formula: (-0.7164, 1890), Vanilla Readability Formula: (-0.7078, 1890)
entropy weightings:
 AVG mBERT:(-0.7739, 1890),Vanilla mBERT:(-0.7531, 1890),Avg mBERT minmax:(-0.7189, 1890),Vanilla mBERT minmax:(-0.7113, 1890),Avg Readability Formula: (-0.774, 1890),Vanilla Readability Formula: (-0.7533, 1890),Average Readability Formula minmax:(-0.7289, 1890), Vanilla Readability Formula minmax:(-0.7217, 1890)
verbal conf weightings:
 AVG mBERT:(-0.765, 1890),Vanilla mBERT:(-0.7482, 1890),Avg mBERT minmax:(-0.6422, 1890),Vanilla mBERT minmax:(-0.6354, 1890),Avg Readability Formula: (-0.7657, 1890),Vanilla Readability Formula:(-0.7493, 1890),Average Readability Formula minmax:(-0.6536, 1890),Vanilla Readability Formula minmax: (-0.6471, 1890)



conf_phi
unweighted:
 AVG:(-0.7632, 1890),Vanilla:(-0.7351, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.7026, 1890),Vanilla mBERT:(-0.6904, 1890), AVG Readability Formula: (-0.7007, 1890), Vanilla Readability Formula: (-0.6898, 1890)
entropy weightings:
 AVG mBERT:(-0.7651, 1890),Vanilla mBERT:(-0.7404, 1890),Avg mBERT minmax:(-0.6291, 1890),Vanilla mBERT minmax:(-0.6225, 1890),Avg Readability Formula: (-0.7613, 1890),Vanilla Readability Formula: (-0.7373, 1890),Average Readability Formula minmax:(-0.6361, 1890), Vanilla Readability Formula minmax:(-0.6302, 1890)
verbal conf weightings:
 AVG mBERT:(-0.7566, 1890),Vanilla mBERT:(-0.7361, 1890),Avg mBERT minmax:(-0.6326, 1890),Vanilla mBERT minmax:(-0.6284, 1890),Avg Readability Formula: (-0.7499, 1890),Vanilla Readability Formula:(-0.7306, 1890),Average Readability Formula minmax:(-0.6347, 1890),Vanilla Readability Formula minmax: (-0.6311, 1890)



mixtral
unweighted:
 AVG:(-0.6356, 1890),Vanilla:(-0.6242, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6401, 1890),Vanilla mBERT:(-0.6349, 1890), AVG Readability Formula: (-0.6395, 1890), Vanilla Readability Formula: (-0.6346, 1890)
entropy weightings:
 AVG mBERT:(-0.6395, 1890),Vanilla mBERT:(-0.629, 1890),Avg mBERT minmax:(-0.6339, 1890),Vanilla mBERT minmax:(-0.6301, 1890),Avg Readability Formula: (-0.6384, 1890),Vanilla Readability Formula: (-0.6279, 1890),Average Readability Formula minmax:(-0.6311, 1890), Vanilla Readability Formula minmax:(-0.6272, 1890)




noscale_mixtral
unweighted:
 AVG:(-0.6701, 1890),Vanilla:(-0.6513, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6679, 1890),Vanilla mBERT:(-0.6589, 1890), AVG Readability Formula: (-0.686, 1890), Vanilla Readability Formula: (-0.6774, 1890)
entropy weightings:
 AVG mBERT:(-0.6746, 1890),Vanilla mBERT:(-0.6575, 1890),Avg mBERT minmax:(-0.666, 1890),Vanilla mBERT minmax:(-0.6603, 1890),Avg Readability Formula: (-0.6756, 1890),Vanilla Readability Formula: (-0.6585, 1890),Average Readability Formula minmax:(-0.6767, 1890), Vanilla Readability Formula minmax:(-0.6713, 1890)




conf_noscale_mixtral
unweighted:
 AVG:(-0.7074, 1890),Vanilla:(-0.6913, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6777, 1890),Vanilla mBERT:(-0.6711, 1890), AVG Readability Formula: (-0.6939, 1890), Vanilla Readability Formula: (-0.688, 1890)
entropy weightings:
 AVG mBERT:(-0.7094, 1890),Vanilla mBERT:(-0.695, 1890),Avg mBERT minmax:(-0.6831, 1890),Vanilla mBERT minmax:(-0.679, 1890),Avg Readability Formula: (-0.7106, 1890),Vanilla Readability Formula: (-0.6963, 1890),Average Readability Formula minmax:(-0.6952, 1890), Vanilla Readability Formula minmax:(-0.6917, 1890)
verbal conf weightings:
 AVG mBERT:(-0.7133, 1890),Vanilla mBERT:(-0.701, 1890),Avg mBERT minmax:(-0.6533, 1890),Vanilla mBERT minmax:(-0.6465, 1890),Avg Readability Formula: (-0.7182, 1890),Vanilla Readability Formula:(-0.7063, 1890),Average Readability Formula minmax:(-0.6661, 1890),Vanilla Readability Formula minmax: (-0.6597, 1890)



conf_mixtral
unweighted:
 AVG:(-0.6958, 1890),Vanilla:(-0.682, 1890),RSRS:(-0.4836, 1890),Readability Formula: (-0.5168, 1890)
naive weightings:
 AVG mBERT:(-0.6645, 1890),Vanilla mBERT:(-0.6591, 1890), AVG Readability Formula: (-0.6625, 1890), Vanilla Readability Formula: (-0.6577, 1890)
entropy weightings:
 AVG mBERT:(-0.6985, 1890),Vanilla mBERT:(-0.6858, 1890),Avg mBERT minmax:(-0.6811, 1890),Vanilla mBERT minmax:(-0.6756, 1890),Avg Readability Formula: (-0.6968, 1890),Vanilla Readability Formula: (-0.6842, 1890),Average Readability Formula minmax:(-0.6763, 1890), Vanilla Readability Formula minmax:(-0.6711, 1890)
verbal conf weightings:
 AVG mBERT:(-0.7019, 1889),Vanilla mBERT:(-0.6914, 1889),Avg mBERT minmax:(-0.6507, 1889),Vanilla mBERT minmax:(-0.646, 1889),Avg Readability Formula: (-0.6964, 1889),Vanilla Readability Formula:(-0.6864, 1889),Average Readability Formula minmax:(-0.651, 1889),Vanilla Readability Formula minmax: (-0.6468, 1889)

## Greek Language

In [12]:
greeklangv2=pd.read_csv('.../greek_languagev2.csv')
greeklangv2

,Unnamed: 0,index,ID,text,course,level,AYA_8B_vanilla,AYA_8B_avg,AYA_8B_entropy,AYA_32B_vanilla,...,noscale_AYA_8B_avg,noscale_AYA_8B_entropy,conf_noscale_aya_32B_vanilla,conf_noscale_aya_32B_avg,conf_noscale_aya_32B_entropy,conf_noscale_aya_32B_verbal_conf,conf_aya_32B_vanilla,conf_aya_32B_avg,conf_aya_32B_entropy,conf_aya_32B_verbal_conf
0,0,59,60,Τα Λαζαράκια\n Το Σάββατο του Λαζάρου τα παιδι...,language,4,3,2.979679,0.007984,3,...,3.274760051127032,0.050514,5,4.920538067348389,0.031053,7.000135879032314,3,3.268951,0.046758,7.320815
1,1,59,60,Τι θα κάνουμε; Πώς θα τους σταματήσουμε;\n Πόσ...,language,6,3,3.609034,0.062214,3,...,6.327549156150781,0.086019,5,4.805657120872411,0.043500,7.025880647372105,3,3.054302,0.017052,7.946597
2,2,11,12,w Ουσιαστικό (ατμός)\n w Επίθετο (ωφέλιμο)\n w...,language,4,3,3.068705,0.021183,4,...,4.283539172960445,0.086496,7,6.945453002,0.017236,7.998817222,4,3.906138,0.026070,7.957911
3,3,21,22,Ποιο ήταν το επάγγελμα του κυρ Παντελή;\n Τι τ...,language,2,2,2.053411,0.016742,3,...,2.9739450391498394,0.065796,3,3.4746785436767595,0.057537,7.3486254635200225,3,3.000224,0.000180,7.962673
4,4,26,27,νια ήταν η νεροσφυρίχτρα. Είναι ένα είδος σφυρ...,language,2,3,2.989026,0.004866,3,...,3.392677454009572,0.058608,5,4.827002798112517,0.041625,7.000093932438176,3,3.000627,0.000422,7.622457
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,388,47,48,ENOTHTA\n Ένας Αρλεκίνος από χαρτί\n Η παράστα...,language,4,3,3.023611,0.008395,3,...,3.4003600906544307,0.060216,5,4.986258894963157,0.021276,7.004568575503072,3,3.007579,0.003579,7.966913
389,389,15,16,"Διπλή γιορτή\n Μια χρονιά, όταν ακόμα οι Έλλην...",language,6,5,4.608131,0.063791,4,...,4.1864501811623995,0.049322,5,5.027905111529265,0.019676,7.000707050290657,4,4.001217,0.001591,7.562173
390,390,47,48,O λύκος μοιάζει με μεγάλο σκύλο. Έχει ψηλά πόδ...,language,2,3,2.947054,0.017022,3,...,2.945402805456979,0.058176,3,3.4471686128109695,0.057896,7.924140998469966,3,3.001169,0.000729,7.995930
391,391,24,25,Το άγαλμα που κρύωνε\n Το μικρό μαρμάρινο αγόρ...,language,6,4,3.933978,0.047654,4,...,2.988237233160703,0.032408,5,4.777656154271199,0.042945,7.000275619182503,4,3.992562,0.003687,7.754913
392,392,55,56,"ENOTHTA\n Πρώτη φορά στο θέατρο\n Η Ελευθερία,...",language,4,4,3.669324,0.056932,3,...,2.8698371088003114,0.039636,5,4.647064031920195,0.053321,7.001667469623499,3,3.437829,0.055045,7.867035

In [13]:
greeklangv2 = greeklangv2.replace("na", np.nan)

In [14]:
greeklangv2.columns

Index(['Unnamed: 0', 'index', 'ID', 'text', 'course', 'level',
       'AYA_8B_vanilla', 'AYA_8B_avg', 'AYA_8B_entropy', 'AYA_32B_vanilla',
       'AYA_32B_avg', 'AYA_32B_entropy', 'noscale_AYA_32B_vanilla',
       'noscale_AYA_32B_avg', 'noscale_AYA_32B_entropy',
       'noscale_AYA_8B_vanilla', 'noscale_AYA_8B_avg',
       'noscale_AYA_8B_entropy', 'conf_noscale_aya_32B_vanilla',
       'conf_noscale_aya_32B_avg', 'conf_noscale_aya_32B_entropy',
       'conf_noscale_aya_32B_verbal_conf', 'conf_aya_32B_vanilla',
       'conf_aya_32B_avg', 'conf_aya_32B_entropy', 'conf_aya_32B_verbal_conf',
       'FKGL', 'ARI', 'LIX', 'RSRS_mBERT'],
      dtype='object')

In [15]:
ref_col = greeklangv2.columns[5]
for i in range(6, len(greeklangv2.columns)):  
    col = greeklangv2.columns[i]
    corr = greeklangv2[ref_col].astype(float).corr(greeklangv2[col].astype(float))
    if ('entropy' not in col) and ('verbal_conf' not in col):
        print(f"{i+1}: {col} -> correlation with {ref_col}: {corr:.4f}")

7: AYA_8B_vanilla -> correlation with level: 0.2814
8: AYA_8B_avg -> correlation with level: 0.3282
10: AYA_32B_vanilla -> correlation with level: 0.4893
11: AYA_32B_avg -> correlation with level: 0.5177
13: noscale_AYA_32B_vanilla -> correlation with level: 0.3889
14: noscale_AYA_32B_avg -> correlation with level: 0.4118
16: noscale_AYA_8B_vanilla -> correlation with level: 0.1747
17: noscale_AYA_8B_avg -> correlation with level: 0.1965
19: conf_noscale_aya_32B_vanilla -> correlation with level: 0.4270
20: conf_noscale_aya_32B_avg -> correlation with level: 0.4361
23: conf_aya_32B_vanilla -> correlation with level: 0.4978
24: conf_aya_32B_avg -> correlation with level: 0.5071
27: FKGL -> correlation with level: 0.0920
28: ARI -> correlation with level: 0.1621
29: LIX -> correlation with level: 0.1203
30: RSRS_mBERT -> correlation with level: 0.1159

In [17]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
rf_string='ARI'
greeklangv2 = greeklangv2.apply(pd.to_numeric, errors="coerce")
std_cols = [c for c in greeklangv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
greeklangv2[std_cols] = StandardScaler().fit_transform(greeklangv2[std_cols])
model='conf_noscale_aya_32B'
vconf_col=f'{model}_verbal_conf'
avg_col = f"{model}_avg"


verbal_avg_rf=((1 - greeklangv2[vconf_col]/10) * greeklangv2[rf_string]) + (greeklangv2[vconf_col]/10 * greeklangv2[avg_col])


rjk,n1=safe_corr_raw(verbal_avg_rf, greeklangv2.iloc[:,5])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(greeklangv2.iloc[:,18], greeklangv2.iloc[:,5])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,greeklangv2.iloc[:,18])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs LLM : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, greeklangv2.iloc[:,5])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(greeklangv2[rf_string], greeklangv2.iloc[:,5])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,greeklangv2[rf_string])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RF : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, greeklangv2.iloc[:,5])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(greeklangv2['RSRS_mBERT'], greeklangv2.iloc[:,5])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,greeklangv2['RSRS_mBERT'])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RSRS : t2:{res1[0]}, p:{res1[1]}')

0.4301974497920238 0.42700382657964037 0.921069852713392
389
t_test: Vconf RF vs LLM : t2:0.17557814601311658, p:0.8607174410415217
0.4301974497920238 0.16212675560615683 0.4944828486247542
389
t_test: Vconf RF vs RF : t2:5.787854705356211, p:1.4769994338692527e-08
0.4301974497920238 0.11589948839330336 0.32485497075227765
389
t_test: Vconf RF vs RSRS : t2:5.843255476816767, p:1.0892786450611425e-08

In [18]:
import numpy as np
greeklangv2 = greeklangv2.apply(pd.to_numeric, errors="coerce")
rjk,n1=safe_corr_raw(greeklangv2.iloc[:,19], greeklangv2.iloc[:,5])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(greeklangv2.iloc[:,18], greeklangv2.iloc[:,5])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(greeklangv2.iloc[:,19],greeklangv2.iloc[:,18])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Expected vs Vanilla : t2:{res1[0]}, p:{res1[1]}')

0.4361486284819588 0.42700382657964037 0.9676916068590465
389
t_test: Expected vs Vanilla : t2:0.7856033163084873, p:0.43258187051770447

In [19]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
greeklangv2 = greeklangv2.apply(pd.to_numeric, errors="coerce")
rf_string='ARI'
ref_col = greeklangv2.columns[5]
entropy_cols = [c for c in greeklangv2.columns if c.endswith("_entropy")]
entropy_cols_minmax = [c + "_minmax" for c in entropy_cols]
greeklangv2[entropy_cols_minmax] = MinMaxScaler().fit_transform(greeklangv2[entropy_cols])

vconf_cols = [c for c in greeklangv2.columns if c.endswith("verbal_conf")]
vconf_cols_minmax = [c + "_minmax" for c in vconf_cols]
greeklangv2[vconf_cols_minmax] = MinMaxScaler().fit_transform(greeklangv2[vconf_cols])
greeklangv2[vconf_cols] = greeklangv2[vconf_cols]/10

std_cols = [c for c in greeklangv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
greeklangv2[std_cols] = StandardScaler().fit_transform(greeklangv2[std_cols])
suffixes = ["_avg", "_vanilla", "_entropy"]
models = set(
    c.rsplit("_", 1)[0]  # remove the last part after the final underscore
    for c in entropy_cols  # for any column list containing these suffixes
)
sorted_models = sorted(models, key=lambda x: x[::-1].lower())
for model in sorted_models:
    print(model)
    vanilla_col = f"{model}_vanilla"
    avg_col = f"{model}_avg"
    print(f'unweighted:\n AVG:{safe_corr(greeklangv2[avg_col], greeklangv2[ref_col])},Vanilla:{safe_corr(greeklangv2[vanilla_col], greeklangv2[ref_col])},RSRS:{safe_corr(greeklangv2["RSRS_mBERT"], greeklangv2[ref_col])},Readability Formula: {safe_corr(greeklangv2[rf_string], greeklangv2[ref_col])}')
    naive_avg_mBERT=greeklangv2[avg_col]+greeklangv2["RSRS_mBERT"]
    naive_vanilla_mBERT=greeklangv2[vanilla_col]+greeklangv2["RSRS_mBERT"]
    
    naive_avg_rf=greeklangv2[avg_col]+greeklangv2[rf_string]
    naive_vanilla_rf=greeklangv2[vanilla_col]+greeklangv2[rf_string]
    print(f'naive weightings: \n AVG mBERT:{safe_corr(naive_avg_mBERT, greeklangv2[ref_col])},Vanilla mBERT:{safe_corr(naive_vanilla_mBERT, greeklangv2[ref_col])}, AVG Readability Formula: {safe_corr(naive_avg_rf, greeklangv2[ref_col])}, Vanilla Readability Formula: {safe_corr(naive_vanilla_rf, greeklangv2[ref_col])}')
    entropy_col = f"{model}_entropy"
    entropy_col_minmax = f"{model}_entropy_minmax"
    if model.startswith('conf_'):
        vconf_col=f'{model}_verbal_conf'
        vconf_col_minmax = f"{model}_verbal_conf_minmax"
    
    entropy_avg_mBERT=(greeklangv2[entropy_col] * greeklangv2["RSRS_mBERT"]) + ((1 - greeklangv2[entropy_col]) * greeklangv2[avg_col])
    entropy_vanilla_mBERT=(greeklangv2[entropy_col] * greeklangv2["RSRS_mBERT"]) + ((1 - greeklangv2[entropy_col]) * greeklangv2[vanilla_col])
    entropy_minmax_avg_mBERT=(greeklangv2[entropy_col_minmax] * greeklangv2["RSRS_mBERT"]) + ((1 - greeklangv2[entropy_col_minmax]) * greeklangv2[avg_col])
    entropy_minmax_vanilla_mBERT=(greeklangv2[entropy_col_minmax] * greeklangv2["RSRS_mBERT"]) + ((1 - greeklangv2[entropy_col_minmax]) * greeklangv2[vanilla_col])
    
    entropy_avg_rf=(greeklangv2[entropy_col] * greeklangv2[rf_string]) + ((1 - greeklangv2[entropy_col]) * greeklangv2[avg_col])
    entropy_vanilla_rf=(greeklangv2[entropy_col] * greeklangv2[rf_string]) + ((1 - greeklangv2[entropy_col]) * greeklangv2[vanilla_col])
    entropy_minmax_avg_rf=(greeklangv2[entropy_col_minmax] * greeklangv2[rf_string]) + ((1 - greeklangv2[entropy_col_minmax]) * greeklangv2[avg_col])
    entropy_minmax_vanilla_rf=(greeklangv2[entropy_col_minmax] * greeklangv2[rf_string]) + ((1 - greeklangv2[entropy_col_minmax]) * greeklangv2[vanilla_col])
    print(f'entropy weightings:\n AVG mBERT:{safe_corr(entropy_avg_mBERT, greeklangv2[ref_col])},Vanilla mBERT:{safe_corr(entropy_vanilla_mBERT, greeklangv2[ref_col])},Avg mBERT minmax:{safe_corr(entropy_minmax_avg_mBERT, greeklangv2[ref_col])},Vanilla mBERT minmax:{safe_corr(entropy_minmax_vanilla_mBERT, greeklangv2[ref_col])},Avg Readability Formula: {safe_corr(entropy_avg_rf, greeklangv2[ref_col])},Vanilla Readability Formula: {safe_corr(entropy_vanilla_rf, greeklangv2[ref_col])},Average Readability Formula minmax:{safe_corr(entropy_minmax_avg_rf, greeklangv2[ref_col])}, Vanilla Readability Formula minmax:{safe_corr(entropy_minmax_vanilla_rf, greeklangv2[ref_col])}')
    if model.startswith('conf_'):
        verbal_avg_mBERT=((1 - greeklangv2[vconf_col]) * greeklangv2["RSRS_mBERT"]) + (greeklangv2[vconf_col] * greeklangv2[avg_col])
        verbal_vanilla_mBERT=((1 - greeklangv2[vconf_col]) * greeklangv2["RSRS_mBERT"]) + (greeklangv2[vconf_col] * greeklangv2[vanilla_col])
        verbal_minmax_avg_mBERT=((1 - greeklangv2[vconf_col_minmax]) * greeklangv2["RSRS_mBERT"]) + (greeklangv2[vconf_col_minmax] * greeklangv2[avg_col])
        verbal_minmax_vanilla_mBERT=((1 - greeklangv2[vconf_col_minmax]) * greeklangv2["RSRS_mBERT"]) + (greeklangv2[vconf_col_minmax] * greeklangv2[vanilla_col])
        
        verbal_avg_rf=((1 - greeklangv2[vconf_col]) * greeklangv2[rf_string]) + (greeklangv2[vconf_col] * greeklangv2[avg_col])
        verbal_vanilla_rf=((1 - greeklangv2[vconf_col]) * greeklangv2[rf_string]) + (greeklangv2[vconf_col] * greeklangv2[vanilla_col])
        verbal_minmax_avg_rf=((1 - greeklangv2[vconf_col_minmax]) * greeklangv2[rf_string]) + (greeklangv2[vconf_col_minmax] * greeklangv2[avg_col])
        verbal_minmax_vanilla_rf=((1 - greeklangv2[vconf_col_minmax]) * greeklangv2[rf_string]) + (greeklangv2[vconf_col_minmax] * greeklangv2[vanilla_col])
        print(f'verbal conf weightings:\n AVG mBERT:{safe_corr(verbal_avg_mBERT, greeklangv2[ref_col])},Vanilla mBERT:{safe_corr(verbal_vanilla_mBERT, greeklangv2[ref_col])},Avg mBERT minmax:{safe_corr(verbal_minmax_avg_mBERT, greeklangv2[ref_col])},Vanilla mBERT minmax:{safe_corr(verbal_minmax_vanilla_mBERT, greeklangv2[ref_col])},Avg Readability Formula: {safe_corr(verbal_avg_rf, greeklangv2[ref_col])},Vanilla Readability Formula:{safe_corr(verbal_vanilla_rf, greeklangv2[ref_col])},Average Readability Formula minmax:{safe_corr(verbal_minmax_avg_rf, greeklangv2[ref_col])},Vanilla Readability Formula minmax: {safe_corr(verbal_minmax_vanilla_rf, greeklangv2[ref_col])}','\n \n \n')
    else:
        print('\n \n \n')

AYA_32B
unweighted:
 AVG:(0.5177, 393),Vanilla:(0.4893, 393),RSRS:(0.1159, 393),Readability Formula: (0.1621, 393)
naive weightings:
 AVG mBERT:(0.4234, 393),Vanilla mBERT:(0.4051, 393), AVG Readability Formula: (0.4432, 393), Vanilla Readability Formula: (0.4278, 393)
entropy weightings:
 AVG mBERT:(0.5191, 393),Vanilla mBERT:(0.4921, 393),Avg mBERT minmax:(0.5032, 393),Vanilla mBERT minmax:(0.4929, 393),Avg Readability Formula: (0.5196, 393),Vanilla Readability Formula: (0.4929, 393),Average Readability Formula minmax:(0.5067, 393), Vanilla Readability Formula minmax:(0.4979, 393)




noscale_AYA_32B
unweighted:
 AVG:(0.4118, 388),Vanilla:(0.3889, 388),RSRS:(0.1159, 393),Readability Formula: (0.1621, 393)
naive weightings:
 AVG mBERT:(0.3559, 388),Vanilla mBERT:(0.3445, 388), AVG Readability Formula: (0.3711, 388), Vanilla Readability Formula: (0.3593, 388)
entropy weightings:
 AVG mBERT:(0.4134, 388),Vanilla mBERT:(0.3921, 388),Avg mBERT minmax:(0.3729, 388),Vanilla mBERT minmax:(0.3649, 388),Avg Readability Formula: (0.413, 388),Vanilla Readability Formula: (0.3915, 388),Average Readability Formula minmax:(0.3745, 388), Vanilla Readability Formula minmax:(0.3659, 388)




conf_noscale_aya_32B
unweighted:
 AVG:(0.4361, 389),Vanilla:(0.427, 389),RSRS:(0.1159, 393),Readability Formula: (0.1621, 393)
naive weightings:
 AVG mBERT:(0.3723, 389),Vanilla mBERT:(0.3682, 389), AVG Readability Formula: (0.3859, 389), Vanilla Readability Formula: (0.3806, 389)
entropy weightings:
 AVG mBERT:(0.4381, 389),Vanilla mBERT:(0.4303, 389),Avg mBERT minmax:(0.369, 389),Vanilla mBERT minmax:(0.3687, 389),Avg Readability Formula: (0.4371, 389),Vanilla Readability Formula: (0.4289, 389),Average Readability Formula minmax:(0.3726, 389), Vanilla Readability Formula minmax:(0.3717, 389)
verbal conf weightings:
 AVG mBERT:(0.4285, 389),Vanilla mBERT:(0.4225, 389),Avg mBERT minmax:(0.4312, 389),Vanilla mBERT minmax:(0.4242, 389),Avg Readability Formula: (0.4302, 389),Vanilla Readability Formula:(0.4233, 389),Average Readability Formula minmax:(0.43, 389),Vanilla Readability Formula minmax: (0.4226, 389)



conf_aya_32B
unweighted:
 AVG:(0.5071, 393),Vanilla:(0.4978, 393),RSRS:(0.1159, 393),Readability Formula: (0.1621, 393)
naive weightings:
 AVG mBERT:(0.4155, 393),Vanilla mBERT:(0.4069, 393), AVG Readability Formula: (0.4342, 393), Vanilla Readability Formula: (0.4278, 393)
entropy weightings:
 AVG mBERT:(0.5094, 393),Vanilla mBERT:(0.5007, 393),Avg mBERT minmax:(0.5085, 393),Vanilla mBERT minmax:(0.5042, 393),Avg Readability Formula: (0.5093, 393),Vanilla Readability Formula: (0.5008, 393),Average Readability Formula minmax:(0.5073, 393), Vanilla Readability Formula minmax:(0.5035, 393)
verbal conf weightings:
 AVG mBERT:(0.5058, 393),Vanilla mBERT:(0.4952, 393),Avg mBERT minmax:(0.4681, 393),Vanilla mBERT minmax:(0.4606, 393),Avg Readability Formula: (0.5096, 393),Vanilla Readability Formula:(0.5007, 393),Average Readability Formula minmax:(0.482, 393),Vanilla Readability Formula minmax: (0.4755, 393)



AYA_8B
unweighted:
 AVG:(0.3282, 393),Vanilla:(0.2814, 393),RSRS:(0.1159, 393),Readability Formula: (0.1621, 393)
naive weightings:
 AVG mBERT:(0.293, 393),Vanilla mBERT:(0.2629, 393), AVG Readability Formula: (0.338, 393), Vanilla Readability Formula: (0.3076, 393)
entropy weightings:
 AVG mBERT:(0.3274, 393),Vanilla mBERT:(0.2834, 393),Avg mBERT minmax:(0.2621, 393),Vanilla mBERT minmax:(0.2526, 393),Avg Readability Formula: (0.3292, 393),Vanilla Readability Formula: (0.2853, 393),Average Readability Formula minmax:(0.2823, 393), Vanilla Readability Formula minmax:(0.2745, 393)




noscale_AYA_8B
unweighted:
 AVG:(0.1965, 387),Vanilla:(0.1747, 387),RSRS:(0.1159, 393),Readability Formula: (0.1621, 393)
naive weightings:
 AVG mBERT:(0.2145, 387),Vanilla mBERT:(0.2016, 387), AVG Readability Formula: (0.2453, 387), Vanilla Readability Formula: (0.2339, 387)
entropy weightings:
 AVG mBERT:(0.2039, 387),Vanilla mBERT:(0.1836, 387),Avg mBERT minmax:(0.2131, 387),Vanilla mBERT minmax:(0.2101, 387),Avg Readability Formula: (0.2064, 387),Vanilla Readability Formula: (0.1865, 387),Average Readability Formula minmax:(0.2419, 387), Vanilla Readability Formula minmax:(0.2403, 387)

## Greek History

In [20]:
greekhistv2=pd.read_csv('.../greekhistoryv2.csv')

,Unnamed: 0,index,ID,text,course,level,AYA_8B_normal_R1,AYA_8B_normal_R2,AYA_8B_normal_R3,AYA_8B_normal_R4,...,AYA_32B_own_R2,AYA_32B_own_R3,AYA_32B_own_R4,AYA_32B_own_R5,FKGL,ARI,LIX,RSRS_BERT,RSRS_XLMR,RSRS_mBERT
0,0,47,48,Κυριαρχία\n ενυπάρχει εις το Έθνος· πάσα εξουσ...,history,12,8.0,8.0,8.0,8.0,...,9.0,9.0,9.0,9.0,2.8,14.3,47.451480,0.001367,0.000323,0.000975
1,1,13,14,Ένας νεολιθικός\n είναι κατασκευασμένα από κλα...,history,10,8.0,8.0,8.0,8.0,...,6.0,6.0,6.0,6.0,1.9,14.0,45.485904,0.001179,0.000292,0.000924
2,2,173,174,"Μανολιό μου,\n Σε λίγες μέρες θα ξημερώσει 14\...",history,4,6.0,6.0,6.0,6.0,...,5.0,5.0,5.0,5.0,1.4,9.3,38.960976,0.001248,0.000304,0.000932
3,3,87,88,Ματιά στο παρελθόν\n Η πρώτη αναγνώριση της «α...,history,6,6.0,6.0,6.0,6.0,...,7.0,7.0,7.0,7.0,7.6,20.7,67.101145,0.001632,0.000425,0.001406
4,4,133,134,πολέμου. Σε αυτό συνέβαλε και η ίδρυση στη Μόσ...,history,12,8.0,8.0,8.0,8.0,...,9.0,9.0,9.0,9.0,1.8,14.0,45.957585,0.001115,0.000283,0.000841
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799,799,156,157,"1. ΗΠΑ, 1928:\n κατάρρευση των τιμών στο χρημα...",history,12,8.0,8.0,8.0,8.0,...,9.0,9.0,9.0,9.0,1.0,12.9,45.917230,0.001233,0.000297,0.000889
800,800,101,102,Ο στρατός των Πελοποννησίων έκανε εισβολή στην...,history,4,6.8,6.6,6.8,7.0,...,6.0,6.0,6.0,6.0,-0.1,8.3,37.005952,0.000866,0.000240,0.000651
801,801,26,27,ΕΝΟΤΗΤΑ 5\n Ο ελληνισμός από τα μέσα του 18ου ...,history,12,7.0,7.0,7.0,7.0,...,7.0,7.0,7.0,7.4,2.6,15.4,52.409945,0.001278,0.000309,0.000964
802,802,71,72,Οι μετακινήσεις πληθυσμών αναστάτωσαν\n τη ζωή...,history,10,6.0,6.0,6.0,6.0,...,6.0,6.0,6.0,6.0,2.4,14.5,55.500000,0.001303,0.000330,0.001107
803,803,202,203,προωθούν την κοινωνική δικαιοσύνη. Σύμφωνα με ...,history,12,6.0,6.0,6.0,6.0,...,7.0,7.0,7.0,7.0,4.4,15.9,61.647088,0.001346,0.000374,0.001266

In [21]:
greekhistv2 = greekhistv2.replace("na", np.nan)

In [22]:
ref_col = greekhistv2.columns[5]
for i in range(6, len(greekhistv2.columns)):  
    col = greekhistv2.columns[i]
    corr = greekhistv2[ref_col].astype(float).corr(greekhistv2[col].astype(float))
    if ('entropy' not in col) and ('verbal_conf' not in col):
        print(f"{i+1}: {col} -> correlation with {ref_col}: {corr:.4f}")

7: AYA_32B_vanilla -> correlation with level: 0.4398
8: AYA_32B_avg -> correlation with level: 0.4637
10: AYA_8B_vanilla -> correlation with level: 0.3052
11: AYA_8B_avg -> correlation with level: 0.3196
13: noscale_AYA_32B_vanilla -> correlation with level: 0.5309
14: noscale_AYA_32B_avg -> correlation with level: 0.5556
16: noscale_AYA_8B_vanilla -> correlation with level: 0.2977
17: noscale_AYA_8B_avg -> correlation with level: 0.3487
19: conf_aya_32B_vanilla -> correlation with level: 0.4116
20: conf_aya_32B_avg -> correlation with level: 0.4434
23: conf_noscale_aya_32B_vanilla -> correlation with level: 0.5201
24: conf_noscale_aya_32B_avg -> correlation with level: 0.5426
27: FKGL -> correlation with level: 0.1198
28: ARI -> correlation with level: 0.3725
29: LIX -> correlation with level: 0.2700
30: RSRS_mBERT -> correlation with level: 0.1627

In [23]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
greekhistv2 = greekhistv2.apply(pd.to_numeric, errors="coerce")
std_cols = [c for c in greekhistv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
greekhistv2[std_cols] = StandardScaler().fit_transform(greekhistv2[std_cols])
model='conf_noscale_aya_32B'
vconf_col=f'{model}_verbal_conf'
avg_col = f"{model}_avg"
rf_string='ARI'

verbal_avg_rf=((1 - greekhistv2[vconf_col]/10) * greekhistv2[rf_string]) + (greekhistv2[vconf_col]/10 * greekhistv2[avg_col])


rjk,n1=safe_corr_raw(verbal_avg_rf, greekhistv2.iloc[:,5])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(greekhistv2.iloc[:,22], greekhistv2.iloc[:,5])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,greekhistv2.iloc[:,22])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs LLM : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, greekhistv2.iloc[:,5])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(greekhistv2[rf_string], greekhistv2.iloc[:,5])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,greekhistv2[rf_string])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RF : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, greekhistv2.iloc[:,5])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(greekhistv2['RSRS_mBERT'], greekhistv2.iloc[:,5])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,greekhistv2['RSRS_mBERT'])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RSRS : t2:{res1[0]}, p:{res1[1]}')

0.5721283661887996 0.5201264779712057 0.9425813110196376
796
t_test: Vconf RF vs LLM : t2:5.280748763865377, p:1.6629210808360995e-07
0.5721283661887996 0.37253659025194674 0.599586700143115
796
t_test: Vconf RF vs RF : t2:7.602742374291172, p:8.193445921733655e-14
0.5721283661887996 0.16270645591587643 0.41272041482550487
796
t_test: Vconf RF vs RSRS : t2:12.87609921678819, p:0.0

In [24]:
import numpy as np
greekhistv2 = greekhistv2.apply(pd.to_numeric, errors="coerce")
rjk,n1=safe_corr_raw(greekhistv2.iloc[:,23], greekhistv2.iloc[:,5])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(greekhistv2.iloc[:,22], greekhistv2.iloc[:,5])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(greekhistv2.iloc[:,22],greekhistv2.iloc[:,23])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Expected vs Vanilla : t2:{res1[0]}, p:{res1[1]}')

0.54262372046157 0.5201264779712057 0.9705037370208598
796
t_test: Expected vs Vanilla : t2:3.1067383987946595, p:0.0019590465529659706

In [25]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
greekhistv2 = greekhistv2.apply(pd.to_numeric, errors="coerce")
rf_string='ARI'
ref_col = greekhistv2.columns[5]
#greekhistv2['RSRS_mBERT']= StandardScaler().fit_transform(greekhistv2['RSRS_mBERT'])
# Step 1: Normalize entropy columns
entropy_cols = [c for c in greekhistv2.columns if c.endswith("_entropy")]
entropy_cols_minmax = [c + "_minmax" for c in entropy_cols]
greekhistv2[entropy_cols_minmax] = MinMaxScaler().fit_transform(greekhistv2[entropy_cols])

vconf_cols = [c for c in greekhistv2.columns if c.endswith("verbal_conf")]
vconf_cols_minmax = [c + "_minmax" for c in vconf_cols]
greekhistv2[vconf_cols_minmax] = MinMaxScaler().fit_transform(greekhistv2[vconf_cols])
greekhistv2[vconf_cols] = greekhistv2[vconf_cols]/10

std_cols = [c for c in greekhistv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
greekhistv2[std_cols] = StandardScaler().fit_transform(greekhistv2[std_cols])
suffixes = ["_avg", "_vanilla", "_entropy"]
models = set(
    c.rsplit("_", 1)[0]  # remove the last part after the final underscore
    for c in entropy_cols  # or any column list containing these suffixes
)
sorted_models = sorted(models, key=lambda x: x[::-1].lower())
for model in sorted_models:
    print(model)
    vanilla_col = f"{model}_vanilla"
    avg_col = f"{model}_avg"
    print(f'unweighted:\n AVG:{safe_corr(greekhistv2[avg_col], greekhistv2[ref_col])},Vanilla:{safe_corr(greekhistv2[vanilla_col], greekhistv2[ref_col])},RSRS:{safe_corr(greekhistv2["RSRS_mBERT"], greekhistv2[ref_col])},Readability Formula: {safe_corr(greekhistv2[rf_string], greekhistv2[ref_col])}')
    naive_avg_mBERT=greekhistv2[avg_col]+greekhistv2["RSRS_mBERT"]
    naive_vanilla_mBERT=greekhistv2[vanilla_col]+greekhistv2["RSRS_mBERT"]
    
    naive_avg_rf=greekhistv2[avg_col]+greekhistv2[rf_string]
    naive_vanilla_rf=greekhistv2[vanilla_col]+greekhistv2[rf_string]
    print(f'naive weightings: \n AVG mBERT:{safe_corr(naive_avg_mBERT, greekhistv2[ref_col])},Vanilla mBERT:{safe_corr(naive_vanilla_mBERT, greekhistv2[ref_col])}, AVG Readability Formula: {safe_corr(naive_avg_rf, greekhistv2[ref_col])}, Vanilla Readability Formula: {safe_corr(naive_vanilla_rf, greekhistv2[ref_col])}')
    entropy_col = f"{model}_entropy"
    entropy_col_minmax = f"{model}_entropy_minmax"
    if model.startswith('conf_'):
        vconf_col=f'{model}_verbal_conf'
        vconf_col_minmax = f"{model}_verbal_conf_minmax"
    
    #greekhistv2[f"{model}_weighted"] = (
    #    greekhistv2[entropy_col] * greekhistv2["RSRS_mBERT"] + 
    #    (1 - greekhistv2[entropy_col]) * (greekhistv2[[vanilla_col, avg_col]].mean(axis=1))
    #)
    entropy_avg_mBERT=(greekhistv2[entropy_col] * greekhistv2["RSRS_mBERT"]) + ((1 - greekhistv2[entropy_col]) * greekhistv2[avg_col])
    entropy_vanilla_mBERT=(greekhistv2[entropy_col] * greekhistv2["RSRS_mBERT"]) + ((1 - greekhistv2[entropy_col]) * greekhistv2[vanilla_col])
    entropy_minmax_avg_mBERT=(greekhistv2[entropy_col_minmax] * greekhistv2["RSRS_mBERT"]) + ((1 - greekhistv2[entropy_col_minmax]) * greekhistv2[avg_col])
    entropy_minmax_vanilla_mBERT=(greekhistv2[entropy_col_minmax] * greekhistv2["RSRS_mBERT"]) + ((1 - greekhistv2[entropy_col_minmax]) * greekhistv2[vanilla_col])
    
    entropy_avg_rf=(greekhistv2[entropy_col] * greekhistv2[rf_string]) + ((1 - greekhistv2[entropy_col]) * greekhistv2[avg_col])
    entropy_vanilla_rf=(greekhistv2[entropy_col] * greekhistv2[rf_string]) + ((1 - greekhistv2[entropy_col]) * greekhistv2[vanilla_col])
    entropy_minmax_avg_rf=(greekhistv2[entropy_col_minmax] * greekhistv2[rf_string]) + ((1 - greekhistv2[entropy_col_minmax]) * greekhistv2[avg_col])
    entropy_minmax_vanilla_rf=(greekhistv2[entropy_col_minmax] * greekhistv2[rf_string]) + ((1 - greekhistv2[entropy_col_minmax]) * greekhistv2[vanilla_col])
    print(f'entropy weightings:\n AVG mBERT:{safe_corr(entropy_avg_mBERT, greekhistv2[ref_col])},Vanilla mBERT:{safe_corr(entropy_vanilla_mBERT, greekhistv2[ref_col])},Avg mBERT minmax:{safe_corr(entropy_minmax_avg_mBERT, greekhistv2[ref_col])},Vanilla mBERT minmax:{safe_corr(entropy_minmax_vanilla_mBERT, greekhistv2[ref_col])},Avg Readability Formula: {safe_corr(entropy_avg_rf, greekhistv2[ref_col])},Vanilla Readability Formula: {safe_corr(entropy_vanilla_rf, greekhistv2[ref_col])},Average Readability Formula minmax:{safe_corr(entropy_minmax_avg_rf, greekhistv2[ref_col])}, Vanilla Readability Formula minmax:{safe_corr(entropy_minmax_vanilla_rf, greekhistv2[ref_col])}')
    if model.startswith('conf_'):
        verbal_avg_mBERT=((1 - greekhistv2[vconf_col]) * greekhistv2["RSRS_mBERT"]) + (greekhistv2[vconf_col] * greekhistv2[avg_col])
        verbal_vanilla_mBERT=((1 - greekhistv2[vconf_col]) * greekhistv2["RSRS_mBERT"]) + (greekhistv2[vconf_col] * greekhistv2[vanilla_col])
        verbal_minmax_avg_mBERT=((1 - greekhistv2[vconf_col_minmax]) * greekhistv2["RSRS_mBERT"]) + (greekhistv2[vconf_col_minmax] * greekhistv2[avg_col])
        verbal_minmax_vanilla_mBERT=((1 - greekhistv2[vconf_col_minmax]) * greekhistv2["RSRS_mBERT"]) + (greekhistv2[vconf_col_minmax] * greekhistv2[vanilla_col])
        
        verbal_avg_rf=((1 - greekhistv2[vconf_col]) * greekhistv2[rf_string]) + (greekhistv2[vconf_col] * greekhistv2[avg_col])
        verbal_vanilla_rf=((1 - greekhistv2[vconf_col]) * greekhistv2[rf_string]) + (greekhistv2[vconf_col] * greekhistv2[vanilla_col])
        verbal_minmax_avg_rf=((1 - greekhistv2[vconf_col_minmax]) * greekhistv2[rf_string]) + (greekhistv2[vconf_col_minmax] * greekhistv2[avg_col])
        verbal_minmax_vanilla_rf=((1 - greekhistv2[vconf_col_minmax]) * greekhistv2[rf_string]) + (greekhistv2[vconf_col_minmax] * greekhistv2[vanilla_col])
        print(f'verbal conf weightings:\n AVG mBERT:{safe_corr(verbal_avg_mBERT, greekhistv2[ref_col])},Vanilla mBERT:{safe_corr(verbal_vanilla_mBERT, greekhistv2[ref_col])},Avg mBERT minmax:{safe_corr(verbal_minmax_avg_mBERT, greekhistv2[ref_col])},Vanilla mBERT minmax:{safe_corr(verbal_minmax_vanilla_mBERT, greekhistv2[ref_col])},Avg Readability Formula: {safe_corr(verbal_avg_rf, greekhistv2[ref_col])},Vanilla Readability Formula:{safe_corr(verbal_vanilla_rf, greekhistv2[ref_col])},Average Readability Formula minmax:{safe_corr(verbal_minmax_avg_rf, greekhistv2[ref_col])},Vanilla Readability Formula minmax: {safe_corr(verbal_minmax_vanilla_rf, greekhistv2[ref_col])}','\n \n \n')
    else:
        print('\n \n \n')

AYA_32B
unweighted:
 AVG:(0.4637, 804),Vanilla:(0.4398, 804),RSRS:(0.1627, 804),Readability Formula: (0.3725, 804)
naive weightings:
 AVG mBERT:(0.3884, 804),Vanilla mBERT:(0.3741, 804), AVG Readability Formula: (0.4963, 804), Vanilla Readability Formula: (0.4845, 804)
entropy weightings:
 AVG mBERT:(0.4659, 804),Vanilla mBERT:(0.4436, 804),Avg mBERT minmax:(0.4428, 804),Vanilla mBERT minmax:(0.4361, 804),Avg Readability Formula: (0.4699, 804),Vanilla Readability Formula: (0.4479, 804),Average Readability Formula minmax:(0.4979, 804), Vanilla Readability Formula minmax:(0.4932, 804)




noscale_AYA_32B
unweighted:
 AVG:(0.5556, 796),Vanilla:(0.5309, 796),RSRS:(0.1627, 804),Readability Formula: (0.3725, 804)
naive weightings:
 AVG mBERT:(0.4524, 796),Vanilla mBERT:(0.4379, 796), AVG Readability Formula: (0.5497, 796), Vanilla Readability Formula: (0.5385, 796)
entropy weightings:
 AVG mBERT:(0.5579, 796),Vanilla mBERT:(0.5353, 796),Avg mBERT minmax:(0.5316, 796),Vanilla mBERT minmax:(0.5213, 796),Avg Readability Formula: (0.5625, 796),Vanilla Readability Formula: (0.5402, 796),Average Readability Formula minmax:(0.582, 796), Vanilla Readability Formula minmax:(0.5742, 796)




conf_noscale_aya_32B
unweighted:
 AVG:(0.5426, 796),Vanilla:(0.5201, 796),RSRS:(0.1627, 804),Readability Formula: (0.3725, 804)
naive weightings:
 AVG mBERT:(0.4422, 796),Vanilla mBERT:(0.4292, 796), AVG Readability Formula: (0.5481, 796), Vanilla Readability Formula: (0.5365, 796)
entropy weightings:
 AVG mBERT:(0.5445, 796),Vanilla mBERT:(0.5231, 796),Avg mBERT minmax:(0.5213, 796),Vanilla mBERT minmax:(0.5077, 796),Avg Readability Formula: (0.5505, 796),Vanilla Readability Formula: (0.529, 796),Average Readability Formula minmax:(0.5865, 796), Vanilla Readability Formula minmax:(0.5758, 796)
verbal conf weightings:
 AVG mBERT:(0.5294, 796),Vanilla mBERT:(0.5094, 796),Avg mBERT minmax:(0.5427, 796),Vanilla mBERT minmax:(0.5197, 796),Avg Readability Formula: (0.5721, 796),Vanilla Readability Formula:(0.5533, 796),Average Readability Formula minmax:(0.5522, 796),Vanilla Readability Formula minmax: (0.5296, 796)



conf_aya_32B
unweighted:
 AVG:(0.4434, 804),Vanilla:(0.4116, 804),RSRS:(0.1627, 804),Readability Formula: (0.3725, 804)
naive weightings:
 AVG mBERT:(0.3832, 804),Vanilla mBERT:(0.3626, 804), AVG Readability Formula: (0.4934, 804), Vanilla Readability Formula: (0.4772, 804)
entropy weightings:
 AVG mBERT:(0.4459, 804),Vanilla mBERT:(0.4163, 804),Avg mBERT minmax:(0.4238, 804),Vanilla mBERT minmax:(0.4149, 804),Avg Readability Formula: (0.4502, 804),Vanilla Readability Formula: (0.4209, 804),Average Readability Formula minmax:(0.4737, 804), Vanilla Readability Formula minmax:(0.4684, 804)
verbal conf weightings:
 AVG mBERT:(0.4419, 803),Vanilla mBERT:(0.4134, 803),Avg mBERT minmax:(0.3266, 803),Vanilla mBERT minmax:(0.3048, 803),Avg Readability Formula: (0.4846, 803),Vanilla Readability Formula:(0.4593, 803),Average Readability Formula minmax:(0.3931, 803),Vanilla Readability Formula minmax: (0.3721, 803)



AYA_8B
unweighted:
 AVG:(0.3196, 804),Vanilla:(0.3052, 804),RSRS:(0.1627, 804),Readability Formula: (0.3725, 804)
naive weightings:
 AVG mBERT:(0.3119, 804),Vanilla mBERT:(0.3031, 804), AVG Readability Formula: (0.4399, 804), Vanilla Readability Formula: (0.4309, 804)
entropy weightings:
 AVG mBERT:(0.3228, 804),Vanilla mBERT:(0.3099, 804),Avg mBERT minmax:(0.3188, 804),Vanilla mBERT minmax:(0.3159, 804),Avg Readability Formula: (0.3305, 804),Vanilla Readability Formula: (0.3176, 804),Average Readability Formula minmax:(0.3917, 804), Vanilla Readability Formula minmax:(0.3913, 804)




noscale_AYA_8B
unweighted:
 AVG:(0.3487, 790),Vanilla:(0.2977, 790),RSRS:(0.1627, 804),Readability Formula: (0.3725, 804)
naive weightings:
 AVG mBERT:(0.3328, 790),Vanilla mBERT:(0.3019, 790), AVG Readability Formula: (0.4549, 790), Vanilla Readability Formula: (0.4262, 790)
entropy weightings:
 AVG mBERT:(0.3558, 790),Vanilla mBERT:(0.307, 790),Avg mBERT minmax:(0.3376, 790),Vanilla mBERT minmax:(0.3145, 790),Avg Readability Formula: (0.3674, 790),Vanilla Readability Formula: (0.3189, 790),Average Readability Formula minmax:(0.4487, 790), Vanilla Readability Formula minmax:(0.4288, 790)

## Medreadme

In [26]:

medreadmev2=pd.read_csv('.../medreadmev2.csv')
medreadmev2 = medreadmev2.replace("na", np.nan)
medreadmev2.columns

Index(['Unnamed: 0', 'Sentence', 'Source', 'Side', 'Readability', 'split',
       'phi_vanilla', 'phi_avg', 'phi_entropy', 'gemma_9b_vanilla',
       ...
       'noscale_gemma_2b_entropy', 'noscale_gemma_9b_vanilla',
       'noscale_gemma_9b_avg', 'noscale_gemma_9b_entropy',
       'noscale_gemma_27b_vanilla', 'noscale_gemma_27b_avg',
       'noscale_gemma_27b_entropy', 'FKGL', 'ARI', 'RSRS_mBERT'],
      dtype='object', length=141)

In [27]:
ref_col = medreadmev2.columns[4]
for i in range(6, len(medreadmev2.columns)): 
    col = medreadmev2.columns[i]
    corr = medreadmev2[ref_col].astype(float).corr(medreadmev2[col].astype(float))
    if ('entropy' not in col) and ('verbal_conf' not in col):
        print(f"{i+1}: {col} -> correlation with {ref_col}: {corr:.4f}")

7: phi_vanilla -> correlation with Readability: 0.6558
8: phi_avg -> correlation with Readability: 0.6909
10: gemma_9b_vanilla -> correlation with Readability: 0.6878
11: gemma_9b_avg -> correlation with Readability: 0.7404
13: gemma_2b_vanilla -> correlation with Readability: 0.3312
14: gemma_2b_avg -> correlation with Readability: 0.4263
16: gemma_27b_vanilla -> correlation with Readability: 0.6818
17: gemma_27b_avg -> correlation with Readability: 0.7177
19: LLAMA_3B_vanilla -> correlation with Readability: 0.5646
20: LLAMA_3B_avg -> correlation with Readability: 0.6454
22: LLAMA_8B_vanilla -> correlation with Readability: 0.6505
23: LLAMA_8B_avg -> correlation with Readability: 0.6906
25: LLAMA_70B_vanilla -> correlation with Readability: 0.7561
26: LLAMA_70B_avg -> correlation with Readability: 0.7726
28: AYA_8B_vanilla -> correlation with Readability: 0.3970
29: AYA_8B_avg -> correlation with Readability: 0.4393
31: AYA_32B_vanilla -> correlation with Readability: 0.6878
32: AYA_32B_avg -> correlation with Readability: 0.7059
34: Mixtral_vanilla -> correlation with Readability: 0.6598
35: Mixtral_avg -> correlation with Readability: 0.6665
37: noscale_phi_vanilla -> correlation with Readability: 0.6691
38: noscale_phi_avg -> correlation with Readability: 0.6888
40: conf_phi_vanilla -> correlation with Readability: 0.6766
41: conf_phi_avg -> correlation with Readability: 0.7020
44: conf_noscale_phi_vanilla -> correlation with Readability: 0.6980
45: conf_noscale_phi_avg -> correlation with Readability: 0.7157
48: conf_noscale_gemma_9b_vanilla -> correlation with Readability: 0.6448
49: conf_noscale_gemma_9b_avg -> correlation with Readability: 0.6879
52: conf_gemma_9b_vanilla -> correlation with Readability: 0.6537
53: conf_gemma_9b_avg -> correlation with Readability: 0.7108
56: conf_gemma_27b_vanilla -> correlation with Readability: 0.7113
57: conf_gemma_27b_avg -> correlation with Readability: 0.7402
60: conf_noscale_gemma_27b_vanilla -> correlation with Readability: 0.7057
61: conf_noscale_gemma_27b_avg -> correlation with Readability: 0.7181
64: conf_noscale_gemma_2b_vanilla -> correlation with Readability: 0.5325
65: conf_noscale_gemma_2b_avg -> correlation with Readability: 0.5650
68: conf_gemma_2b_vanilla -> correlation with Readability: 0.3874
69: conf_gemma_2b_avg -> correlation with Readability: 0.4988
72: conf_llama_3b_vanilla -> correlation with Readability: 0.5992
73: conf_llama_3b_avg -> correlation with Readability: 0.6699
76: conf_noscale_llama_3b_vanilla -> correlation with Readability: 0.5266
77: conf_noscale_llama_3b_avg -> correlation with Readability: 0.5919
80: conf_noscale_llama_8b_vanilla -> correlation with Readability: 0.6827
81: conf_noscale_llama_8b_avg -> correlation with Readability: 0.6984
84: conf_llama_8b_vanilla -> correlation with Readability: 0.6701
85: conf_llama_8b_avg -> correlation with Readability: 0.7047
88: conf_llama_70b_vanilla -> correlation with Readability: 0.7584
89: conf_llama_70b_avg -> correlation with Readability: 0.7724
92: conf_noscale_llama_70b_vanilla -> correlation with Readability: 0.7362
93: conf_noscale_llama_70b_avg -> correlation with Readability: 0.7468
96: conf_noscale_aya_32b_vanilla -> correlation with Readability: 0.7324
97: conf_noscale_aya_32b_avg -> correlation with Readability: 0.7523
100: conf_aya_32b_vanilla -> correlation with Readability: 0.6940
101: conf_aya_32b_avg -> correlation with Readability: 0.7189
104: conf_mixtral_vanilla -> correlation with Readability: 0.6171
105: conf_mixtral_avg -> correlation with Readability: 0.6300
108: conf_noscale_mixtral_vanilla -> correlation with Readability: 0.6271
109: conf_noscale_mixtral_avg -> correlation with Readability: 0.6305
112: noscale_mixtral_vanilla -> correlation with Readability: 0.6262
113: noscale_mixtral_avg -> correlation with Readability: 0.6334
115: noscale_aya_8b_vanilla -> correlation with Readability: 0.6356
116: noscale_aya_8b_avg -> correlation with Readability: 0.6644
118: noscale_aya_32b_vanilla -> correlation with Readability: 0.7223
119: noscale_aya_32b_avg -> correlation with Readability: 0.7415
121: noscale_llama_70b_vanilla -> correlation with Readability: 0.7370
122: noscale_llama_70b_avg -> correlation with Readability: 0.7497
124: noscale_llama_8b_vanilla -> correlation with Readability: 0.6829
125: noscale_llama_8b_avg -> correlation with Readability: 0.6945
127: noscale_llama_3b_vanilla -> correlation with Readability: 0.5352
128: noscale_llama_3b_avg -> correlation with Readability: 0.5829
130: noscale_gemma_2b_vanilla -> correlation with Readability: 0.5041
131: noscale_gemma_2b_avg -> correlation with Readability: 0.5522
133: noscale_gemma_9b_vanilla -> correlation with Readability: 0.6900
134: noscale_gemma_9b_avg -> correlation with Readability: 0.7086
136: noscale_gemma_27b_vanilla -> correlation with Readability: 0.5807
137: noscale_gemma_27b_avg -> correlation with Readability: 0.5929
139: FKGL -> correlation with Readability: 0.4693
140: ARI -> correlation with Readability: 0.4626
141: RSRS_mBERT -> correlation with Readability: 0.6463

In [28]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
medreadmev2 = medreadmev2.apply(pd.to_numeric, errors="coerce")
rf_string='FKGL'
std_cols = [c for c in medreadmev2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
medreadmev2[std_cols] = StandardScaler().fit_transform(medreadmev2[std_cols])
model='conf_llama_70b'
vconf_col=f'{model}_verbal_conf'
avg_col = f"{model}_avg"


verbal_avg_rf=((1 - medreadmev2[vconf_col]/10) * medreadmev2[rf_string]) + (medreadmev2[vconf_col]/10 * medreadmev2[avg_col])


rjk,n1=safe_corr_raw(verbal_avg_rf, medreadmev2.iloc[:,4])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(medreadmev2.iloc[:,91], medreadmev2.iloc[:,4])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,medreadmev2.iloc[:,91])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs LLM : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, medreadmev2.iloc[:,4])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(medreadmev2[rf_string], medreadmev2.iloc[:,4])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,medreadmev2[rf_string])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RF : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, medreadmev2.iloc[:,4])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(medreadmev2['RSRS_mBERT'], medreadmev2.iloc[:,4])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,medreadmev2['RSRS_mBERT'])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RSRS : t2:{res1[0]}, p:{res1[1]}')

0.7704444557220221 0.7361854644132633 0.9290863739686803
1139
t_test: Vconf RF vs LLM : t2:4.82313496823493, p:1.6053049758379956e-06
0.7704444557220221 0.46925246718598945 0.66928791964357
1139
t_test: Vconf RF vs RF : t2:19.374316248535298, p:0.0
0.7704444557220221 0.6462821964061868 0.6892558031430652
1139
t_test: Vconf RF vs RSRS : t2:8.44166923076577, p:2.220446049250313e-16

In [29]:
import numpy as np
medreadmev2 = medreadmev2.apply(pd.to_numeric, errors="coerce")
rjk,n1=safe_corr_raw(medreadmev2.iloc[:,88], medreadmev2.iloc[:,4])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(medreadmev2.iloc[:,92], medreadmev2.iloc[:,4])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(medreadmev2.iloc[:,92],medreadmev2.iloc[:,88])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Scale vs No scale : t2:{res1[0]}, p:{res1[1]}')


import numpy as np
rjk,n1=safe_corr_raw(medreadmev2.iloc[:,88], medreadmev2.iloc[:,4])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(medreadmev2.iloc[:,91], medreadmev2.iloc[:,4])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(medreadmev2.iloc[:,91],medreadmev2.iloc[:,88])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Expected and Scale vs Vanilla and No scale : t2:{res1[0]}, p:{res1[1]}')


import numpy as np
rjk,n1=safe_corr_raw(medreadmev2.iloc[:,88], medreadmev2.iloc[:,4])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(medreadmev2.iloc[:,87], medreadmev2.iloc[:,4])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(medreadmev2.iloc[:,87],medreadmev2.iloc[:,88])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Expected vs Vanilla : t2:{res1[0]}, p:{res1[1]}')


#rjk=np.corrcoef(avg_col, values)[0, 1]
##Change next two lines to best RSRS/readability formula
#rjh=np.corrcoef(df.RSRS_mBERT, values)[0, 1]
#rkh=np.corrcoef(df.RSRS_mBERT, avg_col)[0, 1]
#print(rjk,rjh,rkh)
#res1=calc_williams_t(rjk,rjh,rkh,len(avg_col))
#print(f't_test: LLM vs non-LAURAE best : t2:{res1[0]}, p:{res1[1]}')

0.7723742398879554 0.7467881156596944 0.9523467200356682
1139
t_test: Scale vs No scale : t2:4.403444953028986, p:1.1659329176350042e-05
0.7723742398879554 0.7361854644132633 0.9381539482578322
1139
t_test: Expected and Scale vs Vanilla and No scale : t2:5.4639196509953525, p:5.7202825365365584e-08
0.7723742398879554 0.7584086680833066 0.9835156338780711
1139
t_test: Expected vs Vanilla : t2:4.081425089141652, p:4.7891224055796044e-05

In [30]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
medreadmev2 = medreadmev2.apply(pd.to_numeric, errors="coerce")
rf_string='FKGL'
ref_col = medreadmev2.columns[4]
#medreadmev2['RSRS_mBERT']= StandardScaler().fit_transform(medreadmev2['RSRS_mBERT'])
# Step 1: Normalize entropy columns
entropy_cols = [c for c in medreadmev2.columns if c.endswith("_entropy")]
entropy_cols_minmax = [c + "_minmax" for c in entropy_cols]
medreadmev2[entropy_cols_minmax] = MinMaxScaler().fit_transform(medreadmev2[entropy_cols])

vconf_cols = [c for c in medreadmev2.columns if c.endswith("verbal_conf")]
vconf_cols_minmax = [c + "_minmax" for c in vconf_cols]
medreadmev2[vconf_cols_minmax] = MinMaxScaler().fit_transform(medreadmev2[vconf_cols])
medreadmev2[vconf_cols] = medreadmev2[vconf_cols]/10

std_cols = [c for c in medreadmev2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
medreadmev2[std_cols] = StandardScaler().fit_transform(medreadmev2[std_cols])
suffixes = ["_avg", "_vanilla", "_entropy"]
models = set(
    c.rsplit("_", 1)[0]  # remove the last part after the final underscore
    for c in entropy_cols  # or any column list containing these suffixes
)
sorted_models = sorted(models, key=lambda x: x[::-1].lower())
for model in sorted_models:
    print(model)
    vanilla_col = f"{model}_vanilla"
    avg_col = f"{model}_avg"
    print(f'unweighted:\n AVG:{safe_corr(medreadmev2[avg_col], medreadmev2[ref_col])},Vanilla:{safe_corr(medreadmev2[vanilla_col], medreadmev2[ref_col])},RSRS:{safe_corr(medreadmev2["RSRS_mBERT"], medreadmev2[ref_col])},Readability Formula: {safe_corr(medreadmev2[rf_string], medreadmev2[ref_col])}')
    naive_avg_mBERT=medreadmev2[avg_col]+medreadmev2["RSRS_mBERT"]
    naive_vanilla_mBERT=medreadmev2[vanilla_col]+medreadmev2["RSRS_mBERT"]
    
    naive_avg_rf=medreadmev2[avg_col]+medreadmev2[rf_string]
    naive_vanilla_rf=medreadmev2[vanilla_col]+medreadmev2[rf_string]
    print(f'naive weightings: \n AVG mBERT:{safe_corr(naive_avg_mBERT, medreadmev2[ref_col])},Vanilla mBERT:{safe_corr(naive_vanilla_mBERT, medreadmev2[ref_col])}, AVG Readability Formula: {safe_corr(naive_avg_rf, medreadmev2[ref_col])}, Vanilla Readability Formula: {safe_corr(naive_vanilla_rf, medreadmev2[ref_col])}')
    entropy_col = f"{model}_entropy"
    entropy_col_minmax = f"{model}_entropy_minmax"
    if model.startswith('conf_'):
        vconf_col=f'{model}_verbal_conf'
        vconf_col_minmax = f"{model}_verbal_conf_minmax"
    
    #medreadmev2[f"{model}_weighted"] = (
    #    medreadmev2[entropy_col] * medreadmev2["RSRS_mBERT"] + 
    #    (1 - medreadmev2[entropy_col]) * (medreadmev2[[vanilla_col, avg_col]].mean(axis=1))
    #)
    entropy_avg_mBERT=(medreadmev2[entropy_col] * medreadmev2["RSRS_mBERT"]) + ((1 - medreadmev2[entropy_col]) * medreadmev2[avg_col])
    entropy_vanilla_mBERT=(medreadmev2[entropy_col] * medreadmev2["RSRS_mBERT"]) + ((1 - medreadmev2[entropy_col]) * medreadmev2[vanilla_col])
    entropy_minmax_avg_mBERT=(medreadmev2[entropy_col_minmax] * medreadmev2["RSRS_mBERT"]) + ((1 - medreadmev2[entropy_col_minmax]) * medreadmev2[avg_col])
    entropy_minmax_vanilla_mBERT=(medreadmev2[entropy_col_minmax] * medreadmev2["RSRS_mBERT"]) + ((1 - medreadmev2[entropy_col_minmax]) * medreadmev2[vanilla_col])
    
    entropy_avg_rf=(medreadmev2[entropy_col] * medreadmev2[rf_string]) + ((1 - medreadmev2[entropy_col]) * medreadmev2[avg_col])
    entropy_vanilla_rf=(medreadmev2[entropy_col] * medreadmev2[rf_string]) + ((1 - medreadmev2[entropy_col]) * medreadmev2[vanilla_col])
    entropy_minmax_avg_rf=(medreadmev2[entropy_col_minmax] * medreadmev2[rf_string]) + ((1 - medreadmev2[entropy_col_minmax]) * medreadmev2[avg_col])
    entropy_minmax_vanilla_rf=(medreadmev2[entropy_col_minmax] * medreadmev2[rf_string]) + ((1 - medreadmev2[entropy_col_minmax]) * medreadmev2[vanilla_col])
    print(f'entropy weightings:\n AVG mBERT:{safe_corr(entropy_avg_mBERT, medreadmev2[ref_col])},Vanilla mBERT:{safe_corr(entropy_vanilla_mBERT, medreadmev2[ref_col])},Avg mBERT minmax:{safe_corr(entropy_minmax_avg_mBERT, medreadmev2[ref_col])},Vanilla mBERT minmax:{safe_corr(entropy_minmax_vanilla_mBERT, medreadmev2[ref_col])},Avg Readability Formula: {safe_corr(entropy_avg_rf, medreadmev2[ref_col])},Vanilla Readability Formula: {safe_corr(entropy_vanilla_rf, medreadmev2[ref_col])},Average Readability Formula minmax:{safe_corr(entropy_minmax_avg_rf, medreadmev2[ref_col])}, Vanilla Readability Formula minmax:{safe_corr(entropy_minmax_vanilla_rf, medreadmev2[ref_col])}')
    if model.startswith('conf_'):
        verbal_avg_mBERT=((1 - medreadmev2[vconf_col]) * medreadmev2["RSRS_mBERT"]) + (medreadmev2[vconf_col] * medreadmev2[avg_col])
        verbal_vanilla_mBERT=((1 - medreadmev2[vconf_col]) * medreadmev2["RSRS_mBERT"]) + (medreadmev2[vconf_col] * medreadmev2[vanilla_col])
        verbal_minmax_avg_mBERT=((1 - medreadmev2[vconf_col_minmax]) * medreadmev2["RSRS_mBERT"]) + (medreadmev2[vconf_col_minmax] * medreadmev2[avg_col])
        verbal_minmax_vanilla_mBERT=((1 - medreadmev2[vconf_col_minmax]) * medreadmev2["RSRS_mBERT"]) + (medreadmev2[vconf_col_minmax] * medreadmev2[vanilla_col])
        
        verbal_avg_rf=((1 - medreadmev2[vconf_col]) * medreadmev2[rf_string]) + (medreadmev2[vconf_col] * medreadmev2[avg_col])
        verbal_vanilla_rf=((1 - medreadmev2[vconf_col]) * medreadmev2[rf_string]) + (medreadmev2[vconf_col] * medreadmev2[vanilla_col])
        verbal_minmax_avg_rf=((1 - medreadmev2[vconf_col_minmax]) * medreadmev2[rf_string]) + (medreadmev2[vconf_col_minmax] * medreadmev2[avg_col])
        verbal_minmax_vanilla_rf=((1 - medreadmev2[vconf_col_minmax]) * medreadmev2[rf_string]) + (medreadmev2[vconf_col_minmax] * medreadmev2[vanilla_col])
        print(f'verbal conf weightings:\n AVG mBERT:{safe_corr(verbal_avg_mBERT, medreadmev2[ref_col])},Vanilla mBERT:{safe_corr(verbal_vanilla_mBERT, medreadmev2[ref_col])},Avg mBERT minmax:{safe_corr(verbal_minmax_avg_mBERT, medreadmev2[ref_col])},Vanilla mBERT minmax:{safe_corr(verbal_minmax_vanilla_mBERT, medreadmev2[ref_col])},Avg Readability Formula: {safe_corr(verbal_avg_rf, medreadmev2[ref_col])},Vanilla Readability Formula:{safe_corr(verbal_vanilla_rf, medreadmev2[ref_col])},Average Readability Formula minmax:{safe_corr(verbal_minmax_avg_rf, medreadmev2[ref_col])},Vanilla Readability Formula minmax: {safe_corr(verbal_minmax_vanilla_rf, medreadmev2[ref_col])}','\n \n \n')
    else:
        print('\n \n \n')

LLAMA_70B
unweighted:
 AVG:(0.7726, 1140),Vanilla:(0.7561, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7911, 1140),Vanilla mBERT:(0.7866, 1140), AVG Readability Formula: (0.7073, 1140), Vanilla Readability Formula: (0.7017, 1140)
entropy weightings:
 AVG mBERT:(0.7795, 1140),Vanilla mBERT:(0.7644, 1140),Avg mBERT minmax:(0.787, 1140),Vanilla mBERT minmax:(0.7838, 1140),Avg Readability Formula: (0.7736, 1140),Vanilla Readability Formula: (0.7584, 1140),Average Readability Formula minmax:(0.7149, 1140), Vanilla Readability Formula minmax:(0.7103, 1140)




noscale_llama_70b
unweighted:
 AVG:(0.7497, 1140),Vanilla:(0.737, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7829, 1140),Vanilla mBERT:(0.7779, 1140), AVG Readability Formula: (0.6956, 1140), Vanilla Readability Formula: (0.6901, 1140)
entropy weightings:
 AVG mBERT:(0.7588, 1140),Vanilla mBERT:(0.7475, 1140),Avg mBERT minmax:(0.7782, 1140),Vanilla mBERT minmax:(0.7747, 1140),Avg Readability Formula: (0.7525, 1140),Vanilla Readability Formula: (0.7411, 1140),Average Readability Formula minmax:(0.7186, 1140), Vanilla Readability Formula minmax:(0.7144, 1140)




conf_noscale_llama_70b
unweighted:
 AVG:(0.7468, 1140),Vanilla:(0.7362, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7808, 1140),Vanilla mBERT:(0.7754, 1140), AVG Readability Formula: (0.6952, 1140), Vanilla Readability Formula: (0.6907, 1140)
entropy weightings:
 AVG mBERT:(0.7574, 1140),Vanilla mBERT:(0.7478, 1140),Avg mBERT minmax:(0.7836, 1140),Vanilla mBERT minmax:(0.7788, 1140),Avg Readability Formula: (0.7505, 1140),Vanilla Readability Formula: (0.7412, 1140),Average Readability Formula minmax:(0.7267, 1140), Vanilla Readability Formula minmax:(0.7222, 1140)
verbal conf weightings:
 AVG mBERT:(0.7791, 1140),Vanilla mBERT:(0.7706, 1140),Avg mBERT minmax:(0.781, 1140),Vanilla mBERT minmax:(0.7758, 1140),Avg Readability Formula: (0.7488, 1140),Vanilla Readability Formula:(0.7407, 1140),Average Readability Formula minmax:(0.7096, 1140),Vanilla Readability Formula minmax: (0.7047, 1140)



conf_llama_70b
unweighted:
 AVG:(0.7724, 1139),Vanilla:(0.7584, 1139),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.789, 1139),Vanilla mBERT:(0.785, 1139), AVG Readability Formula: (0.7074, 1139), Vanilla Readability Formula: (0.7024, 1139)
entropy weightings:
 AVG mBERT:(0.7793, 1139),Vanilla mBERT:(0.7666, 1139),Avg mBERT minmax:(0.7912, 1139),Vanilla mBERT minmax:(0.7881, 1139),Avg Readability Formula: (0.7735, 1139),Vanilla Readability Formula: (0.7607, 1139),Average Readability Formula minmax:(0.7227, 1139), Vanilla Readability Formula minmax:(0.7185, 1139)
verbal conf weightings:
 AVG mBERT:(0.7961, 1139),Vanilla mBERT:(0.786, 1139),Avg mBERT minmax:(0.7834, 1139),Vanilla mBERT minmax:(0.7782, 1139),Avg Readability Formula: (0.7704, 1139),Vanilla Readability Formula:(0.76, 1139),Average Readability Formula minmax:(0.707, 1139),Vanilla Readability Formula minmax: (0.7012, 1139)



AYA_32B
unweighted:
 AVG:(0.7059, 1140),Vanilla:(0.6878, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7583, 1140),Vanilla mBERT:(0.7502, 1140), AVG Readability Formula: (0.6707, 1140), Vanilla Readability Formula: (0.663, 1140)
entropy weightings:
 AVG mBERT:(0.7081, 1140),Vanilla mBERT:(0.6911, 1140),Avg mBERT minmax:(0.7142, 1140),Vanilla mBERT minmax:(0.7104, 1140),Avg Readability Formula: (0.7072, 1140),Vanilla Readability Formula: (0.6903, 1140),Average Readability Formula minmax:(0.6918, 1140), Vanilla Readability Formula minmax:(0.6879, 1140)




noscale_aya_32b
unweighted:
 AVG:(0.7415, 1140),Vanilla:(0.7223, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7857, 1140),Vanilla mBERT:(0.7795, 1140), AVG Readability Formula: (0.7008, 1140), Vanilla Readability Formula: (0.6949, 1140)
entropy weightings:
 AVG mBERT:(0.749, 1140),Vanilla mBERT:(0.7319, 1140),Avg mBERT minmax:(0.7578, 1140),Vanilla mBERT minmax:(0.7534, 1140),Avg Readability Formula: (0.7438, 1140),Vanilla Readability Formula: (0.727, 1140),Average Readability Formula minmax:(0.7003, 1140), Vanilla Readability Formula minmax:(0.6955, 1140)




conf_noscale_aya_32b
unweighted:
 AVG:(0.7523, 1140),Vanilla:(0.7324, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7871, 1140),Vanilla mBERT:(0.7809, 1140), AVG Readability Formula: (0.7001, 1140), Vanilla Readability Formula: (0.6929, 1140)
entropy weightings:
 AVG mBERT:(0.7588, 1140),Vanilla mBERT:(0.7413, 1140),Avg mBERT minmax:(0.7702, 1140),Vanilla mBERT minmax:(0.7661, 1140),Avg Readability Formula: (0.7544, 1140),Vanilla Readability Formula: (0.7368, 1140),Average Readability Formula minmax:(0.7211, 1140), Vanilla Readability Formula minmax:(0.7162, 1140)
verbal conf weightings:
 AVG mBERT:(0.7907, 1140),Vanilla mBERT:(0.7779, 1140),Avg mBERT minmax:(0.7514, 1140),Vanilla mBERT minmax:(0.7482, 1140),Avg Readability Formula: (0.7527, 1140),Vanilla Readability Formula:(0.7395, 1140),Average Readability Formula minmax:(0.6205, 1140),Vanilla Readability Formula minmax: (0.6159, 1140)



conf_aya_32b
unweighted:
 AVG:(0.7189, 1140),Vanilla:(0.694, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7608, 1140),Vanilla mBERT:(0.7521, 1140), AVG Readability Formula: (0.6708, 1140), Vanilla Readability Formula: (0.6599, 1140)
entropy weightings:
 AVG mBERT:(0.7215, 1140),Vanilla mBERT:(0.6983, 1140),Avg mBERT minmax:(0.7258, 1140),Vanilla mBERT minmax:(0.7216, 1140),Avg Readability Formula: (0.7195, 1140),Vanilla Readability Formula: (0.696, 1140),Average Readability Formula minmax:(0.681, 1140), Vanilla Readability Formula minmax:(0.6761, 1140)
verbal conf weightings:
 AVG mBERT:(0.7535, 1139),Vanilla mBERT:(0.7356, 1139),Avg mBERT minmax:(0.7521, 1139),Vanilla mBERT minmax:(0.7446, 1139),Avg Readability Formula: (0.7187, 1139),Vanilla Readability Formula:(0.6993, 1139),Average Readability Formula minmax:(0.6487, 1139),Vanilla Readability Formula minmax: (0.639, 1139)



gemma_2b
unweighted:
 AVG:(0.4263, 1131),Vanilla:(0.3312, 1131),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.6587, 1131),Vanilla mBERT:(0.618, 1131), AVG Readability Formula: (0.5434, 1131), Vanilla Readability Formula: (0.4993, 1131)
entropy weightings:
 AVG mBERT:(0.433, 1131),Vanilla mBERT:(0.3417, 1131),Avg mBERT minmax:(0.501, 1131),Vanilla mBERT minmax:(0.4631, 1131),Avg Readability Formula: (0.4304, 1131),Vanilla Readability Formula: (0.339, 1131),Average Readability Formula minmax:(0.4648, 1131), Vanilla Readability Formula minmax:(0.4242, 1131)




noscale_gemma_2b
unweighted:
 AVG:(0.5522, 1131),Vanilla:(0.5041, 1131),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.6945, 1131),Vanilla mBERT:(0.6724, 1131), AVG Readability Formula: (0.5878, 1131), Vanilla Readability Formula: (0.5674, 1131)
entropy weightings:
 AVG mBERT:(0.5884, 1131),Vanilla mBERT:(0.5448, 1131),Avg mBERT minmax:(0.6872, 1131),Vanilla mBERT minmax:(0.6756, 1131),Avg Readability Formula: (0.5689, 1131),Vanilla Readability Formula: (0.5258, 1131),Average Readability Formula minmax:(0.5508, 1131), Vanilla Readability Formula minmax:(0.5364, 1131)




conf_noscale_gemma_2b
unweighted:
 AVG:(0.565, 1131),Vanilla:(0.5325, 1131),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.6801, 1131),Vanilla mBERT:(0.6662, 1131), AVG Readability Formula: (0.5832, 1131), Vanilla Readability Formula: (0.5709, 1131)
entropy weightings:
 AVG mBERT:(0.5912, 1131),Vanilla mBERT:(0.5623, 1131),Avg mBERT minmax:(0.6693, 1131),Vanilla mBERT minmax:(0.6626, 1131),Avg Readability Formula: (0.5764, 1131),Vanilla Readability Formula: (0.548, 1131),Average Readability Formula minmax:(0.5518, 1131), Vanilla Readability Formula minmax:(0.5426, 1131)
verbal conf weightings:
 AVG mBERT:(0.6449, 1131),Vanilla mBERT:(0.6229, 1131),Avg mBERT minmax:(0.6775, 1131),Vanilla mBERT minmax:(0.6677, 1131),Avg Readability Formula: (0.5907, 1131),Vanilla Readability Formula:(0.5698, 1131),Average Readability Formula minmax:(0.5584, 1131),Vanilla Readability Formula minmax: (0.5474, 1131)



conf_gemma_2b
unweighted:
 AVG:(0.4988, 1133),Vanilla:(0.3874, 1133),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.6804, 1133),Vanilla mBERT:(0.6337, 1133), AVG Readability Formula: (0.5777, 1133), Vanilla Readability Formula: (0.5252, 1133)
entropy weightings:
 AVG mBERT:(0.5054, 1133),Vanilla mBERT:(0.3987, 1133),Avg mBERT minmax:(0.5709, 1133),Vanilla mBERT minmax:(0.5369, 1133),Avg Readability Formula: (0.5023, 1133),Vanilla Readability Formula: (0.3951, 1133),Average Readability Formula minmax:(0.5165, 1133), Vanilla Readability Formula minmax:(0.4745, 1133)
verbal conf weightings:
 AVG mBERT:(0.5971, 1133),Vanilla mBERT:(0.5073, 1133),Avg mBERT minmax:(0.5352, 1133),Vanilla mBERT minmax:(0.4266, 1133),Avg Readability Formula: (0.553, 1133),Vanilla Readability Formula:(0.4615, 1133),Average Readability Formula minmax:(0.5152, 1133),Vanilla Readability Formula minmax: (0.4068, 1133)



LLAMA_3B
unweighted:
 AVG:(0.6454, 1140),Vanilla:(0.5646, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7405, 1140),Vanilla mBERT:(0.7084, 1140), AVG Readability Formula: (0.6347, 1140), Vanilla Readability Formula: (0.6041, 1140)
entropy weightings:
 AVG mBERT:(0.6683, 1140),Vanilla mBERT:(0.5956, 1140),Avg mBERT minmax:(0.7391, 1140),Vanilla mBERT minmax:(0.7206, 1140),Avg Readability Formula: (0.6539, 1140),Vanilla Readability Formula: (0.5818, 1140),Average Readability Formula minmax:(0.6293, 1140), Vanilla Readability Formula minmax:(0.6068, 1140)




noscale_llama_3b
unweighted:
 AVG:(0.5829, 1140),Vanilla:(0.5352, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7052, 1140),Vanilla mBERT:(0.69, 1140), AVG Readability Formula: (0.6044, 1140), Vanilla Readability Formula: (0.5877, 1140)
entropy weightings:
 AVG mBERT:(0.6177, 1140),Vanilla mBERT:(0.5774, 1140),Avg mBERT minmax:(0.714, 1140),Vanilla mBERT minmax:(0.708, 1140),Avg Readability Formula: (0.6007, 1140),Vanilla Readability Formula: (0.5603, 1140),Average Readability Formula minmax:(0.6018, 1140), Vanilla Readability Formula minmax:(0.5884, 1140)




conf_noscale_llama_3b
unweighted:
 AVG:(0.5919, 1140),Vanilla:(0.5266, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)

naive weightings:
 AVG mBERT:(0.7099, 1140),Vanilla mBERT:(0.6844, 1140), AVG Readability Formula: (0.6119, 1140), Vanilla Readability Formula: (0.583, 1140)
entropy weightings:
 AVG mBERT:(0.6247, 1140),Vanilla mBERT:(0.5682, 1140),Avg mBERT minmax:(0.7158, 1140),Vanilla mBERT minmax:(0.7061, 1140),Avg Readability Formula: (0.6082, 1140),Vanilla Readability Formula: (0.5509, 1140),Average Readability Formula minmax:(0.5998, 1140), Vanilla Readability Formula minmax:(0.5831, 1140)
verbal conf weightings:
 AVG mBERT:(0.659, 1140),Vanilla mBERT:(0.6101, 1140),Avg mBERT minmax:(0.7034, 1140),Vanilla mBERT minmax:(0.6814, 1140),Avg Readability Formula: (0.6178, 1140),Vanilla Readability Formula:(0.567, 1140),Average Readability Formula minmax:(0.591, 1140),Vanilla Readability Formula minmax: (0.5643, 1140)



conf_llama_3b
unweighted:
 AVG:(0.6699, 1140),Vanilla:(0.5992, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7523, 1140),Vanilla mBERT:(0.7256, 1140), AVG Readability Formula: (0.6496, 1140), Vanilla Readability Formula: (0.6252, 1140)
entropy weightings:
 AVG mBERT:(0.6881, 1140),Vanilla mBERT:(0.622, 1140),Avg mBERT minmax:(0.7516, 1140),Vanilla mBERT minmax:(0.724, 1140),Avg Readability Formula: (0.6768, 1140),Vanilla Readability Formula: (0.6115, 1140),Average Readability Formula minmax:(0.653, 1140), Vanilla Readability Formula minmax:(0.6274, 1140)
verbal conf weightings:
 AVG mBERT:(0.7214, 1140),Vanilla mBERT:(0.6687, 1140),Avg mBERT minmax:(0.7111, 1140),Vanilla mBERT minmax:(0.7041, 1140),Avg Readability Formula: (0.6817, 1140),Vanilla Readability Formula:(0.6307, 1140),Average Readability Formula minmax:(0.5653, 1140),Vanilla Readability Formula minmax: (0.5556, 1140)



gemma_27b
unweighted:
 AVG:(0.7177, 1140),Vanilla:(0.6818, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7624, 1140),Vanilla mBERT:(0.7505, 1140), AVG Readability Formula: (0.6664, 1140), Vanilla Readability Formula: (0.6543, 1140)
entropy weightings:
 AVG mBERT:(0.7242, 1140),Vanilla mBERT:(0.691, 1140),Avg mBERT minmax:(0.749, 1140),Vanilla mBERT minmax:(0.7427, 1140),Avg Readability Formula: (0.7184, 1140),Vanilla Readability Formula: (0.6853, 1140),Average Readability Formula minmax:(0.6639, 1140), Vanilla Readability Formula minmax:(0.6559, 1140)




noscale_gemma_27b
unweighted:
 AVG:(0.5929, 1140),Vanilla:(0.5807, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7037, 1140),Vanilla mBERT:(0.7012, 1140), AVG Readability Formula: (0.6019, 1140), Vanilla Readability Formula: (0.5975, 1140)
entropy weightings:
 AVG mBERT:(0.6111, 1140),Vanilla mBERT:(0.6004, 1140),Avg mBERT minmax:(0.6939, 1140),Vanilla mBERT minmax:(0.692, 1140),Avg Readability Formula: (0.5996, 1140),Vanilla Readability Formula: (0.5887, 1140),Average Readability Formula minmax:(0.5935, 1140), Vanilla Readability Formula minmax:(0.5895, 1140)




conf_noscale_gemma_27b
unweighted:
 AVG:(0.7181, 1140),Vanilla:(0.7057, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7614, 1140),Vanilla mBERT:(0.7582, 1140), AVG Readability Formula: (0.6697, 1140), Vanilla Readability Formula: (0.6667, 1140)
entropy weightings:
 AVG mBERT:(0.7298, 1140),Vanilla mBERT:(0.719, 1140),Avg mBERT minmax:(0.7608, 1140),Vanilla mBERT minmax:(0.7572, 1140),Avg Readability Formula: (0.7194, 1140),Vanilla Readability Formula: (0.7087, 1140),Average Readability Formula minmax:(0.6756, 1140), Vanilla Readability Formula minmax:(0.6715, 1140)
verbal conf weightings:
 AVG mBERT:(0.7564, 1140),Vanilla mBERT:(0.7495, 1140),Avg mBERT minmax:(0.735, 1140),Vanilla mBERT minmax:(0.7298, 1140),Avg Readability Formula: (0.6988, 1140),Vanilla Readability Formula:(0.692, 1140),Average Readability Formula minmax:(0.6417, 1140),Vanilla Readability Formula minmax: (0.6359, 1140)



conf_gemma_27b
unweighted:
 AVG:(0.7402, 1140),Vanilla:(0.7113, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.776, 1140),Vanilla mBERT:(0.7677, 1140), AVG Readability Formula: (0.682, 1140), Vanilla Readability Formula: (0.6732, 1140)
entropy weightings:
 AVG mBERT:(0.7467, 1140),Vanilla mBERT:(0.7201, 1140),Avg mBERT minmax:(0.7687, 1140),Vanilla mBERT minmax:(0.7612, 1140),Avg Readability Formula: (0.7404, 1140),Vanilla Readability Formula: (0.7139, 1140),Average Readability Formula minmax:(0.6987, 1140), Vanilla Readability Formula minmax:(0.6899, 1140)
verbal conf weightings:
 AVG mBERT:(0.7804, 1140),Vanilla mBERT:(0.7639, 1140),Avg mBERT minmax:(0.7152, 1140),Vanilla mBERT minmax:(0.711, 1140),Avg Readability Formula: (0.728, 1140),Vanilla Readability Formula:(0.7112, 1140),Average Readability Formula minmax:(0.5624, 1140),Vanilla Readability Formula minmax: (0.5562, 1140)



LLAMA_8B
unweighted:
 AVG:(0.6906, 1140),Vanilla:(0.6505, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7734, 1140),Vanilla mBERT:(0.7565, 1140), AVG Readability Formula: (0.6812, 1140), Vanilla Readability Formula: (0.6636, 1140)
entropy weightings:
 AVG mBERT:(0.6958, 1140),Vanilla mBERT:(0.6594, 1140),Avg mBERT minmax:(0.7173, 1140),Vanilla mBERT minmax:(0.7097, 1140),Avg Readability Formula: (0.6935, 1140),Vanilla Readability Formula: (0.6573, 1140),Average Readability Formula minmax:(0.6893, 1140), Vanilla Readability Formula minmax:(0.6811, 1140)




noscale_llama_8b
unweighted:
 AVG:(0.6945, 1140),Vanilla:(0.6829, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7735, 1140),Vanilla mBERT:(0.7677, 1140), AVG Readability Formula: (0.6742, 1140), Vanilla Readability Formula: (0.6678, 1140)
entropy weightings:
 AVG mBERT:(0.7133, 1140),Vanilla mBERT:(0.7026, 1140),Avg mBERT minmax:(0.7759, 1140),Vanilla mBERT minmax:(0.7713, 1140),Avg Readability Formula: (0.7025, 1140),Vanilla Readability Formula: (0.6916, 1140),Average Readability Formula minmax:(0.6956, 1140), Vanilla Readability Formula minmax:(0.6896, 1140)




conf_noscale_llama_8b
unweighted:
 AVG:(0.6984, 1139),Vanilla:(0.6827, 1139),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7674, 1139),Vanilla mBERT:(0.7607, 1139), AVG Readability Formula: (0.6736, 1139), Vanilla Readability Formula: (0.6665, 1139)
entropy weightings:
 AVG mBERT:(0.7147, 1139),Vanilla mBERT:(0.7008, 1139),Avg mBERT minmax:(0.7712, 1139),Vanilla mBERT minmax:(0.766, 1139),Avg Readability Formula: (0.7057, 1139),Vanilla Readability Formula: (0.6916, 1139),Average Readability Formula minmax:(0.6998, 1139), Vanilla Readability Formula minmax:(0.6936, 1139)
verbal conf weightings:
 AVG mBERT:(0.7432, 1139),Vanilla mBERT:(0.7308, 1139),Avg mBERT minmax:(0.7241, 1139),Vanilla mBERT minmax:(0.7162, 1139),Avg Readability Formula: (0.706, 1139),Vanilla Readability Formula:(0.6932, 1139),Average Readability Formula minmax:(0.6404, 1139),Vanilla Readability Formula minmax: (0.6316, 1139)



conf_llama_8b
unweighted:
 AVG:(0.7047, 1140),Vanilla:(0.6701, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7705, 1140),Vanilla mBERT:(0.7604, 1140), AVG Readability Formula: (0.6822, 1140), Vanilla Readability Formula: (0.6692, 1140)
entropy weightings:
 AVG mBERT:(0.711, 1140),Vanilla mBERT:(0.6807, 1140),Avg mBERT minmax:(0.73, 1140),Vanilla mBERT minmax:(0.7259, 1140),Avg Readability Formula: (0.7074, 1140),Vanilla Readability Formula: (0.6768, 1140),Average Readability Formula minmax:(0.69, 1140), Vanilla Readability Formula minmax:(0.6842, 1140)
verbal conf weightings:
 AVG mBERT:(0.7508, 1140),Vanilla mBERT:(0.7258, 1140),Avg mBERT minmax:(0.7109, 1140),Vanilla mBERT minmax:(0.7057, 1140),Avg Readability Formula: (0.7197, 1140),Vanilla Readability Formula:(0.6931, 1140),Average Readability Formula minmax:(0.5522, 1140),Vanilla Readability Formula minmax: (0.5446, 1140)



AYA_8B
unweighted:
 AVG:(0.4393, 1140),Vanilla:(0.397, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.6867, 1140),Vanilla mBERT:(0.67, 1140), AVG Readability Formula: (0.5662, 1140), Vanilla Readability Formula: (0.5462, 1140)
entropy weightings:
 AVG mBERT:(0.4449, 1140),Vanilla mBERT:(0.4051, 1140),Avg mBERT minmax:(0.5003, 1140),Vanilla mBERT minmax:(0.4942, 1140),Avg Readability Formula: (0.4424, 1140),Vanilla Readability Formula: (0.4025, 1140),Average Readability Formula minmax:(0.4673, 1140), Vanilla Readability Formula minmax:(0.4582, 1140)




noscale_aya_8b
unweighted:
 AVG:(0.6644, 1140),Vanilla:(0.6356, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7354, 1140),Vanilla mBERT:(0.7266, 1140), AVG Readability Formula: (0.6412, 1140), Vanilla Readability Formula: (0.6307, 1140)
entropy weightings:
 AVG mBERT:(0.6786, 1140),Vanilla mBERT:(0.653, 1140),Avg mBERT minmax:(0.7155, 1140),Vanilla mBERT minmax:(0.7072, 1140),Avg Readability Formula: (0.6687, 1140),Vanilla Readability Formula: (0.6427, 1140),Average Readability Formula minmax:(0.6307, 1140), Vanilla Readability Formula minmax:(0.6197, 1140)




gemma_9b
unweighted:
 AVG:(0.7404, 1140),Vanilla:(0.6878, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7948, 1140),Vanilla mBERT:(0.7737, 1140), AVG Readability Formula: (0.6985, 1140), Vanilla Readability Formula: (0.6739, 1140)
entropy weightings:
 AVG mBERT:(0.7467, 1140),Vanilla mBERT:(0.6974, 1140),Avg mBERT minmax:(0.7776, 1140),Vanilla mBERT minmax:(0.7605, 1140),Avg Readability Formula: (0.7425, 1140),Vanilla Readability Formula: (0.6929, 1140),Average Readability Formula minmax:(0.7276, 1140), Vanilla Readability Formula minmax:(0.7068, 1140)




noscale_gemma_9b
unweighted:
 AVG:(0.7086, 1139),Vanilla:(0.69, 1139),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7639, 1139),Vanilla mBERT:(0.7576, 1139), AVG Readability Formula: (0.6764, 1139), Vanilla Readability Formula: (0.6686, 1139)
entropy weightings:
 AVG mBERT:(0.7225, 1139),Vanilla mBERT:(0.7056, 1139),Avg mBERT minmax:(0.7607, 1139),Vanilla mBERT minmax:(0.7534, 1139),Avg Readability Formula: (0.7133, 1139),Vanilla Readability Formula: (0.6962, 1139),Average Readability Formula minmax:(0.6904, 1139), Vanilla Readability Formula minmax:(0.6812, 1139)




conf_noscale_gemma_9b
unweighted:
 AVG:(0.6879, 1140),Vanilla:(0.6448, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7704, 1140),Vanilla mBERT:(0.7524, 1140), AVG Readability Formula: (0.669, 1140), Vanilla Readability Formula: (0.6509, 1140)
entropy weightings:
 AVG mBERT:(0.7075, 1140),Vanilla mBERT:(0.6694, 1140),Avg mBERT minmax:(0.7733, 1140),Vanilla mBERT minmax:(0.7612, 1140),Avg Readability Formula: (0.6967, 1140),Vanilla Readability Formula: (0.659, 1140),Average Readability Formula minmax:(0.6981, 1140), Vanilla Readability Formula minmax:(0.6844, 1140)
verbal conf weightings:
 AVG mBERT:(0.7432, 1140),Vanilla mBERT:(0.7122, 1140),Avg mBERT minmax:(0.7527, 1140),Vanilla mBERT minmax:(0.73, 1140),Avg Readability Formula: (0.6997, 1140),Vanilla Readability Formula:(0.6688, 1140),Average Readability Formula minmax:(0.6864, 1140),Vanilla Readability Formula minmax: (0.6631, 1140)



conf_gemma_9b
unweighted:
 AVG:(0.7108, 1140),Vanilla:(0.6537, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7832, 1140),Vanilla mBERT:(0.7599, 1140), AVG Readability Formula: (0.6825, 1140), Vanilla Readability Formula: (0.6551, 1140)

entropy weightings:
 AVG mBERT:(0.7176, 1140),Vanilla mBERT:(0.6639, 1140),Avg mBERT minmax:(0.7541, 1140),Vanilla mBERT minmax:(0.7343, 1140),Avg Readability Formula: (0.7133, 1140),Vanilla Readability Formula: (0.6592, 1140),Average Readability Formula minmax:(0.706, 1140), Vanilla Readability Formula minmax:(0.6819, 1140)
verbal conf weightings:
 AVG mBERT:(0.7611, 1140),Vanilla mBERT:(0.7172, 1140),Avg mBERT minmax:(0.7323, 1140),Vanilla mBERT minmax:(0.7232, 1140),Avg Readability Formula: (0.7232, 1140),Vanilla Readability Formula:(0.677, 1140),Average Readability Formula minmax:(0.584, 1140),Vanilla Readability Formula minmax: (0.5714, 1140)



phi
unweighted:
 AVG:(0.6909, 1140),Vanilla:(0.6558, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7663, 1140),Vanilla mBERT:(0.7525, 1140), AVG Readability Formula: (0.6817, 1140), Vanilla Readability Formula: (0.6669, 1140)
entropy weightings:
 AVG mBERT:(0.7107, 1140),Vanilla mBERT:(0.6789, 1140),Avg mBERT minmax:(0.7732, 1140),Vanilla mBERT minmax:(0.7592, 1140),Avg Readability Formula: (0.7011, 1140),Vanilla Readability Formula: (0.6688, 1140),Average Readability Formula minmax:(0.6952, 1140), Vanilla Readability Formula minmax:(0.6812, 1140)




noscale_phi
unweighted:
 AVG:(0.6888, 1140),Vanilla:(0.6691, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7605, 1140),Vanilla mBERT:(0.7559, 1140), AVG Readability Formula: (0.6767, 1140), Vanilla Readability Formula: (0.6717, 1140)
entropy weightings:
 AVG mBERT:(0.7085, 1140),Vanilla mBERT:(0.6933, 1140),Avg mBERT minmax:(0.7447, 1140),Vanilla mBERT minmax:(0.7428, 1140),Avg Readability Formula: (0.6967, 1140),Vanilla Readability Formula: (0.6815, 1140),Average Readability Formula minmax:(0.6619, 1140), Vanilla Readability Formula minmax:(0.6586, 1140)




conf_noscale_phi
unweighted:
 AVG:(0.7157, 1140),Vanilla:(0.698, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7781, 1140),Vanilla mBERT:(0.7724, 1140), AVG Readability Formula: (0.6952, 1140), Vanilla Readability Formula: (0.6891, 1140)
entropy weightings:
 AVG mBERT:(0.7336, 1140),Vanilla mBERT:(0.7191, 1140),Avg mBERT minmax:(0.7713, 1140),Vanilla mBERT minmax:(0.7693, 1140),Avg Readability Formula: (0.7237, 1140),Vanilla Readability Formula: (0.7094, 1140),Average Readability Formula minmax:(0.7003, 1140), Vanilla Readability Formula minmax:(0.6973, 1140)
verbal conf weightings:
 AVG mBERT:(0.764, 1140),Vanilla mBERT:(0.752, 1140),Avg mBERT minmax:(0.7292, 1140),Vanilla mBERT minmax:(0.7237, 1140),Avg Readability Formula: (0.7276, 1140),Vanilla Readability Formula:(0.7154, 1140),Average Readability Formula minmax:(0.6216, 1140),Vanilla Readability Formula minmax: (0.6153, 1140)



conf_phi
unweighted:
 AVG:(0.702, 1140),Vanilla:(0.6766, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7779, 1140),Vanilla mBERT:(0.7666, 1140), AVG Readability Formula: (0.6933, 1140), Vanilla Readability Formula: (0.6826, 1140)
entropy weightings:
 AVG mBERT:(0.7214, 1140),Vanilla mBERT:(0.6977, 1140),Avg mBERT minmax:(0.7835, 1140),Vanilla mBERT minmax:(0.7738, 1140),Avg Readability Formula: (0.7128, 1140),Vanilla Readability Formula: (0.6892, 1140),Average Readability Formula minmax:(0.7052, 1140), Vanilla Readability Formula minmax:(0.6957, 1140)
verbal conf weightings:
 AVG mBERT:(0.7673, 1140),Vanilla mBERT:(0.7512, 1140),Avg mBERT minmax:(0.7729, 1140),Vanilla mBERT minmax:(0.7587, 1140),Avg Readability Formula: (0.7363, 1140),Vanilla Readability Formula:(0.7208, 1140),Average Readability Formula minmax:(0.7414, 1140),Vanilla Readability Formula minmax: (0.7273, 1140)



Mixtral
unweighted:
 AVG:(0.6665, 1140),Vanilla:(0.6598, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7634, 1140),Vanilla mBERT:(0.7602, 1140), AVG Readability Formula: (0.6606, 1140), Vanilla Readability Formula: (0.6576, 1140)
entropy weightings:
 AVG mBERT:(0.673, 1140),Vanilla mBERT:(0.6668, 1140),Avg mBERT minmax:(0.698, 1140),Vanilla mBERT minmax:(0.696, 1140),Avg Readability Formula: (0.6683, 1140),Vanilla Readability Formula: (0.6622, 1140),Average Readability Formula minmax:(0.6559, 1140), Vanilla Readability Formula minmax:(0.6538, 1140)




noscale_mixtral
unweighted:
 AVG:(0.6334, 1140),Vanilla:(0.6262, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7397, 1140),Vanilla mBERT:(0.7363, 1140), AVG Readability Formula: (0.6429, 1140), Vanilla Readability Formula: (0.6396, 1140)
entropy weightings:
 AVG mBERT:(0.642, 1140),Vanilla mBERT:(0.6354, 1140),Avg mBERT minmax:(0.6745, 1140),Vanilla mBERT minmax:(0.6727, 1140),Avg Readability Formula: (0.6369, 1140),Vanilla Readability Formula: (0.6302, 1140),Average Readability Formula minmax:(0.6249, 1140), Vanilla Readability Formula minmax:(0.623, 1140)




conf_noscale_mixtral
unweighted:
 AVG:(0.6305, 1140),Vanilla:(0.6271, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.735, 1140),Vanilla mBERT:(0.7328, 1140), AVG Readability Formula: (0.6411, 1140), Vanilla Readability Formula: (0.6395, 1140)
entropy weightings:
 AVG mBERT:(0.6382, 1140),Vanilla mBERT:(0.6349, 1140),Avg mBERT minmax:(0.6625, 1140),Vanilla mBERT minmax:(0.6612, 1140),Avg Readability Formula: (0.6331, 1140),Vanilla Readability Formula: (0.63, 1140),Average Readability Formula minmax:(0.6109, 1140), Vanilla Readability Formula minmax:(0.6098, 1140)
verbal conf weightings:
 AVG mBERT:(0.6799, 1140),Vanilla mBERT:(0.6766, 1140),Avg mBERT minmax:(0.6578, 1140),Vanilla mBERT minmax:(0.6545, 1140),Avg Readability Formula: (0.6448, 1140),Vanilla Readability Formula:(0.6417, 1140),Average Readability Formula minmax:(0.5737, 1140),Vanilla Readability Formula minmax: (0.5705, 1140)



conf_mixtral
unweighted:
 AVG:(0.63, 1140),Vanilla:(0.6171, 1140),RSRS:(0.6463, 1140),Readability Formula: (0.4693, 1140)
naive weightings:
 AVG mBERT:(0.7514, 1140),Vanilla mBERT:(0.747, 1140), AVG Readability Formula: (0.6478, 1140), Vanilla Readability Formula: (0.6437, 1140)
entropy weightings:
 AVG mBERT:(0.6383, 1140),Vanilla mBERT:(0.6268, 1140),Avg mBERT minmax:(0.6739, 1140),Vanilla mBERT minmax:(0.671, 1140),Avg Readability Formula: (0.6334, 1140),Vanilla Readability Formula: (0.6219, 1140),Average Readability Formula minmax:(0.6301, 1140), Vanilla Readability Formula minmax:(0.6272, 1140)
verbal conf weightings:
 AVG mBERT:(0.6878, 1140),Vanilla mBERT:(0.6772, 1140),Avg mBERT minmax:(0.6595, 1140),Vanilla mBERT minmax:(0.6543, 1140),Avg Readability Formula: (0.654, 1140),Vanilla Readability Formula:(0.6437, 1140),Average Readability Formula minmax:(0.5356, 1140),Vanilla Readability Formula minmax: (0.53, 1140)

## Cambridge

In [31]:
cambridgev2=pd.read_csv('.../cambridgev2.csv')
cambridgev2 = cambridgev2.replace("na", np.nan)
cambridgev2.columns

Index(['Unnamed: 0', 'ID', 'Text', 'Label', 'LLAMA_70b_vanilla',
       'LLAMA_70b_avg', 'LLAMA_70b_entropy', 'LLAMA_8b_vanilla',
       'LLAMA_8b_avg', 'LLAMA_8b_entropy',
       ...
       'conf_noscale_mixtral_avg', 'conf_noscale_mixtral_entropy',
       'conf_noscale_mixtral_verbal_conf', 'conf_mixtral_vanilla',
       'conf_mixtral_avg', 'conf_mixtral_entropy', 'conf_mixtral_verbal_conf',
       'FKGL', 'ARI', 'RSRS_mBERT'],
      dtype='object', length=139)

In [32]:
ref_col = cambridgev2.columns[3]
for i in range(4, len(cambridgev2.columns)): 
    col = cambridgev2.columns[i]
    corr = cambridgev2[ref_col].astype(float).corr(cambridgev2[col].astype(float))
    if ('entropy' not in col) and ('verbal_conf' not in col):
        print(f"{i+1}: {col} -> correlation with {ref_col}: {corr:.4f}")

5: LLAMA_70b_vanilla -> correlation with Label: 0.8420
6: LLAMA_70b_avg -> correlation with Label: 0.8618
8: LLAMA_8b_vanilla -> correlation with Label: 0.7888
9: LLAMA_8b_avg -> correlation with Label: 0.8358
11: LLAMA_3b_vanilla -> correlation with Label: 0.7308
12: LLAMA_3b_avg -> correlation with Label: 0.7997
14: gemma_27b_vanilla -> correlation with Label: 0.7191
15: gemma_27b_avg -> correlation with Label: 0.7836
17: gemma_2b_vanilla -> correlation with Label: 0.2978
18: gemma_2b_avg -> correlation with Label: 0.4483
20: gemma_9b_vanilla -> correlation with Label: 0.6708
21: gemma_9b_avg -> correlation with Label: 0.7329
23: phi_vanilla -> correlation with Label: 0.8038
24: phi_avg -> correlation with Label: 0.8312
26: AYA_32B_vanilla -> correlation with Label: 0.7856
27: AYA_32B_avg -> correlation with Label: 0.8082
29: AYA_8B_vanilla -> correlation with Label: 0.7669
30: AYA_8B_avg -> correlation with Label: 0.7953
32: mixtral_vanilla -> correlation with Label: 0.7460
33: mixtral_avg -> correlation with Label: 0.7696
35: noscale_mixtral_vanilla -> correlation with Label: 0.6399
36: noscale_mixtral_avg -> correlation with Label: 0.6565
38: noscale_aya_32b_vanilla -> correlation with Label: 0.7416
39: noscale_aya_32b_avg -> correlation with Label: 0.7832
41: noscale_aya_8b_vanilla -> correlation with Label: 0.6917
42: noscale_aya_8b_avg -> correlation with Label: 0.7331
44: noscale_llama_8b_vanilla -> correlation with Label: 0.5354
45: noscale_llama_8b_avg -> correlation with Label: 0.5416
47: noscale_llama_70b_vanilla -> correlation with Label: 0.8703
48: noscale_llama_70b_avg -> correlation with Label: 0.8895
50: noscale_llama_3b_vanilla -> correlation with Label: 0.5546
51: noscale_llama_3b_avg -> correlation with Label: 0.6163
53: noscale_gemma_9b_vanilla -> correlation with Label: 0.8431
54: noscale_gemma_9b_avg -> correlation with Label: 0.8688
56: noscale_gemma_2b_vanilla -> correlation with Label: 0.6533
57: noscale_gemma_2b_avg -> correlation with Label: 0.6339
59: noscale_gemma_27b_vanilla -> correlation with Label: 0.8236
60: noscale_gemma_27b_avg -> correlation with Label: 0.8490
62: noscale_phi_vanilla -> correlation with Label: 0.7228
63: noscale_phi_avg -> correlation with Label: 0.7581
65: conf_phi_vanilla -> correlation with Label: 0.8076
66: conf_phi_avg -> correlation with Label: 0.8307
69: conf_noscale_phi_vanilla -> correlation with Label: 0.7277
70: conf_noscale_phi_avg -> correlation with Label: 0.7751
73: conf_noscale_gemma_27b_vanilla -> correlation with Label: 0.8316
74: conf_noscale_gemma_27b_avg -> correlation with Label: 0.8558
77: conf_noscale_gemma_2b_vanilla -> correlation with Label: 0.4900
78: conf_noscale_gemma_2b_avg -> correlation with Label: 0.5573
81: conf_gemma_2b_vanilla -> correlation with Label: 0.5945
82: conf_gemma_2b_avg -> correlation with Label: 0.7043
85: conf_gemma_27b_vanilla -> correlation with Label: 0.7230
86: conf_gemma_27b_avg -> correlation with Label: 0.8039
89: conf_gemma_9b_vanilla -> correlation with Label: 0.6448
90: conf_gemma_9b_avg -> correlation with Label: 0.7277
93: conf_noscale_gemma_9b_vanilla -> correlation with Label: 0.8164
94: conf_noscale_gemma_9b_avg -> correlation with Label: 0.8475
97: conf_noscale_llama_3b_vanilla -> correlation with Label: 0.7529
98: conf_noscale_llama_3b_avg -> correlation with Label: 0.8220
101: conf_llama_3b_vanilla -> correlation with Label: 0.7131
102: conf_llama_3b_avg -> correlation with Label: 0.7934
105: conf_llama_70b_vanilla -> correlation with Label: 0.8206
106: conf_llama_70b_avg -> correlation with Label: 0.8531
109: conf_noscale_llama_70b_vanilla -> correlation with Label: 0.8883
110: conf_noscale_llama_70b_avg -> correlation with Label: 0.9124
113: conf_noscale_llama_8b_vanilla -> correlation with Label: 0.7740
114: conf_noscale_llama_8b_avg -> correlation with Label: 0.8028
117: conf_llama_8b_vanilla -> correlation with Label: 0.7909
118: conf_llama_8b_avg -> correlation with Label: 0.8307
121: conf_aya_32b_vanilla -> correlation with Label: 0.7221
122: conf_aya_32b_avg -> correlation with Label: 0.7622
125: conf_noscale_aya_32b_vanilla -> correlation with Label: 0.7221
126: conf_noscale_aya_32b_avg -> correlation with Label: 0.7622
129: conf_noscale_mixtral_vanilla -> correlation with Label: 0.6245
130: conf_noscale_mixtral_avg -> correlation with Label: 0.6598
133: conf_mixtral_vanilla -> correlation with Label: 0.7609
134: conf_mixtral_avg -> correlation with Label: 0.7794
137: FKGL -> correlation with Label: 0.7018
138: ARI -> correlation with Label: 0.6921
139: RSRS_mBERT -> correlation with Label: 0.7125

In [33]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
cambridgev2 = cambridgev2.apply(pd.to_numeric, errors="coerce")
rf_string='FKGL'
std_cols = [c for c in cambridgev2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
cambridgev2[std_cols] = StandardScaler().fit_transform(cambridgev2[std_cols])
model='conf_llama_70b'
vconf_col=f'{model}_verbal_conf'
avg_col = f"{model}_avg"


verbal_avg_rf=((1 - cambridgev2[vconf_col]/10) * cambridgev2[rf_string]) + (cambridgev2[vconf_col]/10 * cambridgev2[avg_col])


rjk,n1=safe_corr_raw(verbal_avg_rf, cambridgev2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(cambridgev2.iloc[:,108], cambridgev2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,cambridgev2.iloc[:,108])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs LLM : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, cambridgev2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(cambridgev2[rf_string], cambridgev2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,cambridgev2[rf_string])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RF : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, cambridgev2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(cambridgev2['RSRS_mBERT'], cambridgev2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,cambridgev2['RSRS_mBERT'])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RSRS : t2:{res1[0]}, p:{res1[1]}')

0.8595887620300114 0.8883239662078353 0.8952744731641742
299
t_test: Vconf RF vs LLM : t2:-2.4636974634390483, p:0.014319787706916776
0.8595887620300114 0.7018413448796332 0.8208365858684298
299
t_test: Vconf RF vs RF : t2:8.784169235701095, p:0.0
0.8595887620300114 0.7125480896224397 0.796177971205998
299
t_test: Vconf RF vs RSRS : t2:7.6819336857739, p:2.311484337269576e-13

In [34]:
import numpy as np
cambridgev2 = cambridgev2.apply(pd.to_numeric, errors="coerce")
rjk,n1=safe_corr_raw(cambridgev2.iloc[:,105], cambridgev2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(cambridgev2.iloc[:,109], cambridgev2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(cambridgev2.iloc[:,105],cambridgev2.iloc[:,109])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Scale vs No scale : t2:{res1[0]}, p:{res1[1]}')

import numpy as np
rjk,n1=safe_corr_raw(cambridgev2.iloc[:,105], cambridgev2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(cambridgev2.iloc[:,108], cambridgev2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(cambridgev2.iloc[:,105],cambridgev2.iloc[:,108])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Expected and Scale vs Vanilla and No scale : t2:{res1[0]}, p:{res1[1]}')

import numpy as np
rjk,n1=safe_corr_raw(cambridgev2.iloc[:,105], cambridgev2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(cambridgev2.iloc[:,104], cambridgev2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(cambridgev2.iloc[:,105],cambridgev2.iloc[:,104])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Expected vs vanilla : t2:{res1[0]}, p:{res1[1]}')



#rjk=np.corrcoef(avg_col, values)[0, 1]
##Change next two lines to best RSRS/readability formula
#rjh=np.corrcoef(df.RSRS_mBERT, values)[0, 1]
#rkh=np.corrcoef(df.RSRS_mBERT, avg_col)[0, 1]
#print(rjk,rjh,rkh)
#res1=calc_williams_t(rjk,rjh,rkh,len(avg_col))
#print(f't_test: LLM vs non-LAURAE best : t2:{res1[0]}, p:{res1[1]}')

0.8530817772630912 0.9124124610503147 0.908728326320364
299
t_test: Scale vs No scale : t2:-5.86567235292711, p:1.1952157930039675e-08
0.8530817772630912 0.8883239662078353 0.8833845087278069
299
t_test: Expected and Scale vs Vanilla and No scale : t2:-2.862818884637858, p:0.004498654532913315
0.8530817772630912 0.820629608769153 0.9766836764360329
299
t_test: Expected vs vanilla : t2:4.985745690570722, p:1.0529098570799533e-06

In [35]:
## from sklearn.preprocessing import MinMaxScaler, StandardScaler
cambridgev2 = cambridgev2.apply(pd.to_numeric, errors="coerce")
rf_string='FKGL'
ref_col = cambridgev2.columns[3]
#cambridgev2['RSRS_mBERT']= StandardScaler().fit_transform(cambridgev2['RSRS_mBERT'])
# Step 1: Normalize entropy columns
entropy_cols = [c for c in cambridgev2.columns if c.endswith("_entropy")]
entropy_cols_minmax = [c + "_minmax" for c in entropy_cols]
cambridgev2[entropy_cols_minmax] = MinMaxScaler().fit_transform(cambridgev2[entropy_cols])

vconf_cols = [c for c in cambridgev2.columns if c.endswith("verbal_conf")]
vconf_cols_minmax = [c + "_minmax" for c in vconf_cols]
cambridgev2[vconf_cols_minmax] = MinMaxScaler().fit_transform(cambridgev2[vconf_cols])
cambridgev2[vconf_cols] = cambridgev2[vconf_cols]/10

std_cols = [c for c in cambridgev2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
cambridgev2[std_cols] = StandardScaler().fit_transform(cambridgev2[std_cols])
suffixes = ["_avg", "_vanilla", "_entropy"]
models = set(
    c.rsplit("_", 1)[0]  # remove the last part after the final underscore
    for c in entropy_cols  # or any column list containing these suffixes
)
sorted_models = sorted(models, key=lambda x: x[::-1].lower())
for model in sorted_models:
    print(model)
    vanilla_col = f"{model}_vanilla"
    avg_col = f"{model}_avg"
    print(f'unweighted:\n AVG:{safe_corr(cambridgev2[avg_col], cambridgev2[ref_col])},Vanilla:{safe_corr(cambridgev2[vanilla_col], cambridgev2[ref_col])},RSRS:{safe_corr(cambridgev2["RSRS_mBERT"], cambridgev2[ref_col])},Readability Formula: {safe_corr(cambridgev2[rf_string], cambridgev2[ref_col])}')
    naive_avg_mBERT=cambridgev2[avg_col]+cambridgev2["RSRS_mBERT"]
    naive_vanilla_mBERT=cambridgev2[vanilla_col]+cambridgev2["RSRS_mBERT"]
    
    naive_avg_rf=cambridgev2[avg_col]+cambridgev2[rf_string]
    naive_vanilla_rf=cambridgev2[vanilla_col]+cambridgev2[rf_string]
    print(f'naive weightings: \n AVG mBERT:{safe_corr(naive_avg_mBERT, cambridgev2[ref_col])},Vanilla mBERT:{safe_corr(naive_vanilla_mBERT, cambridgev2[ref_col])}, AVG Readability Formula: {safe_corr(naive_avg_rf, cambridgev2[ref_col])}, Vanilla Readability Formula: {safe_corr(naive_vanilla_rf, cambridgev2[ref_col])}')
    entropy_col = f"{model}_entropy"
    entropy_col_minmax = f"{model}_entropy_minmax"
    if model.startswith('conf_'):
        vconf_col=f'{model}_verbal_conf'
        vconf_col_minmax = f"{model}_verbal_conf_minmax"
    
    #cambridgev2[f"{model}_weighted"] = (
    #    cambridgev2[entropy_col] * cambridgev2["RSRS_mBERT"] + 
    #    (1 - cambridgev2[entropy_col]) * (cambridgev2[[vanilla_col, avg_col]].mean(axis=1))
    #)
    entropy_avg_mBERT=(cambridgev2[entropy_col] * cambridgev2["RSRS_mBERT"]) + ((1 - cambridgev2[entropy_col]) * cambridgev2[avg_col])
    entropy_vanilla_mBERT=(cambridgev2[entropy_col] * cambridgev2["RSRS_mBERT"]) + ((1 - cambridgev2[entropy_col]) * cambridgev2[vanilla_col])
    entropy_minmax_avg_mBERT=(cambridgev2[entropy_col_minmax] * cambridgev2["RSRS_mBERT"]) + ((1 - cambridgev2[entropy_col_minmax]) * cambridgev2[avg_col])
    entropy_minmax_vanilla_mBERT=(cambridgev2[entropy_col_minmax] * cambridgev2["RSRS_mBERT"]) + ((1 - cambridgev2[entropy_col_minmax]) * cambridgev2[vanilla_col])
    
    entropy_avg_rf=(cambridgev2[entropy_col] * cambridgev2[rf_string]) + ((1 - cambridgev2[entropy_col]) * cambridgev2[avg_col])
    entropy_vanilla_rf=(cambridgev2[entropy_col] * cambridgev2[rf_string]) + ((1 - cambridgev2[entropy_col]) * cambridgev2[vanilla_col])
    entropy_minmax_avg_rf=(cambridgev2[entropy_col_minmax] * cambridgev2[rf_string]) + ((1 - cambridgev2[entropy_col_minmax]) * cambridgev2[avg_col])
    entropy_minmax_vanilla_rf=(cambridgev2[entropy_col_minmax] * cambridgev2[rf_string]) + ((1 - cambridgev2[entropy_col_minmax]) * cambridgev2[vanilla_col])
    print(f'entropy weightings:\n AVG mBERT:{safe_corr(entropy_avg_mBERT, cambridgev2[ref_col])},Vanilla mBERT:{safe_corr(entropy_vanilla_mBERT, cambridgev2[ref_col])},Avg mBERT minmax:{safe_corr(entropy_minmax_avg_mBERT, cambridgev2[ref_col])},Vanilla mBERT minmax:{safe_corr(entropy_minmax_vanilla_mBERT, cambridgev2[ref_col])},Avg Readability Formula: {safe_corr(entropy_avg_rf, cambridgev2[ref_col])},Vanilla Readability Formula: {safe_corr(entropy_vanilla_rf, cambridgev2[ref_col])},Average Readability Formula minmax:{safe_corr(entropy_minmax_avg_rf, cambridgev2[ref_col])}, Vanilla Readability Formula minmax:{safe_corr(entropy_minmax_vanilla_rf, cambridgev2[ref_col])}')
    if model.startswith('conf_'):
        verbal_avg_mBERT=((1 - cambridgev2[vconf_col]) * cambridgev2["RSRS_mBERT"]) + (cambridgev2[vconf_col] * cambridgev2[avg_col])
        verbal_vanilla_mBERT=((1 - cambridgev2[vconf_col]) * cambridgev2["RSRS_mBERT"]) + (cambridgev2[vconf_col] * cambridgev2[vanilla_col])
        verbal_minmax_avg_mBERT=((1 - cambridgev2[vconf_col_minmax]) * cambridgev2["RSRS_mBERT"]) + (cambridgev2[vconf_col_minmax] * cambridgev2[avg_col])
        verbal_minmax_vanilla_mBERT=((1 - cambridgev2[vconf_col_minmax]) * cambridgev2["RSRS_mBERT"]) + (cambridgev2[vconf_col_minmax] * cambridgev2[vanilla_col])
        
        verbal_avg_rf=((1 - cambridgev2[vconf_col]) * cambridgev2[rf_string]) + (cambridgev2[vconf_col] * cambridgev2[avg_col])
        verbal_vanilla_rf=((1 - cambridgev2[vconf_col]) * cambridgev2[rf_string]) + (cambridgev2[vconf_col] * cambridgev2[vanilla_col])
        verbal_minmax_avg_rf=((1 - cambridgev2[vconf_col_minmax]) * cambridgev2[rf_string]) + (cambridgev2[vconf_col_minmax] * cambridgev2[avg_col])
        verbal_minmax_vanilla_rf=((1 - cambridgev2[vconf_col_minmax]) * cambridgev2[rf_string]) + (cambridgev2[vconf_col_minmax] * cambridgev2[vanilla_col])
        print(f'verbal conf weightings:\n AVG mBERT:{safe_corr(verbal_avg_mBERT, cambridgev2[ref_col])},Vanilla mBERT:{safe_corr(verbal_vanilla_mBERT, cambridgev2[ref_col])},Avg mBERT minmax:{safe_corr(verbal_minmax_avg_mBERT, cambridgev2[ref_col])},Vanilla mBERT minmax:{safe_corr(verbal_minmax_vanilla_mBERT, cambridgev2[ref_col])},Avg Readability Formula: {safe_corr(verbal_avg_rf, cambridgev2[ref_col])},Vanilla Readability Formula:{safe_corr(verbal_vanilla_rf, cambridgev2[ref_col])},Average Readability Formula minmax:{safe_corr(verbal_minmax_avg_rf, cambridgev2[ref_col])},Vanilla Readability Formula minmax: {safe_corr(verbal_minmax_vanilla_rf, cambridgev2[ref_col])}','\n \n \n')
    else:
        print('\n \n \n')

LLAMA_70b
unweighted:
 AVG:(0.8618, 300),Vanilla:(0.842, 300),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8468, 300),Vanilla mBERT:(0.8397, 300), AVG Readability Formula: (0.8406, 300), Vanilla Readability Formula: (0.8353, 300)
entropy weightings:
 AVG mBERT:(0.8629, 300),Vanilla mBERT:(0.8448, 300),Avg mBERT minmax:(0.8088, 300),Vanilla mBERT minmax:(0.8081, 300),Avg Readability Formula: (0.8629, 300),Vanilla Readability Formula: (0.8451, 300),Average Readability Formula minmax:(0.8161, 300), Vanilla Readability Formula minmax:(0.8162, 300)




noscale_llama_70b
unweighted:
 AVG:(0.8895, 293),Vanilla:(0.8703, 293),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8541, 293),Vanilla mBERT:(0.8505, 293), AVG Readability Formula: (0.8461, 293), Vanilla Readability Formula: (0.8409, 293)
entropy weightings:
 AVG mBERT:(0.8904, 293),Vanilla mBERT:(0.8742, 293),Avg mBERT minmax:(0.8275, 293),Vanilla mBERT minmax:(0.8251, 293),Avg Readability Formula: (0.8892, 293),Vanilla Readability Formula: (0.8724, 293),Average Readability Formula minmax:(0.8148, 293), Vanilla Readability Formula minmax:(0.8116, 293)




conf_noscale_llama_70b
unweighted:
 AVG:(0.9124, 299),Vanilla:(0.8883, 299),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8658, 299),Vanilla mBERT:(0.8577, 299), AVG Readability Formula: (0.8593, 299), Vanilla Readability Formula: (0.8509, 299)
entropy weightings:
 AVG mBERT:(0.912, 299),Vanilla mBERT:(0.8906, 299),Avg mBERT minmax:(0.8398, 299),Vanilla mBERT minmax:(0.8352, 299),Avg Readability Formula: (0.9112, 299),Vanilla Readability Formula: (0.8897, 299),Average Readability Formula minmax:(0.8258, 299), Vanilla Readability Formula minmax:(0.8206, 299)
verbal conf weightings:
 AVG mBERT:(0.9077, 299),Vanilla mBERT:(0.8907, 299),Avg mBERT minmax:(0.8465, 299),Vanilla mBERT minmax:(0.8401, 299),Avg Readability Formula: (0.9047, 299),Vanilla Readability Formula:(0.8876, 299),Average Readability Formula minmax:(0.8365, 299),Vanilla Readability Formula minmax: (0.8301, 299)



conf_llama_70b
unweighted:
 AVG:(0.8531, 299),Vanilla:(0.8206, 299),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8416, 299),Vanilla mBERT:(0.8335, 299), AVG Readability Formula: (0.8342, 299), Vanilla Readability Formula: (0.8261, 299)
entropy weightings:
 AVG mBERT:(0.8544, 299),Vanilla mBERT:(0.8251, 299),Avg mBERT minmax:(0.7869, 299),Vanilla mBERT minmax:(0.7861, 299),Avg Readability Formula: (0.8546, 299),Vanilla Readability Formula: (0.8251, 299),Average Readability Formula minmax:(0.7894, 299), Vanilla Readability Formula minmax:(0.7894, 299)
verbal conf weightings:
 AVG mBERT:(0.8635, 299),Vanilla mBERT:(0.8414, 299),Avg mBERT minmax:(0.7374, 299),Vanilla mBERT minmax:(0.7322, 299),Avg Readability Formula: (0.8596, 299),Vanilla Readability Formula:(0.8375, 299),Average Readability Formula minmax:(0.7157, 299),Vanilla Readability Formula minmax: (0.7106, 299)



AYA_32B
unweighted:
 AVG:(0.8082, 300),Vanilla:(0.7856, 300),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8202, 300),Vanilla mBERT:(0.8135, 300), AVG Readability Formula: (0.8162, 300), Vanilla Readability Formula: (0.8108, 300)
entropy weightings:
 AVG mBERT:(0.8089, 300),Vanilla mBERT:(0.7882, 300),Avg mBERT minmax:(0.8017, 300),Vanilla mBERT minmax:(0.7972, 300),Avg Readability Formula: (0.8087, 300),Vanilla Readability Formula: (0.7881, 300),Average Readability Formula minmax:(0.7966, 300), Vanilla Readability Formula minmax:(0.7923, 300)




noscale_aya_32b
unweighted:
 AVG:(0.7832, 248),Vanilla:(0.7416, 248),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8186, 248),Vanilla mBERT:(0.8019, 248), AVG Readability Formula: (0.8169, 248), Vanilla Readability Formula: (0.8039, 248)
entropy weightings:
 AVG mBERT:(0.7877, 248),Vanilla mBERT:(0.7482, 248),Avg mBERT minmax:(0.816, 248),Vanilla mBERT minmax:(0.7987, 248),Avg Readability Formula: (0.7877, 248),Vanilla Readability Formula: (0.7487, 248),Average Readability Formula minmax:(0.8116, 248), Vanilla Readability Formula minmax:(0.7978, 248)




conf_noscale_aya_32b
unweighted:
 AVG:(0.7622, 296),Vanilla:(0.7221, 296),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8058, 296),Vanilla mBERT:(0.7899, 296), AVG Readability Formula: (0.7984, 296), Vanilla Readability Formula: (0.7821, 296)
entropy weightings:
 AVG mBERT:(0.764, 296),Vanilla mBERT:(0.7264, 296),Avg mBERT minmax:(0.7747, 296),Vanilla mBERT minmax:(0.7684, 296),Avg Readability Formula: (0.7637, 296),Vanilla Readability Formula: (0.7262, 296),Average Readability Formula minmax:(0.7721, 296), Vanilla Readability Formula minmax:(0.7657, 296)
verbal conf weightings:
 AVG mBERT:(0.8059, 284),Vanilla mBERT:(0.7788, 284),Avg mBERT minmax:(0.7969, 284),Vanilla mBERT minmax:(0.7666, 284),Avg Readability Formula: (0.8018, 284),Vanilla Readability Formula:(0.7747, 284),Average Readability Formula minmax:(0.7939, 284),Vanilla Readability Formula minmax: (0.7637, 284)



conf_aya_32b
unweighted:
 AVG:(0.7622, 296),Vanilla:(0.7221, 296),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8058, 296),Vanilla mBERT:(0.7899, 296), AVG Readability Formula: (0.7984, 296), Vanilla Readability Formula: (0.7821, 296)
entropy weightings:
 AVG mBERT:(0.764, 296),Vanilla mBERT:(0.7264, 296),Avg mBERT minmax:(0.7747, 296),Vanilla mBERT minmax:(0.7684, 296),Avg Readability Formula: (0.7637, 296),Vanilla Readability Formula: (0.7262, 296),Average Readability Formula minmax:(0.7721, 296), Vanilla Readability Formula minmax:(0.7657, 296)
verbal conf weightings:
 AVG mBERT:(0.8059, 284),Vanilla mBERT:(0.7788, 284),Avg mBERT minmax:(0.7969, 284),Vanilla mBERT minmax:(0.7666, 284),Avg Readability Formula: (0.8018, 284),Vanilla Readability Formula:(0.7747, 284),Average Readability Formula minmax:(0.7939, 284),Vanilla Readability Formula minmax: (0.7637, 284)



gemma_2b
unweighted:
 AVG:(0.4483, 299),Vanilla:(0.2978, 299),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.7179, 299),Vanilla mBERT:(0.6526, 299), AVG Readability Formula: (0.7142, 299), Vanilla Readability Formula: (0.6549, 299)
entropy weightings:
 AVG mBERT:(0.4535, 299),Vanilla mBERT:(0.3062, 299),Avg mBERT minmax:(0.5066, 299),Vanilla mBERT minmax:(0.4507, 299),Avg Readability Formula: (0.4535, 299),Vanilla Readability Formula: (0.3066, 299),Average Readability Formula minmax:(0.488, 299), Vanilla Readability Formula minmax:(0.4311, 299)




noscale_gemma_2b
unweighted:
 AVG:(0.6339, 249),Vanilla:(0.6533, 249),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.7456, 249),Vanilla mBERT:(0.7621, 249), AVG Readability Formula: (0.7429, 249), Vanilla Readability Formula: (0.758, 249)
entropy weightings:
 AVG mBERT:(0.662, 249),Vanilla mBERT:(0.6791, 249),Avg mBERT minmax:(0.7597, 249),Vanilla mBERT minmax:(0.763, 249),Avg Readability Formula: (0.6607, 249),Vanilla Readability Formula: (0.6774, 249),Average Readability Formula minmax:(0.7588, 249), Vanilla Readability Formula minmax:(0.7607, 249)




conf_noscale_gemma_2b
unweighted:
 AVG:(0.5573, 246),Vanilla:(0.49, 246),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.715, 246),Vanilla mBERT:(0.6864, 246), AVG Readability Formula: (0.7084, 246), Vanilla Readability Formula: (0.6823, 246)
entropy weightings:
 AVG mBERT:(0.5829, 246),Vanilla mBERT:(0.5207, 246),Avg mBERT minmax:(0.7131, 246),Vanilla mBERT minmax:(0.6991, 246),Avg Readability Formula: (0.5813, 246),Vanilla Readability Formula: (0.5196, 246),Average Readability Formula minmax:(0.7208, 246), Vanilla Readability Formula minmax:(0.7108, 246)
verbal conf weightings:
 AVG mBERT:(0.6635, 246),Vanilla mBERT:(0.617, 246),Avg mBERT minmax:(0.7082, 246),Vanilla mBERT minmax:(0.6846, 246),Avg Readability Formula: (0.6584, 246),Vanilla Readability Formula:(0.6136, 246),Average Readability Formula minmax:(0.7034, 246),Vanilla Readability Formula minmax: (0.6818, 246)



conf_gemma_2b
unweighted:
 AVG:(0.7043, 153),Vanilla:(0.5945, 153),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.7938, 153),Vanilla mBERT:(0.755, 153), AVG Readability Formula: (0.7922, 153), Vanilla Readability Formula: (0.753, 153)
entropy weightings:
 AVG mBERT:(0.7102, 153),Vanilla mBERT:(0.6064, 153),Avg mBERT minmax:(0.743, 153),Vanilla mBERT minmax:(0.6936, 153),Avg Readability Formula: (0.7099, 153),Vanilla Readability Formula: (0.6061, 153),Average Readability Formula minmax:(0.739, 153), Vanilla Readability Formula minmax:(0.6895, 153)
verbal conf weightings:
 AVG mBERT:(0.7787, 151),Vanilla mBERT:(0.7087, 151),Avg mBERT minmax:(0.7373, 151),Vanilla mBERT minmax:(0.641, 151),Avg Readability Formula: (0.7728, 151),Vanilla Readability Formula:(0.7016, 151),Average Readability Formula minmax:(0.7344, 151),Vanilla Readability Formula minmax: (0.6377, 151)



LLAMA_3b
unweighted:
 AVG:(0.7997, 296),Vanilla:(0.7308, 296),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8435, 296),Vanilla mBERT:(0.8182, 296), AVG Readability Formula: (0.8479, 296), Vanilla Readability Formula: (0.8219, 296)
entropy weightings:
 AVG mBERT:(0.8121, 296),Vanilla mBERT:(0.7481, 296),Avg mBERT minmax:(0.8416, 296),Vanilla mBERT minmax:(0.8229, 296),Avg Readability Formula: (0.8131, 296),Vanilla Readability Formula: (0.7491, 296),Average Readability Formula minmax:(0.8407, 296), Vanilla Readability Formula minmax:(0.8213, 296)




noscale_llama_3b
unweighted:
 AVG:(0.6163, 267),Vanilla:(0.5546, 267),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.7693, 267),Vanilla mBERT:(0.7475, 267), AVG Readability Formula: (0.7749, 267), Vanilla Readability Formula: (0.7508, 267)
entropy weightings:
 AVG mBERT:(0.6308, 267),Vanilla mBERT:(0.5811, 267),Avg mBERT minmax:(0.66, 267),Vanilla mBERT minmax:(0.6684, 267),Avg Readability Formula: (0.6318, 267),Vanilla Readability Formula: (0.5814, 267),Average Readability Formula minmax:(0.6645, 267), Vanilla Readability Formula minmax:(0.6727, 267)




conf_noscale_llama_3b
unweighted:
 AVG:(0.822, 276),Vanilla:(0.7529, 276),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8417, 276),Vanilla mBERT:(0.8206, 276), AVG Readability Formula: (0.8405, 276), Vanilla Readability Formula: (0.8152, 276)
entropy weightings:
 AVG mBERT:(0.8342, 276),Vanilla mBERT:(0.7742, 276),Avg mBERT minmax:(0.8241, 276),Vanilla mBERT minmax:(0.8177, 276),Avg Readability Formula: (0.8352, 276),Vanilla Readability Formula: (0.774, 276),Average Readability Formula minmax:(0.8238, 276), Vanilla Readability Formula minmax:(0.8147, 276)
verbal conf weightings:
 AVG mBERT:(0.8473, 258),Vanilla mBERT:(0.8024, 258),Avg mBERT minmax:(0.8342, 258),Vanilla mBERT minmax:(0.7754, 258),Avg Readability Formula: (0.8501, 258),Vanilla Readability Formula:(0.803, 258),Average Readability Formula minmax:(0.8355, 258),Vanilla Readability Formula minmax: (0.7761, 258)



conf_llama_3b
unweighted:
 AVG:(0.7934, 274),Vanilla:(0.7131, 274),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8366, 274),Vanilla mBERT:(0.8069, 274), AVG Readability Formula: (0.8429, 274), Vanilla Readability Formula: (0.8122, 274)
entropy weightings:
 AVG mBERT:(0.8059, 274),Vanilla mBERT:(0.7318, 274),Avg mBERT minmax:(0.8377, 274),Vanilla mBERT minmax:(0.8177, 274),Avg Readability Formula: (0.8075, 274),Vanilla Readability Formula: (0.7333, 274),Average Readability Formula minmax:(0.8438, 274), Vanilla Readability Formula minmax:(0.8233, 274)
verbal conf weightings:
 AVG mBERT:(0.8226, 204),Vanilla mBERT:(0.7597, 204),Avg mBERT minmax:(0.8045, 204),Vanilla mBERT minmax:(0.7298, 204),Avg Readability Formula: (0.828, 204),Vanilla Readability Formula:(0.7644, 204),Average Readability Formula minmax:(0.8076, 204),Vanilla Readability Formula minmax: (0.7325, 204)



gemma_27b
unweighted:
 AVG:(0.7836, 300),Vanilla:(0.7191, 300),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.815, 300),Vanilla mBERT:(0.7906, 300), AVG Readability Formula: (0.8127, 300), Vanilla Readability Formula: (0.7876, 300)
entropy weightings:
 AVG mBERT:(0.7864, 300),Vanilla mBERT:(0.7256, 300),Avg mBERT minmax:(0.7806, 300),Vanilla mBERT minmax:(0.7648, 300),Avg Readability Formula: (0.7862, 300),Vanilla Readability Formula: (0.7254, 300),Average Readability Formula minmax:(0.7836, 300), Vanilla Readability Formula minmax:(0.7681, 300)




noscale_gemma_27b
unweighted:
 AVG:(0.849, 265),Vanilla:(0.8236, 265),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8377, 265),Vanilla mBERT:(0.8344, 265), AVG Readability Formula: (0.8306, 265), Vanilla Readability Formula: (0.8279, 265)
entropy weightings:
 AVG mBERT:(0.8529, 265),Vanilla mBERT:(0.8305, 265),Avg mBERT minmax:(0.8168, 265),Vanilla mBERT minmax:(0.8157, 265),Avg Readability Formula: (0.8522, 265),Vanilla Readability Formula: (0.83, 265),Average Readability Formula minmax:(0.8055, 265), Vanilla Readability Formula minmax:(0.8042, 265)




conf_noscale_gemma_27b
unweighted:
 AVG:(0.8558, 296),Vanilla:(0.8316, 296),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8373, 296),Vanilla mBERT:(0.8322, 296), AVG Readability Formula: (0.8298, 296), Vanilla Readability Formula: (0.8269, 296)
entropy weightings:
 AVG mBERT:(0.8589, 296),Vanilla mBERT:(0.8372, 296),Avg mBERT minmax:(0.7961, 296),Vanilla mBERT minmax:(0.7931, 296),Avg Readability Formula: (0.8577, 296),Vanilla Readability Formula: (0.8365, 296),Average Readability Formula minmax:(0.7827, 296), Vanilla Readability Formula minmax:(0.781, 296)

verbal conf weightings:
 AVG mBERT:(0.8592, 296),Vanilla mBERT:(0.8475, 296),Avg mBERT minmax:(0.8038, 296),Vanilla mBERT minmax:(0.802, 296),Avg Readability Formula: (0.8533, 296),Vanilla Readability Formula:(0.8435, 296),Average Readability Formula minmax:(0.7904, 296),Vanilla Readability Formula minmax: (0.7901, 296)



conf_gemma_27b
unweighted:
 AVG:(0.8039, 299),Vanilla:(0.723, 299),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8344, 299),Vanilla mBERT:(0.8113, 299), AVG Readability Formula: (0.8289, 299), Vanilla Readability Formula: (0.8051, 299)
entropy weightings:
 AVG mBERT:(0.808, 299),Vanilla mBERT:(0.7331, 299),Avg mBERT minmax:(0.8224, 299),Vanilla mBERT minmax:(0.8089, 299),Avg Readability Formula: (0.8078, 299),Vanilla Readability Formula: (0.7327, 299),Average Readability Formula minmax:(0.8193, 299), Vanilla Readability Formula minmax:(0.8058, 299)
verbal conf weightings:
 AVG mBERT:(0.8358, 299),Vanilla mBERT:(0.7896, 299),Avg mBERT minmax:(0.7272, 299),Vanilla mBERT minmax:(0.7214, 299),Avg Readability Formula: (0.8314, 299),Vanilla Readability Formula:(0.7848, 299),Average Readability Formula minmax:(0.7142, 299),Vanilla Readability Formula minmax: (0.7074, 299)



LLAMA_8b
unweighted:
 AVG:(0.8358, 298),Vanilla:(0.7888, 298),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8448, 298),Vanilla mBERT:(0.8294, 298), AVG Readability Formula: (0.8391, 298), Vanilla Readability Formula: (0.8223, 298)
entropy weightings:
 AVG mBERT:(0.8406, 298),Vanilla mBERT:(0.7976, 298),Avg mBERT minmax:(0.8443, 298),Vanilla mBERT minmax:(0.836, 298),Avg Readability Formula: (0.8403, 298),Vanilla Readability Formula: (0.797, 298),Average Readability Formula minmax:(0.841, 298), Vanilla Readability Formula minmax:(0.8315, 298)




noscale_llama_8b
unweighted:
 AVG:(0.5416, 287),Vanilla:(0.5354, 287),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.7087, 287),Vanilla mBERT:(0.7087, 287), AVG Readability Formula: (0.7013, 287), Vanilla Readability Formula: (0.7032, 287)
entropy weightings:
 AVG mBERT:(0.5477, 287),Vanilla mBERT:(0.5452, 287),Avg mBERT minmax:(0.5551, 287),Vanilla mBERT minmax:(0.5677, 287),Avg Readability Formula: (0.5475, 287),Vanilla Readability Formula: (0.5452, 287),Average Readability Formula minmax:(0.555, 287), Vanilla Readability Formula minmax:(0.5691, 287)




conf_noscale_llama_8b
unweighted:
 AVG:(0.8028, 291),Vanilla:(0.774, 291),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8117, 291),Vanilla mBERT:(0.8041, 291), AVG Readability Formula: (0.8092, 291), Vanilla Readability Formula: (0.7989, 291)
entropy weightings:
 AVG mBERT:(0.8091, 291),Vanilla mBERT:(0.7836, 291),Avg mBERT minmax:(0.8109, 291),Vanilla mBERT minmax:(0.7996, 291),Avg Readability Formula: (0.8088, 291),Vanilla Readability Formula: (0.7825, 291),Average Readability Formula minmax:(0.8087, 291), Vanilla Readability Formula minmax:(0.7957, 291)
verbal conf weightings:
 AVG mBERT:(0.8186, 291),Vanilla mBERT:(0.7996, 291),Avg mBERT minmax:(0.797, 291),Vanilla mBERT minmax:(0.7914, 291),Avg Readability Formula: (0.8176, 291),Vanilla Readability Formula:(0.797, 291),Average Readability Formula minmax:(0.7923, 291),Vanilla Readability Formula minmax: (0.7842, 291)



conf_llama_8b
unweighted:
 AVG:(0.8307, 297),Vanilla:(0.7909, 297),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8446, 297),Vanilla mBERT:(0.8322, 297), AVG Readability Formula: (0.8399, 297), Vanilla Readability Formula: (0.8269, 297)
entropy weightings:
 AVG mBERT:(0.8342, 297),Vanilla mBERT:(0.7981, 297),Avg mBERT minmax:(0.845, 297),Vanilla mBERT minmax:(0.8302, 297),Avg Readability Formula: (0.8342, 297),Vanilla Readability Formula: (0.7979, 297),Average Readability Formula minmax:(0.8441, 297), Vanilla Readability Formula minmax:(0.8286, 297)
verbal conf weightings:
 AVG mBERT:(0.8552, 295),Vanilla mBERT:(0.8274, 295),Avg mBERT minmax:(0.8528, 295),Vanilla mBERT minmax:(0.823, 295),Avg Readability Formula: (0.8533, 295),Vanilla Readability Formula:(0.8252, 295),Average Readability Formula minmax:(0.8509, 295),Vanilla Readability Formula minmax: (0.8208, 295)



AYA_8B
unweighted:
 AVG:(0.7953, 299),Vanilla:(0.7669, 299),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8409, 299),Vanilla mBERT:(0.8345, 299), AVG Readability Formula: (0.835, 299), Vanilla Readability Formula: (0.8298, 299)
entropy weightings:
 AVG mBERT:(0.7978, 299),Vanilla mBERT:(0.772, 299),Avg mBERT minmax:(0.8143, 299),Vanilla mBERT minmax:(0.8096, 299),Avg Readability Formula: (0.7975, 299),Vanilla Readability Formula: (0.7719, 299),Average Readability Formula minmax:(0.8124, 299), Vanilla Readability Formula minmax:(0.8085, 299)




noscale_aya_8b
unweighted:
 AVG:(0.7331, 269),Vanilla:(0.6917, 269),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.7974, 269),Vanilla mBERT:(0.786, 269), AVG Readability Formula: (0.7817, 269), Vanilla Readability Formula: (0.7711, 269)
entropy weightings:
 AVG mBERT:(0.7464, 269),Vanilla mBERT:(0.7101, 269),Avg mBERT minmax:(0.7917, 269),Vanilla mBERT minmax:(0.7884, 269),Avg Readability Formula: (0.7436, 269),Vanilla Readability Formula: (0.7073, 269),Average Readability Formula minmax:(0.7724, 269), Vanilla Readability Formula minmax:(0.7697, 269)




gemma_9b
unweighted:
 AVG:(0.7329, 300),Vanilla:(0.6708, 300),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.7889, 300),Vanilla mBERT:(0.7661, 300), AVG Readability Formula: (0.7816, 300), Vanilla Readability Formula: (0.7602, 300)
entropy weightings:
 AVG mBERT:(0.7358, 300),Vanilla mBERT:(0.6774, 300),Avg mBERT minmax:(0.7541, 300),Vanilla mBERT minmax:(0.7415, 300),Avg Readability Formula: (0.7356, 300),Vanilla Readability Formula: (0.6774, 300),Average Readability Formula minmax:(0.7539, 300), Vanilla Readability Formula minmax:(0.741, 300)




noscale_gemma_9b
unweighted:
 AVG:(0.8688, 259),Vanilla:(0.8431, 259),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.839, 259),Vanilla mBERT:(0.8304, 259), AVG Readability Formula: (0.8355, 259), Vanilla Readability Formula: (0.8274, 259)
entropy weightings:
 AVG mBERT:(0.8703, 259),Vanilla mBERT:(0.8468, 259),Avg mBERT minmax:(0.7979, 259),Vanilla mBERT minmax:(0.7942, 259),Avg Readability Formula: (0.8694, 259),Vanilla Readability Formula: (0.846, 259),Average Readability Formula minmax:(0.7966, 259), Vanilla Readability Formula minmax:(0.7936, 259)




conf_noscale_gemma_9b
unweighted:
 AVG:(0.8475, 298),Vanilla:(0.8164, 298),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8288, 298),Vanilla mBERT:(0.8186, 298), AVG Readability Formula: (0.8243, 298), Vanilla Readability Formula: (0.813, 298)
entropy weightings:
 AVG mBERT:(0.8513, 298),Vanilla mBERT:(0.8236, 298),Avg mBERT minmax:(0.8277, 298),Vanilla mBERT minmax:(0.82, 298),Avg Readability Formula: (0.8506, 298),Vanilla Readability Formula: (0.8226, 298),Average Readability Formula minmax:(0.827, 298), Vanilla Readability Formula minmax:(0.8184, 298)
verbal conf weightings:
 AVG mBERT:(0.8518, 298),Vanilla mBERT:(0.8303, 298),Avg mBERT minmax:(0.8073, 298),Vanilla mBERT minmax:(0.8008, 298),Avg Readability Formula: (0.8492, 298),Vanilla Readability Formula:(0.8271, 298),Average Readability Formula minmax:(0.7943, 298),Vanilla Readability Formula minmax: (0.7863, 298)



conf_gemma_9b
unweighted:
 AVG:(0.7277, 299),Vanilla:(0.6448, 299),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.7897, 299),Vanilla mBERT:(0.7593, 299), AVG Readability Formula: (0.7791, 299), Vanilla Readability Formula: (0.7476, 299)
entropy weightings:
 AVG mBERT:(0.7315, 299),Vanilla mBERT:(0.6536, 299),Avg mBERT minmax:(0.758, 299),Vanilla mBERT minmax:(0.7425, 299),Avg Readability Formula: (0.7309, 299),Vanilla Readability Formula: (0.6528, 299),Average Readability Formula minmax:(0.7517, 299), Vanilla Readability Formula minmax:(0.7355, 299)
verbal conf weightings:
 AVG mBERT:(0.7637, 299),Vanilla mBERT:(0.7018, 299),Avg mBERT minmax:(0.7248, 299),Vanilla mBERT minmax:(0.7168, 299),Avg Readability Formula: (0.7583, 299),Vanilla Readability Formula:(0.6961, 299),Average Readability Formula minmax:(0.7111, 299),Vanilla Readability Formula minmax: (0.7022, 299)



phi
unweighted:
 AVG:(0.8312, 300),Vanilla:(0.8038, 300),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8453, 300),Vanilla mBERT:(0.8383, 300), AVG Readability Formula: (0.834, 300), Vanilla Readability Formula: (0.8262, 300)
entropy weightings:
 AVG mBERT:(0.8367, 300),Vanilla mBERT:(0.8116, 300),Avg mBERT minmax:(0.779, 300),Vanilla mBERT minmax:(0.7751, 300),Avg Readability Formula: (0.8356, 300),Vanilla Readability Formula: (0.8103, 300),Average Readability Formula minmax:(0.7636, 300), Vanilla Readability Formula minmax:(0.7591, 300)




noscale_phi
unweighted:
 AVG:(0.7581, 292),Vanilla:(0.7228, 292),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8078, 292),Vanilla mBERT:(0.7982, 292), AVG Readability Formula: (0.7962, 292), Vanilla Readability Formula: (0.7852, 292)
entropy weightings:
 AVG mBERT:(0.7724, 292),Vanilla mBERT:(0.7408, 292),Avg mBERT minmax:(0.7802, 292),Vanilla mBERT minmax:(0.7665, 292),Avg Readability Formula: (0.7698, 292),Vanilla Readability Formula: (0.7379, 292),Average Readability Formula minmax:(0.7642, 292), Vanilla Readability Formula minmax:(0.7492, 292)




conf_noscale_phi
unweighted:
 AVG:(0.7751, 300),Vanilla:(0.7277, 300),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8122, 300),Vanilla mBERT:(0.795, 300), AVG Readability Formula: (0.8021, 300), Vanilla Readability Formula: (0.7839, 300)
entropy weightings:
 AVG mBERT:(0.7865, 300),Vanilla mBERT:(0.7433, 300),Avg mBERT minmax:(0.7864, 300),Vanilla mBERT minmax:(0.768, 300),Avg Readability Formula: (0.7846, 300),Vanilla Readability Formula: (0.7413, 300),Average Readability Formula minmax:(0.772, 300), Vanilla Readability Formula minmax:(0.752, 300)
verbal conf weightings:
 AVG mBERT:(0.8063, 300),Vanilla mBERT:(0.7707, 300),Avg mBERT minmax:(0.7981, 300),Vanilla mBERT minmax:(0.7783, 300),Avg Readability Formula: (0.8007, 300),Vanilla Readability Formula:(0.7647, 300),Average Readability Formula minmax:(0.7808, 300),Vanilla Readability Formula minmax: (0.7599, 300)



conf_phi
unweighted:
 AVG:(0.8307, 299),Vanilla:(0.8076, 299),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.842, 299),Vanilla mBERT:(0.8354, 299), AVG Readability Formula: (0.8306, 299), Vanilla Readability Formula: (0.8225, 299)
entropy weightings:
 AVG mBERT:(0.8356, 299),Vanilla mBERT:(0.8142, 299),Avg mBERT minmax:(0.8467, 299),Vanilla mBERT minmax:(0.8333, 299),Avg Readability Formula: (0.8344, 299),Vanilla Readability Formula: (0.8128, 299),Average Readability Formula minmax:(0.8399, 299), Vanilla Readability Formula minmax:(0.8251, 299)
verbal conf weightings:
 AVG mBERT:(0.8512, 299),Vanilla mBERT:(0.8344, 299),Avg mBERT minmax:(0.813, 299),Vanilla mBERT minmax:(0.8071, 299),Avg Readability Formula: (0.845, 299),Vanilla Readability Formula:(0.8275, 299),Average Readability Formula minmax:(0.7923, 299),Vanilla Readability Formula minmax: (0.7852, 299)



mixtral
unweighted:
 AVG:(0.7696, 300),Vanilla:(0.746, 300),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8104, 300),Vanilla mBERT:(0.8019, 300), AVG Readability Formula: (0.8071, 300), Vanilla Readability Formula: (0.7976, 300)
entropy weightings:
 AVG mBERT:(0.7721, 300),Vanilla mBERT:(0.7503, 300),Avg mBERT minmax:(0.7818, 300),Vanilla mBERT minmax:(0.778, 300),Avg Readability Formula: (0.7717, 300),Vanilla Readability Formula: (0.7498, 300),Average Readability Formula minmax:(0.7802, 300), Vanilla Readability Formula minmax:(0.776, 300)




noscale_mixtral
unweighted:
 AVG:(0.6565, 289),Vanilla:(0.6399, 289),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.7718, 289),Vanilla mBERT:(0.7643, 289), AVG Readability Formula: (0.7638, 289), Vanilla Readability Formula: (0.7581, 289)
entropy weightings:
 AVG mBERT:(0.6649, 289),Vanilla mBERT:(0.6503, 289),Avg mBERT minmax:(0.6969, 289),Vanilla mBERT minmax:(0.6942, 289),Avg Readability Formula: (0.6647, 289),Vanilla Readability Formula: (0.6506, 289),Average Readability Formula minmax:(0.6955, 289), Vanilla Readability Formula minmax:(0.6934, 289)




conf_noscale_mixtral
unweighted:
 AVG:(0.6598, 299),Vanilla:(0.6245, 299),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.7691, 299),Vanilla mBERT:(0.7575, 299), AVG Readability Formula: (0.7624, 299), Vanilla Readability Formula: (0.7505, 299)
entropy weightings:
 AVG mBERT:(0.6629, 299),Vanilla mBERT:(0.6304, 299),Avg mBERT minmax:(0.6868, 299),Vanilla mBERT minmax:(0.6829, 299),Avg Readability Formula: (0.6626, 299),Vanilla Readability Formula: (0.6301, 299),Average Readability Formula minmax:(0.679, 299), Vanilla Readability Formula minmax:(0.6747, 299)
verbal conf weightings:
 AVG mBERT:(0.7152, 299),Vanilla mBERT:(0.6887, 299),Avg mBERT minmax:(0.73, 299),Vanilla mBERT minmax:(0.7265, 299),Avg Readability Formula: (0.713, 299),Vanilla Readability Formula:(0.6864, 299),Average Readability Formula minmax:(0.7205, 299),Vanilla Readability Formula minmax: (0.7171, 299)



conf_mixtral
unweighted:
 AVG:(0.7794, 300),Vanilla:(0.7609, 300),RSRS:(0.7125, 300),Readability Formula: (0.7018, 300)
naive weightings:
 AVG mBERT:(0.8191, 300),Vanilla mBERT:(0.8147, 300), AVG Readability Formula: (0.8154, 300), Vanilla Readability Formula: (0.8121, 300)
entropy weightings:
 AVG mBERT:(0.7862, 300),Vanilla mBERT:(0.7706, 300),Avg mBERT minmax:(0.8081, 300),Vanilla mBERT minmax:(0.8066, 300),Avg Readability Formula: (0.7865, 300),Vanilla Readability Formula: (0.771, 300),Average Readability Formula minmax:(0.8096, 300), Vanilla Readability Formula minmax:(0.8098, 300)
verbal conf weightings:
 AVG mBERT:(0.8089, 300),Vanilla mBERT:(0.7964, 300),Avg mBERT minmax:(0.8128, 300),Vanilla mBERT minmax:(0.8071, 300),Avg Readability Formula: (0.8077, 300),Vanilla Readability Formula:(0.7957, 300),Average Readability Formula minmax:(0.8067, 300),Vanilla Readability Formula minmax: (0.8014, 300)

## OneStop

In [36]:
onestopv2=pd.read_csv('.../onestopv2.csv')
onestopv2 = onestopv2.replace("na", np.nan)
onestopv2.columns

Index(['Unnamed: 0', 'ID', 'Text', 'Label', 'gemma_27b_vanilla',
       'gemma_27b_avg', 'gemma_27b_entropy', 'gemma_9b_vanilla',
       'gemma_9b_avg', 'gemma_9b_entropy', 'gemma_2b_vanilla', 'gemma_2b_avg',
       'gemma_2b_entropy', 'phi_vanilla', 'phi_avg', 'phi_entropy',
       'mixtral_vanilla', 'mixtral_avg', 'mixtral_entropy',
       'conf_mixtral_vanilla', 'conf_mixtral_avg', 'conf_mixtral_entropy',
       'conf_mixtral_verbal_conf', 'conf_aya_32b_vanilla', 'conf_aya_32b_avg',
       'conf_aya_32b_entropy', 'conf_aya_32b_verbal_conf',
       'conf_llama_8b_vanilla', 'conf_llama_8b_avg', 'conf_llama_8b_entropy',
       'conf_llama_8b_verbal_conf', 'conf_llama_70b_vanilla',
       'conf_llama_70b_avg', 'conf_llama_70b_entropy',
       'conf_llama_70b_verbal_conf', 'conf_llama_3b_vanilla',
       'conf_llama_3b_avg', 'conf_llama_3b_entropy',
       'conf_llama_3b_verbal_conf', 'conf_gemma_2b_vanilla',
       'conf_gemma_2b_avg', 'conf_gemma_2b_entropy',
       'conf_gemma_2b_verbal_conf', 'conf_gemma_9b_vanilla',
       'conf_gemma_9b_avg', 'conf_gemma_9b_entropy',
       'conf_gemma_9b_verbal_conf', 'conf_gemma_27b_vanilla',
       'conf_gemma_27b_avg', 'conf_gemma_27b_entropy',
       'conf_gemma_27b_verbal_conf', 'conf_phi_vanilla', 'conf_phi_avg',
       'conf_phi_entropy', 'conf_phi_verbal_conf', 'llama_70b_vanilla',
       'llama_70b_avg', 'llama_70b_entropy', 'llama_8b_vanilla',
       'llama_8b_avg', 'llama_8b_entropy', 'llama_3b_vanilla', 'llama_3b_avg',
       'llama_3b_entropy', 'aya_32b_vanilla', 'aya_32b_avg', 'aya_32b_entropy',
       'aya_8b_vanilla', 'aya_8b_avg', 'aya_8b_entropy', 'FKGL', 'ARI',
       'RSRS_mBERT'],
      dtype='object')

In [37]:
ref_col = onestopv2.columns[3]
for i in range(4, len(onestopv2.columns)):  # 39 = 40th col in 0-based index
    col = onestopv2.columns[i]
    corr = onestopv2[ref_col].astype(float).corr(onestopv2[col].astype(float))
    if ('entropy' not in col) and ('verbal_conf' not in col):
        print(f"{i+1}: {col} -> correlation with {ref_col}: {corr:.4f}")

5: gemma_27b_vanilla -> correlation with Label: 0.3527
6: gemma_27b_avg -> correlation with Label: 0.3964
8: gemma_9b_vanilla -> correlation with Label: 0.4732
9: gemma_9b_avg -> correlation with Label: 0.4879
11: gemma_2b_vanilla -> correlation with Label: -0.0504
12: gemma_2b_avg -> correlation with Label: -0.0231
14: phi_vanilla -> correlation with Label: 0.4575
15: phi_avg -> correlation with Label: 0.4919
17: mixtral_vanilla -> correlation with Label: 0.2666
18: mixtral_avg -> correlation with Label: 0.3161
20: conf_mixtral_vanilla -> correlation with Label: 0.2078
21: conf_mixtral_avg -> correlation with Label: 0.2226
24: conf_aya_32b_vanilla -> correlation with Label: 0.2890
25: conf_aya_32b_avg -> correlation with Label: 0.3409
28: conf_llama_8b_vanilla -> correlation with Label: 0.1412
29: conf_llama_8b_avg -> correlation with Label: 0.3395
32: conf_llama_70b_vanilla -> correlation with Label: 0.4885
33: conf_llama_70b_avg -> correlation with Label: 0.6096
36: conf_llama_3b_vanilla -> correlation with Label: 0.3583
37: conf_llama_3b_avg -> correlation with Label: 0.4265
40: conf_gemma_2b_vanilla -> correlation with Label: -0.0093
41: conf_gemma_2b_avg -> correlation with Label: -0.0395
44: conf_gemma_9b_vanilla -> correlation with Label: 0.3942
45: conf_gemma_9b_avg -> correlation with Label: 0.4321
48: conf_gemma_27b_vanilla -> correlation with Label: 0.3274
49: conf_gemma_27b_avg -> correlation with Label: 0.3590
52: conf_phi_vanilla -> correlation with Label: 0.4647
53: conf_phi_avg -> correlation with Label: 0.4969
56: llama_70b_vanilla -> correlation with Label: 0.6330
57: llama_70b_avg -> correlation with Label: 0.6948
59: llama_8b_vanilla -> correlation with Label: 0.2795
60: llama_8b_avg -> correlation with Label: 0.4304
62: llama_3b_vanilla -> correlation with Label: 0.1680
63: llama_3b_avg -> correlation with Label: 0.2098
65: aya_32b_vanilla -> correlation with Label: 0.2207
66: aya_32b_avg -> correlation with Label: 0.3082
68: aya_8b_vanilla -> correlation with Label: 0.3186
69: aya_8b_avg -> correlation with Label: 0.3442
71: FKGL -> correlation with Label: 0.5709
72: ARI -> correlation with Label: 0.5774
73: RSRS_mBERT -> correlation with Label: 0.6271

In [38]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
onestopv2 = onestopv2.apply(pd.to_numeric, errors="coerce")
rf_string='ARI'
std_cols = [c for c in onestopv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
onestopv2[std_cols] = StandardScaler().fit_transform(onestopv2[std_cols])
model='conf_llama_70b'
vconf_col=f'{model}_verbal_conf'
avg_col = f"{model}_avg"


verbal_avg_rf=((1 - onestopv2[vconf_col]/10) * onestopv2[rf_string]) + (onestopv2[vconf_col]/10 * onestopv2[avg_col])


rjk,n1=safe_corr_raw(verbal_avg_rf, onestopv2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(onestopv2.iloc[:,31], onestopv2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,onestopv2.iloc[:,31])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs LLM : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, onestopv2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(onestopv2[rf_string], onestopv2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,onestopv2[rf_string])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RF : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, onestopv2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(onestopv2['RSRS_mBERT'], onestopv2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,onestopv2['RSRS_mBERT'])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RSRS : t2:{res1[0]}, p:{res1[1]}')

0.6540887114649118 0.48849249999632977 0.8507946979806412
567
t_test: Vconf RF vs LLM : t2:9.642905946748584, p:0.0
0.6540887114649118 0.5773693435367023 0.6887067250926977
567
t_test: Vconf RF vs RF : t2:3.10689922107943, p:0.001985729599160324
0.6540887114649118 0.6271070873255006 0.5636023767615519
567
t_test: Vconf RF vs RSRS : t2:0.9707937000269291, p:0.3320671595849187

In [39]:
onestopv2 = onestopv2.apply(pd.to_numeric, errors="coerce")
import numpy as np
rjk,n1=safe_corr_raw(onestopv2.iloc[:,32], onestopv2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(onestopv2.iloc[:,31], onestopv2.iloc[:,3])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(onestopv2.iloc[:,32],onestopv2.iloc[:,31])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Expected Value v. Vanilla : t2:{res1[0]}, p:{res1[1]}')

0.609610229473322 0.48849249999632977 0.8810475119108532
567
t_test: Expected Value v. Vanilla : t2:7.4958084777931, p:2.566835632933362e-13

In [40]:
### from sklearn.preprocessing import MinMaxScaler, StandardScaler
onestopv2 = onestopv2.apply(pd.to_numeric, errors="coerce")
rf_string='ARI'
ref_col = onestopv2.columns[3]
#onestopv2['RSRS_mBERT']= StandardScaler().fit_transform(onestopv2['RSRS_mBERT'])
# Step 1: Normalize entropy columns
entropy_cols = [c for c in onestopv2.columns if c.endswith("_entropy")]
entropy_cols_minmax = [c + "_minmax" for c in entropy_cols]
onestopv2[entropy_cols_minmax] = MinMaxScaler().fit_transform(onestopv2[entropy_cols])

vconf_cols = [c for c in onestopv2.columns if c.endswith("verbal_conf")]
vconf_cols_minmax = [c + "_minmax" for c in vconf_cols]
onestopv2[vconf_cols_minmax] = MinMaxScaler().fit_transform(onestopv2[vconf_cols])
onestopv2[vconf_cols] = onestopv2[vconf_cols]/10

std_cols = [c for c in onestopv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
onestopv2[std_cols] = StandardScaler().fit_transform(onestopv2[std_cols])
suffixes = ["_avg", "_vanilla", "_entropy"]
models = set(
    c.rsplit("_", 1)[0]  # remove the last part after the final underscore
    for c in entropy_cols  # or any column list containing these suffixes
)
sorted_models = sorted(models, key=lambda x: x[::-1].lower())
for model in sorted_models:
    print(model)
    vanilla_col = f"{model}_vanilla"
    avg_col = f"{model}_avg"
    print(f'unweighted:\n AVG:{safe_corr(onestopv2[avg_col], onestopv2[ref_col])},Vanilla:{safe_corr(onestopv2[vanilla_col], onestopv2[ref_col])},RSRS:{safe_corr(onestopv2["RSRS_mBERT"], onestopv2[ref_col])},Readability Formula: {safe_corr(onestopv2[rf_string], onestopv2[ref_col])}')
    naive_avg_mBERT=onestopv2[avg_col]+onestopv2["RSRS_mBERT"]
    naive_vanilla_mBERT=onestopv2[vanilla_col]+onestopv2["RSRS_mBERT"]
    
    naive_avg_rf=onestopv2[avg_col]+onestopv2[rf_string]
    naive_vanilla_rf=onestopv2[vanilla_col]+onestopv2[rf_string]
    print(f'naive weightings: \n AVG mBERT:{safe_corr(naive_avg_mBERT, onestopv2[ref_col])},Vanilla mBERT:{safe_corr(naive_vanilla_mBERT, onestopv2[ref_col])}, AVG Readability Formula: {safe_corr(naive_avg_rf, onestopv2[ref_col])}, Vanilla Readability Formula: {safe_corr(naive_vanilla_rf, onestopv2[ref_col])}')
    entropy_col = f"{model}_entropy"
    entropy_col_minmax = f"{model}_entropy_minmax"
    if model.startswith('conf_'):
        vconf_col=f'{model}_verbal_conf'
        vconf_col_minmax = f"{model}_verbal_conf_minmax"
    
    #onestopv2[f"{model}_weighted"] = (
    #    onestopv2[entropy_col] * onestopv2["RSRS_mBERT"] + 
    #    (1 - onestopv2[entropy_col]) * (onestopv2[[vanilla_col, avg_col]].mean(axis=1))
    #)
    entropy_avg_mBERT=(onestopv2[entropy_col] * onestopv2["RSRS_mBERT"]) + ((1 - onestopv2[entropy_col]) * onestopv2[avg_col])
    entropy_vanilla_mBERT=(onestopv2[entropy_col] * onestopv2["RSRS_mBERT"]) + ((1 - onestopv2[entropy_col]) * onestopv2[vanilla_col])
    entropy_minmax_avg_mBERT=(onestopv2[entropy_col_minmax] * onestopv2["RSRS_mBERT"]) + ((1 - onestopv2[entropy_col_minmax]) * onestopv2[avg_col])
    entropy_minmax_vanilla_mBERT=(onestopv2[entropy_col_minmax] * onestopv2["RSRS_mBERT"]) + ((1 - onestopv2[entropy_col_minmax]) * onestopv2[vanilla_col])
    
    entropy_avg_rf=(onestopv2[entropy_col] * onestopv2[rf_string]) + ((1 - onestopv2[entropy_col]) * onestopv2[avg_col])
    entropy_vanilla_rf=(onestopv2[entropy_col] * onestopv2[rf_string]) + ((1 - onestopv2[entropy_col]) * onestopv2[vanilla_col])
    entropy_minmax_avg_rf=(onestopv2[entropy_col_minmax] * onestopv2[rf_string]) + ((1 - onestopv2[entropy_col_minmax]) * onestopv2[avg_col])
    entropy_minmax_vanilla_rf=(onestopv2[entropy_col_minmax] * onestopv2[rf_string]) + ((1 - onestopv2[entropy_col_minmax]) * onestopv2[vanilla_col])
    print(f'entropy weightings:\n AVG mBERT:{safe_corr(entropy_avg_mBERT, onestopv2[ref_col])},Vanilla mBERT:{safe_corr(entropy_vanilla_mBERT, onestopv2[ref_col])},Avg mBERT minmax:{safe_corr(entropy_minmax_avg_mBERT, onestopv2[ref_col])},Vanilla mBERT minmax:{safe_corr(entropy_minmax_vanilla_mBERT, onestopv2[ref_col])},Avg Readability Formula: {safe_corr(entropy_avg_rf, onestopv2[ref_col])},Vanilla Readability Formula: {safe_corr(entropy_vanilla_rf, onestopv2[ref_col])},Average Readability Formula minmax:{safe_corr(entropy_minmax_avg_rf, onestopv2[ref_col])}, Vanilla Readability Formula minmax:{safe_corr(entropy_minmax_vanilla_rf, onestopv2[ref_col])}')
    if model.startswith('conf_'):
        verbal_avg_mBERT=((1 - onestopv2[vconf_col]) * onestopv2["RSRS_mBERT"]) + (onestopv2[vconf_col] * onestopv2[avg_col])
        verbal_vanilla_mBERT=((1 - onestopv2[vconf_col]) * onestopv2["RSRS_mBERT"]) + (onestopv2[vconf_col] * onestopv2[vanilla_col])
        verbal_minmax_avg_mBERT=((1 - onestopv2[vconf_col_minmax]) * onestopv2["RSRS_mBERT"]) + (onestopv2[vconf_col_minmax] * onestopv2[avg_col])
        verbal_minmax_vanilla_mBERT=((1 - onestopv2[vconf_col_minmax]) * onestopv2["RSRS_mBERT"]) + (onestopv2[vconf_col_minmax] * onestopv2[vanilla_col])
        
        verbal_avg_rf=((1 - onestopv2[vconf_col]) * onestopv2[rf_string]) + (onestopv2[vconf_col] * onestopv2[avg_col])
        verbal_vanilla_rf=((1 - onestopv2[vconf_col]) * onestopv2[rf_string]) + (onestopv2[vconf_col] * onestopv2[vanilla_col])
        verbal_minmax_avg_rf=((1 - onestopv2[vconf_col_minmax]) * onestopv2[rf_string]) + (onestopv2[vconf_col_minmax] * onestopv2[avg_col])
        verbal_minmax_vanilla_rf=((1 - onestopv2[vconf_col_minmax]) * onestopv2[rf_string]) + (onestopv2[vconf_col_minmax] * onestopv2[vanilla_col])
        print(f'verbal conf weightings:\n AVG mBERT:{safe_corr(verbal_avg_mBERT, onestopv2[ref_col])},Vanilla mBERT:{safe_corr(verbal_vanilla_mBERT, onestopv2[ref_col])},Avg mBERT minmax:{safe_corr(verbal_minmax_avg_mBERT, onestopv2[ref_col])},Vanilla mBERT minmax:{safe_corr(verbal_minmax_vanilla_mBERT, onestopv2[ref_col])},Avg Readability Formula: {safe_corr(verbal_avg_rf, onestopv2[ref_col])},Vanilla Readability Formula:{safe_corr(verbal_vanilla_rf, onestopv2[ref_col])},Average Readability Formula minmax:{safe_corr(verbal_minmax_avg_rf, onestopv2[ref_col])},Vanilla Readability Formula minmax: {safe_corr(verbal_minmax_vanilla_rf, onestopv2[ref_col])}','\n \n \n')
    else:
        print('\n \n \n')

llama_70b
unweighted:
 AVG:(0.6948, 567),Vanilla:(0.633, 567),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.7666, 567),Vanilla mBERT:(0.7455, 567), AVG Readability Formula: (0.7126, 567), Vanilla Readability Formula: (0.6927, 567)
entropy weightings:
 AVG mBERT:(0.7123, 567),Vanilla mBERT:(0.6568, 567),Avg mBERT minmax:(0.7652, 567),Vanilla mBERT minmax:(0.7566, 567),Avg Readability Formula: (0.7054, 567),Vanilla Readability Formula: (0.6504, 567),Average Readability Formula minmax:(0.7131, 567), Vanilla Readability Formula minmax:(0.703, 567)




conf_llama_70b
unweighted:
 AVG:(0.6096, 567),Vanilla:(0.4885, 567),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.7308, 567),Vanilla mBERT:(0.6854, 567), AVG Readability Formula: (0.6764, 567), Vanilla Readability Formula: (0.6347, 567)
entropy weightings:
 AVG mBERT:(0.6282, 567),Vanilla mBERT:(0.5142, 567),Avg mBERT minmax:(0.709, 567),Vanilla mBERT minmax:(0.6783, 567),Avg Readability Formula: (0.6229, 567),Vanilla Readability Formula: (0.5103, 567),Average Readability Formula minmax:(0.6625, 567), Vanilla Readability Formula minmax:(0.6326, 567)
verbal conf weightings:
 AVG mBERT:(0.6796, 567),Vanilla mBERT:(0.5862, 567),Avg mBERT minmax:(0.6565, 567),Vanilla mBERT minmax:(0.5745, 567),Avg Readability Formula: (0.6541, 567),Vanilla Readability Formula:(0.5644, 567),Average Readability Formula minmax:(0.632, 567),Vanilla Readability Formula minmax: (0.5522, 567)



aya_32b
unweighted:
 AVG:(0.3082, 563),Vanilla:(0.2207, 563),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.5962, 563),Vanilla mBERT:(0.5529, 563), AVG Readability Formula: (0.551, 563), Vanilla Readability Formula: (0.5081, 563)
entropy weightings:
 AVG mBERT:(0.3226, 563),Vanilla mBERT:(0.2386, 563),Avg mBERT minmax:(0.5212, 563),Vanilla mBERT minmax:(0.5119, 563),Avg Readability Formula: (0.3207, 563),Vanilla Readability Formula: (0.2367, 563),Average Readability Formula minmax:(0.4839, 563), Vanilla Readability Formula minmax:(0.4743, 563)




conf_aya_32b
unweighted:
 AVG:(0.3409, 564),Vanilla:(0.289, 564),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.5966, 564),Vanilla mBERT:(0.5803, 564), AVG Readability Formula: (0.5513, 564), Vanilla Readability Formula: (0.5364, 564)
entropy weightings:
 AVG mBERT:(0.3584, 564),Vanilla mBERT:(0.3085, 564),Avg mBERT minmax:(0.5461, 564),Vanilla mBERT minmax:(0.5397, 564),Avg Readability Formula: (0.3554, 564),Vanilla Readability Formula: (0.3058, 564),Average Readability Formula minmax:(0.5026, 564), Vanilla Readability Formula minmax:(0.4943, 564)
verbal conf weightings:
 AVG mBERT:(0.4884, 559),Vanilla mBERT:(0.4556, 559),Avg mBERT minmax:(0.5903, 559),Vanilla mBERT minmax:(0.5824, 559),Avg Readability Formula: (0.4634, 559),Vanilla Readability Formula:(0.4321, 559),Average Readability Formula minmax:(0.5442, 559),Vanilla Readability Formula minmax: (0.537, 559)



gemma_2b
unweighted:
 AVG:(-0.0231, 566),Vanilla:(-0.0504, 566),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.4242, 566),Vanilla mBERT:(0.4022, 566), AVG Readability Formula: (0.3652, 566), Vanilla Readability Formula: (0.3508, 566)
entropy weightings:
 AVG mBERT:(0.0265, 566),Vanilla mBERT:(-0.0009, 566),Avg mBERT minmax:(0.3751, 566),Vanilla mBERT minmax:(0.3638, 566),Avg Readability Formula: (0.0226, 566),Vanilla Readability Formula: (-0.0045, 566),Average Readability Formula minmax:(0.3259, 566), Vanilla Readability Formula minmax:(0.3189, 566)




conf_gemma_2b
unweighted:
 AVG:(-0.0395, 532),Vanilla:(-0.0093, 532),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.4217, 532),Vanilla mBERT:(0.4446, 532), AVG Readability Formula: (0.3679, 532), Vanilla Readability Formula: (0.4006, 532)
entropy weightings:
 AVG mBERT:(-0.0192, 532),Vanilla mBERT:(0.0126, 532),Avg mBERT minmax:(0.2648, 532),Vanilla mBERT minmax:(0.3507, 532),Avg Readability Formula: (-0.0208, 532),Vanilla Readability Formula: (0.0108, 532),Average Readability Formula minmax:(0.2255, 532), Vanilla Readability Formula minmax:(0.3138, 532)
verbal conf weightings:
 AVG mBERT:(0.2005, 532),Vanilla mBERT:(0.2303, 532),Avg mBERT minmax:(0.4098, 532),Vanilla mBERT minmax:(0.4367, 532),Avg Readability Formula: (0.1748, 532),Vanilla Readability Formula:(0.2076, 532),Average Readability Formula minmax:(0.36, 532),Vanilla Readability Formula minmax: (0.394, 532)



llama_3b
unweighted:
 AVG:(0.2098, 567),Vanilla:(0.168, 567),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.543, 567),Vanilla mBERT:(0.5174, 567), AVG Readability Formula: (0.5042, 567), Vanilla Readability Formula: (0.4772, 567)
entropy weightings:
 AVG mBERT:(0.2601, 567),Vanilla mBERT:(0.2205, 567),Avg mBERT minmax:(0.5771, 567),Vanilla mBERT minmax:(0.5692, 567),Avg Readability Formula: (0.2554, 567),Vanilla Readability Formula: (0.2156, 567),Average Readability Formula minmax:(0.5389, 567), Vanilla Readability Formula minmax:(0.5293, 567)




conf_llama_3b
unweighted:
 AVG:(0.4265, 517),Vanilla:(0.3583, 517),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.6421, 517),Vanilla mBERT:(0.6176, 517), AVG Readability Formula: (0.6062, 517), Vanilla Readability Formula: (0.5795, 517)
entropy weightings:
 AVG mBERT:(0.4608, 517),Vanilla mBERT:(0.3967, 517),Avg mBERT minmax:(0.6674, 517),Vanilla mBERT minmax:(0.6503, 517),Avg Readability Formula: (0.4572, 517),Vanilla Readability Formula: (0.3931, 517),Average Readability Formula minmax:(0.6343, 517), Vanilla Readability Formula minmax:(0.6155, 517)
verbal conf weightings:
 AVG mBERT:(0.4988, 448),Vanilla mBERT:(0.4449, 448),Avg mBERT minmax:(0.4841, 448),Vanilla mBERT minmax:(0.4287, 448),Avg Readability Formula: (0.485, 448),Vanilla Readability Formula:(0.4313, 448),Average Readability Formula minmax:(0.4671, 448),Vanilla Readability Formula minmax: (0.4133, 448)



gemma_27b
unweighted:
 AVG:(0.3964, 567),Vanilla:(0.3527, 567),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.6381, 567),Vanilla mBERT:(0.6184, 567), AVG Readability Formula: (0.5814, 567), Vanilla Readability Formula: (0.5692, 567)
entropy weightings:
 AVG mBERT:(0.4233, 567),Vanilla mBERT:(0.3812, 567),Avg mBERT minmax:(0.6004, 567),Vanilla mBERT minmax:(0.5847, 567),Avg Readability Formula: (0.4178, 567),Vanilla Readability Formula: (0.3767, 567),Average Readability Formula minmax:(0.545, 567), Vanilla Readability Formula minmax:(0.5337, 567)




conf_gemma_27b
unweighted:
 AVG:(0.359, 567),Vanilla:(0.3274, 567),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.6204, 567),Vanilla mBERT:(0.6076, 567), AVG Readability Formula: (0.5642, 567), Vanilla Readability Formula: (0.5543, 567)
entropy weightings:
 AVG mBERT:(0.3899, 567),Vanilla mBERT:(0.36, 567),Avg mBERT minmax:(0.6095, 567),Vanilla mBERT minmax:(0.6081, 567),Avg Readability Formula: (0.3843, 567),Vanilla Readability Formula: (0.355, 567),Average Readability Formula minmax:(0.5515, 567), Vanilla Readability Formula minmax:(0.5508, 567)
verbal conf weightings:
 AVG mBERT:(0.5299, 567),Vanilla mBERT:(0.5078, 567),Avg mBERT minmax:(0.603, 567),Vanilla mBERT minmax:(0.5904, 567),Avg Readability Formula: (0.4944, 567),Vanilla Readability Formula:(0.4749, 567),Average Readability Formula minmax:(0.5475, 567),Vanilla Readability Formula minmax: (0.5376, 567)



llama_8b
unweighted:
 AVG:(0.4304, 567),Vanilla:(0.2795, 567),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.6366, 567),Vanilla mBERT:(0.5807, 567), AVG Readability Formula: (0.586, 567), Vanilla Readability Formula: (0.5359, 567)
entropy weightings:
 AVG mBERT:(0.458, 567),Vanilla mBERT:(0.3129, 567),Avg mBERT minmax:(0.6022, 567),Vanilla mBERT minmax:(0.5404, 567),Avg Readability Formula: (0.4527, 567),Vanilla Readability Formula: (0.3094, 567),Average Readability Formula minmax:(0.5773, 567), Vanilla Readability Formula minmax:(0.5224, 567)




conf_llama_8b
unweighted:
 AVG:(0.3395, 566),Vanilla:(0.1412, 566),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.5982, 566),Vanilla mBERT:(0.5053, 566), AVG Readability Formula: (0.5602, 566), Vanilla Readability Formula: (0.4767, 566)
entropy weightings:
 AVG mBERT:(0.3542, 566),Vanilla mBERT:(0.1587, 566),Avg mBERT minmax:(0.5015, 566),Vanilla mBERT minmax:(0.3931, 566),Avg Readability Formula: (0.3523, 566),Vanilla Readability Formula: (0.1575, 566),Average Readability Formula minmax:(0.4758, 566), Vanilla Readability Formula minmax:(0.3789, 566)
verbal conf weightings:
 AVG mBERT:(0.4542, 566),Vanilla mBERT:(0.2848, 566),Avg mBERT minmax:(0.3878, 566),Vanilla mBERT minmax:(0.2054, 566),Avg Readability Formula: (0.4392, 566),Vanilla Readability Formula:(0.2738, 566),Average Readability Formula minmax:(0.3816, 566),Vanilla Readability Formula minmax: (0.2009, 566)



aya_8b
unweighted:
 AVG:(0.3442, 565),Vanilla:(0.3186, 565),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.6396, 565),Vanilla mBERT:(0.6287, 565), AVG Readability Formula: (0.5771, 565), Vanilla Readability Formula: (0.5675, 565)
entropy weightings:
 AVG mBERT:(0.3762, 565),Vanilla mBERT:(0.3532, 565),Avg mBERT minmax:(0.6206, 565),Vanilla mBERT minmax:(0.6302, 565),Avg Readability Formula: (0.3707, 565),Vanilla Readability Formula: (0.3478, 565),Average Readability Formula minmax:(0.5658, 565), Vanilla Readability Formula minmax:(0.5737, 565)




gemma_9b
unweighted:
 AVG:(0.4879, 567),Vanilla:(0.4732, 567),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.6786, 567),Vanilla mBERT:(0.6749, 567), AVG Readability Formula: (0.6234, 567), Vanilla Readability Formula: (0.62, 567)
entropy weightings:
 AVG mBERT:(0.5163, 567),Vanilla mBERT:(0.5033, 567),Avg mBERT minmax:(0.6816, 567),Vanilla mBERT minmax:(0.6846, 567),Avg Readability Formula: (0.5096, 567),Vanilla Readability Formula: (0.4966, 567),Average Readability Formula minmax:(0.6243, 567), Vanilla Readability Formula minmax:(0.6267, 567)




conf_gemma_9b
unweighted:
 AVG:(0.4321, 567),Vanilla:(0.3942, 567),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.6622, 567),Vanilla mBERT:(0.6442, 567), AVG Readability Formula: (0.6136, 567), Vanilla Readability Formula: (0.5974, 567)
entropy weightings:
 AVG mBERT:(0.4683, 567),Vanilla mBERT:(0.4331, 567),Avg mBERT minmax:(0.6695, 567),Vanilla mBERT minmax:(0.6686, 567),Avg Readability Formula: (0.462, 567),Vanilla Readability Formula: (0.427, 567),Average Readability Formula minmax:(0.6166, 567), Vanilla Readability Formula minmax:(0.6164, 567)
verbal conf weightings:
 AVG mBERT:(0.5386, 567),Vanilla mBERT:(0.507, 567),Avg mBERT minmax:(0.6205, 567),Vanilla mBERT minmax:(0.6036, 567),Avg Readability Formula: (0.5187, 567),Vanilla Readability Formula:(0.4883, 567),Average Readability Formula minmax:(0.5769, 567),Vanilla Readability Formula minmax: (0.5609, 567)



phi
unweighted:
 AVG:(0.4919, 567),Vanilla:(0.4575, 567),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.6652, 567),Vanilla mBERT:(0.6494, 567), AVG Readability Formula: (0.609, 567), Vanilla Readability Formula: (0.5944, 567)
entropy weightings:
 AVG mBERT:(0.5308, 567),Vanilla mBERT:(0.4998, 567),Avg mBERT minmax:(0.6402, 567),Vanilla mBERT minmax:(0.6304, 567),Avg Readability Formula: (0.519, 567),Vanilla Readability Formula: (0.4884, 567),Average Readability Formula minmax:(0.5803, 567), Vanilla Readability Formula minmax:(0.5707, 567)




conf_phi
unweighted:
 AVG:(0.4969, 567),Vanilla:(0.4647, 567),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.6754, 567),Vanilla mBERT:(0.661, 567), AVG Readability Formula: (0.6203, 567), Vanilla Readability Formula: (0.6071, 567)
entropy weightings:
 AVG mBERT:(0.5369, 567),Vanilla mBERT:(0.5072, 567),Avg mBERT minmax:(0.6555, 567),Vanilla mBERT minmax:(0.6427, 567),Avg Readability Formula: (0.526, 567),Vanilla Readability Formula: (0.4968, 567),Average Readability Formula minmax:(0.5972, 567), Vanilla Readability Formula minmax:(0.5843, 567)
verbal conf weightings:
 AVG mBERT:(0.5956, 567),Vanilla mBERT:(0.5705, 567),Avg mBERT minmax:(0.622, 567),Vanilla mBERT minmax:(0.6027, 567),Avg Readability Formula: (0.5674, 567),Vanilla Readability Formula:(0.5433, 567),Average Readability Formula minmax:(0.576, 567),Vanilla Readability Formula minmax: (0.5567, 567)



mixtral
unweighted:
 AVG:(0.3161, 565),Vanilla:(0.2666, 565),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.5967, 565),Vanilla mBERT:(0.5737, 565), AVG Readability Formula: (0.5438, 565), Vanilla Readability Formula: (0.5225, 565)
entropy weightings:
 AVG mBERT:(0.3393, 565),Vanilla mBERT:(0.2928, 565),Avg mBERT minmax:(0.5235, 565),Vanilla mBERT minmax:(0.5181, 565),Avg Readability Formula: (0.3359, 565),Vanilla Readability Formula: (0.2896, 565),Average Readability Formula minmax:(0.4801, 565), Vanilla Readability Formula minmax:(0.4724, 565)




conf_mixtral
unweighted:
 AVG:(0.2226, 567),Vanilla:(0.2078, 567),RSRS:(0.6271, 567),Readability Formula: (0.5774, 567)
naive weightings:
 AVG mBERT:(0.5362, 567),Vanilla mBERT:(0.5278, 567), AVG Readability Formula: (0.5019, 567), Vanilla Readability Formula: (0.4953, 567)
entropy weightings:
 AVG mBERT:(0.2479, 567),Vanilla mBERT:(0.2351, 567),Avg mBERT minmax:(0.4435, 567),Vanilla mBERT minmax:(0.4558, 567),Avg Readability Formula: (0.2468, 567),Vanilla Readability Formula: (0.2342, 567),Average Readability Formula minmax:(0.4275, 567), Vanilla Readability Formula minmax:(0.4388, 567)
verbal conf weightings:
 AVG mBERT:(0.3461, 567),Vanilla mBERT:(0.3332, 567),Avg mBERT minmax:(0.6134, 567),Vanilla mBERT minmax:(0.6144, 567),Avg Readability Formula: (0.3332, 567),Vanilla Readability Formula:(0.321, 567),Average Readability Formula minmax:(0.5647, 567),Vanilla Readability Formula minmax: (0.5659, 567)

## READ ME EN

In [41]:
readmeenv2=pd.read_csv('.../readme_en_resultsv2.csv')
readmeenv2 = readmeenv2.replace("na", np.nan)
readmeenv2.columns

Index(['Unnamed: 0', 'Domain', 'Sub-domain', 'Paragraph', 'Context',
       'Sentence', 'Rating', 'LLAMA_70B_vanilla', 'LLAMA_70B_avg',
       'LLAMA_70B_entropy',
       ...
       'noscale_gemma_2b_entropy', 'noscale_gemma_27b_vanilla',
       'noscale_gemma_27b_avg', 'noscale_gemma_27b_entropy',
       'noscale_llama_70b_vanilla', 'noscale_llama_70b_avg',
       'noscale_llama_70b_entropy', 'FKGL', 'ARI', 'RSRS_mBERT'],
      dtype='object', length=142)

In [42]:
ref_col = readmeenv2.columns[6]
for i in range(7, len(readmeenv2.columns)):  # 39 = 40th col in 0-based index
    col = readmeenv2.columns[i]
    corr = readmeenv2[ref_col].astype(float).corr(readmeenv2[col].astype(float))
    if ('entropy' not in col) and ('verbal_conf' not in col):
        print(f"{i+1}: {col} -> correlation with {ref_col}: {corr:.4f}")

8: LLAMA_70B_vanilla -> correlation with Rating: 0.7683
9: LLAMA_70B_avg -> correlation with Rating: 0.7783
11: LLAMA_3B_vanilla -> correlation with Rating: 0.6359
12: LLAMA_3B_avg -> correlation with Rating: 0.6771
14: LLAMA_8B_vanilla -> correlation with Rating: 0.6848
15: LLAMA_8B_avg -> correlation with Rating: 0.7106
17: Mixtral_vanilla -> correlation with Rating: 0.6713
18: Mixtral_avg -> correlation with Rating: 0.6826
20: Aya_8b_vanilla -> correlation with Rating: 0.6387
21: Aya_8b_avg -> correlation with Rating: 0.6571
23: Aya_32b_vanilla -> correlation with Rating: 0.7422
24: Aya_32b_avg -> correlation with Rating: 0.7486
26: Gemma_27b_vanilla -> correlation with Rating: 0.7480
27: Gemma_27b_avg -> correlation with Rating: 0.7856
29: Gemma_9b_vanilla -> correlation with Rating: 0.7370
30: Gemma_9b_avg -> correlation with Rating: 0.7728
32: Gemma_2b_vanilla -> correlation with Rating: 0.6006
33: Gemma_2b_avg -> correlation with Rating: 0.6710
35: phi_vanilla -> correlation with Rating: 0.6661
36: phi_avg -> correlation with Rating: 0.6879
38: noscale_mixtral_vanilla -> correlation with Rating: 0.5715
39: noscale_mixtral_avg -> correlation with Rating: 0.5818
41: noscale_phi_vanilla -> correlation with Rating: 0.6617
42: noscale_phi_avg -> correlation with Rating: 0.6861
44: conf_noscale_phi_vanilla -> correlation with Rating: 0.6506
45: conf_noscale_phi_avg -> correlation with Rating: 0.6670
48: conf_phi_vanilla -> correlation with Rating: 0.6891
49: conf_phi_avg -> correlation with Rating: 0.7145
52: conf_gemma_9b_vanilla -> correlation with Rating: 0.7372
53: conf_gemma_9b_avg -> correlation with Rating: 0.7683
56: conf_noscale_gemma_9b_vanilla -> correlation with Rating: 0.7015
57: conf_noscale_gemma_9b_avg -> correlation with Rating: 0.7258
60: conf_noscale_gemma_27b_vanilla -> correlation with Rating: 0.7354
61: conf_noscale_gemma_27b_avg -> correlation with Rating: 0.7507
64: conf_gemma_27b_vanilla -> correlation with Rating: 0.7464
65: conf_gemma_27b_avg -> correlation with Rating: 0.7778
68: conf_gemma_2b_vanilla -> correlation with Rating: 0.6387
69: conf_gemma_2b_avg -> correlation with Rating: 0.6866
72: conf_noscale_gemma_2b_vanilla -> correlation with Rating: 0.7064
73: conf_noscale_gemma_2b_avg -> correlation with Rating: 0.7322
76: conf_llama_3b_vanilla -> correlation with Rating: 0.6243
77: conf_llama_3b_avg -> correlation with Rating: 0.6721
80: conf_noscale_llama_3b_vanilla -> correlation with Rating: 0.4303
81: conf_noscale_llama_3b_avg -> correlation with Rating: 0.4977
84: conf_noscale_llama_70b_vanilla -> correlation with Rating: 0.7757
85: conf_noscale_llama_70b_avg -> correlation with Rating: 0.8050
88: conf_llama_70b_vanilla -> correlation with Rating: 0.7608
89: conf_llama_70b_avg -> correlation with Rating: 0.7791
92: conf_llama_8b_vanilla -> correlation with Rating: 0.6632
93: conf_llama_8b_avg -> correlation with Rating: 0.7060
96: conf_noscale_llama_8b_vanilla -> correlation with Rating: 0.6918
97: conf_noscale_llama_8b_avg -> correlation with Rating: 0.6989
100: conf_noscale_aya_32b_vanilla -> correlation with Rating: 0.6722
101: conf_noscale_aya_32b_avg -> correlation with Rating: 0.6985
104: conf_aya_32b_vanilla -> correlation with Rating: 0.7299
105: conf_aya_32b_avg -> correlation with Rating: 0.7549
108: conf_mixtral_vanilla -> correlation with Rating: 0.6649
109: conf_mixtral_avg -> correlation with Rating: 0.6813
112: conf_noscale_mixtral_vanilla -> correlation with Rating: 0.6295
113: conf_noscale_mixtral_avg -> correlation with Rating: 0.6336
116: noscale_aya_8b_vanilla -> correlation with Rating: 0.6444
117: noscale_aya_8b_avg -> correlation with Rating: 0.6696
119: noscale_aya_32b_vanilla -> correlation with Rating: 0.6747
120: noscale_aya_32b_avg -> correlation with Rating: 0.6857
122: noscale_llama_8b_vanilla -> correlation with Rating: 0.7001
123: noscale_llama_8b_avg -> correlation with Rating: 0.7113
125: noscale_llama_3b_vanilla -> correlation with Rating: 0.5036
126: noscale_llama_3b_avg -> correlation with Rating: 0.5424
128: noscale_gemma_9b_vanilla -> correlation with Rating: 0.7217
129: noscale_gemma_9b_avg -> correlation with Rating: 0.7444
131: noscale_gemma_2b_vanilla -> correlation with Rating: 0.6130
132: noscale_gemma_2b_avg -> correlation with Rating: 0.6707
134: noscale_gemma_27b_vanilla -> correlation with Rating: 0.7491
135: noscale_gemma_27b_avg -> correlation with Rating: 0.7655
137: noscale_llama_70b_vanilla -> correlation with Rating: 0.7908
138: noscale_llama_70b_avg -> correlation with Rating: 0.8050
140: FKGL -> correlation with Rating: 0.6713
141: ARI -> correlation with Rating: 0.6805
142: RSRS_mBERT -> correlation with Rating: 0.7592

In [43]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
readmeenv2 = readmeenv2.apply(pd.to_numeric, errors="coerce")
rf_string='ARI'
std_cols = [c for c in readmeenv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
readmeenv2[std_cols] = StandardScaler().fit_transform(readmeenv2[std_cols])
model='conf_llama_70b'
vconf_col=f'{model}_verbal_conf'
avg_col = f"{model}_avg"


verbal_avg_rf=((1 - readmeenv2[vconf_col]/10) * readmeenv2[rf_string]) + (readmeenv2[vconf_col]/10 * readmeenv2[avg_col])


rjk,n1=safe_corr_raw(verbal_avg_rf, readmeenv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmeenv2.iloc[:,83], readmeenv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,readmeenv2.iloc[:,83])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs LLM : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, readmeenv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmeenv2[rf_string], readmeenv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,readmeenv2[rf_string])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RF : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, readmeenv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmeenv2['RSRS_mBERT'], readmeenv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,readmeenv2['RSRS_mBERT'])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RSRS : t2:{res1[0]}, p:{res1[1]}')

0.7982059199948837 0.775747598085413 0.9200023830396029
296
t_test: Vconf RF vs LLM : t2:1.618202829567218, p:0.10669483752640874
0.7982059199948837 0.6804787356939188 0.7825894062525418
296
t_test: Vconf RF vs RF : t2:5.079068792334073, p:6.761301900581884e-07
0.7982059199948837 0.7591571098288734 0.7987911050019363
296
t_test: Vconf RF vs RSRS : t2:1.8374890524708671, p:0.06715024309583795

In [44]:
import numpy as np
readmeenv2 = readmeenv2.apply(pd.to_numeric, errors="coerce")
rjk,n1=safe_corr_raw(readmeenv2.iloc[:,84], readmeenv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmeenv2.iloc[:,88], readmeenv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(readmeenv2.iloc[:,84],readmeenv2.iloc[:,88])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Scale vs No scale : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(readmeenv2.iloc[:,83], readmeenv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmeenv2.iloc[:,88], readmeenv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(readmeenv2.iloc[:,83],readmeenv2.iloc[:,88])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Expected and Scale vs Vanillaand  No scale : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(readmeenv2.iloc[:,87], readmeenv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmeenv2.iloc[:,88], readmeenv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(readmeenv2.iloc[:,87],readmeenv2.iloc[:,88])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Expected Value v. Vanilla : t2:{res1[0]}, p:{res1[1]}')



#rjk=np.corrcoef(avg_col, values)[0, 1]
##Change next two lines to best RSRS/readability formula
#rjh=np.corrcoef(df.RSRS_mBERT, values)[0, 1]
#rkh=np.corrcoef(df.RSRS_mBERT, avg_col)[0, 1]
#print(rjk,rjh,rkh)
#res1=calc_williams_t(rjk,rjh,rkh,len(avg_col))
#print(f't_test: LLM vs non-LAURAE best : t2:{res1[0]}, p:{res1[1]}')

0.8050302104330989 0.7790800464752488 0.9281588452367233
296
t_test: Scale vs No scale : t2:1.9938738390100723, p:0.04709256081791202
0.775747598085413 0.7790800464752488 0.9121645235743251
296
t_test: Expected and Scale vs Vanillaand  No scale : t2:-0.22404026358812176, p:0.8228821141274938
0.7608078572897863 0.7790800464752488 0.9848474258674417
296
t_test: Expected Value v. Vanilla : t2:-2.870792182066393, p:0.004392848557181139

In [45]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
readmeenv2 = readmeenv2.apply(pd.to_numeric, errors="coerce")
rf_string='ARI'
ref_col = readmeenv2.columns[6]
#readmeenv2['RSRS_mBERT']= StandardScaler().fit_transform(readmeenv2['RSRS_mBERT'])
# Step 1: Normalize entropy columns
entropy_cols = [c for c in readmeenv2.columns if c.endswith("_entropy")]
entropy_cols_minmax = [c + "_minmax" for c in entropy_cols]
readmeenv2[entropy_cols_minmax] = MinMaxScaler().fit_transform(readmeenv2[entropy_cols])

vconf_cols = [c for c in readmeenv2.columns if c.endswith("verbal_conf")]
vconf_cols_minmax = [c + "_minmax" for c in vconf_cols]
readmeenv2[vconf_cols_minmax] = MinMaxScaler().fit_transform(readmeenv2[vconf_cols])
readmeenv2[vconf_cols] = readmeenv2[vconf_cols]/10

std_cols = [c for c in readmeenv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
readmeenv2[std_cols] = StandardScaler().fit_transform(readmeenv2[std_cols])
suffixes = ["_avg", "_vanilla", "_entropy"]
models = set(
    c.rsplit("_", 1)[0]  # remove the last part after the final underscore
    for c in entropy_cols  # or any column list containing these suffixes
)
sorted_models = sorted(models, key=lambda x: x[::-1].lower())
for model in sorted_models:
    print(model)
    vanilla_col = f"{model}_vanilla"
    avg_col = f"{model}_avg"
    print(f'unweighted:\n AVG:{safe_corr(readmeenv2[avg_col], readmeenv2[ref_col])},Vanilla:{safe_corr(readmeenv2[vanilla_col], readmeenv2[ref_col])},RSRS:{safe_corr(readmeenv2["RSRS_mBERT"], readmeenv2[ref_col])},Readability Formula: {safe_corr(readmeenv2[rf_string], readmeenv2[ref_col])}')
    naive_avg_mBERT=readmeenv2[avg_col]+readmeenv2["RSRS_mBERT"]
    naive_vanilla_mBERT=readmeenv2[vanilla_col]+readmeenv2["RSRS_mBERT"]
    
    naive_avg_rf=readmeenv2[avg_col]+readmeenv2[rf_string]
    naive_vanilla_rf=readmeenv2[vanilla_col]+readmeenv2[rf_string]
    print(f'naive weightings: \n AVG mBERT:{safe_corr(naive_avg_mBERT, readmeenv2[ref_col])},Vanilla mBERT:{safe_corr(naive_vanilla_mBERT, readmeenv2[ref_col])}, AVG Readability Formula: {safe_corr(naive_avg_rf, readmeenv2[ref_col])}, Vanilla Readability Formula: {safe_corr(naive_vanilla_rf, readmeenv2[ref_col])}')
    entropy_col = f"{model}_entropy"
    entropy_col_minmax = f"{model}_entropy_minmax"
    if model.startswith('conf_'):
        vconf_col=f'{model}_verbal_conf'
        vconf_col_minmax = f"{model}_verbal_conf_minmax"
    
    #readmeenv2[f"{model}_weighted"] = (
    #    readmeenv2[entropy_col] * readmeenv2["RSRS_mBERT"] + 
    #    (1 - readmeenv2[entropy_col]) * (readmeenv2[[vanilla_col, avg_col]].mean(axis=1))
    #)
    entropy_avg_mBERT=(readmeenv2[entropy_col] * readmeenv2["RSRS_mBERT"]) + ((1 - readmeenv2[entropy_col]) * readmeenv2[avg_col])
    entropy_vanilla_mBERT=(readmeenv2[entropy_col] * readmeenv2["RSRS_mBERT"]) + ((1 - readmeenv2[entropy_col]) * readmeenv2[vanilla_col])
    entropy_minmax_avg_mBERT=(readmeenv2[entropy_col_minmax] * readmeenv2["RSRS_mBERT"]) + ((1 - readmeenv2[entropy_col_minmax]) * readmeenv2[avg_col])
    entropy_minmax_vanilla_mBERT=(readmeenv2[entropy_col_minmax] * readmeenv2["RSRS_mBERT"]) + ((1 - readmeenv2[entropy_col_minmax]) * readmeenv2[vanilla_col])
    
    entropy_avg_rf=(readmeenv2[entropy_col] * readmeenv2[rf_string]) + ((1 - readmeenv2[entropy_col]) * readmeenv2[avg_col])
    entropy_vanilla_rf=(readmeenv2[entropy_col] * readmeenv2[rf_string]) + ((1 - readmeenv2[entropy_col]) * readmeenv2[vanilla_col])
    entropy_minmax_avg_rf=(readmeenv2[entropy_col_minmax] * readmeenv2[rf_string]) + ((1 - readmeenv2[entropy_col_minmax]) * readmeenv2[avg_col])
    entropy_minmax_vanilla_rf=(readmeenv2[entropy_col_minmax] * readmeenv2[rf_string]) + ((1 - readmeenv2[entropy_col_minmax]) * readmeenv2[vanilla_col])
    print(f'entropy weightings:\n AVG mBERT:{safe_corr(entropy_avg_mBERT, readmeenv2[ref_col])},Vanilla mBERT:{safe_corr(entropy_vanilla_mBERT, readmeenv2[ref_col])},Avg mBERT minmax:{safe_corr(entropy_minmax_avg_mBERT, readmeenv2[ref_col])},Vanilla mBERT minmax:{safe_corr(entropy_minmax_vanilla_mBERT, readmeenv2[ref_col])},Avg Readability Formula: {safe_corr(entropy_avg_rf, readmeenv2[ref_col])},Vanilla Readability Formula: {safe_corr(entropy_vanilla_rf, readmeenv2[ref_col])},Average Readability Formula minmax:{safe_corr(entropy_minmax_avg_rf, readmeenv2[ref_col])}, Vanilla Readability Formula minmax:{safe_corr(entropy_minmax_vanilla_rf, readmeenv2[ref_col])}')
    if model.startswith('conf_'):
        verbal_avg_mBERT=((1 - readmeenv2[vconf_col]) * readmeenv2["RSRS_mBERT"]) + (readmeenv2[vconf_col] * readmeenv2[avg_col])
        verbal_vanilla_mBERT=((1 - readmeenv2[vconf_col]) * readmeenv2["RSRS_mBERT"]) + (readmeenv2[vconf_col] * readmeenv2[vanilla_col])
        verbal_minmax_avg_mBERT=((1 - readmeenv2[vconf_col_minmax]) * readmeenv2["RSRS_mBERT"]) + (readmeenv2[vconf_col_minmax] * readmeenv2[avg_col])
        verbal_minmax_vanilla_mBERT=((1 - readmeenv2[vconf_col_minmax]) * readmeenv2["RSRS_mBERT"]) + (readmeenv2[vconf_col_minmax] * readmeenv2[vanilla_col])
        
        verbal_avg_rf=((1 - readmeenv2[vconf_col]) * readmeenv2[rf_string]) + (readmeenv2[vconf_col] * readmeenv2[avg_col])
        verbal_vanilla_rf=((1 - readmeenv2[vconf_col]) * readmeenv2[rf_string]) + (readmeenv2[vconf_col] * readmeenv2[vanilla_col])
        verbal_minmax_avg_rf=((1 - readmeenv2[vconf_col_minmax]) * readmeenv2[rf_string]) + (readmeenv2[vconf_col_minmax] * readmeenv2[avg_col])
        verbal_minmax_vanilla_rf=((1 - readmeenv2[vconf_col_minmax]) * readmeenv2[rf_string]) + (readmeenv2[vconf_col_minmax] * readmeenv2[vanilla_col])
        print(f'verbal conf weightings:\n AVG mBERT:{safe_corr(verbal_avg_mBERT, readmeenv2[ref_col])},Vanilla mBERT:{safe_corr(verbal_vanilla_mBERT, readmeenv2[ref_col])},Avg mBERT minmax:{safe_corr(verbal_minmax_avg_mBERT, readmeenv2[ref_col])},Vanilla mBERT minmax:{safe_corr(verbal_minmax_vanilla_mBERT, readmeenv2[ref_col])},Avg Readability Formula: {safe_corr(verbal_avg_rf, readmeenv2[ref_col])},Vanilla Readability Formula:{safe_corr(verbal_vanilla_rf, readmeenv2[ref_col])},Average Readability Formula minmax:{safe_corr(verbal_minmax_avg_rf, readmeenv2[ref_col])},Vanilla Readability Formula minmax: {safe_corr(verbal_minmax_vanilla_rf, readmeenv2[ref_col])}','\n \n \n')
    else:
        print('\n \n \n')

LLAMA_70B
unweighted:
 AVG:(0.7783, 296),Vanilla:(0.7683, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8269, 296),Vanilla mBERT:(0.8258, 296), AVG Readability Formula: (0.7938, 296), Vanilla Readability Formula: (0.7924, 296)
entropy weightings:
 AVG mBERT:(0.7871, 296),Vanilla mBERT:(0.7776, 296),Avg mBERT minmax:(0.8174, 296),Vanilla mBERT minmax:(0.8145, 296),Avg Readability Formula: (0.7856, 296),Vanilla Readability Formula: (0.7762, 296),Average Readability Formula minmax:(0.8069, 296), Vanilla Readability Formula minmax:(0.8031, 296)




noscale_llama_70b
unweighted:
 AVG:(0.805, 296),Vanilla:(0.7908, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8264, 296),Vanilla mBERT:(0.8242, 296), AVG Readability Formula: (0.7957, 296), Vanilla Readability Formula: (0.7925, 296)
entropy weightings:
 AVG mBERT:(0.8092, 296),Vanilla mBERT:(0.797, 296),Avg mBERT minmax:(0.8104, 296),Vanilla mBERT minmax:(0.8071, 296),Avg Readability Formula: (0.8078, 296),Vanilla Readability Formula: (0.7955, 296),Average Readability Formula minmax:(0.7954, 296), Vanilla Readability Formula minmax:(0.7912, 296)




conf_noscale_llama_70b
unweighted:
 AVG:(0.805, 296),Vanilla:(0.7757, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8276, 296),Vanilla mBERT:(0.8159, 296), AVG Readability Formula: (0.7999, 296), Vanilla Readability Formula: (0.7878, 296)
entropy weightings:
 AVG mBERT:(0.8112, 296),Vanilla mBERT:(0.7851, 296),Avg mBERT minmax:(0.8234, 296),Vanilla mBERT minmax:(0.814, 296),Avg Readability Formula: (0.8102, 296),Vanilla Readability Formula: (0.7842, 296),Average Readability Formula minmax:(0.8101, 296), Vanilla Readability Formula minmax:(0.8004, 296)
verbal conf weightings:
 AVG mBERT:(0.824, 296),Vanilla mBERT:(0.8025, 296),Avg mBERT minmax:(0.8088, 296),Vanilla mBERT minmax:(0.7987, 296),Avg Readability Formula: (0.8164, 296),Vanilla Readability Formula:(0.7948, 296),Average Readability Formula minmax:(0.7738, 296),Vanilla Readability Formula minmax: (0.7636, 296)



conf_llama_70b
unweighted:
 AVG:(0.7791, 296),Vanilla:(0.7608, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8252, 296),Vanilla mBERT:(0.8199, 296), AVG Readability Formula: (0.7934, 296), Vanilla Readability Formula: (0.7895, 296)
entropy weightings:
 AVG mBERT:(0.7875, 296),Vanilla mBERT:(0.7709, 296),Avg mBERT minmax:(0.8118, 296),Vanilla mBERT minmax:(0.8063, 296),Avg Readability Formula: (0.7861, 296),Vanilla Readability Formula: (0.77, 296),Average Readability Formula minmax:(0.8014, 296), Vanilla Readability Formula minmax:(0.7972, 296)
verbal conf weightings:
 AVG mBERT:(0.8063, 296),Vanilla mBERT:(0.793, 296),Avg mBERT minmax:(0.8112, 296),Vanilla mBERT minmax:(0.8039, 296),Avg Readability Formula: (0.7982, 296),Vanilla Readability Formula:(0.7857, 296),Average Readability Formula minmax:(0.7886, 296),Vanilla Readability Formula minmax: (0.7821, 296)



Aya_32b
unweighted:
 AVG:(0.7486, 296),Vanilla:(0.7422, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8146, 296),Vanilla mBERT:(0.8126, 296), AVG Readability Formula: (0.7747, 296), Vanilla Readability Formula: (0.7734, 296)
entropy weightings:
 AVG mBERT:(0.7504, 296),Vanilla mBERT:(0.7444, 296),Avg mBERT minmax:(0.7593, 296),Vanilla mBERT minmax:(0.7572, 296),Avg Readability Formula: (0.7499, 296),Vanilla Readability Formula: (0.744, 296),Average Readability Formula minmax:(0.7493, 296), Vanilla Readability Formula minmax:(0.7474, 296)




noscale_aya_32b
unweighted:
 AVG:(0.6857, 296),Vanilla:(0.6747, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8031, 296),Vanilla mBERT:(0.8007, 296), AVG Readability Formula: (0.7728, 296), Vanilla Readability Formula: (0.7708, 296)
entropy weightings:
 AVG mBERT:(0.6988, 296),Vanilla mBERT:(0.6891, 296),Avg mBERT minmax:(0.7687, 296),Vanilla mBERT minmax:(0.7689, 296),Avg Readability Formula: (0.6994, 296),Vanilla Readability Formula: (0.6899, 296),Average Readability Formula minmax:(0.7729, 296), Vanilla Readability Formula minmax:(0.7733, 296)




conf_noscale_aya_32b
unweighted:
 AVG:(0.6985, 296),Vanilla:(0.6722, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8072, 296),Vanilla mBERT:(0.7999, 296), AVG Readability Formula: (0.7762, 296), Vanilla Readability Formula: (0.7686, 296)
entropy weightings:
 AVG mBERT:(0.7137, 296),Vanilla mBERT:(0.6901, 296),Avg mBERT minmax:(0.7905, 296),Vanilla mBERT minmax:(0.787, 296),Avg Readability Formula: (0.7112, 296),Vanilla Readability Formula: (0.6875, 296),Average Readability Formula minmax:(0.7596, 296), Vanilla Readability Formula minmax:(0.7561, 296)
verbal conf weightings:
 AVG mBERT:(0.7683, 296),Vanilla mBERT:(0.752, 296),Avg mBERT minmax:(0.8041, 296),Vanilla mBERT minmax:(0.8016, 296),Avg Readability Formula: (0.755, 296),Vanilla Readability Formula:(0.7385, 296),Average Readability Formula minmax:(0.7545, 296),Vanilla Readability Formula minmax: (0.752, 296)



conf_aya_32b
unweighted:
 AVG:(0.7549, 296),Vanilla:(0.7299, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8189, 296),Vanilla mBERT:(0.8097, 296), AVG Readability Formula: (0.7787, 296), Vanilla Readability Formula: (0.7685, 296)
entropy weightings:
 AVG mBERT:(0.7578, 296),Vanilla mBERT:(0.7346, 296),Avg mBERT minmax:(0.7692, 296),Vanilla mBERT minmax:(0.7623, 296),Avg Readability Formula: (0.7568, 296),Vanilla Readability Formula: (0.7334, 296),Average Readability Formula minmax:(0.7574, 296), Vanilla Readability Formula minmax:(0.7501, 296)
verbal conf weightings:
 AVG mBERT:(0.7916, 295),Vanilla mBERT:(0.7729, 295),Avg mBERT minmax:(0.7911, 295),Vanilla mBERT minmax:(0.7809, 295),Avg Readability Formula: (0.7796, 295),Vanilla Readability Formula:(0.7604, 295),Average Readability Formula minmax:(0.7636, 295),Vanilla Readability Formula minmax: (0.7529, 295)



Gemma_2b
unweighted:
 AVG:(0.671, 296),Vanilla:(0.6006, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.7924, 296),Vanilla mBERT:(0.7626, 296), AVG Readability Formula: (0.7464, 296), Vanilla Readability Formula: (0.714, 296)
entropy weightings:
 AVG mBERT:(0.6796, 296),Vanilla mBERT:(0.6141, 296),Avg mBERT minmax:(0.7422, 296),Vanilla mBERT minmax:(0.7201, 296),Avg Readability Formula: (0.6785, 296),Vanilla Readability Formula: (0.6127, 296),Average Readability Formula minmax:(0.7237, 296), Vanilla Readability Formula minmax:(0.6991, 296)




noscale_gemma_2b
unweighted:
 AVG:(0.6707, 296),Vanilla:(0.613, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.783, 296),Vanilla mBERT:(0.7635, 296), AVG Readability Formula: (0.7518, 296), Vanilla Readability Formula: (0.7322, 296)
entropy weightings:
 AVG mBERT:(0.7016, 296),Vanilla mBERT:(0.653, 296),Avg mBERT minmax:(0.7993, 296),Vanilla mBERT minmax:(0.7922, 296),Avg Readability Formula: (0.6982, 296),Vanilla Readability Formula: (0.6498, 296),Average Readability Formula minmax:(0.7668, 296), Vanilla Readability Formula minmax:(0.7592, 296)




conf_noscale_gemma_2b
unweighted:
 AVG:(0.7322, 296),Vanilla:(0.7064, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8043, 296),Vanilla mBERT:(0.7975, 296), AVG Readability Formula: (0.7759, 296), Vanilla Readability Formula: (0.7693, 296)
entropy weightings:
 AVG mBERT:(0.7525, 296),Vanilla mBERT:(0.7314, 296),Avg mBERT minmax:(0.807, 296),Vanilla mBERT minmax:(0.8045, 296),Avg Readability Formula: (0.7499, 296),Vanilla Readability Formula: (0.729, 296),Average Readability Formula minmax:(0.7785, 296), Vanilla Readability Formula minmax:(0.7761, 296)
verbal conf weightings:
 AVG mBERT:(0.7845, 296),Vanilla mBERT:(0.7699, 296),Avg mBERT minmax:(0.8009, 296),Vanilla mBERT minmax:(0.7964, 296),Avg Readability Formula: (0.7733, 296),Vanilla Readability Formula:(0.7589, 296),Average Readability Formula minmax:(0.7679, 296),Vanilla Readability Formula minmax: (0.7633, 296)



conf_gemma_2b
unweighted:
 AVG:(0.6866, 295),Vanilla:(0.6387, 295),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.7987, 295),Vanilla mBERT:(0.7813, 295), AVG Readability Formula: (0.7528, 295), Vanilla Readability Formula: (0.7334, 295)
entropy weightings:
 AVG mBERT:(0.6944, 295),Vanilla mBERT:(0.6496, 295),Avg mBERT minmax:(0.7522, 295),Vanilla mBERT minmax:(0.7343, 295),Avg Readability Formula: (0.6934, 295),Vanilla Readability Formula: (0.6484, 295),Average Readability Formula minmax:(0.7368, 295), Vanilla Readability Formula minmax:(0.7172, 295)
verbal conf weightings:
 AVG mBERT:(0.7559, 295),Vanilla mBERT:(0.7214, 295),Avg mBERT minmax:(0.7188, 295),Vanilla mBERT minmax:(0.674, 295),Avg Readability Formula: (0.7336, 295),Vanilla Readability Formula:(0.698, 295),Average Readability Formula minmax:(0.7065, 295),Vanilla Readability Formula minmax: (0.661, 295)



LLAMA_3B
unweighted:
 AVG:(0.6771, 296),Vanilla:(0.6359, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.7999, 296),Vanilla mBERT:(0.7784, 296), AVG Readability Formula: (0.7569, 296), Vanilla Readability Formula: (0.7351, 296)
entropy weightings:
 AVG mBERT:(0.7057, 296),Vanilla mBERT:(0.667, 296),Avg mBERT minmax:(0.8062, 296),Vanilla mBERT minmax:(0.7921, 296),Avg Readability Formula: (0.6994, 296),Vanilla Readability Formula: (0.6607, 296),Average Readability Formula minmax:(0.7568, 296), Vanilla Readability Formula minmax:(0.7418, 296)




noscale_llama_3b
unweighted:
 AVG:(0.5424, 296),Vanilla:(0.5036, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.746, 296),Vanilla mBERT:(0.7343, 296), AVG Readability Formula: (0.7223, 296), Vanilla Readability Formula: (0.7106, 296)
entropy weightings:
 AVG mBERT:(0.5883, 296),Vanilla mBERT:(0.5566, 296),Avg mBERT minmax:(0.7529, 296),Vanilla mBERT minmax:(0.7549, 296),Avg Readability Formula: (0.5836, 296),Vanilla Readability Formula: (0.5519, 296),Average Readability Formula minmax:(0.7081, 296), Vanilla Readability Formula minmax:(0.7095, 296)




conf_noscale_llama_3b
unweighted:
 AVG:(0.4977, 296),Vanilla:(0.4303, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.731, 296),Vanilla mBERT:(0.7031, 296), AVG Readability Formula: (0.708, 296), Vanilla Readability Formula: (0.6794, 296)
entropy weightings:
 AVG mBERT:(0.5472, 296),Vanilla mBERT:(0.4885, 296),Avg mBERT minmax:(0.7431, 296),Vanilla mBERT minmax:(0.7349, 296),Avg Readability Formula: (0.5435, 296),Vanilla Readability Formula: (0.4844, 296),Average Readability Formula minmax:(0.71, 296), Vanilla Readability Formula minmax:(0.7018, 296)
verbal conf weightings:
 AVG mBERT:(0.6317, 296),Vanilla mBERT:(0.5787, 296),Avg mBERT minmax:(0.7419, 296),Vanilla mBERT minmax:(0.7071, 296),Avg Readability Formula: (0.625, 296),Vanilla Readability Formula:(0.5711, 296),Average Readability Formula minmax:(0.72, 296),Vanilla Readability Formula minmax: (0.6848, 296)



conf_llama_3b
unweighted:
 AVG:(0.6721, 296),Vanilla:(0.6243, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.7986, 296),Vanilla mBERT:(0.7752, 296), AVG Readability Formula: (0.766, 296), Vanilla Readability Formula: (0.7412, 296)
entropy weightings:
 AVG mBERT:(0.6978, 296),Vanilla mBERT:(0.6524, 296),Avg mBERT minmax:(0.786, 296),Vanilla mBERT minmax:(0.7555, 296),Avg Readability Formula: (0.6948, 296),Vanilla Readability Formula: (0.6493, 296),Average Readability Formula minmax:(0.7628, 296), Vanilla Readability Formula minmax:(0.7301, 296)

verbal conf weightings:
 AVG mBERT:(0.7365, 296),Vanilla mBERT:(0.698, 296),Avg mBERT minmax:(0.7915, 296),Vanilla mBERT minmax:(0.7792, 296),Avg Readability Formula: (0.7264, 296),Vanilla Readability Formula:(0.6872, 296),Average Readability Formula minmax:(0.7505, 296),Vanilla Readability Formula minmax: (0.7369, 296)



Gemma_27b
unweighted:
 AVG:(0.7856, 296),Vanilla:(0.748, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8299, 296),Vanilla mBERT:(0.8164, 296), AVG Readability Formula: (0.7965, 296), Vanilla Readability Formula: (0.7837, 296)
entropy weightings:
 AVG mBERT:(0.7924, 296),Vanilla mBERT:(0.7574, 296),Avg mBERT minmax:(0.8166, 296),Vanilla mBERT minmax:(0.7994, 296),Avg Readability Formula: (0.7918, 296),Vanilla Readability Formula: (0.7571, 296),Average Readability Formula minmax:(0.8057, 296), Vanilla Readability Formula minmax:(0.7895, 296)




noscale_gemma_27b
unweighted:
 AVG:(0.7655, 296),Vanilla:(0.7491, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.814, 296),Vanilla mBERT:(0.8085, 296), AVG Readability Formula: (0.7922, 296), Vanilla Readability Formula: (0.7864, 296)
entropy weightings:
 AVG mBERT:(0.7763, 296),Vanilla mBERT:(0.7626, 296),Avg mBERT minmax:(0.8142, 296),Vanilla mBERT minmax:(0.8139, 296),Avg Readability Formula: (0.7765, 296),Vanilla Readability Formula: (0.7628, 296),Average Readability Formula minmax:(0.8088, 296), Vanilla Readability Formula minmax:(0.8081, 296)




conf_noscale_gemma_27b
unweighted:
 AVG:(0.7507, 296),Vanilla:(0.7354, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8159, 296),Vanilla mBERT:(0.8112, 296), AVG Readability Formula: (0.7939, 296), Vanilla Readability Formula: (0.7874, 296)
entropy weightings:
 AVG mBERT:(0.7644, 296),Vanilla mBERT:(0.7511, 296),Avg mBERT minmax:(0.8183, 296),Vanilla mBERT minmax:(0.8165, 296),Avg Readability Formula: (0.7641, 296),Vanilla Readability Formula: (0.7505, 296),Average Readability Formula minmax:(0.8076, 296), Vanilla Readability Formula minmax:(0.8047, 296)
verbal conf weightings:
 AVG mBERT:(0.812, 296),Vanilla mBERT:(0.8043, 296),Avg mBERT minmax:(0.8193, 296),Vanilla mBERT minmax:(0.8133, 296),Avg Readability Formula: (0.8046, 296),Vanilla Readability Formula:(0.7956, 296),Average Readability Formula minmax:(0.8082, 296),Vanilla Readability Formula minmax: (0.8009, 296)



conf_gemma_27b
unweighted:
 AVG:(0.7778, 296),Vanilla:(0.7464, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8332, 296),Vanilla mBERT:(0.82, 296), AVG Readability Formula: (0.7973, 296), Vanilla Readability Formula: (0.7824, 296)
entropy weightings:
 AVG mBERT:(0.7855, 296),Vanilla mBERT:(0.756, 296),Avg mBERT minmax:(0.816, 296),Vanilla mBERT minmax:(0.8026, 296),Avg Readability Formula: (0.784, 296),Vanilla Readability Formula: (0.7542, 296),Average Readability Formula minmax:(0.7973, 296), Vanilla Readability Formula minmax:(0.7822, 296)
verbal conf weightings:
 AVG mBERT:(0.8246, 296),Vanilla mBERT:(0.8016, 296),Avg mBERT minmax:(0.833, 296),Vanilla mBERT minmax:(0.8164, 296),Avg Readability Formula: (0.8096, 296),Vanilla Readability Formula:(0.7853, 296),Average Readability Formula minmax:(0.8058, 296),Vanilla Readability Formula minmax: (0.7877, 296)



LLAMA_8B
unweighted:
 AVG:(0.7106, 296),Vanilla:(0.6848, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8035, 296),Vanilla mBERT:(0.7947, 296), AVG Readability Formula: (0.7644, 296), Vanilla Readability Formula: (0.7549, 296)
entropy weightings:
 AVG mBERT:(0.7193, 296),Vanilla mBERT:(0.696, 296),Avg mBERT minmax:(0.7619, 296),Vanilla mBERT minmax:(0.7546, 296),Avg Readability Formula: (0.7177, 296),Vanilla Readability Formula: (0.6943, 296),Average Readability Formula minmax:(0.7463, 296), Vanilla Readability Formula minmax:(0.7384, 296)




noscale_llama_8b
unweighted:
 AVG:(0.7113, 295),Vanilla:(0.7001, 295),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8021, 295),Vanilla mBERT:(0.7989, 295), AVG Readability Formula: (0.7812, 295), Vanilla Readability Formula: (0.7767, 295)
entropy weightings:
 AVG mBERT:(0.732, 295),Vanilla mBERT:(0.7226, 295),Avg mBERT minmax:(0.8033, 295),Vanilla mBERT minmax:(0.8021, 295),Avg Readability Formula: (0.731, 295),Vanilla Readability Formula: (0.7211, 295),Average Readability Formula minmax:(0.7811, 295), Vanilla Readability Formula minmax:(0.7796, 295)




conf_noscale_llama_8b
unweighted:
 AVG:(0.6989, 296),Vanilla:(0.6918, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.7977, 296),Vanilla mBERT:(0.7979, 296), AVG Readability Formula: (0.7783, 296), Vanilla Readability Formula: (0.7796, 296)
entropy weightings:
 AVG mBERT:(0.7179, 296),Vanilla mBERT:(0.7128, 296),Avg mBERT minmax:(0.793, 296),Vanilla mBERT minmax:(0.7963, 296),Avg Readability Formula: (0.7163, 296),Vanilla Readability Formula: (0.7118, 296),Average Readability Formula minmax:(0.7694, 296), Vanilla Readability Formula minmax:(0.7722, 296)
verbal conf weightings:
 AVG mBERT:(0.7602, 296),Vanilla mBERT:(0.7576, 296),Avg mBERT minmax:(0.8028, 296),Vanilla mBERT minmax:(0.805, 296),Avg Readability Formula: (0.7572, 296),Vanilla Readability Formula:(0.7553, 296),Average Readability Formula minmax:(0.7838, 296),Vanilla Readability Formula minmax: (0.7869, 296)



conf_llama_8b
unweighted:
 AVG:(0.706, 296),Vanilla:(0.6632, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8017, 296),Vanilla mBERT:(0.7874, 296), AVG Readability Formula: (0.7662, 296), Vanilla Readability Formula: (0.748, 296)
entropy weightings:
 AVG mBERT:(0.7187, 296),Vanilla mBERT:(0.68, 296),Avg mBERT minmax:(0.7828, 296),Vanilla mBERT minmax:(0.7704, 296),Avg Readability Formula: (0.7156, 296),Vanilla Readability Formula: (0.6762, 296),Average Readability Formula minmax:(0.7569, 296), Vanilla Readability Formula minmax:(0.7411, 296)
verbal conf weightings:
 AVG mBERT:(0.7597, 294),Vanilla mBERT:(0.729, 294),Avg mBERT minmax:(0.7868, 294),Vanilla mBERT minmax:(0.7813, 294),Avg Readability Formula: (0.7518, 294),Vanilla Readability Formula:(0.7194, 294),Average Readability Formula minmax:(0.7472, 294),Vanilla Readability Formula minmax: (0.7401, 294)



Aya_8b
unweighted:
 AVG:(0.6571, 296),Vanilla:(0.6387, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.7951, 296),Vanilla mBERT:(0.7911, 296), AVG Readability Formula: (0.7563, 296), Vanilla Readability Formula: (0.7503, 296)
entropy weightings:
 AVG mBERT:(0.6633, 296),Vanilla mBERT:(0.6462, 296),Avg mBERT minmax:(0.716, 296),Vanilla mBERT minmax:(0.7135, 296),Avg Readability Formula: (0.6631, 296),Vanilla Readability Formula: (0.6459, 296),Average Readability Formula minmax:(0.6999, 296), Vanilla Readability Formula minmax:(0.6964, 296)




noscale_aya_8b
unweighted:
 AVG:(0.6696, 294),Vanilla:(0.6444, 294),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.7962, 294),Vanilla mBERT:(0.7893, 294), AVG Readability Formula: (0.7605, 294), Vanilla Readability Formula: (0.7506, 294)
entropy weightings:
 AVG mBERT:(0.6887, 294),Vanilla mBERT:(0.6664, 294),Avg mBERT minmax:(0.7922, 294),Vanilla mBERT minmax:(0.7888, 294),Avg Readability Formula: (0.6859, 294),Vanilla Readability Formula: (0.6632, 294),Average Readability Formula minmax:(0.7522, 294), Vanilla Readability Formula minmax:(0.7458, 294)




Gemma_9b
unweighted:
 AVG:(0.7728, 296),Vanilla:(0.737, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8376, 296),Vanilla mBERT:(0.825, 296), AVG Readability Formula: (0.8003, 296), Vanilla Readability Formula: (0.7856, 296)
entropy weightings:
 AVG mBERT:(0.7813, 296),Vanilla mBERT:(0.7482, 296),Avg mBERT minmax:(0.8267, 296),Vanilla mBERT minmax:(0.8143, 296),Avg Readability Formula: (0.7796, 296),Vanilla Readability Formula: (0.7463, 296),Average Readability Formula minmax:(0.814, 296), Vanilla Readability Formula minmax:(0.8001, 296)




noscale_gemma_9b
unweighted:
 AVG:(0.7444, 296),Vanilla:(0.7217, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8132, 296),Vanilla mBERT:(0.8082, 296), AVG Readability Formula: (0.7888, 296), Vanilla Readability Formula: (0.7821, 296)
entropy weightings:
 AVG mBERT:(0.7589, 296),Vanilla mBERT:(0.7398, 296),Avg mBERT minmax:(0.8134, 296),Vanilla mBERT minmax:(0.8097, 296),Avg Readability Formula: (0.7583, 296),Vanilla Readability Formula: (0.7388, 296),Average Readability Formula minmax:(0.8042, 296), Vanilla Readability Formula minmax:(0.7997, 296)




conf_noscale_gemma_9b
unweighted:
 AVG:(0.7258, 296),Vanilla:(0.7015, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8162, 296),Vanilla mBERT:(0.8078, 296), AVG Readability Formula: (0.7916, 296), Vanilla Readability Formula: (0.7852, 296)
entropy weightings:
 AVG mBERT:(0.7423, 296),Vanilla mBERT:(0.7206, 296),Avg mBERT minmax:(0.8135, 296),Vanilla mBERT minmax:(0.8072, 296),Avg Readability Formula: (0.7416, 296),Vanilla Readability Formula: (0.7206, 296),Average Readability Formula minmax:(0.8012, 296), Vanilla Readability Formula minmax:(0.7962, 296)
verbal conf weightings:
 AVG mBERT:(0.7856, 296),Vanilla mBERT:(0.7686, 296),Avg mBERT minmax:(0.804, 296),Vanilla mBERT minmax:(0.7903, 296),Avg Readability Formula: (0.7796, 296),Vanilla Readability Formula:(0.7637, 296),Average Readability Formula minmax:(0.7936, 296),Vanilla Readability Formula minmax: (0.7814, 296)



conf_gemma_9b
unweighted:
 AVG:(0.7683, 296),Vanilla:(0.7372, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)

naive weightings:
 AVG mBERT:(0.8343, 296),Vanilla mBERT:(0.8197, 296), AVG Readability Formula: (0.7982, 296), Vanilla Readability Formula: (0.7822, 296)
entropy weightings:
 AVG mBERT:(0.7758, 296),Vanilla mBERT:(0.7466, 296),Avg mBERT minmax:(0.815, 296),Vanilla mBERT minmax:(0.8001, 296),Avg Readability Formula: (0.7742, 296),Vanilla Readability Formula: (0.7449, 296),Average Readability Formula minmax:(0.8019, 296), Vanilla Readability Formula minmax:(0.7858, 296)
verbal conf weightings:
 AVG mBERT:(0.8084, 296),Vanilla mBERT:(0.7833, 296),Avg mBERT minmax:(0.8066, 296),Vanilla mBERT minmax:(0.8014, 296),Avg Readability Formula: (0.797, 296),Vanilla Readability Formula:(0.7712, 296),Average Readability Formula minmax:(0.7584, 296),Vanilla Readability Formula minmax: (0.7529, 296)



phi
unweighted:
 AVG:(0.6879, 296),Vanilla:(0.6661, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8028, 296),Vanilla mBERT:(0.7978, 296), AVG Readability Formula: (0.7621, 296), Vanilla Readability Formula: (0.7563, 296)
entropy weightings:
 AVG mBERT:(0.7021, 296),Vanilla mBERT:(0.6822, 296),Avg mBERT minmax:(0.7472, 296),Vanilla mBERT minmax:(0.7407, 296),Avg Readability Formula: (0.6998, 296),Vanilla Readability Formula: (0.6799, 296),Average Readability Formula minmax:(0.7272, 296), Vanilla Readability Formula minmax:(0.72, 296)




noscale_phi
unweighted:
 AVG:(0.6861, 296),Vanilla:(0.6617, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.7902, 296),Vanilla mBERT:(0.7838, 296), AVG Readability Formula: (0.7634, 296), Vanilla Readability Formula: (0.7587, 296)
entropy weightings:
 AVG mBERT:(0.7086, 296),Vanilla mBERT:(0.6889, 296),Avg mBERT minmax:(0.7756, 296),Vanilla mBERT minmax:(0.7742, 296),Avg Readability Formula: (0.7069, 296),Vanilla Readability Formula: (0.6877, 296),Average Readability Formula minmax:(0.7527, 296), Vanilla Readability Formula minmax:(0.7523, 296)




conf_noscale_phi
unweighted:
 AVG:(0.667, 296),Vanilla:(0.6506, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.7937, 296),Vanilla mBERT:(0.791, 296), AVG Readability Formula: (0.7619, 296), Vanilla Readability Formula: (0.7588, 296)
entropy weightings:
 AVG mBERT:(0.6911, 296),Vanilla mBERT:(0.6774, 296),Avg mBERT minmax:(0.7681, 296),Vanilla mBERT minmax:(0.765, 296),Avg Readability Formula: (0.6889, 296),Vanilla Readability Formula: (0.6751, 296),Average Readability Formula minmax:(0.7511, 296), Vanilla Readability Formula minmax:(0.7478, 296)
verbal conf weightings:
 AVG mBERT:(0.7423, 295),Vanilla mBERT:(0.7331, 295),Avg mBERT minmax:(0.7671, 295),Vanilla mBERT minmax:(0.7633, 295),Avg Readability Formula: (0.7355, 295),Vanilla Readability Formula:(0.7261, 295),Average Readability Formula minmax:(0.7497, 295),Vanilla Readability Formula minmax: (0.7457, 295)



conf_phi
unweighted:
 AVG:(0.7145, 296),Vanilla:(0.6891, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.8193, 296),Vanilla mBERT:(0.8125, 296), AVG Readability Formula: (0.7768, 296), Vanilla Readability Formula: (0.7699, 296)
entropy weightings:
 AVG mBERT:(0.7293, 296),Vanilla mBERT:(0.7066, 296),Avg mBERT minmax:(0.7813, 296),Vanilla mBERT minmax:(0.7731, 296),Avg Readability Formula: (0.7265, 296),Vanilla Readability Formula: (0.7039, 296),Average Readability Formula minmax:(0.7548, 296), Vanilla Readability Formula minmax:(0.7462, 296)
verbal conf weightings:
 AVG mBERT:(0.7928, 296),Vanilla mBERT:(0.7774, 296),Avg mBERT minmax:(0.7892, 296),Vanilla mBERT minmax:(0.773, 296),Avg Readability Formula: (0.7789, 296),Vanilla Readability Formula:(0.7635, 296),Average Readability Formula minmax:(0.7812, 296),Vanilla Readability Formula minmax: (0.7651, 296)



Mixtral
unweighted:
 AVG:(0.6826, 296),Vanilla:(0.6713, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.7987, 296),Vanilla mBERT:(0.7943, 296), AVG Readability Formula: (0.7651, 296), Vanilla Readability Formula: (0.762, 296)
entropy weightings:
 AVG mBERT:(0.6891, 296),Vanilla mBERT:(0.6784, 296),Avg mBERT minmax:(0.7267, 296),Vanilla mBERT minmax:(0.723, 296),Avg Readability Formula: (0.6879, 296),Vanilla Readability Formula: (0.6774, 296),Average Readability Formula minmax:(0.7137, 296), Vanilla Readability Formula minmax:(0.7108, 296)




noscale_mixtral
unweighted:
 AVG:(0.5818, 295),Vanilla:(0.5715, 295),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.7659, 295),Vanilla mBERT:(0.7629, 295), AVG Readability Formula: (0.7422, 295), Vanilla Readability Formula: (0.7394, 295)
entropy weightings:
 AVG mBERT:(0.5984, 295),Vanilla mBERT:(0.5887, 295),Avg mBERT minmax:(0.6572, 295),Vanilla mBERT minmax:(0.6502, 295),Avg Readability Formula: (0.5985, 295),Vanilla Readability Formula: (0.5888, 295),Average Readability Formula minmax:(0.6581, 295), Vanilla Readability Formula minmax:(0.6515, 295)




conf_noscale_mixtral
unweighted:
 AVG:(0.6336, 296),Vanilla:(0.6295, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.7825, 296),Vanilla mBERT:(0.781, 296), AVG Readability Formula: (0.7579, 296), Vanilla Readability Formula: (0.756, 296)
entropy weightings:
 AVG mBERT:(0.6478, 296),Vanilla mBERT:(0.6442, 296),Avg mBERT minmax:(0.7388, 296),Vanilla mBERT minmax:(0.7384, 296),Avg Readability Formula: (0.6469, 296),Vanilla Readability Formula: (0.6432, 296),Average Readability Formula minmax:(0.7251, 296), Vanilla Readability Formula minmax:(0.7246, 296)
verbal conf weightings:
 AVG mBERT:(0.7048, 296),Vanilla mBERT:(0.7017, 296),Avg mBERT minmax:(0.7326, 296),Vanilla mBERT minmax:(0.7306, 296),Avg Readability Formula: (0.7013, 296),Vanilla Readability Formula:(0.6979, 296),Average Readability Formula minmax:(0.7083, 296),Vanilla Readability Formula minmax: (0.7062, 296)



conf_mixtral
unweighted:
 AVG:(0.6813, 296),Vanilla:(0.6649, 296),RSRS:(0.7592, 296),Readability Formula: (0.6805, 296)
naive weightings:
 AVG mBERT:(0.7971, 296),Vanilla mBERT:(0.7938, 296), AVG Readability Formula: (0.7645, 296), Vanilla Readability Formula: (0.7614, 296)
entropy weightings:
 AVG mBERT:(0.6878, 296),Vanilla mBERT:(0.6732, 296),Avg mBERT minmax:(0.717, 296),Vanilla mBERT minmax:(0.7138, 296),Avg Readability Formula: (0.6872, 296),Vanilla Readability Formula: (0.6726, 296),Average Readability Formula minmax:(0.7013, 296), Vanilla Readability Formula minmax:(0.6982, 296)
verbal conf weightings:
 AVG mBERT:(0.7287, 296),Vanilla mBERT:(0.7168, 296),Avg mBERT minmax:(0.7459, 296),Vanilla mBERT minmax:(0.7387, 296),Avg Readability Formula: (0.7209, 296),Vanilla Readability Formula:(0.7091, 296),Average Readability Formula minmax:(0.7157, 296),Vanilla Readability Formula minmax: (0.7087, 296)

## Read me Fr

In [46]:
readmefrv2=pd.read_csv('.../readme_fr_resultsv2.csv')
readmefrv2 = readmefrv2.replace("na", np.nan)
readmefrv2.columns

Index(['Unnamed: 0', 'Domain', 'Sub-domain', 'Paragraph', 'Context',
       'Sentence', 'Rating', 'Transliteration', 'LLAMA_8B_vanilla',
       'LLAMA_8B_avg', 'LLAMA_8B_entropy', 'LLAMA_70B_vanilla',
       'LLAMA_70B_avg', 'LLAMA_70B_entropy', 'LLAMA_3B_vanilla',
       'LLAMA_3B_avg', 'LLAMA_3B_entropy', 'AYA_32B_vanilla', 'AYA_32B_avg',
       'AYA_32B_entropy', 'AYA_8B_vanilla', 'AYA_8B_avg', 'AYA_8B_entropy',
       'mixtral_vanilla', 'mixtral_avg', 'mixtral_entropy',
       'noscale_mixtral_vanilla', 'noscale_mixtral_avg',
       'noscale_mixtral_entropy', 'conf_noscale_aya_32b_vanilla',
       'conf_noscale_aya_32b_avg', 'conf_noscale_aya_32b_entropy',
       'conf_noscale_aya_32b_verbal_conf', 'conf_aya_32b_vanilla',
       'conf_aya_32b_avg', 'conf_aya_32b_entropy', 'conf_aya_32b_verbal_conf',
       'conf_mixtral_vanilla', 'conf_mixtral_avg', 'conf_mixtral_entropy',
       'conf_mixtral_verbal_conf', 'conf_noscale_mixtral_vanilla',
       'conf_noscale_mixtral_avg', 'conf_noscale_mixtral_entropy',
       'conf_noscale_mixtral_verbal_conf', 'conf_noscale_llama_3b_vanilla',
       'conf_noscale_llama_3b_avg', 'conf_noscale_llama_3b_entropy',
       'conf_noscale_llama_3b_verbal_conf', 'conf_llama_3b_vanilla',
       'conf_llama_3b_avg', 'conf_llama_3b_entropy',
       'conf_llama_3b_verbal_conf', 'conf_llama_8b_vanilla',
       'conf_llama_8b_avg', 'conf_llama_8b_entropy',
       'conf_llama_8b_verbal_conf', 'conf_noscale_llama_8b_vanilla',
       'conf_noscale_llama_8b_avg', 'conf_noscale_llama_8b_entropy',
       'conf_noscale_llama_8b_verbal_conf', 'conf_noscale_llama_70b_vanilla',
       'conf_noscale_llama_70b_avg', 'conf_noscale_llama_70b_entropy',
       'conf_noscale_llama_70b_verbal_conf', 'conf_llama_70b_vanilla',
       'conf_llama_70b_avg', 'conf_llama_70b_entropy',
       'conf_llama_70b_verbal_conf', 'noscale_aya_8b_vanilla',
       'noscale_aya_8b_avg', 'noscale_aya_8b_entropy',
       'noscale_aya_32b_vanilla', 'noscale_aya_32b_avg',
       'noscale_aya_32b_entropy', 'noscale_llama_8b_vanilla',
       'noscale_llama_8b_avg', 'noscale_llama_8b_entropy',
       'noscale_llama_3b_vanilla', 'noscale_llama_3b_avg',
       'noscale_llama_3b_entropy', 'noscale_llama_70b_vanilla',
       'noscale_llama_70b_avg', 'noscale_llama_70b_entropy', 'FKGL', 'FRE',
       'ARI', 'RSRS_mBERT'],
      dtype='object')

In [47]:
ref_col = readmefrv2.columns[6]
for i in range(8, len(readmefrv2.columns)): 
    col = readmefrv2.columns[i]
    corr = readmefrv2[ref_col].astype(float).corr(readmefrv2[col].astype(float))
    if ('entropy' not in col) and ('verbal_conf' not in col):
        print(f"{i+1}: {col} -> correlation with {ref_col}: {corr:.4f}")

9: LLAMA_8B_vanilla -> correlation with Rating: 0.5730
10: LLAMA_8B_avg -> correlation with Rating: 0.6251
12: LLAMA_70B_vanilla -> correlation with Rating: 0.6424
13: LLAMA_70B_avg -> correlation with Rating: 0.6836
15: LLAMA_3B_vanilla -> correlation with Rating: 0.4560
16: LLAMA_3B_avg -> correlation with Rating: 0.6235
18: AYA_32B_vanilla -> correlation with Rating: 0.6514
19: AYA_32B_avg -> correlation with Rating: 0.6662
21: AYA_8B_vanilla -> correlation with Rating: 0.6272
22: AYA_8B_avg -> correlation with Rating: 0.6720
24: mixtral_vanilla -> correlation with Rating: 0.6050
25: mixtral_avg -> correlation with Rating: 0.6133
27: noscale_mixtral_vanilla -> correlation with Rating: 0.2724
28: noscale_mixtral_avg -> correlation with Rating: 0.2947
30: conf_noscale_aya_32b_vanilla -> correlation with Rating: 0.4687
31: conf_noscale_aya_32b_avg -> correlation with Rating: 0.4784
34: conf_aya_32b_vanilla -> correlation with Rating: 0.6768
35: conf_aya_32b_avg -> correlation with Rating: 0.6923
38: conf_mixtral_vanilla -> correlation with Rating: 0.5095
39: conf_mixtral_avg -> correlation with Rating: 0.5452
42: conf_noscale_mixtral_vanilla -> correlation with Rating: 0.3517
43: conf_noscale_mixtral_avg -> correlation with Rating: 0.3659
46: conf_noscale_llama_3b_vanilla -> correlation with Rating: 0.1916
47: conf_noscale_llama_3b_avg -> correlation with Rating: 0.2650
50: conf_llama_3b_vanilla -> correlation with Rating: 0.3570
51: conf_llama_3b_avg -> correlation with Rating: 0.5433
54: conf_llama_8b_vanilla -> correlation with Rating: 0.5870
55: conf_llama_8b_avg -> correlation with Rating: 0.6154
58: conf_noscale_llama_8b_vanilla -> correlation with Rating: 0.5371
59: conf_noscale_llama_8b_avg -> correlation with Rating: 0.5768
62: conf_noscale_llama_70b_vanilla -> correlation with Rating: 0.3669
63: conf_noscale_llama_70b_avg -> correlation with Rating: 0.4444
66: conf_llama_70b_vanilla -> correlation with Rating: 0.6226
67: conf_llama_70b_avg -> correlation with Rating: 0.6897
70: noscale_aya_8b_vanilla -> correlation with Rating: 0.5797
71: noscale_aya_8b_avg -> correlation with Rating: 0.6173
73: noscale_aya_32b_vanilla -> correlation with Rating: 0.4156
74: noscale_aya_32b_avg -> correlation with Rating: 0.4217
76: noscale_llama_8b_vanilla -> correlation with Rating: 0.4973
77: noscale_llama_8b_avg -> correlation with Rating: 0.5357
79: noscale_llama_3b_vanilla -> correlation with Rating: 0.2012
80: noscale_llama_3b_avg -> correlation with Rating: 0.2801
82: noscale_llama_70b_vanilla -> correlation with Rating: 0.3625
83: noscale_llama_70b_avg -> correlation with Rating: 0.4491
85: FKGL -> correlation with Rating: 0.7392
86: FRE -> correlation with Rating: -0.5980
87: ARI -> correlation with Rating: 0.6985
88: RSRS_mBERT -> correlation with Rating: 0.7038

In [48]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
readmefrv2 = readmefrv2.apply(pd.to_numeric, errors="coerce")
rf_string='FKGL'
std_cols = [c for c in readmefrv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
readmefrv2[std_cols] = StandardScaler().fit_transform(readmefrv2[std_cols])
model='conf_aya_32b'
vconf_col=f'{model}_verbal_conf'
avg_col = f"{model}_avg"


verbal_avg_rf=((1 - readmefrv2[vconf_col]/10) * readmefrv2[rf_string]) + (readmefrv2[vconf_col]/10 * readmefrv2[avg_col])


rjk,n1=safe_corr_raw(verbal_avg_rf, readmefrv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmefrv2.iloc[:,29], readmefrv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,readmefrv2.iloc[:,29])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs LLM : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, readmefrv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmefrv2[rf_string], readmefrv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,readmefrv2[rf_string])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RF : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, readmefrv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmefrv2['RSRS_mBERT'], readmefrv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,readmefrv2['RSRS_mBERT'])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RSRS : t2:{res1[0]}, p:{res1[1]}')

0.7496527463153283 0.4687028760678706 0.6337464029006994
185
t_test: Vconf RF vs LLM : t2:6.579592950378244, p:4.862537039684867e-10
0.7496527463153283 0.739192586106686 0.7587872830681893
185
t_test: Vconf RF vs RF : t2:0.3301619177320339, p:0.7416573479621684
0.7496527463153283 0.7037787786480764 0.7220758351967657
185
t_test: Vconf RF vs RSRS : t2:1.3214645768238034, p:0.1880052891268098

In [49]:
import numpy as np
rjk,n1=safe_corr_raw(readmefrv2.iloc[:,30], readmefrv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmefrv2.iloc[:,34], readmefrv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(readmefrv2.iloc[:,30],readmefrv2.iloc[:,34])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Scale vs No scale : t2:{res1[0]}, p:{res1[1]}')


import numpy as np
rjk,n1=safe_corr_raw(readmefrv2.iloc[:,29], readmefrv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmefrv2.iloc[:,34], readmefrv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(readmefrv2.iloc[:,29],readmefrv2.iloc[:,34])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Scale and Expected vs No scale and Vanilla: t2:{res1[0]}, p:{res1[1]}')

0.4784376899579759 0.69232791791452 0.6786587990486568
185
t_test: Scale vs No scale : t2:-4.939616893955538, p:1.7652347248375833e-06
0.4687028760678706 0.69232791791452 0.6507992905611316
185
t_test: Scale and Expected vs No scale and Vanilla: t2:-4.947379579240231, p:1.7043341054012728e-06

In [50]:
readmefrv2 = readmefrv2.apply(pd.to_numeric, errors="coerce")
import numpy as np
rjk,n1=safe_corr_raw(readmefrv2.iloc[:,34], readmefrv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmefrv2.iloc[:,66], readmefrv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(readmefrv2.iloc[:,66],readmefrv2.iloc[:,34])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Aya v Llama : t2:{res1[0]}, p:{res1[1]}')

import numpy as np
rjk,n1=safe_corr_raw(readmefrv2.iloc[:,34], readmefrv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmefrv2.iloc[:,33], readmefrv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(readmefrv2.iloc[:,33],readmefrv2.iloc[:,34])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Expected v Vanilla : t2:{res1[0]}, p:{res1[1]}')

0.69232791791452 0.6896840902909678 0.8022144352819391
185
t_test: Aya v Llama : t2:0.08226418502619144, p:0.9345270359143325
0.69232791791452 0.6768085430677779 0.9864461021700762
185
t_test: Expected v Vanilla : t2:1.7646210439870162, p:0.07930485476259674

In [51]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
readmefrv2 = readmefrv2.apply(pd.to_numeric, errors="coerce")
rf_string='FKGL'
ref_col = readmefrv2.columns[6]
#readmefrv2['RSRS_mBERT']= StandardScaler().fit_transform(readmefrv2['RSRS_mBERT'])
# Step 1: Normalize entropy columns
entropy_cols = [c for c in readmefrv2.columns if c.endswith("_entropy")]
entropy_cols_minmax = [c + "_minmax" for c in entropy_cols]
readmefrv2[entropy_cols_minmax] = MinMaxScaler().fit_transform(readmefrv2[entropy_cols])

vconf_cols = [c for c in readmefrv2.columns if c.endswith("verbal_conf")]
vconf_cols_minmax = [c + "_minmax" for c in vconf_cols]
readmefrv2[vconf_cols_minmax] = MinMaxScaler().fit_transform(readmefrv2[vconf_cols])
readmefrv2[vconf_cols] = readmefrv2[vconf_cols]/10

std_cols = [c for c in readmefrv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
readmefrv2[std_cols] = StandardScaler().fit_transform(readmefrv2[std_cols])
suffixes = ["_avg", "_vanilla", "_entropy"]
models = set(
    c.rsplit("_", 1)[0]  # remove the last part after the final underscore
    for c in entropy_cols  # or any column list containing these suffixes
)
sorted_models = sorted(models, key=lambda x: x[::-1].lower())
for model in sorted_models:
    print(model)
    vanilla_col = f"{model}_vanilla"
    avg_col = f"{model}_avg"
    print(f'unweighted:\n AVG:{safe_corr(readmefrv2[avg_col], readmefrv2[ref_col])},Vanilla:{safe_corr(readmefrv2[vanilla_col], readmefrv2[ref_col])},RSRS:{safe_corr(readmefrv2["RSRS_mBERT"], readmefrv2[ref_col])},Readability Formula: {safe_corr(readmefrv2[rf_string], readmefrv2[ref_col])}')
    naive_avg_mBERT=readmefrv2[avg_col]+readmefrv2["RSRS_mBERT"]
    naive_vanilla_mBERT=readmefrv2[vanilla_col]+readmefrv2["RSRS_mBERT"]
    
    naive_avg_rf=readmefrv2[avg_col]+readmefrv2[rf_string]
    naive_vanilla_rf=readmefrv2[vanilla_col]+readmefrv2[rf_string]
    print(f'naive weightings: \n AVG mBERT:{safe_corr(naive_avg_mBERT, readmefrv2[ref_col])},Vanilla mBERT:{safe_corr(naive_vanilla_mBERT, readmefrv2[ref_col])}, AVG Readability Formula: {safe_corr(naive_avg_rf, readmefrv2[ref_col])}, Vanilla Readability Formula: {safe_corr(naive_vanilla_rf, readmefrv2[ref_col])}')
    entropy_col = f"{model}_entropy"
    entropy_col_minmax = f"{model}_entropy_minmax"
    if model.startswith('conf_'):
        vconf_col=f'{model}_verbal_conf'
        vconf_col_minmax = f"{model}_verbal_conf_minmax"
    
    #readmefrv2[f"{model}_weighted"] = (
    #    readmefrv2[entropy_col] * readmefrv2["RSRS_mBERT"] + 
    #    (1 - readmefrv2[entropy_col]) * (readmefrv2[[vanilla_col, avg_col]].mean(axis=1))
    #)
    entropy_avg_mBERT=(readmefrv2[entropy_col] * readmefrv2["RSRS_mBERT"]) + ((1 - readmefrv2[entropy_col]) * readmefrv2[avg_col])
    entropy_vanilla_mBERT=(readmefrv2[entropy_col] * readmefrv2["RSRS_mBERT"]) + ((1 - readmefrv2[entropy_col]) * readmefrv2[vanilla_col])
    entropy_minmax_avg_mBERT=(readmefrv2[entropy_col_minmax] * readmefrv2["RSRS_mBERT"]) + ((1 - readmefrv2[entropy_col_minmax]) * readmefrv2[avg_col])
    entropy_minmax_vanilla_mBERT=(readmefrv2[entropy_col_minmax] * readmefrv2["RSRS_mBERT"]) + ((1 - readmefrv2[entropy_col_minmax]) * readmefrv2[vanilla_col])
    
    entropy_avg_rf=(readmefrv2[entropy_col] * readmefrv2[rf_string]) + ((1 - readmefrv2[entropy_col]) * readmefrv2[avg_col])
    entropy_vanilla_rf=(readmefrv2[entropy_col] * readmefrv2[rf_string]) + ((1 - readmefrv2[entropy_col]) * readmefrv2[vanilla_col])
    entropy_minmax_avg_rf=(readmefrv2[entropy_col_minmax] * readmefrv2[rf_string]) + ((1 - readmefrv2[entropy_col_minmax]) * readmefrv2[avg_col])
    entropy_minmax_vanilla_rf=(readmefrv2[entropy_col_minmax] * readmefrv2[rf_string]) + ((1 - readmefrv2[entropy_col_minmax]) * readmefrv2[vanilla_col])
    print(f'entropy weightings:\n AVG mBERT:{safe_corr(entropy_avg_mBERT, readmefrv2[ref_col])},Vanilla mBERT:{safe_corr(entropy_vanilla_mBERT, readmefrv2[ref_col])},Avg mBERT minmax:{safe_corr(entropy_minmax_avg_mBERT, readmefrv2[ref_col])},Vanilla mBERT minmax:{safe_corr(entropy_minmax_vanilla_mBERT, readmefrv2[ref_col])},Avg Readability Formula: {safe_corr(entropy_avg_rf, readmefrv2[ref_col])},Vanilla Readability Formula: {safe_corr(entropy_vanilla_rf, readmefrv2[ref_col])},Average Readability Formula minmax:{safe_corr(entropy_minmax_avg_rf, readmefrv2[ref_col])}, Vanilla Readability Formula minmax:{safe_corr(entropy_minmax_vanilla_rf, readmefrv2[ref_col])}')
    if model.startswith('conf_'):
        verbal_avg_mBERT=((1 - readmefrv2[vconf_col]) * readmefrv2["RSRS_mBERT"]) + (readmefrv2[vconf_col] * readmefrv2[avg_col])
        verbal_vanilla_mBERT=((1 - readmefrv2[vconf_col]) * readmefrv2["RSRS_mBERT"]) + (readmefrv2[vconf_col] * readmefrv2[vanilla_col])
        verbal_minmax_avg_mBERT=((1 - readmefrv2[vconf_col_minmax]) * readmefrv2["RSRS_mBERT"]) + (readmefrv2[vconf_col_minmax] * readmefrv2[avg_col])
        verbal_minmax_vanilla_mBERT=((1 - readmefrv2[vconf_col_minmax]) * readmefrv2["RSRS_mBERT"]) + (readmefrv2[vconf_col_minmax] * readmefrv2[vanilla_col])
        
        verbal_avg_rf=((1 - readmefrv2[vconf_col]) * readmefrv2[rf_string]) + (readmefrv2[vconf_col] * readmefrv2[avg_col])
        verbal_vanilla_rf=((1 - readmefrv2[vconf_col]) * readmefrv2[rf_string]) + (readmefrv2[vconf_col] * readmefrv2[vanilla_col])
        verbal_minmax_avg_rf=((1 - readmefrv2[vconf_col_minmax]) * readmefrv2[rf_string]) + (readmefrv2[vconf_col_minmax] * readmefrv2[avg_col])
        verbal_minmax_vanilla_rf=((1 - readmefrv2[vconf_col_minmax]) * readmefrv2[rf_string]) + (readmefrv2[vconf_col_minmax] * readmefrv2[vanilla_col])
        print(f'verbal conf weightings:\n AVG mBERT:{safe_corr(verbal_avg_mBERT, readmefrv2[ref_col])},Vanilla mBERT:{safe_corr(verbal_vanilla_mBERT, readmefrv2[ref_col])},Avg mBERT minmax:{safe_corr(verbal_minmax_avg_mBERT, readmefrv2[ref_col])},Vanilla mBERT minmax:{safe_corr(verbal_minmax_vanilla_mBERT, readmefrv2[ref_col])},Avg Readability Formula: {safe_corr(verbal_avg_rf, readmefrv2[ref_col])},Vanilla Readability Formula:{safe_corr(verbal_vanilla_rf, readmefrv2[ref_col])},Average Readability Formula minmax:{safe_corr(verbal_minmax_avg_rf, readmefrv2[ref_col])},Vanilla Readability Formula minmax: {safe_corr(verbal_minmax_vanilla_rf, readmefrv2[ref_col])}','\n \n \n')
    else:
        print('\n \n \n')

LLAMA_70B
unweighted:
 AVG:(0.6836, 185),Vanilla:(0.6424, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.7596, 185),Vanilla mBERT:(0.7433, 185), AVG Readability Formula: (0.7934, 185), Vanilla Readability Formula: (0.7784, 185)
entropy weightings:
 AVG mBERT:(0.6978, 185),Vanilla mBERT:(0.6613, 185),Avg mBERT minmax:(0.7549, 185),Vanilla mBERT minmax:(0.7513, 185),Avg Readability Formula: (0.703, 185),Vanilla Readability Formula: (0.6667, 185),Average Readability Formula minmax:(0.7825, 185), Vanilla Readability Formula minmax:(0.7812, 185)




noscale_llama_70b
unweighted:
 AVG:(0.4491, 185),Vanilla:(0.3625, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.6663, 185),Vanilla mBERT:(0.6342, 185), AVG Readability Formula: (0.7037, 185), Vanilla Readability Formula: (0.6718, 185)
entropy weightings:
 AVG mBERT:(0.4791, 185),Vanilla mBERT:(0.4044, 185),Avg mBERT minmax:(0.6107, 185),Vanilla mBERT minmax:(0.6011, 185),Avg Readability Formula: (0.4853, 185),Vanilla Readability Formula: (0.4102, 185),Average Readability Formula minmax:(0.6488, 185), Vanilla Readability Formula minmax:(0.6404, 185)




conf_noscale_llama_70b
unweighted:
 AVG:(0.4444, 185),Vanilla:(0.3669, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.6656, 185),Vanilla mBERT:(0.6361, 185), AVG Readability Formula: (0.7036, 185), Vanilla Readability Formula: (0.6772, 185)
entropy weightings:
 AVG mBERT:(0.4742, 185),Vanilla mBERT:(0.4055, 185),Avg mBERT minmax:(0.606, 185),Vanilla mBERT minmax:(0.5856, 185),Avg Readability Formula: (0.4801, 185),Vanilla Readability Formula: (0.4116, 185),Average Readability Formula minmax:(0.6418, 185), Vanilla Readability Formula minmax:(0.6245, 185)
verbal conf weightings:
 AVG mBERT:(0.5758, 185),Vanilla mBERT:(0.5257, 185),Avg mBERT minmax:(0.6145, 185),Vanilla mBERT minmax:(0.5804, 185),Avg Readability Formula: (0.5969, 185),Vanilla Readability Formula:(0.5484, 185),Average Readability Formula minmax:(0.6406, 185),Vanilla Readability Formula minmax: (0.6092, 185)



conf_llama_70b
unweighted:
 AVG:(0.6897, 185),Vanilla:(0.6226, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.7662, 185),Vanilla mBERT:(0.7469, 185), AVG Readability Formula: (0.7993, 185), Vanilla Readability Formula: (0.7854, 185)
entropy weightings:
 AVG mBERT:(0.7027, 185),Vanilla mBERT:(0.6457, 185),Avg mBERT minmax:(0.7495, 185),Vanilla mBERT minmax:(0.7469, 185),Avg Readability Formula: (0.7076, 185),Vanilla Readability Formula: (0.6516, 185),Average Readability Formula minmax:(0.7775, 185), Vanilla Readability Formula minmax:(0.7806, 185)
verbal conf weightings:
 AVG mBERT:(0.7372, 185),Vanilla mBERT:(0.7017, 185),Avg mBERT minmax:(0.7302, 185),Vanilla mBERT minmax:(0.6946, 185),Avg Readability Formula: (0.7506, 185),Vanilla Readability Formula:(0.7176, 185),Average Readability Formula minmax:(0.7394, 185),Vanilla Readability Formula minmax: (0.7053, 185)



AYA_32B
unweighted:
 AVG:(0.6662, 185),Vanilla:(0.6514, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.7643, 185),Vanilla mBERT:(0.7614, 185), AVG Readability Formula: (0.7869, 185), Vanilla Readability Formula: (0.7842, 185)
entropy weightings:
 AVG mBERT:(0.6723, 185),Vanilla mBERT:(0.6588, 185),Avg mBERT minmax:(0.7183, 185),Vanilla mBERT minmax:(0.7184, 185),Avg Readability Formula: (0.6731, 185),Vanilla Readability Formula: (0.6597, 185),Average Readability Formula minmax:(0.739, 185), Vanilla Readability Formula minmax:(0.7398, 185)




noscale_aya_32b
unweighted:
 AVG:(0.4217, 185),Vanilla:(0.4156, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.6716, 185),Vanilla mBERT:(0.6751, 185), AVG Readability Formula: (0.7031, 185), Vanilla Readability Formula: (0.7053, 185)
entropy weightings:
 AVG mBERT:(0.4393, 185),Vanilla mBERT:(0.435, 185),Avg mBERT minmax:(0.5485, 185),Vanilla mBERT minmax:(0.5542, 185),Avg Readability Formula: (0.4425, 185),Vanilla Readability Formula: (0.4379, 185),Average Readability Formula minmax:(0.5739, 185), Vanilla Readability Formula minmax:(0.5803, 185)




conf_noscale_aya_32b
unweighted:
 AVG:(0.4784, 185),Vanilla:(0.4687, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.6922, 185),Vanilla mBERT:(0.6879, 185), AVG Readability Formula: (0.7253, 185), Vanilla Readability Formula: (0.7196, 185)
entropy weightings:
 AVG mBERT:(0.5013, 185),Vanilla mBERT:(0.4921, 185),Avg mBERT minmax:(0.6533, 185),Vanilla mBERT minmax:(0.6527, 185),Avg Readability Formula: (0.5046, 185),Vanilla Readability Formula: (0.4952, 185),Average Readability Formula minmax:(0.6794, 185), Vanilla Readability Formula minmax:(0.6788, 185)
verbal conf weightings:
 AVG mBERT:(0.5871, 185),Vanilla mBERT:(0.5788, 185),Avg mBERT minmax:(0.6289, 185),Vanilla mBERT minmax:(0.6212, 185),Avg Readability Formula: (0.6037, 185),Vanilla Readability Formula:(0.5946, 185),Average Readability Formula minmax:(0.6554, 185),Vanilla Readability Formula minmax: (0.6472, 185)



conf_aya_32b
unweighted:
 AVG:(0.6923, 185),Vanilla:(0.6768, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.772, 185),Vanilla mBERT:(0.7679, 185), AVG Readability Formula: (0.7925, 185), Vanilla Readability Formula: (0.7892, 185)
entropy weightings:
 AVG mBERT:(0.6997, 185),Vanilla mBERT:(0.6852, 185),Avg mBERT minmax:(0.7594, 185),Vanilla mBERT minmax:(0.7553, 185),Avg Readability Formula: (0.7008, 185),Vanilla Readability Formula: (0.6864, 185),Average Readability Formula minmax:(0.775, 185), Vanilla Readability Formula minmax:(0.772, 185)
verbal conf weightings:
 AVG mBERT:(0.7413, 185),Vanilla mBERT:(0.7308, 185),Avg mBERT minmax:(0.7681, 185),Vanilla mBERT minmax:(0.7643, 185),Avg Readability Formula: (0.7497, 185),Vanilla Readability Formula:(0.7396, 185),Average Readability Formula minmax:(0.7841, 185),Vanilla Readability Formula minmax: (0.7809, 185)



LLAMA_3B
unweighted:
 AVG:(0.6235, 185),Vanilla:(0.456, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.7421, 185),Vanilla mBERT:(0.6778, 185), AVG Readability Formula: (0.7576, 185), Vanilla Readability Formula: (0.6983, 185)
entropy weightings:
 AVG mBERT:(0.6509, 185),Vanilla mBERT:(0.5041, 185),Avg mBERT minmax:(0.7439, 185),Vanilla mBERT minmax:(0.7297, 185),Avg Readability Formula: (0.6541, 185),Vanilla Readability Formula: (0.5083, 185),Average Readability Formula minmax:(0.7653, 185), Vanilla Readability Formula minmax:(0.756, 185)




noscale_llama_3b
unweighted:
 AVG:(0.2801, 184),Vanilla:(0.2012, 184),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.5987, 184),Vanilla mBERT:(0.5681, 184), AVG Readability Formula: (0.6427, 184), Vanilla Readability Formula: (0.6121, 184)
entropy weightings:
 AVG mBERT:(0.3127, 184),Vanilla mBERT:(0.2392, 184),Avg mBERT minmax:(0.5061, 184),Vanilla mBERT minmax:(0.4932, 184),Avg Readability Formula: (0.3207, 184),Vanilla Readability Formula: (0.2465, 184),Average Readability Formula minmax:(0.5624, 184), Vanilla Readability Formula minmax:(0.5548, 184)




conf_noscale_llama_3b
unweighted:
 AVG:(0.265, 184),Vanilla:(0.1916, 184),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.5941, 184),Vanilla mBERT:(0.5698, 184), AVG Readability Formula: (0.6351, 184), Vanilla Readability Formula: (0.6058, 184)
entropy weightings:
 AVG mBERT:(0.3032, 184),Vanilla mBERT:(0.2352, 184),Avg mBERT minmax:(0.5229, 184),Vanilla mBERT minmax:(0.5107, 184),Avg Readability Formula: (0.3116, 184),Vanilla Readability Formula: (0.2423, 184),Average Readability Formula minmax:(0.5759, 184), Vanilla Readability Formula minmax:(0.5678, 184)
verbal conf weightings:
 AVG mBERT:(0.4396, 184),Vanilla mBERT:(0.3879, 184),Avg mBERT minmax:(0.5783, 184),Vanilla mBERT minmax:(0.5569, 184),Avg Readability Formula: (0.4592, 184),Vanilla Readability Formula:(0.404, 184),Average Readability Formula minmax:(0.613, 184),Vanilla Readability Formula minmax: (0.5863, 184)



conf_llama_3b
unweighted:
 AVG:(0.5433, 185),Vanilla:(0.357, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.7259, 185),Vanilla mBERT:(0.6512, 185), AVG Readability Formula: (0.7469, 185), Vanilla Readability Formula: (0.6739, 185)
entropy weightings:
 AVG mBERT:(0.5715, 185),Vanilla mBERT:(0.4014, 185),Avg mBERT minmax:(0.6978, 185),Vanilla mBERT minmax:(0.6538, 185),Avg Readability Formula: (0.5752, 185),Vanilla Readability Formula: (0.4053, 185),Average Readability Formula minmax:(0.7147, 185), Vanilla Readability Formula minmax:(0.6739, 185)

verbal conf weightings:
 AVG mBERT:(0.6252, 185),Vanilla mBERT:(0.475, 185),Avg mBERT minmax:(0.6824, 185),Vanilla mBERT minmax:(0.6326, 185),Avg Readability Formula: (0.6334, 185),Vanilla Readability Formula:(0.4835, 185),Average Readability Formula minmax:(0.7103, 185),Vanilla Readability Formula minmax: (0.6605, 185)



LLAMA_8B
unweighted:
 AVG:(0.6251, 185),Vanilla:(0.573, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.7488, 185),Vanilla mBERT:(0.7311, 185), AVG Readability Formula: (0.7737, 185), Vanilla Readability Formula: (0.7555, 185)
entropy weightings:
 AVG mBERT:(0.641, 185),Vanilla mBERT:(0.5938, 185),Avg mBERT minmax:(0.7352, 185),Vanilla mBERT minmax:(0.7293, 185),Avg Readability Formula: (0.6445, 185),Vanilla Readability Formula: (0.5972, 185),Average Readability Formula minmax:(0.7591, 185), Vanilla Readability Formula minmax:(0.7527, 185)




noscale_llama_8b
unweighted:
 AVG:(0.5357, 185),Vanilla:(0.4973, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.7178, 185),Vanilla mBERT:(0.7041, 185), AVG Readability Formula: (0.741, 185), Vanilla Readability Formula: (0.7263, 185)
entropy weightings:
 AVG mBERT:(0.5563, 185),Vanilla mBERT:(0.5211, 185),Avg mBERT minmax:(0.6596, 185),Vanilla mBERT minmax:(0.6478, 185),Avg Readability Formula: (0.5606, 185),Vanilla Readability Formula: (0.5255, 185),Average Readability Formula minmax:(0.6871, 185), Vanilla Readability Formula minmax:(0.6753, 185)




conf_noscale_llama_8b
unweighted:
 AVG:(0.5768, 185),Vanilla:(0.5371, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.729, 185),Vanilla mBERT:(0.7101, 185), AVG Readability Formula: (0.7523, 185), Vanilla Readability Formula: (0.7351, 185)
entropy weightings:
 AVG mBERT:(0.5948, 185),Vanilla mBERT:(0.5602, 185),Avg mBERT minmax:(0.6746, 185),Vanilla mBERT minmax:(0.6679, 185),Avg Readability Formula: (0.5981, 185),Vanilla Readability Formula: (0.5638, 185),Average Readability Formula minmax:(0.6927, 185), Vanilla Readability Formula minmax:(0.689, 185)
verbal conf weightings:
 AVG mBERT:(0.6598, 185),Vanilla mBERT:(0.6288, 185),Avg mBERT minmax:(0.6889, 185),Vanilla mBERT minmax:(0.6694, 185),Avg Readability Formula: (0.6682, 185),Vanilla Readability Formula:(0.6379, 185),Average Readability Formula minmax:(0.7063, 185),Vanilla Readability Formula minmax: (0.6883, 185)



conf_llama_8b
unweighted:
 AVG:(0.6154, 185),Vanilla:(0.587, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.7408, 185),Vanilla mBERT:(0.7307, 185), AVG Readability Formula: (0.7649, 185), Vanilla Readability Formula: (0.7561, 185)
entropy weightings:
 AVG mBERT:(0.6265, 185),Vanilla mBERT:(0.6001, 185),Avg mBERT minmax:(0.6879, 185),Vanilla mBERT minmax:(0.6803, 185),Avg Readability Formula: (0.6295, 185),Vanilla Readability Formula: (0.6032, 185),Average Readability Formula minmax:(0.709, 185), Vanilla Readability Formula minmax:(0.7029, 185)
verbal conf weightings:
 AVG mBERT:(0.6719, 185),Vanilla mBERT:(0.6506, 185),Avg mBERT minmax:(0.6964, 185),Vanilla mBERT minmax:(0.6898, 185),Avg Readability Formula: (0.6812, 185),Vanilla Readability Formula:(0.6603, 185),Average Readability Formula minmax:(0.7265, 185),Vanilla Readability Formula minmax: (0.7211, 185)



AYA_8B
unweighted:
 AVG:(0.672, 185),Vanilla:(0.6272, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.7757, 185),Vanilla mBERT:(0.7627, 185), AVG Readability Formula: (0.7879, 185), Vanilla Readability Formula: (0.7762, 185)
entropy weightings:
 AVG mBERT:(0.6771, 185),Vanilla mBERT:(0.6359, 185),Avg mBERT minmax:(0.7044, 185),Vanilla mBERT minmax:(0.7027, 185),Avg Readability Formula: (0.6777, 185),Vanilla Readability Formula: (0.6367, 185),Average Readability Formula minmax:(0.698, 185), Vanilla Readability Formula minmax:(0.6945, 185)




noscale_aya_8b
unweighted:
 AVG:(0.6173, 185),Vanilla:(0.5797, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.7528, 185),Vanilla mBERT:(0.7333, 185), AVG Readability Formula: (0.7685, 185), Vanilla Readability Formula: (0.7527, 185)
entropy weightings:
 AVG mBERT:(0.6393, 185),Vanilla mBERT:(0.6042, 185),Avg mBERT minmax:(0.7469, 185),Vanilla mBERT minmax:(0.7392, 185),Avg Readability Formula: (0.6398, 185),Vanilla Readability Formula: (0.6053, 185),Average Readability Formula minmax:(0.7608, 185), Vanilla Readability Formula minmax:(0.7564, 185)




mixtral
unweighted:
 AVG:(0.6133, 185),Vanilla:(0.605, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.7389, 185),Vanilla mBERT:(0.7365, 185), AVG Readability Formula: (0.7537, 185), Vanilla Readability Formula: (0.7514, 185)
entropy weightings:
 AVG mBERT:(0.622, 185),Vanilla mBERT:(0.6143, 185),Avg mBERT minmax:(0.6813, 185),Vanilla mBERT minmax:(0.6794, 185),Avg Readability Formula: (0.6231, 185),Vanilla Readability Formula: (0.6153, 185),Average Readability Formula minmax:(0.6957, 185), Vanilla Readability Formula minmax:(0.6941, 185)




noscale_mixtral
unweighted:
 AVG:(0.2947, 185),Vanilla:(0.2724, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.6079, 185),Vanilla mBERT:(0.5989, 185), AVG Readability Formula: (0.6387, 185), Vanilla Readability Formula: (0.6288, 185)
entropy weightings:
 AVG mBERT:(0.3179, 185),Vanilla mBERT:(0.2974, 185),Avg mBERT minmax:(0.5123, 185),Vanilla mBERT minmax:(0.5104, 185),Avg Readability Formula: (0.3208, 185),Vanilla Readability Formula: (0.3002, 185),Average Readability Formula minmax:(0.5339, 185), Vanilla Readability Formula minmax:(0.5317, 185)




conf_noscale_mixtral
unweighted:
 AVG:(0.3659, 185),Vanilla:(0.3517, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.6385, 185),Vanilla mBERT:(0.6332, 185), AVG Readability Formula: (0.6678, 185), Vanilla Readability Formula: (0.6632, 185)
entropy weightings:
 AVG mBERT:(0.3929, 185),Vanilla mBERT:(0.38, 185),Avg mBERT minmax:(0.6072, 185),Vanilla mBERT minmax:(0.6067, 185),Avg Readability Formula: (0.3957, 185),Vanilla Readability Formula: (0.3828, 185),Average Readability Formula minmax:(0.6338, 185), Vanilla Readability Formula minmax:(0.6341, 185)
verbal conf weightings:
 AVG mBERT:(0.5058, 185),Vanilla mBERT:(0.4959, 185),Avg mBERT minmax:(0.6648, 185),Vanilla mBERT minmax:(0.6634, 185),Avg Readability Formula: (0.5189, 185),Vanilla Readability Formula:(0.5092, 185),Average Readability Formula minmax:(0.6967, 185),Vanilla Readability Formula minmax: (0.6953, 185)



conf_mixtral
unweighted:
 AVG:(0.5452, 185),Vanilla:(0.5095, 185),RSRS:(0.7038, 185),Readability Formula: (0.7392, 185)
naive weightings:
 AVG mBERT:(0.706, 185),Vanilla mBERT:(0.6963, 185), AVG Readability Formula: (0.7229, 185), Vanilla Readability Formula: (0.7135, 185)
entropy weightings:
 AVG mBERT:(0.557, 185),Vanilla mBERT:(0.5246, 185),Avg mBERT minmax:(0.6269, 185),Vanilla mBERT minmax:(0.6194, 185),Avg Readability Formula: (0.5567, 185),Vanilla Readability Formula: (0.5242, 185),Average Readability Formula minmax:(0.6353, 185), Vanilla Readability Formula minmax:(0.628, 185)
verbal conf weightings:
 AVG mBERT:(0.6269, 185),Vanilla mBERT:(0.604, 185),Avg mBERT minmax:(0.7195, 185),Vanilla mBERT minmax:(0.7169, 185),Avg Readability Formula: (0.6311, 185),Vanilla Readability Formula:(0.6081, 185),Average Readability Formula minmax:(0.7275, 185),Vanilla Readability Formula minmax: (0.7242, 185)

## Read me HI

In [52]:
readmehiv2=pd.read_csv('.../readme_hi_resultsv2.csv')
readmehiv2 = readmehiv2.replace("na", np.nan)
readmehiv2.columns

Index(['Unnamed: 0', 'Domain', 'Sub-domain', 'Paragraph', 'Context',
       'Sentence', 'Rating', 'Transliteration', 'AYA_8b_vanilla', 'AYA_8b_avg',
       'AYA_8b_entropy', 'AYA_32b_vanilla', 'AYA_32b_avg', 'AYA_32b_entropy',
       'LLAMA_3b_vanilla', 'LLAMA_3b_avg', 'LLAMA_3b_entropy',
       'LLAMA_70b_vanilla', 'LLAMA_70b_avg', 'LLAMA_70b_entropy',
       'LLAMA_8b_vanilla', 'LLAMA_8b_avg', 'LLAMA_8b_entropy',
       'conf_llama_70b_vanilla', 'conf_llama_70b_avg',
       'conf_llama_70b_entropy', 'conf_llama_70b_verbal_conf',
       'conf_noscale_llama_70b_vanilla', 'conf_noscale_llama_70b_avg',
       'conf_noscale_llama_70b_entropy', 'conf_noscale_llama_70b_verbal_conf',
       'conf_noscale_llama_8b_vanilla', 'conf_noscale_llama_8b_avg',
       'conf_noscale_llama_8b_entropy', 'conf_noscale_llama_8b_verbal_conf',
       'conf_llama_8b_vanilla', 'conf_llama_8b_avg', 'conf_llama_8b_entropy',
       'conf_llama_8b_verbal_conf', 'conf_llama_3b_vanilla',
       'conf_llama_3b_avg', 'conf_llama_3b_entropy',
       'conf_llama_3b_verbal_conf', 'conf_noscale_llama_3b_vanilla',
       'conf_noscale_llama_3b_avg', 'conf_noscale_llama_3b_entropy',
       'conf_noscale_llama_3b_verbal_conf', 'conf_noscale_aya_32b_vanilla',
       'conf_noscale_aya_32b_avg', 'conf_noscale_aya_32b_entropy',
       'conf_noscale_aya_32b_verbal_conf', 'conf_aya_32b_vanilla',
       'conf_aya_32b_avg', 'conf_aya_32b_entropy', 'conf_aya_32b_verbal_conf',
       'noscale_aya_8b_vanilla', 'noscale_aya_8b_avg',
       'noscale_aya_8b_entropy', 'noscale_aya_32b_vanilla',
       'noscale_aya_32b_avg', 'noscale_aya_32b_entropy',
       'noscale_llama_8b_vanilla', 'noscale_llama_8b_avg',
       'noscale_llama_8b_entropy', 'noscale_llama_3b_vanilla',
       'noscale_llama_3b_avg', 'noscale_llama_3b_entropy',
       'noscale_llama_70b_vanilla', 'noscale_llama_70b_avg',
       'noscale_llama_70b_entropy', 'FKGL', 'LIX', 'ARI', 'RSRS_mBERT'],
      dtype='object')

In [53]:
ref_col = readmehiv2.columns[6]
for i in range(8, len(readmehiv2.columns)):  
    col = readmehiv2.columns[i]
    corr = readmehiv2[ref_col].astype(float).corr(readmehiv2[col].astype(float))
    if ('entropy' not in col) and ('verbal_conf' not in col):
        print(f"{i+1}: {col} -> correlation with {ref_col}: {corr:.4f}")

9: AYA_8b_vanilla -> correlation with Rating: 0.5836
10: AYA_8b_avg -> correlation with Rating: 0.6274
12: AYA_32b_vanilla -> correlation with Rating: 0.6567
13: AYA_32b_avg -> correlation with Rating: 0.7082
15: LLAMA_3b_vanilla -> correlation with Rating: 0.6257
16: LLAMA_3b_avg -> correlation with Rating: 0.7114
18: LLAMA_70b_vanilla -> correlation with Rating: 0.6509
19: LLAMA_70b_avg -> correlation with Rating: 0.7042
21: LLAMA_8b_vanilla -> correlation with Rating: 0.6291
22: LLAMA_8b_avg -> correlation with Rating: 0.7042
24: conf_llama_70b_vanilla -> correlation with Rating: 0.6255
25: conf_llama_70b_avg -> correlation with Rating: 0.6964
28: conf_noscale_llama_70b_vanilla -> correlation with Rating: 0.4826
29: conf_noscale_llama_70b_avg -> correlation with Rating: 0.6214
32: conf_noscale_llama_8b_vanilla -> correlation with Rating: 0.5483
33: conf_noscale_llama_8b_avg -> correlation with Rating: 0.5500
36: conf_llama_8b_vanilla -> correlation with Rating: 0.5297
37: conf_llama_8b_avg -> correlation with Rating: 0.6320
40: conf_llama_3b_vanilla -> correlation with Rating: 0.3880
41: conf_llama_3b_avg -> correlation with Rating: 0.4995
44: conf_noscale_llama_3b_vanilla -> correlation with Rating: 0.2782
45: conf_noscale_llama_3b_avg -> correlation with Rating: 0.3138
48: conf_noscale_aya_32b_vanilla -> correlation with Rating: 0.4726
49: conf_noscale_aya_32b_avg -> correlation with Rating: 0.5125
52: conf_aya_32b_vanilla -> correlation with Rating: 0.6583
53: conf_aya_32b_avg -> correlation with Rating: 0.7164
56: noscale_aya_8b_vanilla -> correlation with Rating: 0.4965
57: noscale_aya_8b_avg -> correlation with Rating: 0.5197
59: noscale_aya_32b_vanilla -> correlation with Rating: 0.5161
60: noscale_aya_32b_avg -> correlation with Rating: 0.5112
62: noscale_llama_8b_vanilla -> correlation with Rating: 0.5975
63: noscale_llama_8b_avg -> correlation with Rating: 0.6071
65: noscale_llama_3b_vanilla -> correlation with Rating: 0.3550
66: noscale_llama_3b_avg -> correlation with Rating: 0.3785
68: noscale_llama_70b_vanilla -> correlation with Rating: 0.6374
69: noscale_llama_70b_avg -> correlation with Rating: 0.7261
71: FKGL -> correlation with Rating: 0.4844
72: LIX -> correlation with Rating: 0.6306
73: ARI -> correlation with Rating: 0.6020
74: RSRS_mBERT -> correlation with Rating: 0.6950

In [54]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
readmehiv2 = readmehiv2.apply(pd.to_numeric, errors="coerce")
rf_string='LIX'
std_cols = [c for c in readmehiv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
readmehiv2[std_cols] = StandardScaler().fit_transform(readmehiv2[std_cols])
model='conf_aya_32b'
vconf_col=f'{model}_verbal_conf'
avg_col = f"{model}_avg"


verbal_avg_rf=((1 - readmehiv2[vconf_col]/10) * readmehiv2[rf_string]) + (readmehiv2[vconf_col]/10 * readmehiv2[avg_col])


rjk,n1=safe_corr_raw(verbal_avg_rf, readmehiv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmehiv2.iloc[:,47], readmehiv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,readmehiv2.iloc[:,47])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs LLM : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, readmehiv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmehiv2[rf_string], readmehiv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,readmehiv2[rf_string])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RF : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, readmehiv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmehiv2['RSRS_mBERT'], readmehiv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,readmehiv2['RSRS_mBERT'])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RSRS : t2:{res1[0]}, p:{res1[1]}')

0.7544038424189983 0.47260605226202806 0.5246155212034973
158
t_test: Vconf RF vs LLM : t2:5.362033080943747, p:2.936763603411663e-07
0.7544038424189983 0.6306099704291531 0.7313917114457203
162
t_test: Vconf RF vs RF : t2:3.257751961907913, p:0.0013730244512348833
0.7544038424189983 0.694958502771803 0.7544695023814001
162
t_test: Vconf RF vs RSRS : t2:1.6848657413495784, p:0.09397626960893612

In [55]:
readmehiv2 = readmehiv2.apply(pd.to_numeric, errors="coerce")
import numpy as np
rjk,n1=safe_corr_raw(readmehiv2.iloc[:,24], readmehiv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmehiv2.iloc[:,52], readmehiv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(readmehiv2.iloc[:,24],readmehiv2.iloc[:,52])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Aya32B vs Llama70B : t2:{res1[0]}, p:{res1[1]}')


rjk,n1=safe_corr_raw(readmehiv2.iloc[:,51], readmehiv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmehiv2.iloc[:,52], readmehiv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(readmehiv2.iloc[:,51],readmehiv2.iloc[:,52])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Expected Value vs Vnailla : t2:{res1[0]}, p:{res1[1]}')

0.696357557177378 0.7163903446711474 0.8094043220478606
163
t_test: Aya32B vs Llama70B : t2:-0.610214423699898, p:0.5425855089289975
0.6582553243895327 0.7163903446711474 0.9686956898090485
163
t_test: Expected Value vs Vnailla : t2:-4.304172998050383, p:2.9105091730707855e-05

In [56]:
import numpy as np
rjk,n1=safe_corr_raw(readmehiv2.iloc[:,48], readmehiv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmehiv2.iloc[:,52], readmehiv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(readmehiv2.iloc[:,48],readmehiv2.iloc[:,52])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Scale vs No scale : t2:{res1[0]}, p:{res1[1]}')

import numpy as np
rjk,n1=safe_corr_raw(readmehiv2.iloc[:,47], readmehiv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmehiv2.iloc[:,52], readmehiv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(readmehiv2.iloc[:,47],readmehiv2.iloc[:,52])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Expected and Scale v. Vanilla and no scale : t2:{res1[0]}, p:{res1[1]}')

0.512539340016238 0.7163903446711474 0.5604706667801989
159
t_test: Scale vs No scale : t2:-3.871976904888012, p:0.00015841860488241544
0.47260605226202806 0.7163903446711474 0.5150698951861594
159
t_test: Expected and Scale v. Vanilla and no scale : t2:-4.375755839643863, p:2.205526235843358e-05

In [57]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
readmehiv2 = readmehiv2.apply(pd.to_numeric, errors="coerce")
rf_string='LIX'
ref_col = readmehiv2.columns[6]
#readmehiv2['RSRS_mBERT']= StandardScaler().fit_transform(readmehiv2['RSRS_mBERT'])
# Step 1: Normalize entropy columns
entropy_cols = [c for c in readmehiv2.columns if c.endswith("_entropy")]
entropy_cols_minmax = [c + "_minmax" for c in entropy_cols]
readmehiv2[entropy_cols_minmax] = MinMaxScaler().fit_transform(readmehiv2[entropy_cols])

vconf_cols = [c for c in readmehiv2.columns if c.endswith("verbal_conf")]
vconf_cols_minmax = [c + "_minmax" for c in vconf_cols]
readmehiv2[vconf_cols_minmax] = MinMaxScaler().fit_transform(readmehiv2[vconf_cols])
readmehiv2[vconf_cols] = readmehiv2[vconf_cols]/10

std_cols = [c for c in readmehiv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
readmehiv2[std_cols] = StandardScaler().fit_transform(readmehiv2[std_cols])
suffixes = ["_avg", "_vanilla", "_entropy"]
models = set(
    c.rsplit("_", 1)[0]  # remove the last part after the final underscore
    for c in entropy_cols  # or any column list containing these suffixes
)
sorted_models = sorted(models, key=lambda x: x[::-1].lower())
for model in sorted_models:
    print(model)
    vanilla_col = f"{model}_vanilla"
    avg_col = f"{model}_avg"
    print(f'unweighted:\n AVG:{safe_corr(readmehiv2[avg_col], readmehiv2[ref_col])},Vanilla:{safe_corr(readmehiv2[vanilla_col], readmehiv2[ref_col])},RSRS:{safe_corr(readmehiv2["RSRS_mBERT"], readmehiv2[ref_col])},Readability Formula: {safe_corr(readmehiv2[rf_string], readmehiv2[ref_col])}')
    naive_avg_mBERT=readmehiv2[avg_col]+readmehiv2["RSRS_mBERT"]
    naive_vanilla_mBERT=readmehiv2[vanilla_col]+readmehiv2["RSRS_mBERT"]
    
    naive_avg_rf=readmehiv2[avg_col]+readmehiv2[rf_string]
    naive_vanilla_rf=readmehiv2[vanilla_col]+readmehiv2[rf_string]
    print(f'naive weightings: \n AVG mBERT:{safe_corr(naive_avg_mBERT, readmehiv2[ref_col])},Vanilla mBERT:{safe_corr(naive_vanilla_mBERT, readmehiv2[ref_col])}, AVG Readability Formula: {safe_corr(naive_avg_rf, readmehiv2[ref_col])}, Vanilla Readability Formula: {safe_corr(naive_vanilla_rf, readmehiv2[ref_col])}')
    entropy_col = f"{model}_entropy"
    entropy_col_minmax = f"{model}_entropy_minmax"
    if model.startswith('conf_'):
        vconf_col=f'{model}_verbal_conf'
        vconf_col_minmax = f"{model}_verbal_conf_minmax"
    
    #readmehiv2[f"{model}_weighted"] = (
    #    readmehiv2[entropy_col] * readmehiv2["RSRS_mBERT"] + 
    #    (1 - readmehiv2[entropy_col]) * (readmehiv2[[vanilla_col, avg_col]].mean(axis=1))
    #)
    entropy_avg_mBERT=(readmehiv2[entropy_col] * readmehiv2["RSRS_mBERT"]) + ((1 - readmehiv2[entropy_col]) * readmehiv2[avg_col])
    entropy_vanilla_mBERT=(readmehiv2[entropy_col] * readmehiv2["RSRS_mBERT"]) + ((1 - readmehiv2[entropy_col]) * readmehiv2[vanilla_col])
    entropy_minmax_avg_mBERT=(readmehiv2[entropy_col_minmax] * readmehiv2["RSRS_mBERT"]) + ((1 - readmehiv2[entropy_col_minmax]) * readmehiv2[avg_col])
    entropy_minmax_vanilla_mBERT=(readmehiv2[entropy_col_minmax] * readmehiv2["RSRS_mBERT"]) + ((1 - readmehiv2[entropy_col_minmax]) * readmehiv2[vanilla_col])
    
    entropy_avg_rf=(readmehiv2[entropy_col] * readmehiv2[rf_string]) + ((1 - readmehiv2[entropy_col]) * readmehiv2[avg_col])
    entropy_vanilla_rf=(readmehiv2[entropy_col] * readmehiv2[rf_string]) + ((1 - readmehiv2[entropy_col]) * readmehiv2[vanilla_col])
    entropy_minmax_avg_rf=(readmehiv2[entropy_col_minmax] * readmehiv2[rf_string]) + ((1 - readmehiv2[entropy_col_minmax]) * readmehiv2[avg_col])
    entropy_minmax_vanilla_rf=(readmehiv2[entropy_col_minmax] * readmehiv2[rf_string]) + ((1 - readmehiv2[entropy_col_minmax]) * readmehiv2[vanilla_col])
    print(f'entropy weightings:\n AVG mBERT:{safe_corr(entropy_avg_mBERT, readmehiv2[ref_col])},Vanilla mBERT:{safe_corr(entropy_vanilla_mBERT, readmehiv2[ref_col])},Avg mBERT minmax:{safe_corr(entropy_minmax_avg_mBERT, readmehiv2[ref_col])},Vanilla mBERT minmax:{safe_corr(entropy_minmax_vanilla_mBERT, readmehiv2[ref_col])},Avg Readability Formula: {safe_corr(entropy_avg_rf, readmehiv2[ref_col])},Vanilla Readability Formula: {safe_corr(entropy_vanilla_rf, readmehiv2[ref_col])},Average Readability Formula minmax:{safe_corr(entropy_minmax_avg_rf, readmehiv2[ref_col])}, Vanilla Readability Formula minmax:{safe_corr(entropy_minmax_vanilla_rf, readmehiv2[ref_col])}')
    if model.startswith('conf_'):
        verbal_avg_mBERT=((1 - readmehiv2[vconf_col]) * readmehiv2["RSRS_mBERT"]) + (readmehiv2[vconf_col] * readmehiv2[avg_col])
        verbal_vanilla_mBERT=((1 - readmehiv2[vconf_col]) * readmehiv2["RSRS_mBERT"]) + (readmehiv2[vconf_col] * readmehiv2[vanilla_col])
        verbal_minmax_avg_mBERT=((1 - readmehiv2[vconf_col_minmax]) * readmehiv2["RSRS_mBERT"]) + (readmehiv2[vconf_col_minmax] * readmehiv2[avg_col])
        verbal_minmax_vanilla_mBERT=((1 - readmehiv2[vconf_col_minmax]) * readmehiv2["RSRS_mBERT"]) + (readmehiv2[vconf_col_minmax] * readmehiv2[vanilla_col])
        
        verbal_avg_rf=((1 - readmehiv2[vconf_col]) * readmehiv2[rf_string]) + (readmehiv2[vconf_col] * readmehiv2[avg_col])
        verbal_vanilla_rf=((1 - readmehiv2[vconf_col]) * readmehiv2[rf_string]) + (readmehiv2[vconf_col] * readmehiv2[vanilla_col])
        verbal_minmax_avg_rf=((1 - readmehiv2[vconf_col_minmax]) * readmehiv2[rf_string]) + (readmehiv2[vconf_col_minmax] * readmehiv2[avg_col])
        verbal_minmax_vanilla_rf=((1 - readmehiv2[vconf_col_minmax]) * readmehiv2[rf_string]) + (readmehiv2[vconf_col_minmax] * readmehiv2[vanilla_col])
        print(f'verbal conf weightings:\n AVG mBERT:{safe_corr(verbal_avg_mBERT, readmehiv2[ref_col])},Vanilla mBERT:{safe_corr(verbal_vanilla_mBERT, readmehiv2[ref_col])},Avg mBERT minmax:{safe_corr(verbal_minmax_avg_mBERT, readmehiv2[ref_col])},Vanilla mBERT minmax:{safe_corr(verbal_minmax_vanilla_mBERT, readmehiv2[ref_col])},Avg Readability Formula: {safe_corr(verbal_avg_rf, readmehiv2[ref_col])},Vanilla Readability Formula:{safe_corr(verbal_vanilla_rf, readmehiv2[ref_col])},Average Readability Formula minmax:{safe_corr(verbal_minmax_avg_rf, readmehiv2[ref_col])},Vanilla Readability Formula minmax: {safe_corr(verbal_minmax_vanilla_rf, readmehiv2[ref_col])}','\n \n \n')
    else:
        print('\n \n \n')

LLAMA_70b
unweighted:
 AVG:(0.7042, 163),Vanilla:(0.6509, 163),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.7576, 163),Vanilla mBERT:(0.7391, 163), AVG Readability Formula: (0.7462, 163), Vanilla Readability Formula: (0.7228, 163)
entropy weightings:
 AVG mBERT:(0.7118, 163),Vanilla mBERT:(0.6627, 163),Avg mBERT minmax:(0.7333, 163),Vanilla mBERT minmax:(0.7137, 163),Avg Readability Formula: (0.712, 163),Vanilla Readability Formula: (0.662, 163),Average Readability Formula minmax:(0.7213, 163), Vanilla Readability Formula minmax:(0.6978, 163)




noscale_llama_70b
unweighted:
 AVG:(0.7261, 163),Vanilla:(0.6374, 163),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.7605, 163),Vanilla mBERT:(0.7366, 163), AVG Readability Formula: (0.752, 163), Vanilla Readability Formula: (0.7245, 163)
entropy weightings:
 AVG mBERT:(0.7382, 163),Vanilla mBERT:(0.6645, 163),Avg mBERT minmax:(0.7616, 163),Vanilla mBERT minmax:(0.7444, 163),Avg Readability Formula: (0.7399, 163),Vanilla Readability Formula: (0.6655, 163),Average Readability Formula minmax:(0.7512, 163), Vanilla Readability Formula minmax:(0.7306, 163)




conf_noscale_llama_70b
unweighted:
 AVG:(0.6214, 163),Vanilla:(0.4826, 163),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.7198, 163),Vanilla mBERT:(0.6668, 163), AVG Readability Formula: (0.7118, 163), Vanilla Readability Formula: (0.6583, 163)
entropy weightings:
 AVG mBERT:(0.6463, 163),Vanilla mBERT:(0.5238, 163),Avg mBERT minmax:(0.7296, 163),Vanilla mBERT minmax:(0.6974, 163),Avg Readability Formula: (0.6468, 163),Vanilla Readability Formula: (0.5239, 163),Average Readability Formula minmax:(0.715, 163), Vanilla Readability Formula minmax:(0.6831, 163)
verbal conf weightings:
 AVG mBERT:(0.6899, 163),Vanilla mBERT:(0.6018, 163),Avg mBERT minmax:(0.7102, 163),Vanilla mBERT minmax:(0.6477, 163),Avg Readability Formula: (0.6887, 163),Vanilla Readability Formula:(0.5988, 163),Average Readability Formula minmax:(0.6989, 163),Vanilla Readability Formula minmax: (0.6353, 163)



conf_llama_70b
unweighted:
 AVG:(0.6964, 163),Vanilla:(0.6255, 163),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.7558, 163),Vanilla mBERT:(0.727, 163), AVG Readability Formula: (0.7443, 163), Vanilla Readability Formula: (0.7177, 163)
entropy weightings:
 AVG mBERT:(0.7043, 163),Vanilla mBERT:(0.6411, 163),Avg mBERT minmax:(0.7242, 163),Vanilla mBERT minmax:(0.7042, 163),Avg Readability Formula: (0.7047, 163),Vanilla Readability Formula: (0.6419, 163),Average Readability Formula minmax:(0.7162, 163), Vanilla Readability Formula minmax:(0.697, 163)
verbal conf weightings:
 AVG mBERT:(0.7316, 163),Vanilla mBERT:(0.6879, 163),Avg mBERT minmax:(0.7214, 163),Vanilla mBERT minmax:(0.676, 163),Avg Readability Formula: (0.7338, 163),Vanilla Readability Formula:(0.6916, 163),Average Readability Formula minmax:(0.7242, 163),Vanilla Readability Formula minmax: (0.6799, 163)



AYA_32b
unweighted:
 AVG:(0.7082, 163),Vanilla:(0.6567, 163),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.7792, 163),Vanilla mBERT:(0.7572, 163), AVG Readability Formula: (0.757, 163), Vanilla Readability Formula: (0.7345, 163)
entropy weightings:
 AVG mBERT:(0.7147, 163),Vanilla mBERT:(0.6662, 163),Avg mBERT minmax:(0.7523, 163),Vanilla mBERT minmax:(0.7344, 163),Avg Readability Formula: (0.715, 163),Vanilla Readability Formula: (0.6663, 163),Average Readability Formula minmax:(0.7484, 163), Vanilla Readability Formula minmax:(0.7319, 163)




noscale_aya_32b
unweighted:
 AVG:(0.5112, 163),Vanilla:(0.5161, 163),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.7116, 163),Vanilla mBERT:(0.7202, 163), AVG Readability Formula: (0.6796, 163), Vanilla Readability Formula: (0.6859, 163)
entropy weightings:
 AVG mBERT:(0.531, 163),Vanilla mBERT:(0.5374, 163),Avg mBERT minmax:(0.6426, 163),Vanilla mBERT minmax:(0.651, 163),Avg Readability Formula: (0.5292, 163),Vanilla Readability Formula: (0.5352, 163),Average Readability Formula minmax:(0.6383, 163), Vanilla Readability Formula minmax:(0.6469, 163)




conf_noscale_aya_32b
unweighted:
 AVG:(0.5125, 159),Vanilla:(0.4726, 159),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.7042, 159),Vanilla mBERT:(0.6933, 159), AVG Readability Formula: (0.6726, 159), Vanilla Readability Formula: (0.66, 159)
entropy weightings:
 AVG mBERT:(0.5299, 159),Vanilla mBERT:(0.4948, 159),Avg mBERT minmax:(0.631, 159),Vanilla mBERT minmax:(0.6323, 159),Avg Readability Formula: (0.528, 159),Vanilla Readability Formula: (0.4927, 159),Average Readability Formula minmax:(0.6259, 159), Vanilla Readability Formula minmax:(0.6275, 159)
verbal conf weightings:
 AVG mBERT:(0.609, 159),Vanilla mBERT:(0.5808, 159),Avg mBERT minmax:(0.538, 159),Vanilla mBERT minmax:(0.5063, 159),Avg Readability Formula: (0.5979, 159),Vanilla Readability Formula:(0.5687, 159),Average Readability Formula minmax:(0.5315, 159),Vanilla Readability Formula minmax: (0.4986, 159)



conf_aya_32b
unweighted:
 AVG:(0.7164, 163),Vanilla:(0.6583, 163),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.7777, 163),Vanilla mBERT:(0.7613, 163), AVG Readability Formula: (0.7582, 163), Vanilla Readability Formula: (0.7356, 163)
entropy weightings:
 AVG mBERT:(0.7241, 163),Vanilla mBERT:(0.671, 163),Avg mBERT minmax:(0.7701, 163),Vanilla mBERT minmax:(0.7514, 163),Avg Readability Formula: (0.7235, 163),Vanilla Readability Formula: (0.669, 163),Average Readability Formula minmax:(0.7612, 163), Vanilla Readability Formula minmax:(0.7402, 163)
verbal conf weightings:
 AVG mBERT:(0.7586, 162),Vanilla mBERT:(0.7191, 162),Avg mBERT minmax:(0.774, 162),Vanilla mBERT minmax:(0.7618, 162),Avg Readability Formula: (0.7544, 162),Vanilla Readability Formula:(0.7111, 162),Average Readability Formula minmax:(0.7416, 162),Vanilla Readability Formula minmax: (0.7246, 162)



LLAMA_3b
unweighted:
 AVG:(0.7114, 163),Vanilla:(0.6257, 163),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.7762, 163),Vanilla mBERT:(0.7435, 163), AVG Readability Formula: (0.7608, 163), Vanilla Readability Formula: (0.7258, 163)
entropy weightings:
 AVG mBERT:(0.7305, 163),Vanilla mBERT:(0.6528, 163),Avg mBERT minmax:(0.7758, 163),Vanilla mBERT minmax:(0.729, 163),Avg Readability Formula: (0.7298, 163),Vanilla Readability Formula: (0.6512, 163),Average Readability Formula minmax:(0.7661, 163), Vanilla Readability Formula minmax:(0.7173, 163)




noscale_llama_3b
unweighted:
 AVG:(0.3785, 163),Vanilla:(0.355, 163),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.6307, 163),Vanilla mBERT:(0.631, 163), AVG Readability Formula: (0.6034, 163), Vanilla Readability Formula: (0.6026, 163)
entropy weightings:
 AVG mBERT:(0.4173, 163),Vanilla mBERT:(0.3948, 163),Avg mBERT minmax:(0.6582, 163),Vanilla mBERT minmax:(0.6451, 163),Avg Readability Formula: (0.4158, 163),Vanilla Readability Formula: (0.3928, 163),Average Readability Formula minmax:(0.6638, 163), Vanilla Readability Formula minmax:(0.6499, 163)




conf_noscale_llama_3b
unweighted:
 AVG:(0.3138, 162),Vanilla:(0.2782, 162),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.609, 162),Vanilla mBERT:(0.6007, 162), AVG Readability Formula: (0.5696, 162), Vanilla Readability Formula: (0.5618, 162)
entropy weightings:
 AVG mBERT:(0.3613, 162),Vanilla mBERT:(0.3275, 162),Avg mBERT minmax:(0.667, 162),Vanilla mBERT minmax:(0.6588, 162),Avg Readability Formula: (0.3574, 162),Vanilla Readability Formula: (0.3239, 162),Average Readability Formula minmax:(0.6474, 162), Vanilla Readability Formula minmax:(0.6417, 162)
verbal conf weightings:
 AVG mBERT:(0.4733, 162),Vanilla mBERT:(0.4525, 162),Avg mBERT minmax:(0.5495, 162),Vanilla mBERT minmax:(0.5474, 162),Avg Readability Formula: (0.4542, 162),Vanilla Readability Formula:(0.4338, 162),Average Readability Formula minmax:(0.5139, 162),Vanilla Readability Formula minmax: (0.5123, 162)



conf_llama_3b
unweighted:
 AVG:(0.4995, 163),Vanilla:(0.388, 163),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.7037, 163),Vanilla mBERT:(0.6588, 163), AVG Readability Formula: (0.6789, 163), Vanilla Readability Formula: (0.6161, 163)

entropy weightings:
 AVG mBERT:(0.5317, 163),Vanilla mBERT:(0.4315, 163),Avg mBERT minmax:(0.6617, 163),Vanilla mBERT minmax:(0.6298, 163),Avg Readability Formula: (0.5292, 163),Vanilla Readability Formula: (0.4258, 163),Average Readability Formula minmax:(0.6465, 163), Vanilla Readability Formula minmax:(0.6031, 163)
verbal conf weightings:
 AVG mBERT:(0.5899, 163),Vanilla mBERT:(0.5041, 163),Avg mBERT minmax:(0.648, 163),Vanilla mBERT minmax:(0.655, 163),Avg Readability Formula: (0.5818, 163),Vanilla Readability Formula:(0.4881, 163),Average Readability Formula minmax:(0.6153, 163),Vanilla Readability Formula minmax: (0.6143, 163)



LLAMA_8b
unweighted:
 AVG:(0.7042, 163),Vanilla:(0.6291, 163),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.7547, 163),Vanilla mBERT:(0.7283, 163), AVG Readability Formula: (0.7458, 163), Vanilla Readability Formula: (0.7156, 163)
entropy weightings:
 AVG mBERT:(0.7145, 163),Vanilla mBERT:(0.645, 163),Avg mBERT minmax:(0.7345, 163),Vanilla mBERT minmax:(0.7089, 163),Avg Readability Formula: (0.7157, 163),Vanilla Readability Formula: (0.6449, 163),Average Readability Formula minmax:(0.719, 163), Vanilla Readability Formula minmax:(0.6924, 163)




noscale_llama_8b
unweighted:
 AVG:(0.6071, 125),Vanilla:(0.5975, 125),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.739, 125),Vanilla mBERT:(0.7454, 125), AVG Readability Formula: (0.7075, 125), Vanilla Readability Formula: (0.7088, 125)
entropy weightings:
 AVG mBERT:(0.6334, 125),Vanilla mBERT:(0.6271, 125),Avg mBERT minmax:(0.7394, 125),Vanilla mBERT minmax:(0.7468, 125),Avg Readability Formula: (0.6319, 125),Vanilla Readability Formula: (0.6249, 125),Average Readability Formula minmax:(0.727, 125), Vanilla Readability Formula minmax:(0.7297, 125)




conf_noscale_llama_8b
unweighted:
 AVG:(0.55, 123),Vanilla:(0.5483, 123),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.7093, 123),Vanilla mBERT:(0.704, 123), AVG Readability Formula: (0.6736, 123), Vanilla Readability Formula: (0.6738, 123)
entropy weightings:
 AVG mBERT:(0.5727, 123),Vanilla mBERT:(0.5701, 123),Avg mBERT minmax:(0.6645, 123),Vanilla mBERT minmax:(0.6612, 123),Avg Readability Formula: (0.5688, 123),Vanilla Readability Formula: (0.5678, 123),Average Readability Formula minmax:(0.6334, 123), Vanilla Readability Formula minmax:(0.6351, 123)
verbal conf weightings:
 AVG mBERT:(0.6477, 123),Vanilla mBERT:(0.6447, 123),Avg mBERT minmax:(0.6853, 123),Vanilla mBERT minmax:(0.6824, 123),Avg Readability Formula: (0.6264, 123),Vanilla Readability Formula:(0.6263, 123),Average Readability Formula minmax:(0.6097, 123),Vanilla Readability Formula minmax: (0.6095, 123)



conf_llama_8b
unweighted:
 AVG:(0.632, 163),Vanilla:(0.5297, 163),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.7337, 163),Vanilla mBERT:(0.7043, 163), AVG Readability Formula: (0.7232, 163), Vanilla Readability Formula: (0.6917, 163)
entropy weightings:
 AVG mBERT:(0.6494, 163),Vanilla mBERT:(0.5574, 163),Avg mBERT minmax:(0.708, 163),Vanilla mBERT minmax:(0.686, 163),Avg Readability Formula: (0.6499, 163),Vanilla Readability Formula: (0.5569, 163),Average Readability Formula minmax:(0.7061, 163), Vanilla Readability Formula minmax:(0.6835, 163)
verbal conf weightings:
 AVG mBERT:(0.6841, 163),Vanilla mBERT:(0.6108, 163),Avg mBERT minmax:(0.7109, 163),Vanilla mBERT minmax:(0.6987, 163),Avg Readability Formula: (0.6837, 163),Vanilla Readability Formula:(0.6085, 163),Average Readability Formula minmax:(0.6619, 163),Vanilla Readability Formula minmax: (0.6466, 163)



AYA_8b
unweighted:
 AVG:(0.6274, 163),Vanilla:(0.5836, 163),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.7691, 163),Vanilla mBERT:(0.7584, 163), AVG Readability Formula: (0.7453, 163), Vanilla Readability Formula: (0.7278, 163)
entropy weightings:
 AVG mBERT:(0.6346, 163),Vanilla mBERT:(0.5935, 163),Avg mBERT minmax:(0.6943, 163),Vanilla mBERT minmax:(0.6855, 163),Avg Readability Formula: (0.6347, 163),Vanilla Readability Formula: (0.5926, 163),Average Readability Formula minmax:(0.6801, 163), Vanilla Readability Formula minmax:(0.6683, 163)




noscale_aya_8b
unweighted:
 AVG:(0.5197, 163),Vanilla:(0.4965, 163),RSRS:(0.695, 163),Readability Formula: (0.6306, 163)
naive weightings:
 AVG mBERT:(0.7126, 163),Vanilla mBERT:(0.7034, 163), AVG Readability Formula: (0.6869, 163), Vanilla Readability Formula: (0.6829, 163)
entropy weightings:
 AVG mBERT:(0.5544, 163),Vanilla mBERT:(0.5341, 163),Avg mBERT minmax:(0.7185, 163),Vanilla mBERT minmax:(0.7215, 163),Avg Readability Formula: (0.5537, 163),Vanilla Readability Formula: (0.5345, 163),Average Readability Formula minmax:(0.7192, 163), Vanilla Readability Formula minmax:(0.7258, 163)

## README AR

In [58]:
readmearv2=pd.read_csv('.../readme_ar_resultsv2.csv')
readmearv2 = readmearv2.replace("na", np.nan)
readmearv2.columns

Index(['Unnamed: 0', 'Domain', 'Sub-domain', 'Paragraph', 'Context',
       'Sentence', 'Rating', 'Transliteration', 'AYA_32b_vanilla',
       'AYA_32b_avg', 'AYA_32b_entropy', 'AYA_8b_vanilla', 'AYA_8b_avg',
       'AYA_8b_entropy', 'conf_noscale_aya_32b_vanilla',
       'conf_noscale_aya_32b_avg', 'conf_noscale_aya_32b_entropy',
       'conf_noscale_aya_32b_verbal_conf', 'conf_aya_32b_vanilla',
       'conf_aya_32b_avg', 'conf_aya_32b_entropy', 'conf_aya_32b_verbal_conf',
       'noscale_aya_32b_vanilla', 'noscale_aya_32b_avg',
       'noscale_aya_32b_entropy', 'noscale_aya_8b_vanilla',
       'noscale_aya_8b_avg', 'noscale_aya_8b_entropy', 'FKGL', 'osman', 'ARI',
       'RSRS_mBERT'],
      dtype='object')

In [59]:
ref_col = readmearv2.columns[6]
for i in range(8, len(readmearv2.columns)):  
    col = readmearv2.columns[i]
    corr = readmearv2[ref_col].astype(float).corr(readmearv2[col].astype(float))
    if ('entropy' not in col) and ('verbal_conf' not in col):
        print(f"{i+1}: {col} -> correlation with {ref_col}: {corr:.4f}")

9: AYA_32b_vanilla -> correlation with Rating: 0.6951
10: AYA_32b_avg -> correlation with Rating: 0.7196
12: AYA_8b_vanilla -> correlation with Rating: 0.6213
13: AYA_8b_avg -> correlation with Rating: 0.6445
15: conf_noscale_aya_32b_vanilla -> correlation with Rating: 0.5229
16: conf_noscale_aya_32b_avg -> correlation with Rating: 0.5445
19: conf_aya_32b_vanilla -> correlation with Rating: 0.6926
20: conf_aya_32b_avg -> correlation with Rating: 0.7216
23: noscale_aya_32b_vanilla -> correlation with Rating: 0.5259
24: noscale_aya_32b_avg -> correlation with Rating: 0.5256
26: noscale_aya_8b_vanilla -> correlation with Rating: 0.6292
27: noscale_aya_8b_avg -> correlation with Rating: 0.6388
29: FKGL -> correlation with Rating: 0.4377
30: osman -> correlation with Rating: 0.5964
31: ARI -> correlation with Rating: 0.5498
32: RSRS_mBERT -> correlation with Rating: 0.4405

In [60]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
readmearv2 = readmearv2.apply(pd.to_numeric, errors="coerce")
rf_string='osman'
std_cols = [c for c in readmearv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
readmearv2[std_cols] = StandardScaler().fit_transform(readmearv2[std_cols])
model='conf_aya_32b'
vconf_col=f'{model}_verbal_conf'
avg_col = f"{model}_avg"


verbal_avg_rf=((1 - readmearv2[vconf_col]/10) * readmearv2[rf_string]) + (readmearv2[vconf_col]/10 * readmearv2[avg_col])


rjk,n1=safe_corr_raw(verbal_avg_rf, readmearv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmearv2.iloc[:,14], readmearv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,readmearv2.iloc[:,14])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs LLM : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, readmearv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmearv2[rf_string], readmearv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,readmearv2[rf_string])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RF : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, readmearv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmearv2['RSRS_mBERT'], readmearv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,readmearv2['RSRS_mBERT'])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RSRS : t2:{res1[0]}, p:{res1[1]}')

0.7565834385450698 0.5229356994796694 0.49519840029891327
200
t_test: Vconf RF vs LLM : t2:4.96004584302079, p:1.5182988197803837e-06
0.7565834385450698 0.5963954658097425 0.6672244927222585
206
t_test: Vconf RF vs RF : t2:4.278704444547753, p:2.895086507703759e-05
0.7565834385450698 0.4405105481881346 0.5146126874575542
206
t_test: Vconf RF vs RSRS : t2:6.801314678485381, p:1.1363798790853252e-10

In [61]:
import numpy as np
readmearv2 = readmearv2.apply(pd.to_numeric, errors="coerce")
rjk,n1=safe_corr_raw(readmearv2.iloc[:,15], readmearv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmearv2.iloc[:,19], readmearv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(readmearv2.iloc[:,19],readmearv2.iloc[:,15])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Scale vs No scale : t2:{res1[0]}, p:{res1[1]}')

import numpy as np
rjk,n1=safe_corr_raw(readmearv2.iloc[:,14], readmearv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmearv2.iloc[:,19], readmearv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(readmearv2.iloc[:,19],readmearv2.iloc[:,14])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Both Scale and Expected Value vs. No scale and Vanilla : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(readmearv2.iloc[:,18], readmearv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmearv2.iloc[:,19], readmearv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(readmearv2.iloc[:,18],readmearv2.iloc[:,19])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Expected Val vs. Vanilla : t2:{res1[0]}, p:{res1[1]}')

0.5444816090784707 0.7215783444087658 0.5197908008700673
200
t_test: Scale vs No scale : t2:-3.699307895364302, p:0.0002803772648281022
0.5229356994796694 0.7215783444087658 0.4881246521902476
200
t_test: Both Scale and Expected Value vs. No scale and Vanilla : t2:-3.9989734655876403, p:8.99326080807672e-05
0.6925527682528831 0.7215783444087658 0.9765864999695295
206
t_test: Expected Val vs. Vanilla : t2:-2.7693627264844496, p:0.006137162198218027

In [62]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
readmearv2 = readmearv2.apply(pd.to_numeric, errors="coerce")
rf_string='osman'
ref_col = readmearv2.columns[6]
#readmearv2['RSRS_mBERT']= StandardScaler().fit_transform(readmearv2['RSRS_mBERT'])
# Step 1: Normalize entropy columns
entropy_cols = [c for c in readmearv2.columns if c.endswith("_entropy")]
entropy_cols_minmax = [c + "_minmax" for c in entropy_cols]
readmearv2[entropy_cols_minmax] = MinMaxScaler().fit_transform(readmearv2[entropy_cols])

vconf_cols = [c for c in readmearv2.columns if c.endswith("verbal_conf")]
vconf_cols_minmax = [c + "_minmax" for c in vconf_cols]
readmearv2[vconf_cols_minmax] = MinMaxScaler().fit_transform(readmearv2[vconf_cols])
readmearv2[vconf_cols] = readmearv2[vconf_cols]/10

std_cols = [c for c in readmearv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
readmearv2[std_cols] = StandardScaler().fit_transform(readmearv2[std_cols])
suffixes = ["_avg", "_vanilla", "_entropy"]
models = set(
    c.rsplit("_", 1)[0]  # remove the last part after the final underscore
    for c in entropy_cols  # or any column list containing these suffixes
)
sorted_models = sorted(models, key=lambda x: x[::-1].lower())
for model in sorted_models:
    print(model)
    vanilla_col = f"{model}_vanilla"
    avg_col = f"{model}_avg"
    print(f'unweighted:\n AVG:{safe_corr(readmearv2[avg_col], readmearv2[ref_col])},Vanilla:{safe_corr(readmearv2[vanilla_col], readmearv2[ref_col])},RSRS:{safe_corr(readmearv2["RSRS_mBERT"], readmearv2[ref_col])},Readability Formula: {safe_corr(readmearv2[rf_string], readmearv2[ref_col])}')
    naive_avg_mBERT=readmearv2[avg_col]+readmearv2["RSRS_mBERT"]
    naive_vanilla_mBERT=readmearv2[vanilla_col]+readmearv2["RSRS_mBERT"]
    
    naive_avg_rf=readmearv2[avg_col]+readmearv2[rf_string]
    naive_vanilla_rf=readmearv2[vanilla_col]+readmearv2[rf_string]
    print(f'naive weightings: \n AVG mBERT:{safe_corr(naive_avg_mBERT, readmearv2[ref_col])},Vanilla mBERT:{safe_corr(naive_vanilla_mBERT, readmearv2[ref_col])}, AVG Readability Formula: {safe_corr(naive_avg_rf, readmearv2[ref_col])}, Vanilla Readability Formula: {safe_corr(naive_vanilla_rf, readmearv2[ref_col])}')
    entropy_col = f"{model}_entropy"
    entropy_col_minmax = f"{model}_entropy_minmax"
    if model.startswith('conf_'):
        vconf_col=f'{model}_verbal_conf'
        vconf_col_minmax = f"{model}_verbal_conf_minmax"
    
    #readmearv2[f"{model}_weighted"] = (
    #    readmearv2[entropy_col] * readmearv2["RSRS_mBERT"] + 
    #    (1 - readmearv2[entropy_col]) * (readmearv2[[vanilla_col, avg_col]].mean(axis=1))
    #)
    entropy_avg_mBERT=(readmearv2[entropy_col] * readmearv2["RSRS_mBERT"]) + ((1 - readmearv2[entropy_col]) * readmearv2[avg_col])
    entropy_vanilla_mBERT=(readmearv2[entropy_col] * readmearv2["RSRS_mBERT"]) + ((1 - readmearv2[entropy_col]) * readmearv2[vanilla_col])
    entropy_minmax_avg_mBERT=(readmearv2[entropy_col_minmax] * readmearv2["RSRS_mBERT"]) + ((1 - readmearv2[entropy_col_minmax]) * readmearv2[avg_col])
    entropy_minmax_vanilla_mBERT=(readmearv2[entropy_col_minmax] * readmearv2["RSRS_mBERT"]) + ((1 - readmearv2[entropy_col_minmax]) * readmearv2[vanilla_col])
    
    entropy_avg_rf=(readmearv2[entropy_col] * readmearv2[rf_string]) + ((1 - readmearv2[entropy_col]) * readmearv2[avg_col])
    entropy_vanilla_rf=(readmearv2[entropy_col] * readmearv2[rf_string]) + ((1 - readmearv2[entropy_col]) * readmearv2[vanilla_col])
    entropy_minmax_avg_rf=(readmearv2[entropy_col_minmax] * readmearv2[rf_string]) + ((1 - readmearv2[entropy_col_minmax]) * readmearv2[avg_col])
    entropy_minmax_vanilla_rf=(readmearv2[entropy_col_minmax] * readmearv2[rf_string]) + ((1 - readmearv2[entropy_col_minmax]) * readmearv2[vanilla_col])
    print(f'entropy weightings:\n AVG mBERT:{safe_corr(entropy_avg_mBERT, readmearv2[ref_col])},Vanilla mBERT:{safe_corr(entropy_vanilla_mBERT, readmearv2[ref_col])},Avg mBERT minmax:{safe_corr(entropy_minmax_avg_mBERT, readmearv2[ref_col])},Vanilla mBERT minmax:{safe_corr(entropy_minmax_vanilla_mBERT, readmearv2[ref_col])},Avg Readability Formula: {safe_corr(entropy_avg_rf, readmearv2[ref_col])},Vanilla Readability Formula: {safe_corr(entropy_vanilla_rf, readmearv2[ref_col])},Average Readability Formula minmax:{safe_corr(entropy_minmax_avg_rf, readmearv2[ref_col])}, Vanilla Readability Formula minmax:{safe_corr(entropy_minmax_vanilla_rf, readmearv2[ref_col])}')
    if model.startswith('conf_'):
        verbal_avg_mBERT=((1 - readmearv2[vconf_col]) * readmearv2["RSRS_mBERT"]) + (readmearv2[vconf_col] * readmearv2[avg_col])
        verbal_vanilla_mBERT=((1 - readmearv2[vconf_col]) * readmearv2["RSRS_mBERT"]) + (readmearv2[vconf_col] * readmearv2[vanilla_col])
        verbal_minmax_avg_mBERT=((1 - readmearv2[vconf_col_minmax]) * readmearv2["RSRS_mBERT"]) + (readmearv2[vconf_col_minmax] * readmearv2[avg_col])
        verbal_minmax_vanilla_mBERT=((1 - readmearv2[vconf_col_minmax]) * readmearv2["RSRS_mBERT"]) + (readmearv2[vconf_col_minmax] * readmearv2[vanilla_col])
        
        verbal_avg_rf=((1 - readmearv2[vconf_col]) * readmearv2[rf_string]) + (readmearv2[vconf_col] * readmearv2[avg_col])
        verbal_vanilla_rf=((1 - readmearv2[vconf_col]) * readmearv2[rf_string]) + (readmearv2[vconf_col] * readmearv2[vanilla_col])
        verbal_minmax_avg_rf=((1 - readmearv2[vconf_col_minmax]) * readmearv2[rf_string]) + (readmearv2[vconf_col_minmax] * readmearv2[avg_col])
        verbal_minmax_vanilla_rf=((1 - readmearv2[vconf_col_minmax]) * readmearv2[rf_string]) + (readmearv2[vconf_col_minmax] * readmearv2[vanilla_col])
        print(f'verbal conf weightings:\n AVG mBERT:{safe_corr(verbal_avg_mBERT, readmearv2[ref_col])},Vanilla mBERT:{safe_corr(verbal_vanilla_mBERT, readmearv2[ref_col])},Avg mBERT minmax:{safe_corr(verbal_minmax_avg_mBERT, readmearv2[ref_col])},Vanilla mBERT minmax:{safe_corr(verbal_minmax_vanilla_mBERT, readmearv2[ref_col])},Avg Readability Formula: {safe_corr(verbal_avg_rf, readmearv2[ref_col])},Vanilla Readability Formula:{safe_corr(verbal_vanilla_rf, readmearv2[ref_col])},Average Readability Formula minmax:{safe_corr(verbal_minmax_avg_rf, readmearv2[ref_col])},Vanilla Readability Formula minmax: {safe_corr(verbal_minmax_vanilla_rf, readmearv2[ref_col])}','\n \n \n')
    else:
        print('\n \n \n')

AYA_32b
unweighted:
 AVG:(0.7196, 206),Vanilla:(0.6951, 206),RSRS:(0.4405, 206),Readability Formula: (0.5964, 206)
naive weightings:
 AVG mBERT:(0.6947, 206),Vanilla mBERT:(0.6836, 206), AVG Readability Formula: (0.7597, 206), Vanilla Readability Formula: (0.7483, 206)
entropy weightings:
 AVG mBERT:(0.723, 206),Vanilla mBERT:(0.7001, 206),Avg mBERT minmax:(0.6821, 206),Vanilla mBERT minmax:(0.6714, 206),Avg Readability Formula: (0.7259, 206),Vanilla Readability Formula: (0.7027, 206),Average Readability Formula minmax:(0.7573, 206), Vanilla Readability Formula minmax:(0.7485, 206)




noscale_aya_32b
unweighted:
 AVG:(0.5256, 206),Vanilla:(0.5259, 206),RSRS:(0.4405, 206),Readability Formula: (0.5964, 206)
naive weightings:
 AVG mBERT:(0.6031, 206),Vanilla mBERT:(0.6073, 206), AVG Readability Formula: (0.6865, 206), Vanilla Readability Formula: (0.6831, 206)
entropy weightings:
 AVG mBERT:(0.5323, 206),Vanilla mBERT:(0.5337, 206),Avg mBERT minmax:(0.5385, 206),Vanilla mBERT minmax:(0.5385, 206),Avg Readability Formula: (0.5378, 206),Vanilla Readability Formula: (0.5376, 206),Average Readability Formula minmax:(0.5953, 206), Vanilla Readability Formula minmax:(0.5935, 206)




conf_noscale_aya_32b
unweighted:
 AVG:(0.5445, 200),Vanilla:(0.5229, 200),RSRS:(0.4405, 206),Readability Formula: (0.5964, 206)
naive weightings:
 AVG mBERT:(0.6355, 200),Vanilla mBERT:(0.6231, 200), AVG Readability Formula: (0.6828, 200), Vanilla Readability Formula: (0.6745, 200)
entropy weightings:
 AVG mBERT:(0.5542, 200),Vanilla mBERT:(0.5336, 200),Avg mBERT minmax:(0.5955, 200),Vanilla mBERT minmax:(0.584, 200),Avg Readability Formula: (0.558, 200),Vanilla Readability Formula: (0.5381, 200),Average Readability Formula minmax:(0.645, 200), Vanilla Readability Formula minmax:(0.6378, 200)
verbal conf weightings:
 AVG mBERT:(0.603, 200),Vanilla mBERT:(0.5847, 200),Avg mBERT minmax:(0.536, 200),Vanilla mBERT minmax:(0.5195, 200),Avg Readability Formula: (0.6201, 200),Vanilla Readability Formula:(0.604, 200),Average Readability Formula minmax:(0.5402, 200),Vanilla Readability Formula minmax: (0.5244, 200)



conf_aya_32b
unweighted:
 AVG:(0.7216, 206),Vanilla:(0.6926, 206),RSRS:(0.4405, 206),Readability Formula: (0.5964, 206)
naive weightings:
 AVG mBERT:(0.6795, 206),Vanilla mBERT:(0.6692, 206), AVG Readability Formula: (0.7589, 206), Vanilla Readability Formula: (0.7487, 206)
entropy weightings:
 AVG mBERT:(0.7218, 206),Vanilla mBERT:(0.6946, 206),Avg mBERT minmax:(0.6815, 206),Vanilla mBERT minmax:(0.6752, 206),Avg Readability Formula: (0.7268, 206),Vanilla Readability Formula: (0.7003, 206),Average Readability Formula minmax:(0.7511, 206), Vanilla Readability Formula minmax:(0.7408, 206)
verbal conf weightings:
 AVG mBERT:(0.7225, 206),Vanilla mBERT:(0.7018, 206),Avg mBERT minmax:(0.6129, 206),Vanilla mBERT minmax:(0.6053, 206),Avg Readability Formula: (0.7566, 206),Vanilla Readability Formula:(0.7364, 206),Average Readability Formula minmax:(0.7178, 206),Vanilla Readability Formula minmax: (0.7088, 206)



AYA_8b
unweighted:
 AVG:(0.6445, 206),Vanilla:(0.6213, 206),RSRS:(0.4405, 206),Readability Formula: (0.5964, 206)
naive weightings:
 AVG mBERT:(0.6231, 206),Vanilla mBERT:(0.6151, 206), AVG Readability Formula: (0.7367, 206), Vanilla Readability Formula: (0.7255, 206)
entropy weightings:
 AVG mBERT:(0.647, 206),Vanilla mBERT:(0.6257, 206),Avg mBERT minmax:(0.6297, 206),Vanilla mBERT minmax:(0.6265, 206),Avg Readability Formula: (0.6483, 206),Vanilla Readability Formula: (0.6264, 206),Average Readability Formula minmax:(0.6541, 206), Vanilla Readability Formula minmax:(0.6514, 206)




noscale_aya_8b
unweighted:
 AVG:(0.6388, 206),Vanilla:(0.6292, 206),RSRS:(0.4405, 206),Readability Formula: (0.5964, 206)
naive weightings:
 AVG mBERT:(0.6358, 206),Vanilla mBERT:(0.6381, 206), AVG Readability Formula: (0.7369, 206), Vanilla Readability Formula: (0.7321, 206)
entropy weightings:
 AVG mBERT:(0.645, 206),Vanilla mBERT:(0.6387, 206),Avg mBERT minmax:(0.5905, 206),Vanilla mBERT minmax:(0.5902, 206),Avg Readability Formula: (0.6599, 206),Vanilla Readability Formula: (0.652, 206),Average Readability Formula minmax:(0.7158, 206), Vanilla Readability Formula minmax:(0.717, 206)

## READ ME RU

In [63]:
readmeruv2=pd.read_csv('.../readme_ru_resultsv2.csv')
readmeruv2 = readmeruv2.replace("na", np.nan)
readmeruv2.columns

Index(['Unnamed: 0', 'Domain', 'Sub-domain', 'Paragraph', 'Context',
       'Sentence', 'Rating', 'Transliteration', 'AYA_8b_vanilla', 'AYA_8b_avg',
       'AYA_8b_entropy', 'AYA_32b_vanilla', 'AYA_32b_avg', 'AYA_32b_entropy',
       'conf_aya_32b_vanilla', 'conf_aya_32b_avg', 'conf_aya_32b_entropy',
       'conf_aya_32b_verbal_conf', 'conf_noscale_aya_32b_vanilla',
       'conf_noscale_aya_32b_avg', 'conf_noscale_aya_32b_entropy',
       'conf_noscale_aya_32b_verbal_conf', 'noscale_aya_8b_vanilla',
       'noscale_aya_8b_avg', 'noscale_aya_8b_entropy',
       'noscale_aya_32b_vanilla', 'noscale_aya_32b_avg',
       'noscale_aya_32b_entropy', 'FKGL', 'FRE', 'ARI', 'RSRS_mBERT'],
      dtype='object')

In [64]:
ref_col = readmeruv2.columns[6]
for i in range(8, len(readmeruv2.columns)):  
    col = readmeruv2.columns[i]
    corr = readmeruv2[ref_col].astype(float).corr(readmeruv2[col].astype(float))
    if ('entropy' not in col) and ('verbal_conf' not in col):
        print(f"{i+1}: {col} -> correlation with {ref_col}: {corr:.4f}")

9: AYA_8b_vanilla -> correlation with Rating: 0.3975
10: AYA_8b_avg -> correlation with Rating: 0.4225
12: AYA_32b_vanilla -> correlation with Rating: 0.7219
13: AYA_32b_avg -> correlation with Rating: 0.7410
15: conf_aya_32b_vanilla -> correlation with Rating: 0.7353
16: conf_aya_32b_avg -> correlation with Rating: 0.7648
19: conf_noscale_aya_32b_vanilla -> correlation with Rating: 0.3925
20: conf_noscale_aya_32b_avg -> correlation with Rating: 0.4262
23: noscale_aya_8b_vanilla -> correlation with Rating: 0.5647
24: noscale_aya_8b_avg -> correlation with Rating: 0.5577
26: noscale_aya_32b_vanilla -> correlation with Rating: 0.4012
27: noscale_aya_32b_avg -> correlation with Rating: 0.4103
29: FKGL -> correlation with Rating: 0.5556
30: FRE -> correlation with Rating: -0.5368
31: ARI -> correlation with Rating: 0.6389
32: RSRS_mBERT -> correlation with Rating: 0.6941

In [65]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
readmeruv2 = readmeruv2.apply(pd.to_numeric, errors="coerce")
rf_string='ARI'
std_cols = [c for c in readmeruv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
readmeruv2[std_cols] = StandardScaler().fit_transform(readmeruv2[std_cols])
model='conf_aya_32b'
vconf_col=f'{model}_verbal_conf'
avg_col = f"{model}_avg"


verbal_avg_rf=((1 - readmeruv2[vconf_col]/10) * readmeruv2[rf_string]) + (readmeruv2[vconf_col]/10 * readmeruv2[avg_col])


rjk,n1=safe_corr_raw(verbal_avg_rf, readmeruv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmeruv2.iloc[:,18], readmeruv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,readmeruv2.iloc[:,18])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs LLM : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, readmeruv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmeruv2[rf_string], readmeruv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,readmeruv2[rf_string])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RF : t2:{res1[0]}, p:{res1[1]}')

rjk,n1=safe_corr_raw(verbal_avg_rf, readmeruv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmeruv2['RSRS_mBERT'], readmeruv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(verbal_avg_rf,readmeruv2['RSRS_mBERT'])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Vconf RF vs RSRS : t2:{res1[0]}, p:{res1[1]}')

0.8033734798583819 0.39250822996524776 0.43479982229975256
178
t_test: Vconf RF vs LLM : t2:8.168795267688461, p:5.995204332975845e-14
0.8033734798583819 0.6388513565936157 0.6757747286563135
178
t_test: Vconf RF vs RF : t2:4.544052964591268, p:1.02558957233434e-05
0.8033734798583819 0.6940888249708337 0.7423659193559496
178
t_test: Vconf RF vs RSRS : t2:3.434417646475854, p:0.0007414592338916837

In [66]:
import numpy as np
readmeruv2 = readmeruv2.apply(pd.to_numeric, errors="coerce")
rjk,n1=safe_corr_raw(readmeruv2.iloc[:,15], readmeruv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmeruv2.iloc[:,19], readmeruv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(readmeruv2.iloc[:,19],readmeruv2.iloc[:,15])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Scale vs No scale : t2:{res1[0]}, p:{res1[1]}')


import numpy as np
rjk,n1=safe_corr_raw(readmeruv2.iloc[:,15], readmeruv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmeruv2.iloc[:,18], readmeruv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(readmeruv2.iloc[:,18],readmeruv2.iloc[:,15])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Scale vs No scale and Expected Value v Vanilla: t2:{res1[0]}, p:{res1[1]}')


import numpy as np
rjk,n1=safe_corr_raw(readmeruv2.iloc[:,15], readmeruv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rjh,n2=safe_corr_raw(readmeruv2.iloc[:,14], readmeruv2.iloc[:,6])
## Change from avg_col if LLM is not outperforming RSRS or readability formula
rkh,n3=safe_corr_raw(readmeruv2.iloc[:,14],readmeruv2.iloc[:,15])
print(rjk,rjh,rkh)
res1=calc_williams_t(rjk,rjh,rkh,min(n1,n2,n3))
print(min(n1,n2,n3))
print(f't_test: Expected Value v Vanilla : t2:{res1[0]}, p:{res1[1]}')

0.7648030182340159 0.42623219662972905 0.4979217314816531
178
t_test: Scale vs No scale : t2:6.724140385364956, p:2.406810306609941e-10
0.7648030182340159 0.39250822996524776 0.4512687142133388
178
t_test: Scale vs No scale and Expected Value v Vanilla: t2:7.034788244584993, p:4.327627145528368e-11
0.7648030182340159 0.7352612103999872 0.9830429811923144
178
t_test: Expected Value v Vanilla : t2:3.326569439780023, p:0.001071464629646135

In [67]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
readmeruv2 = readmeruv2.apply(pd.to_numeric, errors="coerce")
rf_string='ARI'
ref_col = readmeruv2.columns[6]
#readmeruv2['RSRS_mBERT']= StandardScaler().fit_transform(readmeruv2['RSRS_mBERT'])
# Step 1: Normalize entropy columns
entropy_cols = [c for c in readmeruv2.columns if c.endswith("_entropy")]
entropy_cols_minmax = [c + "_minmax" for c in entropy_cols]
readmeruv2[entropy_cols_minmax] = MinMaxScaler().fit_transform(readmeruv2[entropy_cols])

vconf_cols = [c for c in readmeruv2.columns if c.endswith("verbal_conf")]
vconf_cols_minmax = [c + "_minmax" for c in vconf_cols]
readmeruv2[vconf_cols_minmax] = MinMaxScaler().fit_transform(readmeruv2[vconf_cols])
readmeruv2[vconf_cols] = readmeruv2[vconf_cols]/10

std_cols = [c for c in readmeruv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
readmeruv2[std_cols] = StandardScaler().fit_transform(readmeruv2[std_cols])
suffixes = ["_avg", "_vanilla", "_entropy"]
models = set(
    c.rsplit("_", 1)[0]  # remove the last part after the final underscore
    for c in entropy_cols  # or any column list containing these suffixes
)
sorted_models = sorted(models, key=lambda x: x[::-1].lower())
for model in sorted_models:
    print(model)
    vanilla_col = f"{model}_vanilla"
    avg_col = f"{model}_avg"
    print(f'unweighted:\n AVG:{safe_corr(readmeruv2[avg_col], readmeruv2[ref_col])},Vanilla:{safe_corr(readmeruv2[vanilla_col], readmeruv2[ref_col])},RSRS:{safe_corr(readmeruv2["RSRS_mBERT"], readmeruv2[ref_col])},Readability Formula: {safe_corr(readmeruv2[rf_string], readmeruv2[ref_col])}')
    naive_avg_mBERT=readmeruv2[avg_col]+readmeruv2["RSRS_mBERT"]
    naive_vanilla_mBERT=readmeruv2[vanilla_col]+readmeruv2["RSRS_mBERT"]
    
    naive_avg_rf=readmeruv2[avg_col]+readmeruv2[rf_string]
    naive_vanilla_rf=readmeruv2[vanilla_col]+readmeruv2[rf_string]
    print(f'naive weightings: \n AVG mBERT:{safe_corr(naive_avg_mBERT, readmeruv2[ref_col])},Vanilla mBERT:{safe_corr(naive_vanilla_mBERT, readmeruv2[ref_col])}, AVG Readability Formula: {safe_corr(naive_avg_rf, readmeruv2[ref_col])}, Vanilla Readability Formula: {safe_corr(naive_vanilla_rf, readmeruv2[ref_col])}')
    entropy_col = f"{model}_entropy"
    entropy_col_minmax = f"{model}_entropy_minmax"
    if model.startswith('conf_'):
        vconf_col=f'{model}_verbal_conf'
        vconf_col_minmax = f"{model}_verbal_conf_minmax"
    
    #readmeruv2[f"{model}_weighted"] = (
    #    readmeruv2[entropy_col] * readmeruv2["RSRS_mBERT"] + 
    #    (1 - readmeruv2[entropy_col]) * (readmeruv2[[vanilla_col, avg_col]].mean(axis=1))
    #)
    entropy_avg_mBERT=(readmeruv2[entropy_col] * readmeruv2["RSRS_mBERT"]) + ((1 - readmeruv2[entropy_col]) * readmeruv2[avg_col])
    entropy_vanilla_mBERT=(readmeruv2[entropy_col] * readmeruv2["RSRS_mBERT"]) + ((1 - readmeruv2[entropy_col]) * readmeruv2[vanilla_col])
    entropy_minmax_avg_mBERT=(readmeruv2[entropy_col_minmax] * readmeruv2["RSRS_mBERT"]) + ((1 - readmeruv2[entropy_col_minmax]) * readmeruv2[avg_col])
    entropy_minmax_vanilla_mBERT=(readmeruv2[entropy_col_minmax] * readmeruv2["RSRS_mBERT"]) + ((1 - readmeruv2[entropy_col_minmax]) * readmeruv2[vanilla_col])
    
    entropy_avg_rf=(readmeruv2[entropy_col] * readmeruv2[rf_string]) + ((1 - readmeruv2[entropy_col]) * readmeruv2[avg_col])
    entropy_vanilla_rf=(readmeruv2[entropy_col] * readmeruv2[rf_string]) + ((1 - readmeruv2[entropy_col]) * readmeruv2[vanilla_col])
    entropy_minmax_avg_rf=(readmeruv2[entropy_col_minmax] * readmeruv2[rf_string]) + ((1 - readmeruv2[entropy_col_minmax]) * readmeruv2[avg_col])
    entropy_minmax_vanilla_rf=(readmeruv2[entropy_col_minmax] * readmeruv2[rf_string]) + ((1 - readmeruv2[entropy_col_minmax]) * readmeruv2[vanilla_col])
    print(f'entropy weightings:\n AVG mBERT:{safe_corr(entropy_avg_mBERT, readmeruv2[ref_col])},Vanilla mBERT:{safe_corr(entropy_vanilla_mBERT, readmeruv2[ref_col])},Avg mBERT minmax:{safe_corr(entropy_minmax_avg_mBERT, readmeruv2[ref_col])},Vanilla mBERT minmax:{safe_corr(entropy_minmax_vanilla_mBERT, readmeruv2[ref_col])},Avg Readability Formula: {safe_corr(entropy_avg_rf, readmeruv2[ref_col])},Vanilla Readability Formula: {safe_corr(entropy_vanilla_rf, readmeruv2[ref_col])},Average Readability Formula minmax:{safe_corr(entropy_minmax_avg_rf, readmeruv2[ref_col])}, Vanilla Readability Formula minmax:{safe_corr(entropy_minmax_vanilla_rf, readmeruv2[ref_col])}')
    if model.startswith('conf_'):
        verbal_avg_mBERT=((1 - readmeruv2[vconf_col]) * readmeruv2["RSRS_mBERT"]) + (readmeruv2[vconf_col] * readmeruv2[avg_col])
        verbal_vanilla_mBERT=((1 - readmeruv2[vconf_col]) * readmeruv2["RSRS_mBERT"]) + (readmeruv2[vconf_col] * readmeruv2[vanilla_col])
        verbal_minmax_avg_mBERT=((1 - readmeruv2[vconf_col_minmax]) * readmeruv2["RSRS_mBERT"]) + (readmeruv2[vconf_col_minmax] * readmeruv2[avg_col])
        verbal_minmax_vanilla_mBERT=((1 - readmeruv2[vconf_col_minmax]) * readmeruv2["RSRS_mBERT"]) + (readmeruv2[vconf_col_minmax] * readmeruv2[vanilla_col])
        
        verbal_avg_rf=((1 - readmeruv2[vconf_col]) * readmeruv2[rf_string]) + (readmeruv2[vconf_col] * readmeruv2[avg_col])
        verbal_vanilla_rf=((1 - readmeruv2[vconf_col]) * readmeruv2[rf_string]) + (readmeruv2[vconf_col] * readmeruv2[vanilla_col])
        verbal_minmax_avg_rf=((1 - readmeruv2[vconf_col_minmax]) * readmeruv2[rf_string]) + (readmeruv2[vconf_col_minmax] * readmeruv2[avg_col])
        verbal_minmax_vanilla_rf=((1 - readmeruv2[vconf_col_minmax]) * readmeruv2[rf_string]) + (readmeruv2[vconf_col_minmax] * readmeruv2[vanilla_col])
        print(f'verbal conf weightings:\n AVG mBERT:{safe_corr(verbal_avg_mBERT, readmeruv2[ref_col])},Vanilla mBERT:{safe_corr(verbal_vanilla_mBERT, readmeruv2[ref_col])},Avg mBERT minmax:{safe_corr(verbal_minmax_avg_mBERT, readmeruv2[ref_col])},Vanilla mBERT minmax:{safe_corr(verbal_minmax_vanilla_mBERT, readmeruv2[ref_col])},Avg Readability Formula: {safe_corr(verbal_avg_rf, readmeruv2[ref_col])},Vanilla Readability Formula:{safe_corr(verbal_vanilla_rf, readmeruv2[ref_col])},Average Readability Formula minmax:{safe_corr(verbal_minmax_avg_rf, readmeruv2[ref_col])},Vanilla Readability Formula minmax: {safe_corr(verbal_minmax_vanilla_rf, readmeruv2[ref_col])}','\n \n \n')
    else:
        print('\n \n \n')

AYA_32b
unweighted:
 AVG:(0.741, 178),Vanilla:(0.7219, 178),RSRS:(0.6941, 178),Readability Formula: (0.6389, 178)
naive weightings:
 AVG mBERT:(0.7932, 178),Vanilla mBERT:(0.788, 178), AVG Readability Formula: (0.8013, 178), Vanilla Readability Formula: (0.7919, 178)
entropy weightings:
 AVG mBERT:(0.7451, 178),Vanilla mBERT:(0.7276, 178),Avg mBERT minmax:(0.7642, 178),Vanilla mBERT minmax:(0.7622, 178),Avg Readability Formula: (0.7457, 178),Vanilla Readability Formula: (0.7276, 178),Average Readability Formula minmax:(0.7669, 178), Vanilla Readability Formula minmax:(0.7643, 178)




noscale_aya_32b
unweighted:
 AVG:(0.4103, 178),Vanilla:(0.4012, 178),RSRS:(0.6941, 178),Readability Formula: (0.6389, 178)
naive weightings:
 AVG mBERT:(0.666, 178),Vanilla mBERT:(0.6632, 178), AVG Readability Formula: (0.68, 178), Vanilla Readability Formula: (0.6787, 178)
entropy weightings:
 AVG mBERT:(0.423, 178),Vanilla mBERT:(0.4145, 178),Avg mBERT minmax:(0.5077, 178),Vanilla mBERT minmax:(0.5031, 178),Avg Readability Formula: (0.4248, 178),Vanilla Readability Formula: (0.4166, 178),Average Readability Formula minmax:(0.5045, 178), Vanilla Readability Formula minmax:(0.5006, 178)




conf_noscale_aya_32b
unweighted:
 AVG:(0.4262, 178),Vanilla:(0.3925, 178),RSRS:(0.6941, 178),Readability Formula: (0.6389, 178)
naive weightings:
 AVG mBERT:(0.6703, 178),Vanilla mBERT:(0.6578, 178), AVG Readability Formula: (0.6861, 178), Vanilla Readability Formula: (0.6693, 178)
entropy weightings:
 AVG mBERT:(0.4396, 178),Vanilla mBERT:(0.4083, 178),Avg mBERT minmax:(0.5319, 178),Vanilla mBERT minmax:(0.522, 178),Avg Readability Formula: (0.4399, 178),Vanilla Readability Formula: (0.4082, 178),Average Readability Formula minmax:(0.5244, 178), Vanilla Readability Formula minmax:(0.5117, 178)
verbal conf weightings:
 AVG mBERT:(0.5382, 178),Vanilla mBERT:(0.5121, 178),Avg mBERT minmax:(0.6439, 178),Vanilla mBERT minmax:(0.6337, 178),Avg Readability Formula: (0.5458, 178),Vanilla Readability Formula:(0.5174, 178),Average Readability Formula minmax:(0.6334, 178),Vanilla Readability Formula minmax: (0.6205, 178)



conf_aya_32b
unweighted:
 AVG:(0.7648, 178),Vanilla:(0.7353, 178),RSRS:(0.6941, 178),Readability Formula: (0.6389, 178)
naive weightings:
 AVG mBERT:(0.797, 178),Vanilla mBERT:(0.7874, 178), AVG Readability Formula: (0.806, 178), Vanilla Readability Formula: (0.7952, 178)
entropy weightings:
 AVG mBERT:(0.7684, 178),Vanilla mBERT:(0.7412, 178),Avg mBERT minmax:(0.7783, 178),Vanilla mBERT minmax:(0.7728, 178),Avg Readability Formula: (0.7694, 178),Vanilla Readability Formula: (0.742, 178),Average Readability Formula minmax:(0.7854, 178), Vanilla Readability Formula minmax:(0.78, 178)
verbal conf weightings:
 AVG mBERT:(0.792, 178),Vanilla mBERT:(0.771, 178),Avg mBERT minmax:(0.7719, 178),Vanilla mBERT minmax:(0.7619, 178),Avg Readability Formula: (0.8034, 178),Vanilla Readability Formula:(0.7814, 178),Average Readability Formula minmax:(0.7709, 178),Vanilla Readability Formula minmax: (0.7597, 178)



AYA_8b
unweighted:
 AVG:(0.4225, 178),Vanilla:(0.3975, 178),RSRS:(0.6941, 178),Readability Formula: (0.6389, 178)
naive weightings:
 AVG mBERT:(0.6796, 178),Vanilla mBERT:(0.6731, 178), AVG Readability Formula: (0.6836, 178), Vanilla Readability Formula: (0.6741, 178)
entropy weightings:
 AVG mBERT:(0.429, 178),Vanilla mBERT:(0.4051, 178),Avg mBERT minmax:(0.5102, 178),Vanilla mBERT minmax:(0.5003, 178),Avg Readability Formula: (0.428, 178),Vanilla Readability Formula: (0.4038, 178),Average Readability Formula minmax:(0.4732, 178), Vanilla Readability Formula minmax:(0.4621, 178)




noscale_aya_8b
unweighted:
 AVG:(0.5577, 178),Vanilla:(0.5647, 178),RSRS:(0.6941, 178),Readability Formula: (0.6389, 178)
naive weightings:
 AVG mBERT:(0.7238, 178),Vanilla mBERT:(0.7232, 178), AVG Readability Formula: (0.7321, 178), Vanilla Readability Formula: (0.7288, 178)
entropy weightings:
 AVG mBERT:(0.5801, 178),Vanilla mBERT:(0.5858, 178),Avg mBERT minmax:(0.7089, 178),Vanilla mBERT minmax:(0.7095, 178),Avg Readability Formula: (0.5839, 178),Vanilla Readability Formula: (0.5896, 178),Average Readability Formula minmax:(0.7236, 178), Vanilla Readability Formula minmax:(0.7234, 178)

## Asset

In [98]:
import pandas as pd
import numpy as np
assetv2=pd.read_csv('.../assetv2.csv')
#assetv2 = assetv2.replace("na", np.nan)
assetv2.columns

Index(['Unnamed: 0', 'ID', 'first_wins', 's', 'phi_vanilla', 'phi_avg',
       'phi_entropy', 'gemma_27b_vanilla', 'gemma_27b_avg',
       'gemma_27b_entropy', 'gemma_2b_vanilla', 'gemma_2b_avg',
       'gemma_2b_entropy', 'gemma_9b_vanilla', 'gemma_9b_avg',
       'gemma_9b_entropy', 'llama_3b_vanilla', 'llama_3b_avg',
       'llama_3b_entropy', 'llama_8b_vanilla', 'llama_8b_avg',
       'llama_8b_entropy', 'llama_70b_vanilla', 'llama_70b_avg',
       'llama_70b_entropy', 'aya_32b_vanilla', 'aya_32b_avg',
       'aya_32b_entropy', 'aya_8b_vanilla', 'aya_8b_avg', 'aya_8b_entropy',
       'mixtral_vanilla', 'mixtral_avg', 'mixtral_entropy', 'conf_phi_vanilla',
       'conf_phi_avg', 'conf_phi_entropy', 'conf_phi_verbal_conf',
       'conf_llama_3b_vanilla', 'conf_llama_3b_avg', 'conf_llama_3b_entropy',
       'conf_llama_3b_verbal_conf', 'conf_llama_8b_vanilla',
       'conf_llama_8b_avg', 'conf_llama_8b_entropy',
       'conf_llama_8b_verbal_conf', 'conf_llama_70b_vanilla',
       'conf_llama_70b_avg', 'conf_llama_70b_entropy',
       'conf_llama_70b_verbal_conf', 'conf_gemma_27b_vanilla',
       'conf_gemma_27b_avg', 'conf_gemma_27b_entropy',
       'conf_gemma_27b_verbal_conf', 'conf_gemma_2b_vanilla',
       'conf_gemma_2b_avg', 'conf_gemma_2b_entropy',
       'conf_gemma_2b_verbal_conf', 'conf_gemma_9b_vanilla',
       'conf_gemma_9b_avg', 'conf_gemma_9b_entropy',
       'conf_gemma_9b_verbal_conf', 'conf_aya_32b_vanilla', 'conf_aya_32b_avg',
       'conf_aya_32b_entropy', 'conf_aya_32b_verbal_conf',
       'conf_mixtral_vanilla', 'conf_mixtral_avg', 'conf_mixtral_entropy',
       'conf_mixtral_verbal_conf', 'FKGL', 'ARI', 'RSRS_mBERT'],
      dtype='object')

In [99]:
df1=assetv2[:485]
df2=assetv2[485:].reset_index(drop=True)
len(df1),len(df2)

(485, 485)

In [103]:
for i in range(4, len(assetv2.columns)):  
    col = assetv2.columns[i]
    acc=(((df1[col]<df2[col])&(df2.first_wins==1)).sum()+((df1[col]>df2[col])&(df2.first_wins==2)).sum())/len(df1)
    if ('entropy' not in col) and ('verbal_conf' not in col):
        print(f"{i+1}: {col} -> correlation with {ref_col}: {acc:.4f}")

5: phi_vanilla -> correlation with Rating: 0.3505
6: phi_avg -> correlation with Rating: 0.6742
8: gemma_27b_vanilla -> correlation with Rating: 0.4268
9: gemma_27b_avg -> correlation with Rating: 0.6907
11: gemma_2b_vanilla -> correlation with Rating: 0.4309
12: gemma_2b_avg -> correlation with Rating: 0.6474
14: gemma_9b_vanilla -> correlation with Rating: 0.4825
15: gemma_9b_avg -> correlation with Rating: 0.6619
17: llama_3b_vanilla -> correlation with Rating: 0.3381
18: llama_3b_avg -> correlation with Rating: 0.6330
20: llama_8b_vanilla -> correlation with Rating: 0.4268
21: llama_8b_avg -> correlation with Rating: 0.6660
23: llama_70b_vanilla -> correlation with Rating: 0.2887
24: llama_70b_avg -> correlation with Rating: 0.5608
26: aya_32b_vanilla -> correlation with Rating: 0.3856
27: aya_32b_avg -> correlation with Rating: 0.6680
29: aya_8b_vanilla -> correlation with Rating: 0.3381
30: aya_8b_avg -> correlation with Rating: 0.6639
32: mixtral_vanilla -> correlation with Rating: 0.4351
33: mixtral_avg -> correlation with Rating: 0.6289
35: conf_phi_vanilla -> correlation with Rating: 0.3423
36: conf_phi_avg -> correlation with Rating: 0.6454
39: conf_llama_3b_vanilla -> correlation with Rating: 0.3299
40: conf_llama_3b_avg -> correlation with Rating: 0.6124
43: conf_llama_8b_vanilla -> correlation with Rating: 0.3773
44: conf_llama_8b_avg -> correlation with Rating: 0.6701
47: conf_llama_70b_vanilla -> correlation with Rating: 0.3237
48: conf_llama_70b_avg -> correlation with Rating: 0.5546
51: conf_gemma_27b_vanilla -> correlation with Rating: 0.4722
52: conf_gemma_27b_avg -> correlation with Rating: 0.6763
55: conf_gemma_2b_vanilla -> correlation with Rating: 0.4082
56: conf_gemma_2b_avg -> correlation with Rating: 0.6598
59: conf_gemma_9b_vanilla -> correlation with Rating: 0.4536
60: conf_gemma_9b_avg -> correlation with Rating: 0.6474
63: conf_aya_32b_vanilla -> correlation with Rating: 0.4103
64: conf_aya_32b_avg -> correlation with Rating: 0.6763
67: conf_mixtral_vanilla -> correlation with Rating: 0.4041
68: conf_mixtral_avg -> correlation with Rating: 0.6206
71: FKGL -> correlation with Rating: 0.5258
72: ARI -> correlation with Rating: 0.5567
73: RSRS_mBERT -> correlation with Rating: 0.5608

In [104]:
assetv2 = assetv2.apply(pd.to_numeric, errors="coerce")
rf_string='ARI'
model='conf_llama_70b'
vconf_cols = [c for c in assetv2.columns if c.endswith("verbal_conf")]
assetv2[vconf_cols] = assetv2[vconf_cols]/10

std_cols = [c for c in assetv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
assetv2[std_cols] = StandardScaler().fit_transform(assetv2[std_cols])

avg_col = f"{model}_avg"
vconf_col=f'{model}_verbal_conf'
df1=assetv2[:485]
df2=assetv2[485:].reset_index(drop=True)


verbal_avg_rf_df1=((1 - df1[vconf_col]) * df1[rf_string]) + (df1[vconf_col] * df1[avg_col])
verbal_avg_rf_df2=((1 - df2[vconf_col]) * df2[rf_string]) + (df2[vconf_col] * df2[avg_col])





preds_a=((verbal_avg_rf_df1<verbal_avg_rf_df2)&(df2.first_wins==1)) | ((verbal_avg_rf_df1>verbal_avg_rf_df2)&(df2.first_wins==2))
##change to second best model if it is not LLM
preds_b=((df1.iloc[:,46]<df2.iloc[:,46])&(df2.first_wins==1)) | ((df1.iloc[:,46]>df2.iloc[:,46])&(df2.first_wins==2))

print(preds_a.sum()/len(preds_a),preds_b.sum()/len(preds_a))

print(((preds_a==True)&(preds_b==False)).sum(),((preds_a==False)&(preds_b==True)).sum())
b=((preds_a==True)&(preds_b==False)).sum()
c=((preds_a==False)&(preds_b==True)).sum()
print(f'p_value for difference LAURAE and LLM: {mcnemar(int(b),int(c),True)}')



preds_a=((verbal_avg_rf_df1<verbal_avg_rf_df2)&(df2.first_wins==1)) | ((verbal_avg_rf_df1>verbal_avg_rf_df2)&(df2.first_wins==2))
##change to second best model if it is not LLM
preds_b=((df1[rf_string]<df2[rf_string])&(df2.first_wins==1)) | ((df1[rf_string]>df2[rf_string])&(df2.first_wins==2))

print(preds_a.sum()/len(preds_a),preds_b.sum()/len(preds_a))

print(((preds_a==True)&(preds_b==False)).sum(),((preds_a==False)&(preds_b==True)).sum())
b=((preds_a==True)&(preds_b==False)).sum()
c=((preds_a==False)&(preds_b==True)).sum()
print(f'p_value for difference LAURAE and RF: {mcnemar(int(b),int(c),True)}')


preds_a=((verbal_avg_rf_df1<verbal_avg_rf_df2)&(df2.first_wins==1)) | ((verbal_avg_rf_df1>verbal_avg_rf_df2)&(df2.first_wins==2))
##change to second best model if it is not LLM
preds_b=((df1['RSRS_mBERT']<df2['RSRS_mBERT'])&(df2.first_wins==1)) | ((df1['RSRS_mBERT']>df2['RSRS_mBERT'])&(df2.first_wins==2))

print(preds_a.sum()/len(preds_a),preds_b.sum()/len(preds_a))

print(((preds_a==True)&(preds_b==False)).sum(),((preds_a==False)&(preds_b==True)).sum())
b=((preds_a==True)&(preds_b==False)).sum()
c=((preds_a==False)&(preds_b==True)).sum()
print(f'p_value for difference LAURAE and RSRS: {mcnemar(int(b),int(c),True)}')

0.6288659793814433 0.3237113402061856
148 0
p_value for difference LAURAE and LLM: 1.2937906295836791e-33
0.6288659793814433 0.5567010309278351
64 29
p_value for difference LAURAE and RF: 0.00042246757669391993
0.6288659793814433 0.5608247422680412
71 38
p_value for difference LAURAE and RSRS: 0.0021763789422183954

In [105]:
preds_a=((df1.iloc[:,46]<df2.iloc[:,46])&(df2.first_wins==1)) | ((df1.iloc[:,46]>df2.iloc[:,46])&(df2.first_wins==2))
##change to second best model if it is not LLM
preds_b=((df1.iloc[:,47]<df2.iloc[:,47])&(df2.first_wins==1)) | ((df1.iloc[:,47]>df2.iloc[:,47])&(df2.first_wins==2))

print(preds_a.sum()/len(preds_a),preds_b.sum()/len(preds_a))

print(((preds_a==True)&(preds_b==False)).sum(),((preds_a==False)&(preds_b==True)).sum())
b=((preds_a==True)&(preds_b==False)).sum()
c=((preds_a==False)&(preds_b==True)).sum()
print(f'p_value for difference (Expected v Vanilla): {mcnemar(int(b),int(c),True)}')

0.3237113402061856 0.554639175257732
0 112
p_value for difference (Expected v Vanilla): 9.755036475112228e-26

In [113]:
import pandas as pd
import numpy as np
assetv2=pd.read_csv('.../assetv2.csv')
#assetv2 = assetv2.replace("na", np.nan)
assetv2.columns

from sklearn.preprocessing import MinMaxScaler, StandardScaler
assetv2 = assetv2.apply(pd.to_numeric, errors="coerce")
rf_string='ARI'
#readmeruv2['RSRS_mBERT']= StandardScaler().fit_transform(readmeruv2['RSRS_mBERT'])
# Step 1: Normalize entropy columns
entropy_cols = [c for c in assetv2.columns if c.endswith("_entropy")]
entropy_cols_minmax = [c + "_minmax" for c in entropy_cols]
assetv2[entropy_cols_minmax] = MinMaxScaler().fit_transform(assetv2[entropy_cols])

vconf_cols = [c for c in assetv2.columns if c.endswith("verbal_conf")]
vconf_cols_minmax = [c + "_minmax" for c in vconf_cols]
assetv2[vconf_cols_minmax] = MinMaxScaler().fit_transform(assetv2[vconf_cols])
assetv2[vconf_cols] = assetv2[vconf_cols]/10

std_cols = [c for c in assetv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
assetv2[std_cols] = StandardScaler().fit_transform(assetv2[std_cols])
suffixes = ["_avg", "_vanilla", "_entropy"]
models = set(
    c.rsplit("_", 1)[0]  # remove the last part after the final underscore
    for c in entropy_cols  # or any column list containing these suffixes
)

df1=assetv2[:485]
df2=assetv2[485:].reset_index(drop=True)
sorted_models = sorted(models, key=lambda x: x[::-1].lower())
for model in sorted_models:
    #if model!='conf_llama_70b':
    #    continue
    print(model)
    vanilla_col = f"{model}_vanilla"
    avg_col = f"{model}_avg"
    print(f'unweighted: \n Avg: {(((df1[avg_col]<df2[avg_col])&(df2.first_wins==1)).sum()+((df1[avg_col]>df2[avg_col])&(df2.first_wins==2)).sum())/len(df1)},Vanilla: {(((df1[vanilla_col]<df2[vanilla_col])&(df2.first_wins==1)).sum()+((df1[vanilla_col]>df2[vanilla_col])&(df2.first_wins==2)).sum())/len(df1)}, mBERT: {(((df1["RSRS_mBERT"]<df2["RSRS_mBERT"])&(df2.first_wins==1)).sum()+((df1["RSRS_mBERT"]>df2["RSRS_mBERT"])&(df2.first_wins==2)).sum())/len(df1)}, readability formula: {(((df1[rf_string]<df2[rf_string])&(df2.first_wins==1)).sum()+((df1[rf_string]>df2[rf_string])&(df2.first_wins==2)).sum())/len(df1)}')
    naive_avg_mBERT_df1=df1[avg_col]+df1["RSRS_mBERT"]
    naive_vanilla_mBERT_df1=df1[vanilla_col]+df1["RSRS_mBERT"]
    naive_avg_rf_df1=df1[avg_col]+df1[rf_string]
    naive_vanilla_rf_df1=df1[vanilla_col]+df1[rf_string]
    
    naive_avg_mBERT_df2=df2[avg_col]+df2["RSRS_mBERT"]
    naive_vanilla_mBERT_df2=df2[vanilla_col]+df2["RSRS_mBERT"]
    naive_avg_rf_df2=df2[avg_col]+df2[rf_string]
    naive_vanilla_rf_df2=df2[vanilla_col]+df2[rf_string]
    print(f'naive weightings:\n Avg mBERT: {(((naive_avg_mBERT_df1<naive_avg_mBERT_df2)&(df2.first_wins==1)).sum()+((naive_avg_mBERT_df1>naive_avg_mBERT_df2)&(df2.first_wins==2)).sum())/len(df1)}, Vanilla mBERT:{(((naive_vanilla_mBERT_df1<naive_vanilla_mBERT_df2)&(df2.first_wins==1)).sum()+((naive_vanilla_mBERT_df1>naive_vanilla_mBERT_df2)&(df2.first_wins==2)).sum())/len(df1)}, Avg Readability Formula: {(((naive_avg_rf_df1<naive_avg_rf_df2)&(df2.first_wins==1)).sum()+((naive_avg_rf_df1>naive_avg_rf_df2)&(df2.first_wins==2)).sum())/len(df1)}, Vanilla Readability Formula:{(((naive_vanilla_rf_df1<naive_vanilla_rf_df2)&(df2.first_wins==1)).sum()+((naive_vanilla_rf_df1>naive_vanilla_rf_df2)&(df2.first_wins==2)).sum())/len(df1)}')
    entropy_col = f"{model}_entropy"
    entropy_col_minmax = f"{model}_entropy_minmax"
    
    if model.startswith('conf_'):
        vconf_col=f'{model}_verbal_conf'
        vconf_col_minmax = f"{model}_verbal_conf_minmax"
    

    entropy_avg_rf_df1=(df1[entropy_col] * df1[rf_string]) + ((1 - df1[entropy_col]) * df1[avg_col])
    entropy_vanilla_rf_df1=(df1[entropy_col] * df1[rf_string]) + ((1 - df1[entropy_col]) * df1[vanilla_col])
    entropy_avg_rf_df2=(df2[entropy_col] * df2[rf_string]) + ((1 - df2[entropy_col]) * df2[avg_col])
    entropy_vanilla_rf_df2=(df2[entropy_col] * df2[rf_string]) + ((1 - df2[entropy_col]) * df2[vanilla_col])
    
    entropy_minmax_avg_rf_df1=(df1[entropy_col_minmax] * df1[rf_string]) + ((1 - df1[entropy_col_minmax]) * df1[avg_col])
    entropy_minmax_vanilla_rf_df1=(df1[entropy_col_minmax] * df1[rf_string]) + ((1 - df1[entropy_col_minmax]) * df1[vanilla_col])
    entropy_minmax_avg_rf_df2=(df2[entropy_col_minmax] * df2[rf_string]) + ((1 - df2[entropy_col_minmax]) * df2[avg_col])
    entropy_minmax_vanilla_rf_df2=(df2[entropy_col_minmax] * df2[rf_string]) + ((1 - df2[entropy_col_minmax]) * df2[vanilla_col])
    
    
    
    
    
    
    print(f'entropy weightings: \n Avg mBERT{(((entropy_avg_mBERT_df1<entropy_avg_mBERT_df2)&(df2.first_wins==1)).sum()+((entropy_avg_mBERT_df1>entropy_avg_mBERT_df2)&(df2.first_wins==2)).sum())/len(df1)}, Vanilla mBERT: {(((entropy_vanilla_mBERT_df1<entropy_vanilla_mBERT_df2)&(df2.first_wins==1)).sum()+((entropy_vanilla_mBERT_df1>entropy_vanilla_mBERT_df2)&(df2.first_wins==2)).sum())/len(df1)}, Avg minmax mBERT: {(((entropy_minmax_avg_mBERT_df1<entropy_minmax_avg_mBERT_df2)&(df2.first_wins==1)).sum()+((entropy_minmax_avg_mBERT_df1>entropy_minmax_avg_mBERT_df2)&(df2.first_wins==2)).sum())/len(df1)}, Vanilla minmax mBERT: {(((entropy_minmax_vanilla_mBERT_df1<entropy_minmax_vanilla_mBERT_df2)&(df2.first_wins==1)).sum()+((entropy_minmax_vanilla_mBERT_df1>entropy_minmax_vanilla_mBERT_df2)&(df2.first_wins==2)).sum())/len(df1)},Avg rf{(((entropy_avg_rf_df1<entropy_avg_rf_df2)&(df2.first_wins==1)).sum()+((entropy_avg_rf_df1>entropy_avg_rf_df2)&(df2.first_wins==2)).sum())/len(df1)}, Vanilla rf: {(((entropy_vanilla_rf_df1<entropy_vanilla_rf_df2)&(df2.first_wins==1)).sum()+((entropy_vanilla_rf_df1>entropy_vanilla_rf_df2)&(df2.first_wins==2)).sum())/len(df1)}, Avg minmax rf{(((entropy_minmax_avg_rf_df1<entropy_minmax_avg_rf_df2)&(df2.first_wins==1)).sum()+((entropy_minmax_avg_rf_df1>entropy_minmax_avg_rf_df2)&(df2.first_wins==2)).sum())/len(df1)}, Vanilla minmax rf: {(((entropy_minmax_vanilla_rf_df1<entropy_minmax_vanilla_rf_df2)&(df2.first_wins==1)).sum()+((entropy_minmax_vanilla_rf_df1>entropy_minmax_vanilla_rf_df2)&(df2.first_wins==2)).sum())/len(df1)}')
    if model.startswith('conf_'):       
        verbal_avg_rf_df1=((1 - df1[vconf_col]) * df1[rf_string]) + (df1[vconf_col] * df1[avg_col])
        verbal_avg_rf_df2=((1 - df2[vconf_col]) * df2[rf_string]) + (df2[vconf_col] * df2[avg_col])
        verbal_vanilla_rf_df1=((1 - df1[vconf_col]) * df1[rf_string]) + (df1[vconf_col] * df1[vanilla_col])
        verbal_vanilla_rf_df2=((1 - df2[vconf_col]) * df2[rf_string]) + (df2[vconf_col] * df2[vanilla_col])
        
        verbal_minmax_avg_rf_df1=((1 - df1[vconf_col_minmax]) * df1[rf_string]) + (df1[vconf_col_minmax] * df1[avg_col])
        verbal_minmax_vanilla_rf_df1=((1 - df1[vconf_col_minmax]) * df1[rf_string]) + (df1[vconf_col_minmax] * df1[vanilla_col])
        verbal_minmax_avg_rf_df2=((1 - df2[vconf_col_minmax]) * df2[rf_string]) + (df2[vconf_col_minmax] * df2[avg_col])
        verbal_minmax_vanilla_rf_df2=((1 - df2[vconf_col_minmax]) * df2[rf_string]) + (df2[vconf_col_minmax] * df2[vanilla_col])
        print((((verbal_avg_rf_df1<verbal_avg_rf_df2)&(df2.first_wins==1)).sum()+((verbal_avg_rf_df1>verbal_avg_rf_df2)&(df2.first_wins==2)).sum())/len(df1))
        print(f'verbal weightings: \n Avg mBERT{(((verbal_avg_mBERT_df1<verbal_avg_mBERT_df2)&(df2.first_wins==1)).sum()+((verbal_avg_mBERT_df1>verbal_avg_mBERT_df2)&(df2.first_wins==2)).sum())/len(df1)}, Vanilla mBERT: {(((verbal_vanilla_mBERT_df1<verbal_vanilla_mBERT_df2)&(df2.first_wins==1)).sum()+((verbal_vanilla_mBERT_df1>verbal_vanilla_mBERT_df2)&(df2.first_wins==2)).sum())/len(df1)}, Avg minmax mBERT: {(((verbal_minmax_avg_mBERT_df1<verbal_minmax_avg_mBERT_df2)&(df2.first_wins==1)).sum()+((verbal_minmax_avg_mBERT_df1>verbal_minmax_avg_mBERT_df2)&(df2.first_wins==2)).sum())/len(df1)}, Vanilla minmax mBERT: {(((verbal_minmax_vanilla_mBERT_df1<verbal_minmax_vanilla_mBERT_df2)&(df2.first_wins==1)).sum()+((verbal_minmax_vanilla_mBERT_df1>verbal_minmax_vanilla_mBERT_df2)&(df2.first_wins==2)).sum())/len(df1)},Avg rf{(((verbal_avg_rf_df1<verbal_avg_rf_df2)&(df2.first_wins==1)).sum()+((verbal_avg_rf_df1>verbal_avg_rf_df2)&(df2.first_wins==2)).sum())/len(df1)}, Vanilla rf: {(((verbal_vanilla_rf_df1<verbal_vanilla_rf_df2)&(df2.first_wins==1)).sum()+((verbal_vanilla_rf_df1>verbal_vanilla_rf_df2)&(df2.first_wins==2)).sum())/len(df1)}, Avg minmax rf{(((verbal_minmax_avg_rf_df1<verbal_minmax_avg_rf_df2)&(df2.first_wins==1)).sum()+((verbal_minmax_avg_rf_df1>verbal_minmax_avg_rf_df2)&(df2.first_wins==2)).sum())/len(df1)}, Vanilla minmax rf: {(((verbal_minmax_vanilla_rf_df1<verbal_minmax_vanilla_rf_df2)&(df2.first_wins==1)).sum()+((verbal_minmax_vanilla_rf_df1>verbal_minmax_vanilla_rf_df2)&(df2.first_wins==2)).sum())/len(df1)}')
    else:
        print('\n')

llama_70b
unweighted:
 Avg: 0.5608247422680412,Vanilla: 0.28865979381443296, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.5855670103092784, Vanilla mBERT:0.5958762886597938, Avg Readability Formula: 0.6041237113402061, Vanilla Readability Formula:0.6041237113402061
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.5567010309278351, Vanilla rf: 0.5422680412371134, Avg minmax rf0.5463917525773195, Vanilla minmax rf: 0.5402061855670103


conf_llama_70b
unweighted:
 Avg: 0.554639175257732,Vanilla: 0.3237113402061856, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.5917525773195876, Vanilla mBERT:0.5855670103092784, Avg Readability Formula: 0.6041237113402061, Vanilla Readability Formula:0.6
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.5608247422680412, Vanilla rf: 0.5525773195876289, Avg minmax rf0.5381443298969072, Vanilla minmax rf: 0.5484536082474227
0.6288659793814433
verbal weightings:
 Avg mBERT0.1670103092783505, Vanilla mBERT: 0.16494845360824742, Avg minmax mBERT: 0.16288659793814433, Vanilla minmax mBERT: 0.16082474226804125,Avg rf0.6288659793814433, Vanilla rf: 0.6020618556701031, Avg minmax rf0.6082474226804123, Vanilla minmax rf: 0.5855670103092784
aya_32b
unweighted:
 Avg: 0.668041237113402,Vanilla: 0.38556701030927837, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.6164948453608248, Vanilla mBERT:0.6329896907216495, Avg Readability Formula: 0.6206185567010309, Vanilla Readability Formula:0.6041237113402061
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.6742268041237114, Vanilla rf: 0.6103092783505155, Avg minmax rf0.6123711340206186, Vanilla minmax rf: 0.5979381443298969


conf_aya_32b
unweighted:
 Avg: 0.6762886597938145,Vanilla: 0.41030927835051545, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.6268041237113402, Vanilla mBERT:0.6268041237113402, Avg Readability Formula: 0.6164948453608248, Vanilla Readability Formula:0.6185567010309279
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.6721649484536083, Vanilla rf: 0.6288659793814433, Avg minmax rf0.6268041237113402, Vanilla minmax rf: 0.6206185567010309
0.6618556701030928
verbal weightings:
 Avg mBERT0.1670103092783505, Vanilla mBERT: 0.16494845360824742, Avg minmax mBERT: 0.16288659793814433, Vanilla minmax mBERT: 0.16082474226804125,Avg rf0.6618556701030928, Vanilla rf: 0.6536082474226804, Avg minmax rf0.6, Vanilla minmax rf: 0.6041237113402061
gemma_2b
unweighted:
 Avg: 0.6474226804123712,Vanilla: 0.4309278350515464, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.6268041237113402, Vanilla mBERT:0.6123711340206186, Avg Readability Formula: 0.622680412371134, Vanilla Readability Formula:0.6082474226804123
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.6453608247422681, Vanilla rf: 0.6597938144329897, Avg minmax rf0.6268041237113402, Vanilla minmax rf: 0.6082474226804123


conf_gemma_2b
unweighted:
 Avg: 0.6597938144329897,Vanilla: 0.40824742268041236, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.6268041237113402, Vanilla mBERT:0.6164948453608248, Avg Readability Formula: 0.6371134020618556, Vanilla Readability Formula:0.6206185567010309
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.6618556701030928, Vanilla rf: 0.6474226804123712, Avg minmax rf0.6391752577319587, Vanilla minmax rf: 0.6329896907216495
0.6350515463917525
verbal weightings:
 Avg mBERT0.1670103092783505, Vanilla mBERT: 0.16494845360824742, Avg minmax mBERT: 0.16288659793814433, Vanilla minmax mBERT: 0.16082474226804125,Avg rf0.6350515463917525, Vanilla rf: 0.6268041237113402, Avg minmax rf0.6329896907216495, Vanilla minmax rf: 0.622680412371134
llama_3b
unweighted:
 Avg: 0.6329896907216495,Vanilla: 0.33814432989690724, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.6185567010309279, Vanilla mBERT:0.6061855670103092, Avg Readability Formula: 0.6329896907216495, Vanilla Readability Formula:0.622680412371134
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.6329896907216495, Vanilla rf: 0.6268041237113402, Avg minmax rf0.6061855670103092, Vanilla minmax rf: 0.5958762886597938


conf_llama_3b
unweighted:
 Avg: 0.6123711340206186,Vanilla: 0.32989690721649484, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.6164948453608248, Vanilla mBERT:0.6309278350515464, Avg Readability Formula: 0.6371134020618556, Vanilla Readability Formula:0.6206185567010309
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.6288659793814433, Vanilla rf: 0.6329896907216495, Avg minmax rf0.6350515463917525, Vanilla minmax rf: 0.6288659793814433
0.6371134020618556
verbal weightings:
 Avg mBERT0.1670103092783505, Vanilla mBERT: 0.16494845360824742, Avg minmax mBERT: 0.16288659793814433, Vanilla minmax mBERT: 0.16082474226804125,Avg rf0.6371134020618556, Vanilla rf: 0.6268041237113402, Avg minmax rf0.6371134020618556, Vanilla minmax rf: 0.6309278350515464
gemma_27b
unweighted:
 Avg: 0.6907216494845361,Vanilla: 0.4268041237113402, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.6268041237113402, Vanilla mBERT:0.6247422680412371, Avg Readability Formula: 0.6268041237113402, Vanilla Readability Formula:0.622680412371134
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.6927835051546392, Vanilla rf: 0.6474226804123712, Avg minmax rf0.6309278350515464, Vanilla minmax rf: 0.6185567010309279


conf_gemma_27b
unweighted:
 Avg: 0.6762886597938145,Vanilla: 0.47216494845360824, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.6309278350515464, Vanilla mBERT:0.622680412371134, Avg Readability Formula: 0.6453608247422681, Vanilla Readability Formula:0.6288659793814433
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.6659793814432989, Vanilla rf: 0.6536082474226804, Avg minmax rf0.6453608247422681, Vanilla minmax rf: 0.6453608247422681
0.6515463917525773
verbal weightings:
 Avg mBERT0.1670103092783505, Vanilla mBERT: 0.16494845360824742, Avg minmax mBERT: 0.16288659793814433, Vanilla minmax mBERT: 0.16082474226804125,Avg rf0.6515463917525773, Vanilla rf: 0.6494845360824743, Avg minmax rf0.6494845360824743, Vanilla minmax rf: 0.6412371134020619
llama_8b
unweighted:
 Avg: 0.6639175257731958,Vanilla: 0.4247422680412371, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.6309278350515464, Vanilla mBERT:0.6350515463917525, Avg Readability Formula: 0.6412371134020619, Vanilla Readability Formula:0.6288659793814433
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.6639175257731958, Vanilla rf: 0.6391752577319587, Avg minmax rf0.6371134020618556, Vanilla minmax rf: 0.6185567010309279


conf_llama_8b
unweighted:
 Avg: 0.6597938144329897,Vanilla: 0.3670103092783505, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.5917525773195876, Vanilla mBERT:0.5876288659793815, Avg Readability Formula: 0.622680412371134, Vanilla Readability Formula:0.6164948453608248
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.6515463917525773, Vanilla rf: 0.622680412371134, Avg minmax rf0.6185567010309279, Vanilla minmax rf: 0.6123711340206186
0.6391752577319587
verbal weightings:
 Avg mBERT0.1670103092783505, Vanilla mBERT: 0.16494845360824742, Avg minmax mBERT: 0.16288659793814433, Vanilla minmax mBERT: 0.16082474226804125,Avg rf0.6391752577319587, Vanilla rf: 0.6247422680412371, Avg minmax rf0.6268041237113402, Vanilla minmax rf: 0.622680412371134
aya_8b
unweighted:
 Avg: 0.6639175257731958,Vanilla: 0.33814432989690724, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.6061855670103092, Vanilla mBERT:0.6, Avg Readability Formula: 0.6082474226804123, Vanilla Readability Formula:0.6
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.6659793814432989, Vanilla rf: 0.6082474226804123, Avg minmax rf0.6185567010309279, Vanilla minmax rf: 0.6082474226804123


gemma_9b
unweighted:
 Avg: 0.6618556701030928,Vanilla: 0.4824742268041237, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.6164948453608248, Vanilla mBERT:0.6329896907216495, Avg Readability Formula: 0.6474226804123712, Vanilla Readability Formula:0.6515463917525773
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.6597938144329897, Vanilla rf: 0.6639175257731958, Avg minmax rf0.6494845360824743, Vanilla minmax rf: 0.6412371134020619


conf_gemma_9b
unweighted:
 Avg: 0.6474226804123712,Vanilla: 0.4536082474226804, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.622680412371134, Vanilla mBERT:0.6329896907216495, Avg Readability Formula: 0.6577319587628866, Vanilla Readability Formula:0.6391752577319587

entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.643298969072165, Vanilla rf: 0.6556701030927835, Avg minmax rf0.6577319587628866, Vanilla minmax rf: 0.6577319587628866
0.6391752577319587
verbal weightings:
 Avg mBERT0.1670103092783505, Vanilla mBERT: 0.16494845360824742, Avg minmax mBERT: 0.16288659793814433, Vanilla minmax mBERT: 0.16082474226804125,Avg rf0.6391752577319587, Vanilla rf: 0.6453608247422681, Avg minmax rf0.6659793814432989, Vanilla minmax rf: 0.6536082474226804
phi
unweighted:
 Avg: 0.6742268041237114,Vanilla: 0.35051546391752575, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.6, Vanilla mBERT:0.6103092783505155, Avg Readability Formula: 0.6123711340206186, Vanilla Readability Formula:0.5938144329896907
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.6742268041237114, Vanilla rf: 0.6123711340206186, Avg minmax rf0.6288659793814433, Vanilla minmax rf: 0.5917525773195876


conf_phi
unweighted:
 Avg: 0.6453608247422681,Vanilla: 0.3422680412371134, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.5896907216494846, Vanilla mBERT:0.5896907216494846, Avg Readability Formula: 0.6082474226804123, Vanilla Readability Formula:0.5896907216494846
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.643298969072165, Vanilla rf: 0.6041237113402061, Avg minmax rf0.622680412371134, Vanilla minmax rf: 0.6041237113402061
0.6371134020618556
verbal weightings:
 Avg mBERT0.1670103092783505, Vanilla mBERT: 0.16494845360824742, Avg minmax mBERT: 0.16288659793814433, Vanilla minmax mBERT: 0.16082474226804125,Avg rf0.6371134020618556, Vanilla rf: 0.6123711340206186, Avg minmax rf0.6144329896907217, Vanilla minmax rf: 0.5752577319587628
mixtral
unweighted:
 Avg: 0.6288659793814433,Vanilla: 0.4350515463917526, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.6164948453608248, Vanilla mBERT:0.6061855670103092, Avg Readability Formula: 0.6103092783505155, Vanilla Readability Formula:0.6082474226804123
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.6350515463917525, Vanilla rf: 0.6350515463917525, Avg minmax rf0.6309278350515464, Vanilla minmax rf: 0.6247422680412371


conf_mixtral
unweighted:
 Avg: 0.6206185567010309,Vanilla: 0.4041237113402062, mBERT: 0.5608247422680412, readability formula: 0.5567010309278351
naive weightings:
 Avg mBERT: 0.6020618556701031, Vanilla mBERT:0.6144329896907217, Avg Readability Formula: 0.6144329896907217, Vanilla Readability Formula:0.6061855670103092
entropy weightings:
 Avg mBERT0.16494845360824742, Vanilla mBERT: 0.15670103092783505, Avg minmax mBERT: 0.16082474226804125, Vanilla minmax mBERT: 0.15876288659793814,Avg rf0.6144329896907217, Vanilla rf: 0.6144329896907217, Avg minmax rf0.6123711340206186, Vanilla minmax rf: 0.6185567010309279
0.622680412371134
verbal weightings:
 Avg mBERT0.1670103092783505, Vanilla mBERT: 0.16494845360824742, Avg minmax mBERT: 0.16288659793814433, Vanilla minmax mBERT: 0.16082474226804125,Avg rf0.622680412371134, Vanilla rf: 0.6329896907216495, Avg minmax rf0.6268041237113402, Vanilla minmax rf: 0.622680412371134

## VIKIDIA -EN

In [107]:
vikidiav2=pd.read_csv('.../vikidiav2.csv')
vikidiav2 = vikidiav2.replace("na", np.nan)
vikidiav2.columns

Index(['Unnamed: 0', 'check', 'File_Number', 'Language', 'Simplicity', 'Text',
       'mixtral_vanilla', 'mixtral_avg', 'mixtral_entropy', 'aya_8b_vanilla',
       'aya_8b_avg', 'aya_8b_entropy', 'aya_32b_vanilla', 'aya_32b_avg',
       'aya_32b_entropy', 'llama_70b_vanilla', 'llama_70b_avg',
       'llama_70b_entropy', 'llama_8b_vanilla', 'llama_8b_avg',
       'llama_8b_entropy', 'llama_3b_vanilla', 'llama_3b_avg',
       'llama_3b_entropy', 'gemma_9b_vanilla', 'gemma_9b_avg',
       'gemma_9b_entropy', 'gemma_2b_vanilla', 'gemma_2b_avg',
       'gemma_2b_entropy', 'gemma_27b_vanilla', 'gemma_27b_avg',
       'gemma_27b_entropy', 'phi_vanilla', 'phi_avg', 'phi_entropy',
       'conf_mixtral_vanilla', 'conf_mixtral_avg', 'conf_mixtral_entropy',
       'conf_mixtral_verbal_conf', 'conf_aya_32b_vanilla', 'conf_aya_32b_avg',
       'conf_aya_32b_entropy', 'conf_aya_32b_verbal_conf',
       'conf_llama_70b_vanilla', 'conf_llama_70b_avg',
       'conf_llama_70b_entropy', 'conf_llama_70b_verbal_conf',
       'conf_llama_8b_vanilla', 'conf_llama_8b_avg', 'conf_llama_8b_entropy',
       'conf_llama_8b_verbal_conf', 'conf_llama_3b_vanilla',
       'conf_llama_3b_avg', 'conf_llama_3b_entropy',
       'conf_llama_3b_verbal_conf', 'conf_phi_vanilla', 'conf_phi_avg',
       'conf_phi_entropy', 'conf_phi_verbal_conf', 'conf_gemma_9b_vanilla',
       'conf_gemma_9b_avg', 'conf_gemma_9b_entropy',
       'conf_gemma_9b_verbal_conf', 'conf_gemma_27b_vanilla',
       'conf_gemma_27b_avg', 'conf_gemma_27b_entropy',
       'conf_gemma_27b_verbal_conf', 'conf_gemma_2b_vanilla',
       'conf_gemma_2b_avg', 'conf_gemma_2b_entropy',
       'conf_gemma_2b_verbal_conf', 'FKGL', 'ARI', 'RSRS_mBERT'],
      dtype='object')

In [108]:
df1=vikidiav2[vikidiav2.Simplicity=='simple'].sort_values(by='File_Number').reset_index(drop=True)
df2=vikidiav2[vikidiav2.Simplicity=='not simple'].sort_values(by='File_Number').reset_index(drop=True)
len(df1),len(df2)

(150, 150)

In [109]:
for i in range(6, len(vikidiav2.columns)):  # 39 = 40th col in 0-based index
    col = vikidiav2.columns[i]
    acc=((df1[col]<df2[col]).sum())/len(df1)
    #corr = readmeruv2[ref_col].astype(float).corr(readmeruv2[col].astype(float))
    if ('entropy' not in col) and ('verbal_conf' not in col):
        print(f"{i+1}: {col} -> correlation with {ref_col}: {acc:.4f}")

7: mixtral_vanilla -> correlation with Rating: 0.7733
8: mixtral_avg -> correlation with Rating: 0.8400
10: aya_8b_vanilla -> correlation with Rating: 0.5333
11: aya_8b_avg -> correlation with Rating: 0.7400
13: aya_32b_vanilla -> correlation with Rating: 0.8333
14: aya_32b_avg -> correlation with Rating: 0.9333
16: llama_70b_vanilla -> correlation with Rating: 0.8267
17: llama_70b_avg -> correlation with Rating: 0.8933
19: llama_8b_vanilla -> correlation with Rating: 0.8067
20: llama_8b_avg -> correlation with Rating: 0.8667
22: llama_3b_vanilla -> correlation with Rating: 0.6267
23: llama_3b_avg -> correlation with Rating: 0.8333
25: gemma_9b_vanilla -> correlation with Rating: 0.7467
26: gemma_9b_avg -> correlation with Rating: 0.8467
28: gemma_2b_vanilla -> correlation with Rating: 0.4533
29: gemma_2b_avg -> correlation with Rating: 0.6733
31: gemma_27b_vanilla -> correlation with Rating: 0.8133
32: gemma_27b_avg -> correlation with Rating: 0.8800
34: phi_vanilla -> correlation with Rating: 0.7933
35: phi_avg -> correlation with Rating: 0.8133
37: conf_mixtral_vanilla -> correlation with Rating: 0.7133
38: conf_mixtral_avg -> correlation with Rating: 0.8333
41: conf_aya_32b_vanilla -> correlation with Rating: 0.8133
42: conf_aya_32b_avg -> correlation with Rating: 0.9267
45: conf_llama_70b_vanilla -> correlation with Rating: 0.8267
46: conf_llama_70b_avg -> correlation with Rating: 0.8867
49: conf_llama_8b_vanilla -> correlation with Rating: 0.6867
50: conf_llama_8b_avg -> correlation with Rating: 0.8400
53: conf_llama_3b_vanilla -> correlation with Rating: 0.3000
54: conf_llama_3b_avg -> correlation with Rating: 0.4533
57: conf_phi_vanilla -> correlation with Rating: 0.7600
58: conf_phi_avg -> correlation with Rating: 0.8067
61: conf_gemma_9b_vanilla -> correlation with Rating: 0.7133
62: conf_gemma_9b_avg -> correlation with Rating: 0.8133
65: conf_gemma_27b_vanilla -> correlation with Rating: 0.8133
66: conf_gemma_27b_avg -> correlation with Rating: 0.8600
69: conf_gemma_2b_vanilla -> correlation with Rating: 0.0533
70: conf_gemma_2b_avg -> correlation with Rating: 0.0800
73: FKGL -> correlation with Rating: 0.8600
74: ARI -> correlation with Rating: 0.8600
75: RSRS_mBERT -> correlation with Rating: 0.8467

In [110]:
vikidiav2.iloc[:, 6:] = vikidiav2.iloc[:, 6:].apply(pd.to_numeric, errors="coerce")
rf_string='FKGL'
model='conf_llama_70b'
vconf_cols = [c for c in vikidiav2.columns if c.endswith("verbal_conf")]
vikidiav2[vconf_cols] = vikidiav2[vconf_cols]/10

std_cols = [c for c in vikidiav2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
vikidiav2[std_cols] = StandardScaler().fit_transform(vikidiav2[std_cols])

avg_col = f"{model}_avg"
vconf_col=f'{model}_verbal_conf'
df1=vikidiav2[vikidiav2.Simplicity=='simple'].sort_values(by='File_Number').reset_index(drop=True)
df2=vikidiav2[vikidiav2.Simplicity=='not simple'].sort_values(by='File_Number').reset_index(drop=True)


verbal_avg_rf_df1=((1 - df1[vconf_col]) * df1[rf_string]) + (df1[vconf_col] * df1[avg_col])
verbal_avg_rf_df2=((1 - df2[vconf_col]) * df2[rf_string]) + (df2[vconf_col] * df2[avg_col])




preds_a=(verbal_avg_rf_df1<verbal_avg_rf_df2)
##change to second best model if it is not LLM
preds_b=(df1.iloc[:,44]<df2.iloc[:,44])

print(preds_a.sum()/len(preds_a),preds_b.sum()/len(preds_a))

print(((preds_a==True)&(preds_b==False)).sum(),((preds_a==False)&(preds_b==True)).sum())
b=((preds_a==True)&(preds_b==False)).sum()
c=((preds_a==False)&(preds_b==True)).sum()
print(f'p_value for difference LAURAE and LLM: {mcnemar(int(b),int(c),True)}')



preds_a=(verbal_avg_rf_df1<verbal_avg_rf_df2)
##change to second best model if it is not LLM
preds_b=(df1[rf_string]<df2[rf_string])

print(preds_a.sum()/len(preds_a),preds_b.sum()/len(preds_a))

print(((preds_a==True)&(preds_b==False)).sum(),((preds_a==False)&(preds_b==True)).sum())
b=((preds_a==True)&(preds_b==False)).sum()
c=((preds_a==False)&(preds_b==True)).sum()
print(f'p_value for difference LAURAE and RF: {mcnemar(int(b),int(c),True)}')


preds_a=(verbal_avg_rf_df1<verbal_avg_rf_df2)
##change to second best model if it is not LLM
preds_b=(df1['RSRS_mBERT']<df2['RSRS_mBERT'])

print(preds_a.sum()/len(preds_a),preds_b.sum()/len(preds_a))

print(((preds_a==True)&(preds_b==False)).sum(),((preds_a==False)&(preds_b==True)).sum())
b=((preds_a==True)&(preds_b==False)).sum()
c=((preds_a==False)&(preds_b==True)).sum()
print(f'p_value for difference LAURAE and RSRS: {mcnemar(int(b),int(c),True)}')

0.9 0.8266666666666667
11 0
p_value for difference LAURAE and LLM: 0.00048828125
0.9 0.86
9 3
p_value for difference LAURAE and RF: 0.09228515624999999
0.9 0.8466666666666667
9 1
p_value for difference LAURAE and RSRS: 0.011718749999999998

In [111]:
preds_a=df1.iloc[:,44]<df2.iloc[:,44]
##change to second best model if it is not LLM
preds_b=df1.iloc[:,45]<df2.iloc[:,45]

print(preds_a.sum()/len(preds_a),preds_b.sum()/len(preds_a))

print(((preds_a==True)&(preds_b==False)).sum(),((preds_a==False)&(preds_b==True)).sum())
b=((preds_a==True)&(preds_b==False)).sum()
c=((preds_a==False)&(preds_b==True)).sum()
print(f'p_value for difference (Expected v Vanilla): {mcnemar(int(b),int(c),True)}')

0.8266666666666667 0.8866666666666667
0 9
p_value for difference (Expected v Vanilla): 0.0019531249999999996

In [112]:
vikidiav2=pd.read_csv('.../vikidiav2.csv')
vikidiav2 = vikidiav2.replace("na", np.nan)
vikidiav2.columns


from sklearn.preprocessing import MinMaxScaler, StandardScaler
vikidiav2.iloc[:, 6:] = vikidiav2.iloc[:, 6:].apply(pd.to_numeric, errors="coerce")
rf_string='FKGL'
#readmeruv2['RSRS_mBERT']= StandardScaler().fit_transform(readmeruv2['RSRS_mBERT'])
# Step 1: Normalize entropy columns
entropy_cols = [c for c in vikidiav2.columns if c.endswith("_entropy")]
entropy_cols_minmax = [c + "_minmax" for c in entropy_cols]
vikidiav2[entropy_cols_minmax] = MinMaxScaler().fit_transform(vikidiav2[entropy_cols])

vconf_cols = [c for c in vikidiav2.columns if c.endswith("verbal_conf")]
vconf_cols_minmax = [c + "_minmax" for c in vconf_cols]
vikidiav2[vconf_cols_minmax] = MinMaxScaler().fit_transform(vikidiav2[vconf_cols])
vikidiav2[vconf_cols] = vikidiav2[vconf_cols]/10

std_cols = [c for c in vikidiav2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
vikidiav2[std_cols] = StandardScaler().fit_transform(vikidiav2[std_cols])
suffixes = ["_avg", "_vanilla", "_entropy"]
models = set(
    c.rsplit("_", 1)[0]  # remove the last part after the final underscore
    for c in entropy_cols  # or any column list containing these suffixes
)


df1=vikidiav2[vikidiav2.Simplicity=='simple'].sort_values(by='File_Number').reset_index(drop=True)
df2=vikidiav2[vikidiav2.Simplicity=='not simple'].sort_values(by='File_Number').reset_index(drop=True)
sorted_models = sorted(models, key=lambda x: x[::-1].lower())
for model in sorted_models:
    print(model)
    vanilla_col = f"{model}_vanilla"
    avg_col = f"{model}_avg"
    print(f'unweighted: \n Avg: {((df1[avg_col]<df2[avg_col]).sum())/len(df1)},Vanilla: {((df1[vanilla_col]<df2[vanilla_col]).sum())/len(df1)}, mBERT: {((df1["RSRS_mBERT"]<df2["RSRS_mBERT"]).sum())/len(df1)}, readability formula: {((df1[rf_string]<df2[rf_string]).sum())/len(df1)}')
    naive_avg_mBERT_df1=df1[avg_col]+df1["RSRS_mBERT"]
    naive_vanilla_mBERT_df1=df1[vanilla_col]+df1["RSRS_mBERT"]
    naive_avg_rf_df1=df1[avg_col]+df1[rf_string]
    naive_vanilla_rf_df1=df1[vanilla_col]+df1[rf_string]
    
    naive_avg_mBERT_df2=df2[avg_col]+df2["RSRS_mBERT"]
    naive_vanilla_mBERT_df2=df2[vanilla_col]+df2["RSRS_mBERT"]
    naive_avg_rf_df2=df2[avg_col]+df2[rf_string]
    naive_vanilla_rf_df2=df2[vanilla_col]+df2[rf_string]
    print(f'naive weightings:\n Avg mBERT: {((naive_avg_mBERT_df1<naive_avg_mBERT_df2).sum())/len(df1)}, Vanilla mBERT:{((naive_vanilla_mBERT_df1<naive_vanilla_mBERT_df2).sum())/len(df1)}, Avg Readability Formula: {((naive_avg_rf_df1<naive_avg_rf_df2).sum())/len(df1)}, Vanilla Readability Formula:{((naive_vanilla_rf_df1<naive_vanilla_rf_df2).sum())/len(df1)}')
    entropy_col = f"{model}_entropy"
    entropy_col_minmax = f"{model}_entropy_minmax"
    if model.startswith('conf_'):
        vconf_col=f'{model}_verbal_conf'
        vconf_col_minmax = f"{model}_verbal_conf_minmax"
    
    #readmeruv2[f"{model}_weighted"] = (
    #    readmeruv2[entropy_col] * readmeruv2["RSRS_mBERT"] + 
    #    (1 - readmeruv2[entropy_col]) * (readmeruv2[[vanilla_col, avg_col]].mean(axis=1))
    #)
    entropy_avg_mBERT_df1=(df1[entropy_col] * df1["RSRS_mBERT"]) + ((1 - df1[entropy_col]) * df1[avg_col])
    entropy_vanilla_mBERT_df1=(df1[entropy_col] * df1["RSRS_mBERT"]) + ((1 - df1[entropy_col]) * df1[vanilla_col])
    entropy_avg_mBERT_df2=(df2[entropy_col] * df2["RSRS_mBERT"]) + ((1 - df2[entropy_col]) * df2[avg_col])
    entropy_vanilla_mBERT_df2=(df2[entropy_col] * df2["RSRS_mBERT"]) + ((1 - df2[entropy_col]) * df2[vanilla_col])
    
    entropy_minmax_avg_mBERT_df1=(df1[entropy_col_minmax] * df1["RSRS_mBERT"]) + ((1 - df1[entropy_col_minmax]) * df1[avg_col])
    entropy_minmax_vanilla_mBERT_df1=(df1[entropy_col_minmax] * df1["RSRS_mBERT"]) + ((1 - df1[entropy_col_minmax]) * df1[vanilla_col])
    entropy_minmax_avg_mBERT_df2=(df2[entropy_col_minmax] * df2["RSRS_mBERT"]) + ((1 - df2[entropy_col_minmax]) * df2[avg_col])
    entropy_minmax_vanilla_mBERT_df2=(df2[entropy_col_minmax] * df2["RSRS_mBERT"]) + ((1 - df2[entropy_col_minmax]) * df2[vanilla_col])
    
    entropy_avg_rf_df1=(df1[entropy_col] * df1[rf_string]) + ((1 - df1[entropy_col]) * df1[avg_col])
    entropy_vanilla_rf_df1=(df1[entropy_col] * df1[rf_string]) + ((1 - df1[entropy_col]) * df1[vanilla_col])
    entropy_avg_rf_df2=(df2[entropy_col] * df2[rf_string]) + ((1 - df2[entropy_col]) * df2[avg_col])
    entropy_vanilla_rf_df2=(df2[entropy_col] * df2[rf_string]) + ((1 - df2[entropy_col]) * df2[vanilla_col])
    
    entropy_minmax_avg_rf_df1=(df1[entropy_col_minmax] * df1[rf_string]) + ((1 - df1[entropy_col_minmax]) * df1[avg_col])
    entropy_minmax_vanilla_rf_df1=(df1[entropy_col_minmax] * df1[rf_string]) + ((1 - df1[entropy_col_minmax]) * df1[vanilla_col])
    entropy_minmax_avg_rf_df2=(df2[entropy_col_minmax] * df2[rf_string]) + ((1 - df2[entropy_col_minmax]) * df2[avg_col])
    entropy_minmax_vanilla_rf_df2=(df2[entropy_col_minmax] * df2[rf_string]) + ((1 - df2[entropy_col_minmax]) * df2[vanilla_col])
    
    
    
    
    
    
    print(f'entropy weightings: \n Avg mBERT{((entropy_avg_mBERT_df1<entropy_avg_mBERT_df2).sum())/len(df1)}, Vanilla mBERT: {((entropy_vanilla_mBERT_df1<entropy_vanilla_mBERT_df2).sum())/len(df1)}, Avg minmax mBERT: {((entropy_minmax_avg_mBERT_df1<entropy_minmax_avg_mBERT_df2).sum())/len(df1)}, Vanilla minmax mBERT: {((entropy_minmax_vanilla_mBERT_df1<entropy_minmax_vanilla_mBERT_df2).sum())/len(df1)},Avg rf{((entropy_avg_rf_df1<entropy_avg_rf_df2).sum())/len(df1)}, Vanilla rf: {((entropy_vanilla_rf_df1<entropy_vanilla_rf_df2).sum())/len(df1)}, Avg minmax rf: {((entropy_minmax_avg_rf_df1<entropy_minmax_avg_rf_df2).sum())/len(df1)}, Vanilla minmax rf: {((entropy_minmax_vanilla_rf_df1<entropy_minmax_vanilla_rf_df2).sum())/len(df1)}')
    if model.startswith('conf_'):
        verbal_avg_mBERT_df1=((1 - df1[vconf_col]) * df1["RSRS_mBERT"]) + (df1[vconf_col] * df1[avg_col])
        verbal_vanilla_mBERT_df1=((1 - df1[vconf_col]) * df1["RSRS_mBERT"]) + (df1[vconf_col] * df1[vanilla_col])
        verbal_avg_mBERT_df2=((1 - df2[vconf_col]) * df2["RSRS_mBERT"]) + (df2[vconf_col] * df2[avg_col])
        verbal_vanilla_mBERT_df2=((1 - df2[vconf_col]) * df2["RSRS_mBERT"]) + (df2[vconf_col] * df2[vanilla_col])
        
        verbal_minmax_avg_mBERT_df1=((1 - df1[vconf_col_minmax]) * df1["RSRS_mBERT"]) + (df1[vconf_col_minmax] * df1[avg_col])
        verbal_minmax_vanilla_mBERT_df1=((1 - df1[vconf_col_minmax]) * df1["RSRS_mBERT"]) + (df1[vconf_col_minmax] * df1[vanilla_col])
        verbal_minmax_avg_mBERT_df2=((1 - df2[vconf_col_minmax]) * df2["RSRS_mBERT"]) + (df2[vconf_col_minmax] * df2[avg_col])
        verbal_minmax_vanilla_mBERT_df2=((1 - df2[vconf_col_minmax]) * df2["RSRS_mBERT"]) + (df2[vconf_col_minmax] * df2[vanilla_col])
        
        verbal_avg_rf_df1=((1 - df1[vconf_col]) * df1[rf_string]) + (df1[vconf_col] * df1[avg_col])
        verbal_vanilla_rf_df1=((1 - df1[vconf_col]) * df1[rf_string]) + (df1[vconf_col] * df1[vanilla_col])
        verbal_avg_rf_df2=((1 - df2[vconf_col]) * df2[rf_string]) + (df2[vconf_col] * df2[avg_col])
        verbal_vanilla_rf_df2=((1 - df2[vconf_col]) * df2[rf_string]) + (df2[vconf_col] * df2[vanilla_col])
        
        verbal_minmax_avg_rf_df1=((1 - df1[vconf_col_minmax]) * df1[rf_string]) + (df1[vconf_col_minmax] * df1[avg_col])
        verbal_minmax_vanilla_rf_df1=((1 - df1[vconf_col_minmax]) * df1[rf_string]) + (df1[vconf_col_minmax] * df1[vanilla_col])
        verbal_minmax_avg_rf_df2=((1 - df2[vconf_col_minmax]) * df2[rf_string]) + (df2[vconf_col_minmax] * df2[avg_col])
        verbal_minmax_vanilla_rf_df2=((1 - df2[vconf_col_minmax]) * df2[rf_string]) + (df2[vconf_col_minmax] * df2[vanilla_col])
        print(f'verbal weightings: \n Avg mBERT{((verbal_avg_mBERT_df1<verbal_avg_mBERT_df2).sum())/len(df1)}, Vanilla mBERT: {((verbal_vanilla_mBERT_df1<verbal_vanilla_mBERT_df2).sum())/len(df1)}, Avg minmax mBERT: {((verbal_minmax_avg_mBERT_df1<verbal_minmax_avg_mBERT_df2).sum())/len(df1)}, Vanilla minmax mBERT: {((verbal_minmax_vanilla_mBERT_df1<verbal_minmax_vanilla_mBERT_df2).sum())/len(df1)},Avg rf: {((verbal_avg_rf_df1<verbal_avg_rf_df2).sum())/len(df1)}, Vanilla rf: {((verbal_vanilla_rf_df1<verbal_vanilla_rf_df2).sum())/len(df1)}, Avg minmax rf{((verbal_minmax_avg_rf_df1<verbal_minmax_avg_rf_df2).sum())/len(df1)}, Vanilla minmax rf: {((verbal_minmax_vanilla_rf_df1<verbal_minmax_vanilla_rf_df2).sum())/len(df1)}')
    else:
        print('\n')

llama_70b
unweighted:
 Avg: 0.8933333333333333,Vanilla: 0.8266666666666667, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.8733333333333333, Vanilla mBERT:0.8733333333333333, Avg Readability Formula: 0.9, Vanilla Readability Formula:0.88
entropy weightings:
 Avg mBERT0.8933333333333333, Vanilla mBERT: 0.8866666666666667, Avg minmax mBERT: 0.8666666666666667, Vanilla minmax mBERT: 0.8733333333333333,Avg rf0.8933333333333333, Vanilla rf: 0.8866666666666667, Avg minmax rf: 0.8933333333333333, Vanilla minmax rf: 0.8733333333333333


conf_llama_70b
unweighted:
 Avg: 0.8866666666666667,Vanilla: 0.8266666666666667, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.8666666666666667, Vanilla mBERT:0.8733333333333333, Avg Readability Formula: 0.8933333333333333, Vanilla Readability Formula:0.8866666666666667
entropy weightings:
 Avg mBERT0.88, Vanilla mBERT: 0.8733333333333333, Avg minmax mBERT: 0.8666666666666667, Vanilla minmax mBERT: 0.8733333333333333,Avg rf0.8866666666666667, Vanilla rf: 0.86, Avg minmax rf: 0.8733333333333333, Vanilla minmax rf: 0.8666666666666667
verbal weightings:
 Avg mBERT0.88, Vanilla mBERT: 0.8733333333333333, Avg minmax mBERT: 0.8733333333333333, Vanilla minmax mBERT: 0.86,Avg rf: 0.9, Vanilla rf: 0.8733333333333333, Avg minmax rf0.8866666666666667, Vanilla minmax rf: 0.8733333333333333
aya_32b
unweighted:
 Avg: 0.9333333333333333,Vanilla: 0.8333333333333334, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.9266666666666666, Vanilla mBERT:0.9333333333333333, Avg Readability Formula: 0.9266666666666666, Vanilla Readability Formula:0.92
entropy weightings:
 Avg mBERT0.9333333333333333, Vanilla mBERT: 0.9333333333333333, Avg minmax mBERT: 0.9333333333333333, Vanilla minmax mBERT: 0.9266666666666666,Avg rf0.9333333333333333, Vanilla rf: 0.94, Avg minmax rf: 0.9333333333333333, Vanilla minmax rf: 0.9333333333333333


conf_aya_32b
unweighted:
 Avg: 0.9266666666666666,Vanilla: 0.8133333333333334, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.9266666666666666, Vanilla mBERT:0.9266666666666666, Avg Readability Formula: 0.9066666666666666, Vanilla Readability Formula:0.9133333333333333
entropy weightings:
 Avg mBERT0.9266666666666666, Vanilla mBERT: 0.9333333333333333, Avg minmax mBERT: 0.9133333333333333, Vanilla minmax mBERT: 0.92,Avg rf0.9133333333333333, Vanilla rf: 0.9266666666666666, Avg minmax rf: 0.92, Vanilla minmax rf: 0.9266666666666666
verbal weightings:
 Avg mBERT0.9266666666666666, Vanilla mBERT: 0.9333333333333333, Avg minmax mBERT: 0.9266666666666666, Vanilla minmax mBERT: 0.92,Avg rf: 0.9266666666666666, Vanilla rf: 0.92, Avg minmax rf0.9066666666666666, Vanilla minmax rf: 0.9066666666666666
gemma_2b
unweighted:
 Avg: 0.6733333333333333,Vanilla: 0.4533333333333333, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.7666666666666667, Vanilla mBERT:0.76, Avg Readability Formula: 0.78, Vanilla Readability Formula:0.7666666666666667
entropy weightings:
 Avg mBERT0.6933333333333334, Vanilla mBERT: 0.7466666666666667, Avg minmax mBERT: 0.76, Vanilla minmax mBERT: 0.7666666666666667,Avg rf0.7, Vanilla rf: 0.74, Avg minmax rf: 0.7866666666666666, Vanilla minmax rf: 0.78


conf_gemma_2b
unweighted:
 Avg: 0.08,Vanilla: 0.05333333333333334, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.08666666666666667, Vanilla mBERT:0.08666666666666667, Avg Readability Formula: 0.10666666666666667, Vanilla Readability Formula:0.1
entropy weightings:
 Avg mBERT0.08, Vanilla mBERT: 0.07333333333333333, Avg minmax mBERT: 0.1, Vanilla minmax mBERT: 0.1,Avg rf0.08, Vanilla rf: 0.08, Avg minmax rf: 0.10666666666666667, Vanilla minmax rf: 0.10666666666666667
verbal weightings:
 Avg mBERT0.08666666666666667, Vanilla mBERT: 0.07333333333333333, Avg minmax mBERT: 0.09333333333333334, Vanilla minmax mBERT: 0.09333333333333334,Avg rf: 0.08666666666666667, Vanilla rf: 0.08666666666666667, Avg minmax rf0.10666666666666667, Vanilla minmax rf: 0.10666666666666667
llama_3b
unweighted:
 Avg: 0.8333333333333334,Vanilla: 0.6266666666666667, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.8533333333333334, Vanilla mBERT:0.84, Avg Readability Formula: 0.8733333333333333, Vanilla Readability Formula:0.86
entropy weightings:
 Avg mBERT0.8533333333333334, Vanilla mBERT: 0.8533333333333334, Avg minmax mBERT: 0.8533333333333334, Vanilla minmax mBERT: 0.8533333333333334,Avg rf0.8666666666666667, Vanilla rf: 0.86, Avg minmax rf: 0.8733333333333333, Vanilla minmax rf: 0.8666666666666667


conf_llama_3b
unweighted:
 Avg: 0.4533333333333333,Vanilla: 0.3, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.47333333333333333, Vanilla mBERT:0.44666666666666666, Avg Readability Formula: 0.48, Vanilla Readability Formula:0.47333333333333333
entropy weightings:
 Avg mBERT0.4533333333333333, Vanilla mBERT: 0.44666666666666666, Avg minmax mBERT: 0.4666666666666667, Vanilla minmax mBERT: 0.46,Avg rf0.4533333333333333, Vanilla rf: 0.46, Avg minmax rf: 0.5, Vanilla minmax rf: 0.48
verbal weightings:
 Avg mBERT0.4066666666666667, Vanilla mBERT: 0.38, Avg minmax mBERT: 0.4, Vanilla minmax mBERT: 0.38,Avg rf: 0.4066666666666667, Vanilla rf: 0.4066666666666667, Avg minmax rf0.4066666666666667, Vanilla minmax rf: 0.41333333333333333
gemma_27b
unweighted:
 Avg: 0.88,Vanilla: 0.8133333333333334, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.86, Vanilla mBERT:0.8666666666666667, Avg Readability Formula: 0.8933333333333333, Vanilla Readability Formula:0.88
entropy weightings:
 Avg mBERT0.88, Vanilla mBERT: 0.88, Avg minmax mBERT: 0.8733333333333333, Vanilla minmax mBERT: 0.8733333333333333,Avg rf0.88, Vanilla rf: 0.8733333333333333, Avg minmax rf: 0.8866666666666667, Vanilla minmax rf: 0.8866666666666667


conf_gemma_27b
unweighted:
 Avg: 0.86,Vanilla: 0.8133333333333334, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.8533333333333334, Vanilla mBERT:0.86, Avg Readability Formula: 0.8933333333333333, Vanilla Readability Formula:0.8866666666666667
entropy weightings:
 Avg mBERT0.86, Vanilla mBERT: 0.8666666666666667, Avg minmax mBERT: 0.86, Vanilla minmax mBERT: 0.86,Avg rf0.86, Vanilla rf: 0.8733333333333333, Avg minmax rf: 0.88, Vanilla minmax rf: 0.8933333333333333
verbal weightings:
 Avg mBERT0.86, Vanilla mBERT: 0.8666666666666667, Avg minmax mBERT: 0.8666666666666667, Vanilla minmax mBERT: 0.8666666666666667,Avg rf: 0.8733333333333333, Vanilla rf: 0.8666666666666667, Avg minmax rf0.86, Vanilla minmax rf: 0.8666666666666667
llama_8b
unweighted:
 Avg: 0.8666666666666667,Vanilla: 0.8066666666666666, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.8466666666666667, Vanilla mBERT:0.86, Avg Readability Formula: 0.86, Vanilla Readability Formula:0.8666666666666667
entropy weightings:
 Avg mBERT0.86, Vanilla mBERT: 0.8666666666666667, Avg minmax mBERT: 0.86, Vanilla minmax mBERT: 0.8533333333333334,Avg rf0.8666666666666667, Vanilla rf: 0.8733333333333333, Avg minmax rf: 0.8733333333333333, Vanilla minmax rf: 0.8733333333333333


conf_llama_8b
unweighted:
 Avg: 0.84,Vanilla: 0.6866666666666666, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.84, Vanilla mBERT:0.84, Avg Readability Formula: 0.84, Vanilla Readability Formula:0.8333333333333334
entropy weightings:
 Avg mBERT0.84, Vanilla mBERT: 0.8466666666666667, Avg minmax mBERT: 0.8333333333333334, Vanilla minmax mBERT: 0.84,Avg rf0.8466666666666667, Vanilla rf: 0.8466666666666667, Avg minmax rf: 0.8666666666666667, Vanilla minmax rf: 0.8666666666666667
verbal weightings:
 Avg mBERT0.84, Vanilla mBERT: 0.84, Avg minmax mBERT: 0.8266666666666667, Vanilla minmax mBERT: 0.84,Avg rf: 0.8466666666666667, Vanilla rf: 0.8333333333333334, Avg minmax rf0.84, Vanilla minmax rf: 0.8333333333333334
aya_8b
unweighted:
 Avg: 0.74,Vanilla: 0.5333333333333333, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.8266666666666667, Vanilla mBERT:0.8266666666666667, Avg Readability Formula: 0.8466666666666667, Vanilla Readability Formula:0.8066666666666666
entropy weightings:
 Avg mBERT0.76, Vanilla mBERT: 0.78, Avg minmax mBERT: 0.8266666666666667, Vanilla minmax mBERT: 0.8266666666666667,Avg rf0.76, Vanilla rf: 0.78, Avg minmax rf: 0.8266666666666667, Vanilla minmax rf: 0.8133333333333334


gemma_9b
unweighted:
 Avg: 0.8466666666666667,Vanilla: 0.7466666666666667, mBERT: 0.8466666666666667, readability formula: 0.86

naive weightings:
 Avg mBERT: 0.8666666666666667, Vanilla mBERT:0.8466666666666667, Avg Readability Formula: 0.8733333333333333, Vanilla Readability Formula:0.8733333333333333
entropy weightings:
 Avg mBERT0.8466666666666667, Vanilla mBERT: 0.8533333333333334, Avg minmax mBERT: 0.84, Vanilla minmax mBERT: 0.8466666666666667,Avg rf0.8466666666666667, Vanilla rf: 0.86, Avg minmax rf: 0.8533333333333334, Vanilla minmax rf: 0.84


conf_gemma_9b
unweighted:
 Avg: 0.8133333333333334,Vanilla: 0.7133333333333334, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.8666666666666667, Vanilla mBERT:0.84, Avg Readability Formula: 0.86, Vanilla Readability Formula:0.8733333333333333
entropy weightings:
 Avg mBERT0.8266666666666667, Vanilla mBERT: 0.8266666666666667, Avg minmax mBERT: 0.8533333333333334, Vanilla minmax mBERT: 0.82,Avg rf0.8333333333333334, Vanilla rf: 0.8466666666666667, Avg minmax rf: 0.86, Vanilla minmax rf: 0.84
verbal weightings:
 Avg mBERT0.8466666666666667, Vanilla mBERT: 0.84, Avg minmax mBERT: 0.8533333333333334, Vanilla minmax mBERT: 0.86,Avg rf: 0.86, Vanilla rf: 0.84, Avg minmax rf0.86, Vanilla minmax rf: 0.88
phi
unweighted:
 Avg: 0.8133333333333334,Vanilla: 0.7933333333333333, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.8666666666666667, Vanilla mBERT:0.86, Avg Readability Formula: 0.88, Vanilla Readability Formula:0.88
entropy weightings:
 Avg mBERT0.84, Vanilla mBERT: 0.8533333333333334, Avg minmax mBERT: 0.86, Vanilla minmax mBERT: 0.86,Avg rf0.84, Vanilla rf: 0.8666666666666667, Avg minmax rf: 0.8866666666666667, Vanilla minmax rf: 0.8733333333333333


conf_phi
unweighted:
 Avg: 0.8066666666666666,Vanilla: 0.76, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.8666666666666667, Vanilla mBERT:0.8666666666666667, Avg Readability Formula: 0.88, Vanilla Readability Formula:0.88
entropy weightings:
 Avg mBERT0.8133333333333334, Vanilla mBERT: 0.84, Avg minmax mBERT: 0.8533333333333334, Vanilla minmax mBERT: 0.86,Avg rf0.8266666666666667, Vanilla rf: 0.86, Avg minmax rf: 0.88, Vanilla minmax rf: 0.8733333333333333
verbal weightings:
 Avg mBERT0.8333333333333334, Vanilla mBERT: 0.8533333333333334, Avg minmax mBERT: 0.8533333333333334, Vanilla minmax mBERT: 0.8733333333333333,Avg rf: 0.8533333333333334, Vanilla rf: 0.8666666666666667, Avg minmax rf0.8533333333333334, Vanilla minmax rf: 0.8666666666666667
mixtral
unweighted:
 Avg: 0.84,Vanilla: 0.7733333333333333, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.8533333333333334, Vanilla mBERT:0.86, Avg Readability Formula: 0.8933333333333333, Vanilla Readability Formula:0.8933333333333333
entropy weightings:
 Avg mBERT0.86, Vanilla mBERT: 0.88, Avg minmax mBERT: 0.88, Vanilla minmax mBERT: 0.88,Avg rf0.8666666666666667, Vanilla rf: 0.88, Avg minmax rf: 0.8733333333333333, Vanilla minmax rf: 0.8733333333333333


conf_mixtral
unweighted:
 Avg: 0.8333333333333334,Vanilla: 0.7133333333333334, mBERT: 0.8466666666666667, readability formula: 0.86
naive weightings:
 Avg mBERT: 0.86, Vanilla mBERT:0.8533333333333334, Avg Readability Formula: 0.88, Vanilla Readability Formula:0.88
entropy weightings:
 Avg mBERT0.86, Vanilla mBERT: 0.86, Avg minmax mBERT: 0.8733333333333333, Vanilla minmax mBERT: 0.8666666666666667,Avg rf0.8666666666666667, Vanilla rf: 0.8533333333333334, Avg minmax rf: 0.86, Vanilla minmax rf: 0.86
verbal weightings:
 Avg mBERT0.84, Vanilla mBERT: 0.8466666666666667, Avg minmax mBERT: 0.8666666666666667, Vanilla minmax mBERT: 0.8466666666666667,Avg rf: 0.8533333333333334, Vanilla rf: 0.86, Avg minmax rf0.8733333333333333, Vanilla minmax rf: 0.86

## Vikidia fr

In [114]:
vikidiafrv2=pd.read_csv('.../vikidia_frv2.csv')
vikidiafrv2 = vikidiafrv2.replace("na", np.nan)
vikidiafrv2.columns

Index(['Unnamed: 0', 'check', 'File_Number', 'Language', 'Simplicity', 'Text',
       'mixtral_vanilla', 'mixtral_avg', 'mixtral_entropy', 'aya_32b_vanilla',
       'aya_32b_avg', 'aya_32b_entropy', 'aya_8b_vanilla', 'aya_8b_avg',
       'aya_8b_entropy', 'llama_8b_vanilla', 'llama_8b_avg',
       'llama_8b_entropy', 'llama_70b_vanilla', 'llama_70b_avg',
       'llama_70b_entropy', 'llama_3b_vanilla', 'llama_3b_avg',
       'llama_3b_entropy', 'conf_llama_70b_vanilla', 'conf_llama_70b_avg',
       'conf_llama_70b_entropy', 'conf_llama_70b_verbal_conf',
       'conf_llama_8b_vanilla', 'conf_llama_8b_avg', 'conf_llama_8b_entropy',
       'conf_llama_8b_verbal_conf', 'conf_llama_3b_vanilla',
       'conf_llama_3b_avg', 'conf_llama_3b_entropy',
       'conf_llama_3b_verbal_conf', 'conf_aya_32b_vanilla', 'conf_aya_32b_avg',
       'conf_aya_32b_entropy', 'conf_aya_32b_verbal_conf',
       'conf_mixtral_vanilla', 'conf_mixtral_avg', 'conf_mixtral_entropy',
       'conf_mixtral_verbal_conf', 'FKGL', 'FRE', 'ARI', 'RSRS_mBERT'],
      dtype='object')

In [116]:
df1=vikidiafrv2[vikidiafrv2.Simplicity=='simple'].sort_values(by='File_Number').reset_index(drop=True)
df2=vikidiafrv2[vikidiafrv2.Simplicity=='not simple'].sort_values(by='File_Number').reset_index(drop=True)
len(df1),len(df2)

(150, 150)

In [117]:
for i in range(6, len(vikidiafrv2.columns)): 
    col = vikidiafrv2.columns[i]
    acc=((df1[col]<df2[col]).sum())/len(df1)
    if ('entropy' not in col) and ('verbal_conf' not in col):
        print(f"{i+1}: {col} -> correlation with {ref_col}: {acc:.4f}")

7: mixtral_vanilla -> correlation with Rating: 0.7400
8: mixtral_avg -> correlation with Rating: 0.8467
10: aya_32b_vanilla -> correlation with Rating: 0.8600
11: aya_32b_avg -> correlation with Rating: 0.9467
13: aya_8b_vanilla -> correlation with Rating: 0.5000
14: aya_8b_avg -> correlation with Rating: 0.6600
16: llama_8b_vanilla -> correlation with Rating: 0.6333
17: llama_8b_avg -> correlation with Rating: 0.8467
19: llama_70b_vanilla -> correlation with Rating: 0.9067
20: llama_70b_avg -> correlation with Rating: 0.9600
22: llama_3b_vanilla -> correlation with Rating: 0.4067
23: llama_3b_avg -> correlation with Rating: 0.7133
25: conf_llama_70b_vanilla -> correlation with Rating: 0.8867
26: conf_llama_70b_avg -> correlation with Rating: 0.9533
29: conf_llama_8b_vanilla -> correlation with Rating: 0.5133
30: conf_llama_8b_avg -> correlation with Rating: 0.8133
33: conf_llama_3b_vanilla -> correlation with Rating: 0.0200
34: conf_llama_3b_avg -> correlation with Rating: 0.0533
37: conf_aya_32b_vanilla -> correlation with Rating: 0.7600
38: conf_aya_32b_avg -> correlation with Rating: 0.9200
41: conf_mixtral_vanilla -> correlation with Rating: 0.7733
42: conf_mixtral_avg -> correlation with Rating: 0.8733
45: FKGL -> correlation with Rating: 0.5200
46: FRE -> correlation with Rating: 0.8867
47: ARI -> correlation with Rating: 0.5933
48: RSRS_mBERT -> correlation with Rating: 0.8400

In [118]:
vikidiafrv2.iloc[:, 6:] = vikidiafrv2.iloc[:, 6:].apply(pd.to_numeric, errors="coerce")
rf_string='FRE'
model='conf_aya_32b'
vconf_cols = [c for c in vikidiafrv2.columns if c.endswith("verbal_conf")]
vikidiafrv2[vconf_cols] = vikidiafrv2[vconf_cols]/10

std_cols = [c for c in vikidiafrv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
vikidiafrv2[std_cols] = StandardScaler().fit_transform(vikidiafrv2[std_cols])

avg_col = f"{model}_avg"
vconf_col=f'{model}_verbal_conf'
df1=vikidiafrv2[vikidiafrv2.Simplicity=='simple'].sort_values(by='File_Number').reset_index(drop=True)
df2=vikidiafrv2[vikidiafrv2.Simplicity=='not simple'].sort_values(by='File_Number').reset_index(drop=True)


verbal_avg_rf_df1=((1 - df1[vconf_col]) * df1[rf_string]) + (df1[vconf_col] * df1[avg_col])
verbal_avg_rf_df2=((1 - df2[vconf_col]) * df2[rf_string]) + (df2[vconf_col] * df2[avg_col])




preds_a=(verbal_avg_rf_df1<verbal_avg_rf_df2)
##change to second best model if it is not LLM
preds_b=(df1.iloc[:,36]<df2.iloc[:,36])

print(preds_a.sum()/len(preds_a),preds_b.sum()/len(preds_a))

print(((preds_a==True)&(preds_b==False)).sum(),((preds_a==False)&(preds_b==True)).sum())
b=((preds_a==True)&(preds_b==False)).sum()
c=((preds_a==False)&(preds_b==True)).sum()
print(f'p_value for difference LAURAE and LLM: {mcnemar(int(b),int(c),True)}')



preds_a=(verbal_avg_rf_df1<verbal_avg_rf_df2)
##change to second best model if it is not LLM
preds_b=(df1[rf_string]<df2[rf_string])

print(preds_a.sum()/len(preds_a),preds_b.sum()/len(preds_a))

print(((preds_a==True)&(preds_b==False)).sum(),((preds_a==False)&(preds_b==True)).sum())
b=((preds_a==True)&(preds_b==False)).sum()
c=((preds_a==False)&(preds_b==True)).sum()
print(f'p_value for difference LAURAE and RF: {mcnemar(int(b),int(c),True)}')


preds_a=(verbal_avg_rf_df1<verbal_avg_rf_df2)
##change to second best model if it is not LLM
preds_b=(df1['RSRS_mBERT']<df2['RSRS_mBERT'])

print(preds_a.sum()/len(preds_a),preds_b.sum()/len(preds_a))

print(((preds_a==True)&(preds_b==False)).sum(),((preds_a==False)&(preds_b==True)).sum())
b=((preds_a==True)&(preds_b==False)).sum()
c=((preds_a==False)&(preds_b==True)).sum()
print(f'p_value for difference LAURAE and RSRS: {mcnemar(int(b),int(c),True)}')

0.9533333333333334 0.76
29 0
p_value for difference LAURAE and LLM: 1.9985815081381854e-07
0.9533333333333334 0.8866666666666667
13 3
p_value for difference LAURAE and RF: 0.012725830078124991
0.9533333333333334 0.84
20 3
p_value for difference LAURAE and RSRS: 0.00027716159820556684

In [119]:
preds_a=df1.iloc[:,36]<df2.iloc[:,36]
##change to second best model if it is not LLM
preds_b=df1.iloc[:,37]<df2.iloc[:,37]

print(preds_a.sum()/len(preds_a),preds_b.sum()/len(preds_a))

print(((preds_a==True)&(preds_b==False)).sum(),((preds_a==False)&(preds_b==True)).sum())
b=((preds_a==True)&(preds_b==False)).sum()
c=((preds_a==False)&(preds_b==True)).sum()
print(f'p_value for difference (expected v Vanilla): {mcnemar(int(b),int(c),True)}')


#Change to top of RSRS and readability formula
#preds_c=(df1.ARI<df2.ARI)
#print(preds_b.sum()/len(preds_a),preds_c.sum()/len(preds_a))
#print(((preds_b==True)&(preds_c==False)).sum(),((preds_b==False)&(preds_c==True)).sum())
#b=((preds_b==True)&(preds_c==False)).sum()
#c=((preds_b==False)&(preds_c==True)).sum()
#print(f'p_value for difference: {mcnemar(int(b),int(c),True)}')

0.76 0.92
0 24
p_value for difference (expected v Vanilla): 5.960464477539052e-08

In [120]:
vikidiafrv2=pd.read_csv('.../vikidia_frv2.csv')
vikidiafrv2 = vikidiafrv2.replace("na", np.nan)
vikidiafrv2.columns


from sklearn.preprocessing import MinMaxScaler, StandardScaler
vikidiafrv2.iloc[:, 6:] = vikidiafrv2.iloc[:, 6:].apply(pd.to_numeric, errors="coerce")
rf_string='FRE'
#readmeruv2['RSRS_mBERT']= StandardScaler().fit_transform(readmeruv2['RSRS_mBERT'])
# Step 1: Normalize entropy columns
entropy_cols = [c for c in vikidiafrv2.columns if c.endswith("_entropy")]
entropy_cols_minmax = [c + "_minmax" for c in entropy_cols]
vikidiafrv2[entropy_cols_minmax] = MinMaxScaler().fit_transform(vikidiafrv2[entropy_cols])

vconf_cols = [c for c in vikidiafrv2.columns if c.endswith("verbal_conf")]
vconf_cols_minmax = [c + "_minmax" for c in vconf_cols]
vikidiafrv2[vconf_cols_minmax] = MinMaxScaler().fit_transform(vikidiafrv2[vconf_cols])
vikidiafrv2[vconf_cols] = vikidiafrv2[vconf_cols]/10

std_cols = [c for c in vikidiafrv2.columns if c.endswith("_avg") or c.endswith("_vanilla")]+ ["RSRS_mBERT"]+[rf_string]
vikidiafrv2[std_cols] = StandardScaler().fit_transform(vikidiafrv2[std_cols])
suffixes = ["_avg", "_vanilla", "_entropy"]
models = set(
    c.rsplit("_", 1)[0]  # remove the last part after the final underscore
    for c in entropy_cols  # or any column list containing these suffixes
)
df1=vikidiafrv2[vikidiafrv2.Simplicity=='simple'].sort_values(by='File_Number').reset_index(drop=True)
df2=vikidiafrv2[vikidiafrv2.Simplicity=='not simple'].sort_values(by='File_Number').reset_index(drop=True)
sorted_models = sorted(models, key=lambda x: x[::-1].lower())
for model in sorted_models:
    print(model)
    vanilla_col = f"{model}_vanilla"
    avg_col = f"{model}_avg"
    print(f'unweighted: \n Avg: {((df1[avg_col]<df2[avg_col]).sum())/len(df1)},Vanilla: {((df1[vanilla_col]<df2[vanilla_col]).sum())/len(df1)}, mBERT: {((df1["RSRS_mBERT"]<df2["RSRS_mBERT"]).sum())/len(df1)}, readability formula: {((df1[rf_string]<df2[rf_string]).sum())/len(df1)}')
    naive_avg_mBERT_df1=df1[avg_col]+df1["RSRS_mBERT"]
    naive_vanilla_mBERT_df1=df1[vanilla_col]+df1["RSRS_mBERT"]
    naive_avg_rf_df1=df1[avg_col]+df1[rf_string]
    naive_vanilla_rf_df1=df1[vanilla_col]+df1[rf_string]
    
    naive_avg_mBERT_df2=df2[avg_col]+df2["RSRS_mBERT"]
    naive_vanilla_mBERT_df2=df2[vanilla_col]+df2["RSRS_mBERT"]
    naive_avg_rf_df2=df2[avg_col]+df2[rf_string]
    naive_vanilla_rf_df2=df2[vanilla_col]+df2[rf_string]
    print(f'naive weightings:\n Avg mBERT: {((naive_avg_mBERT_df1<naive_avg_mBERT_df2).sum())/len(df1)}, Vanilla mBERT:{((naive_vanilla_mBERT_df1<naive_vanilla_mBERT_df2).sum())/len(df1)}, Avg Readability Formula: {((naive_avg_rf_df1<naive_avg_rf_df2).sum())/len(df1)}, Vanilla Readability Formula:{((naive_vanilla_rf_df1<naive_vanilla_rf_df2).sum())/len(df1)}')
    entropy_col = f"{model}_entropy"
    entropy_col_minmax = f"{model}_entropy_minmax"
    if model.startswith('conf_'):
        vconf_col=f'{model}_verbal_conf'
        vconf_col_minmax = f"{model}_verbal_conf_minmax"
    
    #readmeruv2[f"{model}_weighted"] = (
    #    readmeruv2[entropy_col] * readmeruv2["RSRS_mBERT"] + 
    #    (1 - readmeruv2[entropy_col]) * (readmeruv2[[vanilla_col, avg_col]].mean(axis=1))
    #)
    entropy_avg_mBERT_df1=(df1[entropy_col] * df1["RSRS_mBERT"]) + ((1 - df1[entropy_col]) * df1[avg_col])
    entropy_vanilla_mBERT_df1=(df1[entropy_col] * df1["RSRS_mBERT"]) + ((1 - df1[entropy_col]) * df1[vanilla_col])
    entropy_avg_mBERT_df2=(df2[entropy_col] * df2["RSRS_mBERT"]) + ((1 - df2[entropy_col]) * df2[avg_col])
    entropy_vanilla_mBERT_df2=(df2[entropy_col] * df2["RSRS_mBERT"]) + ((1 - df2[entropy_col]) * df2[vanilla_col])
    
    entropy_minmax_avg_mBERT_df1=(df1[entropy_col_minmax] * df1["RSRS_mBERT"]) + ((1 - df1[entropy_col_minmax]) * df1[avg_col])
    entropy_minmax_vanilla_mBERT_df1=(df1[entropy_col_minmax] * df1["RSRS_mBERT"]) + ((1 - df1[entropy_col_minmax]) * df1[vanilla_col])
    entropy_minmax_avg_mBERT_df2=(df2[entropy_col_minmax] * df2["RSRS_mBERT"]) + ((1 - df2[entropy_col_minmax]) * df2[avg_col])
    entropy_minmax_vanilla_mBERT_df2=(df2[entropy_col_minmax] * df2["RSRS_mBERT"]) + ((1 - df2[entropy_col_minmax]) * df2[vanilla_col])
    
    entropy_avg_rf_df1=(df1[entropy_col] * df1[rf_string]) + ((1 - df1[entropy_col]) * df1[avg_col])
    entropy_vanilla_rf_df1=(df1[entropy_col] * df1[rf_string]) + ((1 - df1[entropy_col]) * df1[vanilla_col])
    entropy_avg_rf_df2=(df2[entropy_col] * df2[rf_string]) + ((1 - df2[entropy_col]) * df2[avg_col])
    entropy_vanilla_rf_df2=(df2[entropy_col] * df2[rf_string]) + ((1 - df2[entropy_col]) * df2[vanilla_col])
    
    entropy_minmax_avg_rf_df1=(df1[entropy_col_minmax] * df1[rf_string]) + ((1 - df1[entropy_col_minmax]) * df1[avg_col])
    entropy_minmax_vanilla_rf_df1=(df1[entropy_col_minmax] * df1[rf_string]) + ((1 - df1[entropy_col_minmax]) * df1[vanilla_col])
    entropy_minmax_avg_rf_df2=(df2[entropy_col_minmax] * df2[rf_string]) + ((1 - df2[entropy_col_minmax]) * df2[avg_col])
    entropy_minmax_vanilla_rf_df2=(df2[entropy_col_minmax] * df2[rf_string]) + ((1 - df2[entropy_col_minmax]) * df2[vanilla_col])
    
    
    
    
    
    
    print(f'entropy weightings: \n Avg mBERT{((entropy_avg_mBERT_df1<entropy_avg_mBERT_df2).sum())/len(df1)}, Vanilla mBERT: {((entropy_vanilla_mBERT_df1<entropy_vanilla_mBERT_df2).sum())/len(df1)}, Avg minmax mBERT: {((entropy_minmax_avg_mBERT_df1<entropy_minmax_avg_mBERT_df2).sum())/len(df1)}, Vanilla minmax mBERT: {((entropy_minmax_vanilla_mBERT_df1<entropy_minmax_vanilla_mBERT_df2).sum())/len(df1)},Avg rf{((entropy_avg_rf_df1<entropy_avg_rf_df2).sum())/len(df1)}, Vanilla rf: {((entropy_vanilla_rf_df1<entropy_vanilla_rf_df2).sum())/len(df1)}, Avg minmax rf: {((entropy_minmax_avg_rf_df1<entropy_minmax_avg_rf_df2).sum())/len(df1)}, Vanilla minmax rf: {((entropy_minmax_vanilla_rf_df1<entropy_minmax_vanilla_rf_df2).sum())/len(df1)}')
    if model.startswith('conf_'):
        verbal_avg_mBERT_df1=((1 - df1[vconf_col]) * df1["RSRS_mBERT"]) + (df1[vconf_col] * df1[avg_col])
        verbal_vanilla_mBERT_df1=((1 - df1[vconf_col]) * df1["RSRS_mBERT"]) + (df1[vconf_col] * df1[vanilla_col])
        verbal_avg_mBERT_df2=((1 - df2[vconf_col]) * df2["RSRS_mBERT"]) + (df2[vconf_col] * df2[avg_col])
        verbal_vanilla_mBERT_df2=((1 - df2[vconf_col]) * df2["RSRS_mBERT"]) + (df2[vconf_col] * df2[vanilla_col])
        
        verbal_minmax_avg_mBERT_df1=((1 - df1[vconf_col_minmax]) * df1["RSRS_mBERT"]) + (df1[vconf_col_minmax] * df1[avg_col])
        verbal_minmax_vanilla_mBERT_df1=((1 - df1[vconf_col_minmax]) * df1["RSRS_mBERT"]) + (df1[vconf_col_minmax] * df1[vanilla_col])
        verbal_minmax_avg_mBERT_df2=((1 - df2[vconf_col_minmax]) * df2["RSRS_mBERT"]) + (df2[vconf_col_minmax] * df2[avg_col])
        verbal_minmax_vanilla_mBERT_df2=((1 - df2[vconf_col_minmax]) * df2["RSRS_mBERT"]) + (df2[vconf_col_minmax] * df2[vanilla_col])
        
        verbal_avg_rf_df1=((1 - df1[vconf_col]) * df1[rf_string]) + (df1[vconf_col] * df1[avg_col])
        verbal_vanilla_rf_df1=((1 - df1[vconf_col]) * df1[rf_string]) + (df1[vconf_col] * df1[vanilla_col])
        verbal_avg_rf_df2=((1 - df2[vconf_col]) * df2[rf_string]) + (df2[vconf_col] * df2[avg_col])
        verbal_vanilla_rf_df2=((1 - df2[vconf_col]) * df2[rf_string]) + (df2[vconf_col] * df2[vanilla_col])
        
        verbal_minmax_avg_rf_df1=((1 - df1[vconf_col_minmax]) * df1[rf_string]) + (df1[vconf_col_minmax] * df1[avg_col])
        verbal_minmax_vanilla_rf_df1=((1 - df1[vconf_col_minmax]) * df1[rf_string]) + (df1[vconf_col_minmax] * df1[vanilla_col])
        verbal_minmax_avg_rf_df2=((1 - df2[vconf_col_minmax]) * df2[rf_string]) + (df2[vconf_col_minmax] * df2[avg_col])
        verbal_minmax_vanilla_rf_df2=((1 - df2[vconf_col_minmax]) * df2[rf_string]) + (df2[vconf_col_minmax] * df2[vanilla_col])
        print(f'verbal weightings: \n Avg mBERT{((verbal_avg_mBERT_df1<verbal_avg_mBERT_df2).sum())/len(df1)}, Vanilla mBERT: {((verbal_vanilla_mBERT_df1<verbal_vanilla_mBERT_df2).sum())/len(df1)}, Avg minmax mBERT: {((verbal_minmax_avg_mBERT_df1<verbal_minmax_avg_mBERT_df2).sum())/len(df1)}, Vanilla minmax mBERT: {((verbal_minmax_vanilla_mBERT_df1<verbal_minmax_vanilla_mBERT_df2).sum())/len(df1)},Avg rf: {((verbal_avg_rf_df1<verbal_avg_rf_df2).sum())/len(df1)}, Vanilla rf: {((verbal_vanilla_rf_df1<verbal_vanilla_rf_df2).sum())/len(df1)}, Avg minmax rf{((verbal_minmax_avg_rf_df1<verbal_minmax_avg_rf_df2).sum())/len(df1)}, Vanilla minmax rf: {((verbal_minmax_vanilla_rf_df1<verbal_minmax_vanilla_rf_df2).sum())/len(df1)}','\n \n \n')
    else:
        print('\n')

llama_70b
unweighted:
 Avg: 0.96,Vanilla: 0.9066666666666666, mBERT: 0.84, readability formula: 0.8866666666666667
naive weightings:
 Avg mBERT: 0.92, Vanilla mBERT:0.9333333333333333, Avg Readability Formula: 0.9666666666666667, Vanilla Readability Formula:0.9533333333333334
entropy weightings:
 Avg mBERT0.96, Vanilla mBERT: 0.94, Avg minmax mBERT: 0.94, Vanilla minmax mBERT: 0.92,Avg rf0.9666666666666667, Vanilla rf: 0.9466666666666667, Avg minmax rf: 0.9733333333333334, Vanilla minmax rf: 0.96


conf_llama_70b
unweighted:
 Avg: 0.9533333333333334,Vanilla: 0.8866666666666667, mBERT: 0.84, readability formula: 0.8866666666666667
naive weightings:
 Avg mBERT: 0.9266666666666666, Vanilla mBERT:0.94, Avg Readability Formula: 0.9466666666666667, Vanilla Readability Formula:0.9533333333333334
entropy weightings:
 Avg mBERT0.9466666666666667, Vanilla mBERT: 0.9466666666666667, Avg minmax mBERT: 0.92, Vanilla minmax mBERT: 0.92,Avg rf0.9533333333333334, Vanilla rf: 0.9466666666666667, Avg minmax rf: 0.96, Vanilla minmax rf: 0.9533333333333334
verbal weightings:
 Avg mBERT0.9533333333333334, Vanilla mBERT: 0.9533333333333334, Avg minmax mBERT: 0.9533333333333334, Vanilla minmax mBERT: 0.9533333333333334,Avg rf: 0.9533333333333334, Vanilla rf: 0.96, Avg minmax rf0.9533333333333334, Vanilla minmax rf: 0.96



aya_32b
unweighted:
 Avg: 0.9466666666666667,Vanilla: 0.86, mBERT: 0.84, readability formula: 0.8866666666666667
naive weightings:
 Avg mBERT: 0.9533333333333334, Vanilla mBERT:0.9466666666666667, Avg Readability Formula: 0.98, Vanilla Readability Formula:0.98
entropy weightings:
 Avg mBERT0.9533333333333334, Vanilla mBERT: 0.9533333333333334, Avg minmax mBERT: 0.9333333333333333, Vanilla minmax mBERT: 0.94,Avg rf0.9466666666666667, Vanilla rf: 0.9666666666666667, Avg minmax rf: 0.9666666666666667, Vanilla minmax rf: 0.9666666666666667


conf_aya_32b
unweighted:
 Avg: 0.92,Vanilla: 0.76, mBERT: 0.84, readability formula: 0.8866666666666667
naive weightings:
 Avg mBERT: 0.9333333333333333, Vanilla mBERT:0.9266666666666666, Avg Readability Formula: 0.9666666666666667, Vanilla Readability Formula:0.96
entropy weightings:
 Avg mBERT0.9466666666666667, Vanilla mBERT: 0.94, Avg minmax mBERT: 0.94, Vanilla minmax mBERT: 0.9333333333333333,Avg rf0.94, Vanilla rf: 0.96, Avg minmax rf: 0.9666666666666667, Vanilla minmax rf: 0.9666666666666667
verbal weightings:
 Avg mBERT0.9466666666666667, Vanilla mBERT: 0.9333333333333333, Avg minmax mBERT: 0.8666666666666667, Vanilla minmax mBERT: 0.8466666666666667,Avg rf: 0.9533333333333334, Vanilla rf: 0.96, Avg minmax rf0.8933333333333333, Vanilla minmax rf: 0.92



llama_3b
unweighted:
 Avg: 0.7133333333333334,Vanilla: 0.4066666666666667, mBERT: 0.84, readability formula: 0.8866666666666667
naive weightings:
 Avg mBERT: 0.8266666666666667, Vanilla mBERT:0.8133333333333334, Avg Readability Formula: 0.8666666666666667, Vanilla Readability Formula:0.8533333333333334
entropy weightings:
 Avg mBERT0.74, Vanilla mBERT: 0.7866666666666666, Avg minmax mBERT: 0.8333333333333334, Vanilla minmax mBERT: 0.8333333333333334,Avg rf0.7533333333333333, Vanilla rf: 0.8, Avg minmax rf: 0.88, Vanilla minmax rf: 0.86


conf_llama_3b
unweighted:
 Avg: 0.05333333333333334,Vanilla: 0.02, mBERT: 0.84, readability formula: 0.8866666666666667
naive weightings:
 Avg mBERT: 0.06666666666666667, Vanilla mBERT:0.06, Avg Readability Formula: 0.07333333333333333, Vanilla Readability Formula:0.06666666666666667
entropy weightings:
 Avg mBERT0.05333333333333334, Vanilla mBERT: 0.05333333333333334, Avg minmax mBERT: 0.06, Vanilla minmax mBERT: 0.06666666666666667,Avg rf0.05333333333333334, Vanilla rf: 0.06, Avg minmax rf: 0.07333333333333333, Vanilla minmax rf: 0.08
verbal weightings:
 Avg mBERT0.06, Vanilla mBERT: 0.05333333333333334, Avg minmax mBERT: 0.05333333333333334, Vanilla minmax mBERT: 0.05333333333333334,Avg rf: 0.05333333333333334, Vanilla rf: 0.06, Avg minmax rf0.05333333333333334, Vanilla minmax rf: 0.06



llama_8b
unweighted:
 Avg: 0.8466666666666667,Vanilla: 0.6333333333333333, mBERT: 0.84, readability formula: 0.8866666666666667
naive weightings:
 Avg mBERT: 0.9066666666666666, Vanilla mBERT:0.8866666666666667, Avg Readability Formula: 0.9533333333333334, Vanilla Readability Formula:0.9066666666666666
entropy weightings:
 Avg mBERT0.86, Vanilla mBERT: 0.8866666666666667, Avg minmax mBERT: 0.9, Vanilla minmax mBERT: 0.88,Avg rf0.8533333333333334, Vanilla rf: 0.8866666666666667, Avg minmax rf: 0.94, Vanilla minmax rf: 0.8933333333333333


conf_llama_8b
unweighted:
 Avg: 0.8133333333333334,Vanilla: 0.5133333333333333, mBERT: 0.84, readability formula: 0.8866666666666667
naive weightings:
 Avg mBERT: 0.8733333333333333, Vanilla mBERT:0.8333333333333334, Avg Readability Formula: 0.92, Vanilla Readability Formula:0.8533333333333334
entropy weightings:
 Avg mBERT0.8133333333333334, Vanilla mBERT: 0.8333333333333334, Avg minmax mBERT: 0.8666666666666667, Vanilla minmax mBERT: 0.8333333333333334,Avg rf0.8266666666666667, Vanilla rf: 0.8533333333333334, Avg minmax rf: 0.8866666666666667, Vanilla minmax rf: 0.8533333333333334
verbal weightings:
 Avg mBERT0.8666666666666667, Vanilla mBERT: 0.8333333333333334, Avg minmax mBERT: 0.86, Vanilla minmax mBERT: 0.84,Avg rf: 0.86, Vanilla rf: 0.86, Avg minmax rf0.8333333333333334, Vanilla minmax rf: 0.8466666666666667



aya_8b
unweighted:
 Avg: 0.66,Vanilla: 0.5, mBERT: 0.84, readability formula: 0.8866666666666667
naive weightings:
 Avg mBERT: 0.7933333333333333, Vanilla mBERT:0.7666666666666667, Avg Readability Formula: 0.8133333333333334, Vanilla Readability Formula:0.7733333333333333
entropy weightings:
 Avg mBERT0.6733333333333333, Vanilla mBERT: 0.6866666666666666, Avg minmax mBERT: 0.8066666666666666, Vanilla minmax mBERT: 0.7733333333333333,Avg rf0.6733333333333333, Vanilla rf: 0.7, Avg minmax rf: 0.82, Vanilla minmax rf: 0.82


mixtral
unweighted:
 Avg: 0.8466666666666667,Vanilla: 0.74, mBERT: 0.84, readability formula: 0.8866666666666667
naive weightings:
 Avg mBERT: 0.8866666666666667, Vanilla mBERT:0.8866666666666667, Avg Readability Formula: 0.9466666666666667, Vanilla Readability Formula:0.92
entropy weightings:
 Avg mBERT0.8533333333333334, Vanilla mBERT: 0.8666666666666667, Avg minmax mBERT: 0.88, Vanilla minmax mBERT: 0.8866666666666667,Avg rf0.8733333333333333, Vanilla rf: 0.88, Avg minmax rf: 0.92, Vanilla minmax rf: 0.8933333333333333


conf_mixtral
unweighted:
 Avg: 0.8733333333333333,Vanilla: 0.7733333333333333, mBERT: 0.84, readability formula: 0.8866666666666667
naive weightings:
 Avg mBERT: 0.92, Vanilla mBERT:0.92, Avg Readability Formula: 0.92, Vanilla Readability Formula:0.92
entropy weightings:
 Avg mBERT0.88, Vanilla mBERT: 0.8866666666666667, Avg minmax mBERT: 0.8933333333333333, Vanilla minmax mBERT: 0.8933333333333333,Avg rf0.8866666666666667, Vanilla rf: 0.9066666666666666, Avg minmax rf: 0.9266666666666666, Vanilla minmax rf: 0.9266666666666666
verbal weightings:
 Avg mBERT0.9066666666666666, Vanilla mBERT: 0.9, Avg minmax mBERT: 0.9066666666666666, Vanilla minmax mBERT: 0.9,Avg rf: 0.9133333333333333, Vanilla rf: 0.9066666666666666, Avg minmax rf0.9133333333333333, Vanilla minmax rf: 0.9066666666666666

In [86]:
## Descriptive stats for conf/entropy
clearv2.conf_noscale_llama_70b_verbal_conf.describe(),greekhistv2.conf_noscale_aya_32B_verbal_conf.describe(),greeklangv2.conf_noscale_aya_32B_verbal_conf.describe(),cambridgev2.conf_llama_70b_verbal_conf.describe(),onestopv2.conf_llama_70b_verbal_conf.describe(),medreadmev2.conf_llama_70b_verbal_conf.describe(),readmeenv2.conf_llama_70b_verbal_conf.describe(),readmefrv2.conf_aya_32b_verbal_conf.describe(),readmehiv2.conf_aya_32b_verbal_conf.describe(),readmearv2.conf_aya_32b_verbal_conf.describe(),readmeruv2.conf_aya_32b_verbal_conf.describe(),vikidiav2.conf_llama_70b_verbal_conf.describe(),vikidiafrv2.conf_aya_32b_verbal_conf.describe(),assetv2.conf_llama_70b_verbal_conf.describe()
#clearv2.conf_noscale_llama_70b_entropy.describe()

(count    1890.000000
 mean        0.796186
 std         0.018699
 min         0.718872
 25%         0.788927
 50%         0.800000
 75%         0.800000
 max         0.900000
 Name: conf_noscale_llama_70b_verbal_conf, dtype: float64,
 count    797.000000
 mean       0.773633
 std        0.048363
 min        0.100000
 25%        0.722265
 50%        0.799582
 75%        0.799867
 max        0.799997
 Name: conf_noscale_aya_32B_verbal_conf, dtype: float64,
 count    391.000000
 mean       0.716998
 std        0.048567
 min        0.199929
 25%        0.700243
 50%        0.701241
 75%        0.709534
 max        0.805297
 Name: conf_noscale_aya_32B_verbal_conf, dtype: float64,
 count    299.000000
 mean       0.818283
 std        0.037328
 min        0.800000
 25%        0.800000
 50%        0.800000
 75%        0.800000
 max        0.900000
 Name: conf_llama_70b_verbal_conf, dtype: float64,
 count    567.000000
 mean       0.793434
 std        0.007613
 min        0.769706
 25%        0.786704
 50%        0.800000
 75%        0.800000
 max        0.800000
 Name: conf_llama_70b_verbal_conf, dtype: float64,
 count    1139.000000
 mean        0.822259
 std         0.035508
 min         0.722550
 25%         0.800000
 50%         0.800000
 75%         0.844810
 max         0.900000
 Name: conf_llama_70b_verbal_conf, dtype: float64,
 count    296.000000
 mean       0.849675
 std        0.045429
 min        0.718419
 25%        0.800000
 50%        0.850000
 75%        0.900000
 max        0.900000
 Name: conf_llama_70b_verbal_conf, dtype: float64,
 count    185.000000
 mean       0.797469
 std        0.028766
 min        0.718242
 25%        0.788079
 50%        0.797702
 75%        0.799872
 max        0.899998
 Name: conf_aya_32b_verbal_conf, dtype: float64,
 count    162.000000
 mean       0.797802
 std        0.036464
 min        0.706754
 25%        0.787047
 50%        0.798201
 75%        0.799847
 max        0.899990
 Name: conf_aya_32b_verbal_conf, dtype: float64,
 count    206.000000
 mean       0.790520
 std        0.043303
 min        0.701401
 25%        0.775491
 50%        0.793619
 75%        0.799409
 max        0.899993
 Name: conf_aya_32b_verbal_conf, dtype: float64,
 count    178.000000
 mean       0.788551
 std        0.032117
 min        0.702929
 25%        0.781757
 50%        0.794660
 75%        0.799245
 max        0.899720
 Name: conf_aya_32b_verbal_conf, dtype: float64,
 count    300.000000
 mean       0.802498
 std        0.044769
 min        0.711073
 25%        0.773917
 50%        0.800000
 75%        0.815887
 max        0.900000
 Name: conf_llama_70b_verbal_conf, dtype: float64,
 count     298.000000
 unique    297.000000
 top         0.767918
 freq        2.000000
 Name: conf_aya_32b_verbal_conf, dtype: float64,
 count    970.000000
 mean       0.803165
 std        0.028275
 min        0.669729
 25%        0.800000
 50%        0.800000
 75%        0.811073
 max        0.900000
 Name: conf_llama_70b_verbal_conf, dtype: float64)